= JReleaser Ant Tasks

Executes a JReleaser workflow as Ant tasks

The following tasks are provided:

== jreleaser-init

Create a jreleaser config file.

*format*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.format
Required:: true
Description:: Configuration file format. Currently supported formats are: `yml`, `toml`, `json`.

*overwrite*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.overwrite
Required:: false
Description:: Overwrites existing template files.

== jreleaser-config

Display current configuration.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*full*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.full
Required:: false
Description:: Display full configuration.
---

*assembly*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.assembly
Required:: false
Description:: Display only assembly configuration.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

== jreleaser-template

Generate a tool template.

*distributionName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.distribution.name
Required:: true
Description:: The name of the distribution.

---

*distributionType*
[horizontal]
Type:: String
Default value:: JAVA_BINARY
Property:: jreleaser.distribution.type
Required:: false
Description:: The name of the distribution.

---

*toolName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.tool.name
Required:: true
Description:: The name of the tool.

---

*overwrite*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.overwrite
Required:: false
Description:: Overwrites existing template files.

---

*snapshot*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.snapshot
Required:: false
Description:: Lookup snapshot specific template files.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

== jreleaser-assemble

Upload all distributions.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributionName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.distribution.name
Required:: false
Description:: The name of the distribution to be assembled.

---

*assemblerName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.assembler.name
Required:: false
Description:: The name of the assembler to run.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

== jreleaser-changelog

Calculate the changelog.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

== jreleaser-checksum

Calculate checksums.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

== jreleaser-sign

Sign release artifacts.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

== jreleaser-release

Create or update a release.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dryrun
Required:: false
Description: Skips remote operations.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

== jreleaser-prepare

Prepare all distributions.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributionName*
[horizontal]
Type:: String
Default value:: <none
Property:: jreleaser.distribution.name
Required:: false
Description:: The name of the distribution to be prepared.

---

*toolName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.tool.name
Required:: false
Description:: The name of the tool for preparing distributions.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

== jreleaser-package

Package all distributions.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributionName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.distribution.name
Required:: false
Description:: The name of the distribution to be packaged.

---

*toolName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.tool.name
Required:: false
Description:: The name of the tool for packaging distributions.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dryrun
Required:: false
Description: Skips remote operations.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

== jreleaser-upload

Upload all distributions.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributionName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.distribution.name
Required:: false
Description:: The name of the distribution to be upload.

---

*toolName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.tool.name
Required:: false
Description:: The name of the tool for uploading distributions.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dryrun
Required:: false
Description: Skips remote operations.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

== jreleaser-announce

Announce a release.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*announcerName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.announcer.name
Required:: false
Description:: The name of the announcer to be used.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dryrun
Required:: false
Description: Skips remote operations.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

== jreleaser-full-release

Perform a full release.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dryrun
Required:: false
Description: Skips remote operations.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.


