= JReleaser Ant Tasks

Executes a JReleaser workflow as Ant tasks.

== Install

Download jreleaser-ant-tasks ZIP bundle from the
link:https://github.com/jreleaser/jreleaser/releases[releases page] and unzip it in your project. Place all JARs inside
the `lib` folder. Create this folder if there is none. Add the following elements to your `build.xml` file

[source,xml]
[subs="verbatim,attributes"]
.build.xml
----
<path id="jreleaser.classpath">
    <fileset dir="lib">
        <include name="jreleaser-ant-tasks-{jreleaser-version}/*.jar"/>
    </fileset>
</path>

<import>
  <javaresource name="org/jreleaser/ant/targets.xml"
                classpathref="jreleaser.classpath"/>
</import>
----

== Configuration

JReleaser must be configured using the YAML, TOML, or JSON DSLs shown at xref:reference:index.adoc[].

== Environment Variables

The following settings may also be specified via environment variables

[options="header", cols="3*"]
|===
| Setting               | Environment Variable              | Default
| basedir               | JRELEASER_BASEDIR                 | <current-execution-directory>
| outputDir             | JRELEASER_OUTPUT_DIRECTORY        | out
| dryrun                | JRELEASER_DRY_RUN                 | false
| strict                | JRELEASER_STRICT                  | false
| yolo                  | JRELEASER_YOLO                    | false
| gitRootSearch         | JRELEASER_GIT_ROOT_SEARCH         | false
| selectCurrentPlatform | JRELEASER_SELECT_CURRENT_PLATFORM | false
| selectPlatforms       | JRELEASER_SELECT_PLATFORMS        | <empty-string>
| rejectPlatforms       | JRELEASER_REJECT_PLATFORMS        | <empty-string>
|                       | JRELEASER_DEFAULT_GIT_REMOTE      | origin
|===

`JRELEASER_SELECT_PLATFORMs` and `JRELEASER_REJECT_PLATFORMs` may define a command separated list of values such as
`osx-x86_64,linux-x86_64`.

These additional environment variables are supported as well:

[options="header", cols="2*"]
|===
| Environment Variable | Description
| NO_COLOR             | disable colors in output
| JRELEASER_NO_COLOR   | disable colors in output
|===

WARNING: These environment variables cannot be defined in `.env` files nor any other input files supported by
xref:reference:environment.adoc[].

== Filtering Artifacts

Many commands let you filter (include or exclude) artifacts using a combination of target properties or environment variables.
This filter capability allows you to test out a release configuration on a node where not all artifacts may be available.
For example, when building on `linux-x86_64` while also having `osx-x86_64` and `windows-x86_64`.

.Include only for the current platform

Use the `JRELEASER_SELECT_CURRENT_PLATFORM` environment variable or the `selectCurrentPlatform` target property.

[source]
----
$ JRELEASER_SELECT_CURRENT_PLATFORM ant jreleaser-checksum
----

.Include a specific platform

Use the `JRELEASER_SELECT_PLATFORMS` environment variable or the `selectPlatform` target property, i.e,

[source]
----
$ JRELEASER_SELECT_PLATFORMS=osx-x86_64 ant jreleaser-checksum
----

Every artifact whose platform property *does not* match the given platform will end up filtered out.

.Exclude a specific platform

Use the `JRELEASER_REJECT_PLATFORMS` environment variable or the `rejectPlatform` target property, i.e,

[source]
----
$ JRELEASER_REJECT_PLATFORMS=windows-x86_64 ant jreleaser-checksum
----

Every artifact whose platform property *matches* the given platform will end up filtered out.

== Tasks

The following tasks are provided:

=== jreleaser-env

Display environment variable names.

*settingsFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.settings.file
Required:: false
Description:: The settings file.

=== jreleaser-init

Create a jreleaser config file.

*format*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.format
Required:: true
Description:: Configuration file format. Currently supported formats are: `yml`, `json`, and `toml`.

*overwrite*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.overwrite
Required:: false
Description:: Overwrites existing template files.

=== jreleaser-config

Display current configuration.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*full*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.full
Required:: false
Description:: Display full configuration.

---

*announce*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.announce
Required:: false
Description:: Display only announce configuration.

---

*assembly*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.assembly
Required:: false
Description:: Display only assembly configuration.

---

*changelog*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.changelog
Required:: false
Description:: Display only changelog configuration.

---

*deploy*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.deploy
Required:: false
Description:: Display only deploy configuration.

---

*download*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.download
Required:: false
Description:: Display only download configuration.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*rejectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths not matching the given platform.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*settingsFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.settings.file
Required:: false
Description:: The settings file.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*strict*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.strict
Required:: false
Description:: Enable strict mode.

=== jreleaser-template-generate

Generate a tool/announcer template.

*distributionName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.distribution.name
Required:: true
Description:: The name of the distribution.

---

*announcerName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.announcer.name
Required:: false
Description:: The name of the announcer to be used.

---

*assemblerName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.assembler.name
Required:: false
Description:: The name of the assembler to be used.

---

*assemblerType*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.assembler.type
Required:: false
Description:: The type of the assembler to be used.

---

*distributionType*
[horizontal]
Type:: String
Default value:: JAVA_BINARY
Property:: jreleaser.distribution.type
Required:: false
Description:: The name of the distribution.

---

*packagerName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.packager.name
Required:: true
Description:: The name of the packager.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*overwrite*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.overwrite
Required:: false
Description:: Overwrites existing template files.

---

*snapshot*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.snapshot
Required:: false
Description:: Lookup snapshot specific template files.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

=== jreleaser-template-eval

Evaluate a template or templates.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*announce*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.announce
Required:: false
Description:: Display only announce configuration.

---

*assembly*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.assembly
Required:: false
Description:: Display only assembly configuration.

---

*changelog*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.changelog
Required:: false
Description:: Display only changelog configuration.

---

*download*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.download
Required:: false
Description:: Display only download configuration.

---

*inputFile*
[horizontal]
Type:: File
Property:: releaser.template.input.file
Required:: true
Description:: An input template file.

---

*inputDir*
[horizontal]
Type:: File
Property:: releaser.template.input.dir
Required:: true
Description:: A directory with input templates.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*rejectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths not matching the given platform.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*settingsFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.settings.file
Required:: false
Description:: The settings file.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*strict*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.strict
Required:: false
Description:: Enable strict mode.

---

*targetDir*
[horizontal]
Type:: File
Property:: jreleaser.template.target.dir
Required:: true
Description:: Directory where evaluated template(s) will be placed.

=== jreleaser-download

Downloads assets. +
Executes the xref:concepts:workflow.adoc#_download[Download] workflow step.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*downloaderNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of downloaders to include.

---

*downloaderTypes*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of downloaders to include.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dry.run
Required:: false
Description: Skips remote operations.

---

*excludedDownloaderNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of downloaders to exclude.

---

*excludedDownloaderTypes*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of downloaders to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*settingsFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.settings.file
Required:: false
Description:: The settings file.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*strict*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.strict
Required:: false
Description:: Enable strict mode.

---

*yolo*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.yolo
Required:: false
Description: Skips non-configured operations.

=== jreleaser-assemble

Assemble all distributions. +
Executes the xref:concepts:workflow.adoc#_assemble[Assemble] workflow step.

*assemblers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of assemblers to run.

---

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to be assembled.

---

*excludedAssemblers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of assemblers to exclude.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*rejectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths not matching the given platform.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*settingsFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.settings.file
Required:: false
Description:: The settings file.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*strict*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.strict
Required:: false
Description:: Enable strict mode.

---

*yolo*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.yolo
Required:: false
Description: Skips non-configured operations.

=== jreleaser-changelog

Calculate the changelog. +
Executes the xref:concepts:workflow.adoc#_changelog[Changelog] workflow step.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*settingsFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.settings.file
Required:: false
Description:: The settings file.

---

*strict*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.strict
Required:: false
Description:: Enable strict mode.

---

*yolo*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.yolo
Required:: false
Description: Skips non-configured operations.

=== jreleaser-catalog

Catalogs all distributions and files. +
Executes the xref:concepts:workflow.adoc#_catalog[Catalog] workflow step.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*catalogers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the catalogers to include.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to include.

---

*excludedCatalogers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of catalogers to exclude.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*rejectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths not matching the given platform.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*settingsFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.settings.file
Required:: false
Description:: The settings file.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*strict*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.strict
Required:: false
Description:: Enable strict mode.

---

*yolo*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.yolo
Required:: false
Description: Skips non-configured operations.

=== jreleaser-checksum

Calculate checksums. +
Executes the xref:concepts:workflow.adoc#_checksum[Checksum] workflow step.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to include.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*rejectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths not matching the given platform.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*settingsFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.settings.file
Required:: false
Description:: The settings file.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*strict*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.strict
Required:: false
Description:: Enable strict mode.

---

*yolo*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.yolo
Required:: false
Description: Skips non-configured operations.

=== jreleaser-sign

Sign release artifacts. +
Executes the xref:concepts:workflow.adoc#_sign[Sign] workflow step.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to include.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*rejectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths not matching the given platform.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*settingsFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.settings.file
Required:: false
Description:: The settings file.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*strict*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.strict
Required:: false
Description:: Enable strict mode.

---

*yolo*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.yolo
Required:: false
Description: Skips non-configured operations.

=== jreleaser-deploy

Deploys all staged artifacts. +
Executes the xref:concepts:workflow.adoc#_deploy[Deploy] workflow step.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*deployers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of deployers to include.

---

*deployerNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of deployers to include.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dry.run
Required:: false
Description: Skips remote operations.

---

*excludedDeployers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of deployers to exclude.

---

*excludedDeployerNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of deployers to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*settingsFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.settings.file
Required:: false
Description:: The settings file.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*strict*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.strict
Required:: false
Description:: Enable strict mode.

---

*yolo*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.yolo
Required:: false
Description: Skips non-configured operations.

=== jreleaser-upload

Uploads all artifacts. +
Executes the xref:concepts:workflow.adoc#_upload[Upload] workflow step.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*catalogers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of catalogers to include.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to include.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dry.run
Required:: false
Description: Skips remote operations.

---

*excludedCatalogers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of catalogers to exclude.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*excludedUploaderNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of uploaders to exclude.

---

*excludedUploaderTypes*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of uploaders to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*rejectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths not matching the given platform.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*settingsFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.settings.file
Required:: false
Description:: The settings file.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*strict*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.strict
Required:: false
Description:: Enable strict mode.

---

*uploaderNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of uploaders to include.

---

*uploaderTypes*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of uploaders to include.

---

*yolo*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.yolo
Required:: false
Description: Skips non-configured operations.

=== jreleaser-release

Create or update a release. +
Executes the xref:concepts:workflow.adoc#_release[Release] workflow step.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*catalogers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of catalogers to include.

---

*deployers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of deployers to include.

---

*deployerNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of deployers to include.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to include.

---

*excludedCatalogers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of catalogers to exclude.

---

*excludedDeployers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of deployers to exclude.

---

*excludedDeployerNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of deployers to exclude.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*excludedUploaderNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of uploaders to exclude.

---

*excludedUploaderTypes*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of uploaders to exclude.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dry.run
Required:: false
Description: Skips remote operations.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*rejectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths not matching the given platform.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*settingsFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.settings.file
Required:: false
Description:: The settings file.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*strict*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.strict
Required:: false
Description:: Enable strict mode.

---

*uploaderNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of uploaders to include.

---

*uploaderTypes*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of uploaders to include.

---

*yolo*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.yolo
Required:: false
Description: Skips non-configured operations.

=== jreleaser-prepare

Prepare all distributions. +
Executes the xref:concepts:workflow.adoc#_prepare[Prepare] workflow step.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to include.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*excludedPackagers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of packagers to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*packagers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the packagers to include.

---

*rejectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths not matching the given platform.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*settingsFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.settings.file
Required:: false
Description:: The settings file.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*strict*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.strict
Required:: false
Description:: Enable strict mode.

---

*yolo*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.yolo
Required:: false
Description: Skips non-configured operations.

=== jreleaser-package

Package all distributions. +
Executes the xref:concepts:workflow.adoc#_package[Package] workflow step.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to include.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*excludedPackagers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of packagers to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*packagers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the packagers to include.

---

*rejectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths not matching the given platform.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*settingsFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.settings.file
Required:: false
Description:: The settings file.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*strict*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.strict
Required:: false
Description:: Enable strict mode.

---

*yolo*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.yolo
Required:: false
Description: Skips non-configured operations.

=== jreleaser-publish

Publish all distributions. +
Executes the xref:concepts:workflow.adoc#_publish[Publish] workflow step.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to include.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*excludedPackagers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of packagers to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*packagers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the packagers to include.

---

*rejectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths not matching the given platform.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*settingsFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.settings.file
Required:: false
Description:: The settings file.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*strict*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.strict
Required:: false
Description:: Enable strict mode.

---

*yolo*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.yolo
Required:: false
Description: Skips non-configured operations.

=== jreleaser-announce

Announce a release. +
Executes the xref:concepts:workflow.adoc#_announce[Announce] workflow step.

*announcers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the announcers to include.

---

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dry.run
Required:: false
Description: Skips remote operations.

---

*excludedAnnouncers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of announcers to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*settingsFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.settings.file
Required:: false
Description:: The settings file.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*strict*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.strict
Required:: false
Description:: Enable strict mode.

---

*yolo*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.yolo
Required:: false
Description: Skips non-configured operations.

=== jreleaser-full-release

Perform a full release. +
Executes the xref:concepts:workflow.adoc#_full_release[Full Release] workflow step.

*announcers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the announcers to include.

---

*catalogers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of catalogers to include.

---

*deployers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of deployers to include.

---

*deployerNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of deployers to include.

---

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to include.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dry.run
Required:: false
Description: Skips remote operations.

---

*excludedAnnouncers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of announcers to exclude.

---

*excludedCatalogers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of catalogers to exclude.

---

*excludedDeployers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of deployers to exclude.

---

*excludedDeployerNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of deployers to exclude.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*excludedPackagers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of packagers to exclude.

---

*excludedUploaderNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of uploaders to exclude.

---

*excludedUploaderTypes*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of uploaders to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*packagers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the packagers to include.

---

*rejectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths not matching the given platform.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*settingsFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.settings.file
Required:: false
Description:: The settings file.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*strict*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.strict
Required:: false
Description:: Enable strict mode.

---

*uploaderNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of uploaders to include.

---

*uploaderTypes*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of uploaders to include.

---

*yolo*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.yolo
Required:: false
Description: Skips non-configured operations.

=== jreleaser-json-schema

Generate JSON schema.
