= JReleaser Ant Tasks

Executes a JReleaser workflow as Ant tasks.

== Install

Download jreleaser-ant-tasks ZIP bundle from the
link:https://github.com/jreleaser/jreleaser/releases[releases page] and unzip it in your project. Place all JARs inside
the `lib` folder. Create this folder if there is none. Add the following elements to your `build.xml` file

[source,xml]
[subs="verbatim,attributes"]
.build.xml
----
<path id="jreleaser.classpath">
    <fileset dir="lib">
        <include name="jreleaser-ant-tasks-{jreleaser-version}/*.jar"/>
    </fileset>
</path>

<import>
  <javaresource name="org/jreleaser/ant/targets.xml"
                classpathref="jreleaser.classpath"/>
</import>
----

== Configuration

JReleaser must be configured using the YAML, TOML, or JSON DSLs shown at xref:configuration:index.adoc[].

== Environment Variables

The following settings may also be specified via environment variables

|===
| Setting   | Environment Variable         | Default
| outputDir | JRELEASER_OUTPUT_DIRECTORY   | out
|           | JRELEASER_DEFAULT_GIT_REMOTE | origin
|===

== Tasks

The following tasks are provided:

=== jreleaser-init

Create a jreleaser config file.

*format*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.format
Required:: true
Description:: Configuration file format. Currently supported formats are: `yml`, `toml`, `json`.

*overwrite*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.overwrite
Required:: false
Description:: Overwrites existing template files.

=== jreleaser-config

Display current configuration.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*full*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.full
Required:: false
Description:: Display full configuration.

---

*assembly*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.assembly
Required:: false
Description:: Display only assembly configuration.

---

*changelog*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.assembly
Required:: false
Description:: Display only changelog configuration.

*download*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.download
Required:: false
Description:: Display only download configuration.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

=== jreleaser-template

Generate a tool/announcer template.

*distributionName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.distribution.name
Required:: true
Description:: The name of the distribution.

---

*announcerName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.announcer.name
Required:: false
Description:: The name of the announcer to be used.

---

*distributionType*
[horizontal]
Type:: String
Default value:: JAVA_BINARY
Property:: jreleaser.distribution.type
Required:: false
Description:: The name of the distribution.

---

*packagerName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.packager.name
Required:: true
Description:: The name of the packager.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*overwrite*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.overwrite
Required:: false
Description:: Overwrites existing template files.

---

*snapshot*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.snapshot
Required:: false
Description:: Lookup snapshot specific template files.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

=== jreleaser-download

Downloads assets.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*downloaderNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of downloaders to include.

---

*downloaderTypes*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of downloaders to include.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dry.run
Required:: false
Description: Skips remote operations.

---

*excludedDownloaderNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of downloaders to exclude.

---

*excludedDownloaderTypes*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of downloaders to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

=== jreleaser-assemble

Assemble all distributions.

*assemblers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of assemblers to run.

---

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to be assembled.

---

*excludedAssemblers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of assemblers to exclude.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

=== jreleaser-changelog

Calculate the changelog.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

=== jreleaser-checksum

Calculate checksums.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to include.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

=== jreleaser-sign

Sign release artifacts.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to include.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

=== jreleaser-upload

Uploads all files.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to include.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dry.run
Required:: false
Description: Skips remote operations.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*excludedUploaderNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of uploaders to exclude.

---

*excludedUploaderTypes*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of uploaders to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*uploaderNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of uploaders to include.

---

*uploaderTypes*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of uploaders to include.

=== jreleaser-release

Create or update a release.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to include.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*excludedUploaderNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of uploaders to exclude.

---

*excludedUploaderTypes*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of uploaders to exclude.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dry.run
Required:: false
Description: Skips remote operations.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*uploaderNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of uploaders to include.

---

*uploaderTypes*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of uploaders to include.

=== jreleaser-prepare

Prepare all distributions.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to include.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*excludedPackagers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of packagers to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*packagers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the packagers to include.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

=== jreleaser-package

Package all distributions.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to include.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*excludedPackagers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of packagers to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*packagers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the packagers to include.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

=== jreleaser-publish

Publish all distributions.

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to include.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*excludedPackagers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of packagers to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*packagers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the packagers to include.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

=== jreleaser-announce

Announce a release.

*announcers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the announcers to include.

---

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dry.run
Required:: false
Description: Skips remote operations.

---

*excludedAnnouncers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of announcers to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

=== jreleaser-full-release

Perform a full release.


*announcers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the announcers to include.

---

*configFile*
[horizontal]
Type:: File
Default value:: <none>
Property:: jreleaser.config.file
Required:: true
Description:: The config file.

---

*distributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the distributions to include.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dry.run
Required:: false
Description: Skips remote operations.

---

*excludedAnnouncers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of announcers to exclude.

---

*excludedDistributions*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of distributions to exclude.

---

*excludedPackagers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of packagers to exclude.

---

*excludedUploaderNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of uploaders to exclude.

---

*excludedUploaderTypes*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of uploaders to exclude.

---

*outputDir*
[horizontal]
Type:: File
Default value:: "build"
Property:: jreleaser.outputdir
Required:: false
Description:: Overwrites existing template files.

---

*packagers*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Name of the packagers to include.

---

*selectCurrentPlatform*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.select.current.platform
Required:: false
Description:: Activates paths matching the current platform.

---

*selectPlatforms*
[horizontal]
Type:: List<String>
Default value:: []
Property::
Required:: false
Description:: Activates paths matching the given platform.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.skip
Required:: false
Description:: Skips execution of this task.

---

*uploaderNames*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Names of uploaders to include.

---

*uploaderTypes*
[horizontal]
Type:: List<String>
Default value:: <none>
Required:: false
Description:: Types of uploaders to include.
