= JReleaser Gradle Plugin

Executes a JReleaser workflow as a Gradle plugin.

== Install

[source,groovy]
[subs="attributes"]
.build.gradle
----
plugins {
    id 'org.jreleaser' version '{jreleaser-version}'
}
----

== Configuration

JReleaser must be configured using the Gradle DSL shown at xref:configuration:index.adoc[].

== Tasks

The following tasks are provided:

=== jreleaserConfig

Display current configuration.

*full*
[horizontal]
Type:: Boolean
Default value:: false
Option:: full
Required:: false
Description:: Displays full configuration.

*assembly*
[horizontal]
Type:: Boolean
Default value:: false
Option:: assembly
Required:: false
Description:: Displays assembly configuration.

=== jreleaserTemplate

Generate a tool/announcer template.

*announcerName*
[horizontal]
Type:: String
Default value:: <none>
Option:: announcer-name
Required:: false
Description:: The name of the announcer to be used.
---

*distributionName*
[horizontal]
Type:: String
Default value:: <none>
Option:: distribution-name
Required:: true
Description:: The name of the distribution.

---

*distributionType*
[horizontal]
Type:: Distribution.DistributionType
Default value:: JAVA_BINARY
Option:: distribution-type
Required:: false
Description:: The name of the distribution.

---

*toolName*
[horizontal]
Type:: String
Default value:: <none>
Option:: tool-name
Required:: true
Description:: The name of the tool.

---

*overwrite*
[horizontal]
Type:: boolean
Default value:: false
Option:: overwrite
Required:: false
Description:: Overwrites existing template files.

---

*snapshot*
[horizontal]
Type:: boolean
Default value:: false
Option:: snapshot
Required:: false
Description:: Lookup snapshot specific template files.

=== jreleaserAssemble

Assembles distributions

*distributionName*
[horizontal]
Type:: String
Default value:: <none>
Option:: distribution-name
Required:: true
Description:: The name of the distribution.

*assemblerName*
[horizontal]
Type:: String
Default value:: <none>
Option:: assembler-name
Required:: true
Description:: The name of the assembler.

=== jreleaserChangelog

Calculate the changelog.

=== jreleaserChecksum

Calculate checksums.

=== jreleaserSign

Sign release artifacts.

=== jreleaserRelease

Create or update a release

=== jreleaserPrepare

Prepare all distributions.

*distributionName*
[horizontal]
Type:: String
Default value:: <none>
Option:: distribution-name
Required:: false
Description:: The name of the distribution to be prepared.

---

*toolName*
[horizontal]
Type:: String
Default value:: <none>
Option:: tool-name
Required:: false
Description:: The name of the tool for preparing distributions.

=== jreleaserPackage

Package all distributions.

*distributionName*
[horizontal]
Type:: String
Default value:: <none>
Option:: distribution-name
Required:: false
Description:: The name of the distribution to be packaged.

---

*toolName*
[horizontal]
Type:: String
Default value:: <none>
Option:: tool-name
Required:: false
Description:: The name of the tool for packaging distributions.

=== jreleaserPublish

Publish all distributions.

*distributionName*
[horizontal]
Type:: String
Default value:: <none>
Option:: distribution-name
Required:: false
Description:: The name of the distribution to be published.

---

*toolName*
[horizontal]
Type:: String
Default value:: <none>
Option:: tool-name
Required:: false
Description:: The name of the tool for publishing distributions.

=== jreleaserAnnounce

Announce a release.

*announcerName*
[horizontal]
Type:: String
Default value:: <none>
Option:: announcer-name
Required:: false
Description:: The name of the announcer to be used.

=== jreleaserFullRelease

Perform a full release.
