= JReleaser CLI

Executes a JReleaser workflow as a command-line interface (CLI).

[source]
----
JReleaser is a release automation tool for Java projects.
Its goal is to simplify creating releases and publishing
artifacts to multiple package managers while providing
customizable options.

Usage: jreleaser [-hV] [-D=<key=value>]... [COMMAND]

Options:
  -D=<key=value>    Sets a System property. Repeatable.
  -h, --help        Show this help message and exit.
  -V, --version     Print version information and exit.

Commands:
  init                 Create a jreleaser config file.
  config               Display current configuration.
  template             Generate a packager/announcer template.
  download             Download assets.
  assemble             Assemble distributions.
  changelog            Calculate the changelog.
  checksum             Calculate checksums.
  sign                 Sign release artifacts.
  deploy               Deploys all staged artifacts.
  upload               Upload all artifacts.
  release              Create or update a release.
  prepare              Prepare all distributions.
  package              Package all distributions.
  publish              Publish all distributions.
  announce             Announce a release.
  full-release         Perform a full release.
  generate-completion  Generate bash/zsh completion script for jreleaser.
  json-schema          Generate JSON schema.

Documentation found at https://jreleaser.org
----

== Environment Variables

The following settings may also be specified via environment variables

|===
| Setting          | Environment Variable         | Default
| output-directory | JRELEASER_OUTPUT_DIRECTORY   | out
|                  | JRELEASER_DEFAULT_GIT_REMOTE | origin
|===

== Install

[tabs]
====
Windows::
+
--
*sdkman*
[source]
----
sdk install jreleaser
----

*manually*

Download the pre-compiled binary from the link:https://github.com/jreleaser/jreleaser/releases[releases page],
uncompress and copy to the desired location.
--
Linux::
+
--
*sdkman*
[source]
----
sdk install jreleaser
----

*manually*

Download the pre-compiled binary from the link:https://github.com/jreleaser/jreleaser/releases[releases page],
uncompress and copy to the desired location.
--
Mac::
+
--
*homebrew tap*
[source]
----
brew install jreleaser/tap/jreleaser
----

*sdkman*
[source]
----
sdk install jreleaser
----

*manually*

Download the pre-compiled binary from the link:https://github.com/jreleaser/jreleaser/releases[releases page],
uncompress and copy to the desired location.
--
====

== Configuration

JReleaser must be configured using the YAML, TOML, or JSON DSLs shown at xref:configuration:index.adoc[].

== Commands

The following commands are supported:

=== init

[source]
----
$ jreleaser init -h
Create a jreleaser config file.

Usage: jreleaser init [-ghioqVw] [-b=<basedir>] [-f=<format>] [-od=<outputdir>]
                      [-D=<key=value>]...

Options:
  -b, --basedir=<basedir>   Base directory.
  -D=<key=value>            Sets a System property. Repeatable.
  -f, --format=<format>     Configuration file format.
  -g, --debug               Set log level to debug.
  -h, --help                Show this help message and exit.
  -i, --info                Set log level to info.
  -o, --overwrite           Overwrite existing files.
      -od, --output-directory=<outputdir>
                            Output directory.
  -q, --quiet               Log errors only.
  -V, --version             Print version information and exit.
  -w, --warn                Set log level to warn.

Documentation found at https://jreleaser.org
----

Currently supported formats are: `yml`, `json`.

The file will be generated at `<basedir>` if specified, otherwise at the current directory.

=== config

[source]
----
$ jreleaser config -h
Display current configuration.

Usage: jreleaser config [-fghiqVw] [-grs] [-scp] [-b=<basedir>]
                        [-c=<configFile>] [-od=<outputdir>] [-D=<key=value>]...
                        [-P=<key=value>]... [-sp=<platform>]... [--announce |
                        -a | --changelog | -d]

Options:
  -a, --assembly            Display assembly configuration.
      --announce            Display announce configuration.
  -b, --basedir=<basedir>   Base directory.
  -c, --config-file=<configFile>
                            The config file.
      --changelog           Display changelog configuration.
  -d, --download            Display download configuration.
  -D=<key=value>            Sets a System property. Repeatable.
  -f, --full                Display full configuration.
  -g, --debug               Set log level to debug.
      -grs, --git-root-search
                            Searches for the Git root.
  -h, --help                Show this help message and exit.
  -i, --info                Set log level to info.
      -od, --output-directory=<outputdir>
                            Output directory.
  -P, --set-property=<key=value>
                            Sets the value of a property. Repeatable.
  -q, --quiet               Log errors only.
      -scp, --select-current-platform
                            Activates paths matching the current platform.
      -sp, --select-platform=<platform>
                            Activates paths matching the given platform.
                              Repeatable.
  -V, --version             Print version information and exit.
  -w, --warn                Set log level to warn.

Documentation found at https://jreleaser.org
----

If `--config-file` is undefined then the command assumes the file is named `jreleaser.[yml|toml|json]` and it's
found at the current directory.

If `--basedir` is undefined then the command assumes it's the same directory that contains the resolved config file.

=== template

[source]
----
$ jreleaser template -h
Generate a packager/announcer template.

Usage: jreleaser template [-ghioqVw] [-sn] [-b=<basedir>] [-od=<outputdir>]
                          [-D=<key=value>]... ([-a=<announcer>] |
                          [-st=<assembler-type> -s=<assembler-name>] |
                          [-d=<distribution> -p=<packager> [-dt=<type>]])

Options:
  -b, --basedir=<basedir>   Base directory.
  -D=<key=value>            Sets a System property. Repeatable.
  -g, --debug               Set log level to debug.
  -h, --help                Show this help message and exit.
  -i, --info                Set log level to info.
  -o, --overwrite           Overwrite existing files.
      -od, --output-directory=<outputdir>
                            Output directory.
  -q, --quiet               Log errors only.
      -sn, --snapshot       Use snapshot templates.
  -V, --version             Print version information and exit.
  -w, --warn                Set log level to warn.

Announcer templates
  -a, --announcer=<announcer>
                            The name of the announcer.

Assembler templates
  -s, --assembler-name=<assembler-name>
                            The name of the assembler.
      -st, --assembler-type=<assembler-type>
                            The type of the assembler.

Packager templates
  -d, --distribution=<distribution>
                            The name of the distribution.
      -dt, --distribution-type=<type>
                            The type of the distribution.
                            Defaults to JAVA_BINARY.
  -p, --packager=<packager> The name of the packager.

Documentation found at https://jreleaser.org
----

If `--basedir` is undefined then the command assumes it's the current directory.

Announcer and tool settings are mutually exclusive.

The value of `--announcer` must match any of the available xref:configuration:announce/index.adoc[announcers].

The value of `--assembler-type` must match any of the available xref:configuration:assemble/index.adoc[assemblers] while
the value of `--assembler-name` must match any of the available xref:configuration:assemble/index.adoc[assembler names].

The value of `--distribution` must match the name of a configured
xref:configuration:distributions.adoc[distribution].

The value of `--distribution-type` must match any of the available
xref:ROOT:distributions/index.adoc[distribution types].

The value of `--packager` must match any of the available xref:configuration:packagers/index.adoc[].

=== download

[source]
----
$ jreleaser download -h
Download assets.

Usage: jreleaser download [-ghiqVw] [--dry-run] [-grs] [-b=<basedir>]
                          [-c=<configFile>] [-od=<outputdir>]
                          [-D=<key=value>]... [-P=<key=value>]...
                          [[[-d=<downloader>]... [-dn=<name>]...] |
                          [[-xd=<downloader>]... [-xdn=<name>]...]]

Options:
  -b, --basedir=<basedir>   Base directory.
  -c, --config-file=<configFile>
                            The config file.
  -D=<key=value>            Sets a System property. Repeatable.
      --dry-run             Skip remote operations.
  -g, --debug               Set log level to debug.
      -grs, --git-root-search
                            Searches for the Git root.
  -h, --help                Show this help message and exit.
  -i, --info                Set log level to info.
      -od, --output-directory=<outputdir>
                            Output directory.
  -P, --set-property=<key=value>
                            Sets the value of a property. Repeatable.
  -q, --quiet               Log errors only.
  -V, --version             Print version information and exit.
  -w, --warn                Set log level to warn.

Include Filter:
  -d, --downloader=<downloader>
                            Include an downloader by type. Repeatable.
      -dn, --downloader-name=<name>
                            Include an downloader by name. Repeatable.

Exclude Filter:
      -xd, --exclude-downloader=<downloader>
                            Exclude an downloader by type. Repeatable.
      -xdn, --exclude-downloader-name=<name>
                            Exclude an downloader by name. Repeatable.

Documentation found at https://jreleaser.org
----

If `--config-file` is undefined then the command assumes the file is named `jreleaser.[yml|toml|json]` and it's
found at the current directory.

If `--basedir` is undefined then the command assumes it's the same directory that contains the resolved config file.

The value of `--downloader` and `--exclude-downloader-type` must match the type of configured
xref:configuration:download/index.adoc[downloader].

The value of `--downloader-name` and `--exclude-downloader-name` must match any of the available named
xref:configuration:download/index.adoc[downloaders].

This command must be invoked separately from the others.

=== assemble

[source]
----
$ jreleaser assemble -h
Assemble distributions.

Usage: jreleaser assemble [-ghiqVw] [-grs] [-scp] [-b=<basedir>]
                          [-c=<configFile>] [-od=<outputdir>]
                          [-D=<key=value>]... [-P=<key=value>]...
                          [-sp=<platform>]... [[[-s=<assembler>]...
                          [-d=<distribution>]...] | [[-xs=<assembler>]...
                          [-xd=<distribution>]...]]

Options:
  -b, --basedir=<basedir>   Base directory.
  -c, --config-file=<configFile>
                            The config file.
  -D=<key=value>            Sets a System property. Repeatable.
  -g, --debug               Set log level to debug.
      -grs, --git-root-search
                            Searches for the Git root.
  -h, --help                Show this help message and exit.
  -i, --info                Set log level to info.
      -od, --output-directory=<outputdir>
                            Output directory.
  -P, --set-property=<key=value>
                            Sets the value of a property. Repeatable.
  -q, --quiet               Log errors only.
      -scp, --select-current-platform
                            Activates paths matching the current platform.
      -sp, --select-platform=<platform>
                            Activates paths matching the given platform.
                              Repeatable.
  -V, --version             Print version information and exit.
  -w, --warn                Set log level to warn.

Include Filter:
  -d, --distribution=<distribution>
                            Include a distribution. Repeatable.
  -s, --assembler=<assembler>
                            Include an assembler. Repeatable.

Exclude Filter:
      -xd, --exclude-distribution=<distribution>
                            Exclude a distribution. Repeatable.
      -xs, --exclude-assembler=<assembler>
                            Exclude an assembler. Repeatable.

Documentation found at https://jreleaser.org
----

If `--config-file` is undefined then the command assumes the file is named `jreleaser.[yml|toml|json]` and it's
found at the current directory.

If `--basedir` is undefined then the command assumes it's the same directory that contains the resolved config file.

The value of `--assembler` and `--exclude-assembler` must match any of the available
xref:configuration:assemble/index.adoc[assemblers].

The value of `--distribution` and `--exclude-distribution` must match the name of a configured assembler found in the
xref:configuration:assemble/index.adoc[assemblers] section.

This command must be invoked separately from the others as some assemblers are platform specific.

=== changelog

[source]
----
$ jreleaser changelog -h
Calculate the changelog.

Usage: jreleaser changelog [-ghiqVw] [-grs] [-b=<basedir>] [-c=<configFile>]
                           [-od=<outputdir>] [-D=<key=value>]...
                           [-P=<key=value>]...

Options:
  -b, --basedir=<basedir>   Base directory.
  -c, --config-file=<configFile>
                            The config file.
  -D=<key=value>            Sets a System property. Repeatable.
  -g, --debug               Set log level to debug.
      -grs, --git-root-search
                            Searches for the Git root.
  -h, --help                Show this help message and exit.
  -i, --info                Set log level to info.
      -od, --output-directory=<outputdir>
                            Output directory.
  -P, --set-property=<key=value>
                            Sets the value of a property. Repeatable.
  -q, --quiet               Log errors only.
  -V, --version             Print version information and exit.
  -w, --warn                Set log level to warn.

Documentation found at https://jreleaser.org
----

If `--config-file` is undefined then the command assumes the file is named `jreleaser.[yml|toml|json]` and it's
found at the current directory.

If `--basedir` is undefined then the command assumes it's the same directory that contains the resolved config file.

=== checksum

[source]
----
$ jreleaser checksum -h
Calculate checksums.

Usage: jreleaser checksum [-ghiqVw] [-grs] [-scp] [-b=<basedir>]
                          [-c=<configFile>] [-od=<outputdir>]
                          [-D=<key=value>]... [-P=<key=value>]...
                          [-sp=<platform>]... [[[-d=<distribution>]...] |
                          [[-xd=<distribution>]...]]

Options:
  -b, --basedir=<basedir>   Base directory.
  -c, --config-file=<configFile>
                            The config file.
  -D=<key=value>            Sets a System property. Repeatable.
  -g, --debug               Set log level to debug.
      -grs, --git-root-search
                            Searches for the Git root.
  -h, --help                Show this help message and exit.
  -i, --info                Set log level to info.
      -od, --output-directory=<outputdir>
                            Output directory.
  -P, --set-property=<key=value>
                            Sets the value of a property. Repeatable.
  -q, --quiet               Log errors only.
      -scp, --select-current-platform
                            Activates paths matching the current platform.
      -sp, --select-platform=<platform>
                            Activates paths matching the given platform.
                              Repeatable.
  -V, --version             Print version information and exit.
  -w, --warn                Set log level to warn.

Include Filter:
  -d, --distribution=<distribution>
                            Include a distribution. Repeatable.

Exclude Filter:
      -xd, --exclude-distribution=<distribution>
                            Exclude a distribution. Repeatable.

Documentation found at https://jreleaser.org
----

If `--config-file` is undefined then the command assumes the file is named `jreleaser.[yml|toml|json]` and it's
found at the current directory.

If `--basedir` is undefined then the command assumes it's the same directory that contains the resolved config file.

The value of `--distribution` and `--exclude-distribution` must match the name of a configured distribution found
in the xref:configuration:distributions.adoc[distribution] section.

=== sign

[source]
----
$ jreleaser sign -h
Sign release artifacts.

Usage: jreleaser sign [-ghiqVw] [-grs] [-scp] [-b=<basedir>] [-c=<configFile>]
                      [-od=<outputdir>] [-D=<key=value>]... [-P=<key=value>]...
                      [-sp=<platform>]... [[[-d=<distribution>]...] |
                      [[-xd=<distribution>]...]]

Options:
  -b, --basedir=<basedir>   Base directory.
  -c, --config-file=<configFile>
                            The config file.
  -D=<key=value>            Sets a System property. Repeatable.
  -g, --debug               Set log level to debug.
      -grs, --git-root-search
                            Searches for the Git root.
  -h, --help                Show this help message and exit.
  -i, --info                Set log level to info.
      -od, --output-directory=<outputdir>
                            Output directory.
  -P, --set-property=<key=value>
                            Sets the value of a property. Repeatable.
  -q, --quiet               Log errors only.
      -scp, --select-current-platform
                            Activates paths matching the current platform.
      -sp, --select-platform=<platform>
                            Activates paths matching the given platform.
                              Repeatable.
  -V, --version             Print version information and exit.
  -w, --warn                Set log level to warn.

Include Filter:
  -d, --distribution=<distribution>
                            Include a distribution. Repeatable.

Exclude Filter:
      -xd, --exclude-distribution=<distribution>
                            Exclude a distribution. Repeatable.

Documentation found at https://jreleaser.org
----

If `--config-file` is undefined then the command assumes the file is named `jreleaser.[yml|toml|json]` and it's
found at the current directory.

If `--basedir` is undefined then the command assumes it's the same directory that contains the resolved config file.

The value of `--distribution` and `--exclude-distribution` must match the name of a configured distribution found
in the xref:configuration:distributions.adoc[distribution] section.

=== deploy

[source]
----
$ jreleaser deploy -h
Deploys all staged artifacts.

Usage: jreleaser deploy [-ghiqVw] [--dry-run] [-grs] [-scp] [-b=<basedir>]
                        [-c=<configFile>] [-od=<outputdir>] [-D=<key=value>]...
                        [-P=<key=value>]... [-sp=<platform>]...
                        [[[-y=<deployer>]... [-yn=<name>]...] |
                        [[-xy=<deployer>]... [-xyn=<name>]...]]

Options:
  -b, --basedir=<basedir>   Base directory.
  -c, --config-file=<configFile>
                            The config file.
  -D=<key=value>            Sets a System property. Repeatable.
      --dry-run             Skip remote operations.
  -g, --debug               Set log level to debug.
      -grs, --git-root-search
                            Searches for the Git root.
  -h, --help                Show this help message and exit.
  -i, --info                Set log level to info.
      -od, --output-directory=<outputdir>
                            Output directory.
  -P, --set-property=<key=value>
                            Sets the value of a property. Repeatable.
  -q, --quiet               Log errors only.
      -scp, --select-current-platform
                            Activates paths matching the current platform.
      -sp, --select-platform=<platform>
                            Activates paths matching the given platform.
                              Repeatable.
  -V, --version             Print version information and exit.
  -w, --warn                Set log level to warn.

Include Filter:
  -y, --deployer=<deployer> Include a deployer by type. Repeatable.
      -yn, --deployer-name=<name>
                            Include a deployer by name. Repeatable.

Exclude Filter:
      -xy, --exclude-deployer=<deployer>
                            Exclude a deployer by type. Repeatable.
      -xyn, --exclude-deployer-name=<name>
                            Exclude a deployer by name. Repeatable.

Documentation found at https://jreleaser.org
----

If `--config-file` is undefined then the command assumes the file is named `jreleaser.[yml|toml|json]` and it's
found at the current directory.

If `--basedir` is undefined then the command assumes it's the same directory that contains the resolved config file.

The value of `--deployer` and `--exclude-deployer` must match the type of configured
xref:configuration:deploy/index.adoc[deployer].

The value of `--deployer-name` and `--exclude-deployer-name` must match any of the available named
xref:configuration:deploy/index.adoc[deployers].

NOTE: Use `--dry-run` during development to verify your configuration settings. No network deploys nor repository
mutations should occur when this mode is activated.

You may invoke this command in the following ways:

Deploy all artifacts:
[source]
----
$ jreleaser deploy
----

Deploy all artifacts to all configured Artifactory deployers:
[source]
----
$ jreleaser deploy --deployer artifactory
----

Deploy all artifacts with all deployers with matching name:
[source]
----
$ jreleaser deploy --deployer-name mine
----

Deploy all artifacts to a matching Artifactory deployer:
[source]
----
$ jreleaser deploy --deployer artifactory --deployer-name mine
----

=== upload

[source]
----
$ jreleaser upload -h
Upload all artifacts.

Usage: jreleaser upload [-ghiqVw] [--dry-run] [-grs] [-scp] [-b=<basedir>]
                        [-c=<configFile>] [-od=<outputdir>] [-D=<key=value>]...
                        [-P=<key=value>]... [-sp=<platform>]...
                        [[[-u=<uploader>]... [-un=<name>]...
                        [-d=<distribution>]...] | [[-xu=<uploader>]...
                        [-xun=<name>]... [-xd=<distribution>]...]]

Options:
  -b, --basedir=<basedir>   Base directory.
  -c, --config-file=<configFile>
                            The config file.
  -D=<key=value>            Sets a System property. Repeatable.
      --dry-run             Skip remote operations.
  -g, --debug               Set log level to debug.
      -grs, --git-root-search
                            Searches for the Git root.
  -h, --help                Show this help message and exit.
  -i, --info                Set log level to info.
      -od, --output-directory=<outputdir>
                            Output directory.
  -P, --set-property=<key=value>
                            Sets the value of a property. Repeatable.
  -q, --quiet               Log errors only.
      -scp, --select-current-platform
                            Activates paths matching the current platform.
      -sp, --select-platform=<platform>
                            Activates paths matching the given platform.
                              Repeatable.
  -V, --version             Print version information and exit.
  -w, --warn                Set log level to warn.

Include Filter:
  -d, --distribution=<distribution>
                            Include a distribution. Repeatable.
  -u, --uploader=<uploader> Include an uploader by type. Repeatable.
      -un, --uploader-name=<name>
                            Include an uploader by name. Repeatable.

Exclude Filter:
      -xd, --exclude-distribution=<distribution>
                            Exclude a distribution. Repeatable.
      -xu, --exclude-uploader=<uploader>
                            Exclude an uploader by type. Repeatable.
      -xun, --exclude-uploader-name=<name>
                            Exclude an uploader by name. Repeatable.

Documentation found at https://jreleaser.org
----

If `--config-file` is undefined then the command assumes the file is named `jreleaser.[yml|toml|json]` and it's
found at the current directory.

If `--basedir` is undefined then the command assumes it's the same directory that contains the resolved config file.

The value of `--uploader` and `--exclude-uploader-type` must match the type of configured
xref:configuration:upload/index.adoc[uploader].

The value of `--uploader-name` and `--exclude-uploader-name` must match any of the available named
xref:configuration:upload/index.adoc[uploaders].

NOTE: Use `--dry-run` during development to verify your configuration settings. No network uploads nor repository
mutations should occur when this mode is activated.

You may invoke this command in the following ways:

Upload all artifacts:
[source]
----
$ jreleaser upload
----

Upload all artifacts to all configured Artifactory uploaders:
[source]
----
$ jreleaser upload --uploader-type artifactory
----

Upload all artifacts with all uploaders with matching name:
[source]
----
$ jreleaser upload --uploader-name mine
----

Upload all artifacts to a matching Artifactory uploader:
[source]
----
$ jreleaser upload --uploader-type artifactory --uploader-name mine
----

=== release

[source]
----
$ jreleaser release -h
Create or update a release.

Usage: jreleaser release [-ghiqVw] [--dry-run] [-grs] [-scp] [-b=<basedir>]
                         [-c=<configFile>] [-od=<outputdir>]
                         [-D=<key=value>]... [-P=<key=value>]...
                         [-sp=<platform>]... [[[-d=<distribution>]...
                         [-y=<deployer>]... [-yn=<name>]... [-u=<uploader>]...
                         [-un=<name>]...] | [[-xd=<distribution>]...
                         [-xy=<deployer>]... [-xyn=<name>]...
                         [-xu=<uploader>]... [-xun=<name>]...] |
                         [[--auto-config] [--project-name=<projectName>]
                         [--project-version=<projectVersion>]
                         [--project-version-pattern=<projectVersionPattern>]
                         [--project-snapshot-pattern=<projectSnapshotPattern>]
                         [--project-snapshot-label=<projectSnapshotLabel>]
                         [--project-snapshot-full-changelog]
                         [--project-copyright=<projectCopyright>]
                         [--project-description=<projectDescription>]
                         [--project-inception-year=<projectInceptionYear>]
                         [--project-stereotype=<projectStereotype>]
                         [--author=<author>]... [--tag-name=<tagName>]
                         [--previous-tag-name=<previousTagName>]
                         [--release-name=<releaseName>]
                         [--milestone-name=<milestoneName>] [--prerelease]
                         [--prerelease-pattern=<prereleasePattern>] [--draft]
                         [--overwrite] [--update]
                         [--update-section=<section>]... [--skip-tag]
                         [--skip-release] [--branch=<branch>]
                         [--changelog=<changelog>] [--changelog-formatted]
                         [--username=<username>]
                         [--commit-author-name=<commitAuthorName>]
                         [--commit-author-email=<commitAuthorEmail>]
                         [--signing-enabled] [--signing-armored]
                         [--file=<file>]... [--glob=<glob>]...]]

Options:
  -b, --basedir=<basedir>    Base directory.
  -c, --config-file=<configFile>
                             The config file.
  -D=<key=value>             Sets a System property. Repeatable.
      --dry-run              Skip remote operations.
  -g, --debug                Set log level to debug.
      -grs, --git-root-search
                             Searches for the Git root.
  -h, --help                 Show this help message and exit.
  -i, --info                 Set log level to info.
      -od, --output-directory=<outputdir>
                             Output directory.
  -P, --set-property=<key=value>
                             Sets the value of a property. Repeatable.
  -q, --quiet                Log errors only.
      -scp, --select-current-platform
                             Activates paths matching the current platform.
      -sp, --select-platform=<platform>
                             Activates paths matching the given platform.
                               Repeatable.
  -V, --version              Print version information and exit.
  -w, --warn                 Set log level to warn.

Include Filter:
  -d, --distribution=<distribution>
                             Include a distribution. Repeatable.
  -u, --uploader=<uploader>  Include an uploader by type. Repeatable.
      -un, --uploader-name=<name>
                             Include an uploader by name. Repeatable.
  -y, --deployer=<deployer>  Include a deployer by type. Repeatable.
      -yn, --deployer-name=<name>
                             Include a deployer by name. Repeatable.

Exclude Filter:
      -xd, --exclude-distribution=<distribution>
                             Exclude a distribution. Repeatable.
      -xu, --exclude-uploader=<uploader>
                             Exclude an uploader by type. Repeatable.
      -xun, --exclude-uploader-name=<name>
                             Exclude an uploader by name. Repeatable.
      -xy, --exclude-deployer=<deployer>
                             Exclude a deployer by type. Repeatable.
      -xyn, --exclude-deployer-name=<name>
                             Exclude a deployer by name. Repeatable.

Auto Config Options:
      --author=<author>      The project authors. Repeatable.
      --auto-config          Activate auto configuration.
      --branch=<branch>      The release branch.
      --changelog=<changelog>
                             Path to changelog file.
      --changelog-formatted  Format generated changelog.
      --commit-author-email=<commitAuthorEmail>
                             Commit author e-mail.
      --commit-author-name=<commitAuthorName>
                             Commit author name.
      --draft                If the release is a draft.
      --file=<file>          Input file to be uploaded. Repeatable.
      --glob=<glob>          Input file to be uploaded (as glob). Repeatable.
      --milestone-name=<milestoneName>
                             The milestone name.
      --overwrite            Overwrite an existing release.
      --prerelease           If the release is a prerelease.
      --prerelease-pattern=<prereleasePattern>
                             The prerelease pattern.
      --previous-tag-name=<previousTagName>
                             The previous release tag.
      --project-copyright=<projectCopyright>
                             The project copyright.
      --project-description=<projectDescription>
                             The project description.
      --project-inception-year=<projectInceptionYear>
                             The project inception year.
      --project-name=<projectName>
                             The project name.
      --project-snapshot-full-changelog
                             Calculate full changelog since last non-snapshot
                               release.
      --project-snapshot-label=<projectSnapshotLabel>
                             The project snapshot label.
      --project-snapshot-pattern=<projectSnapshotPattern>
                             The project snapshot pattern.
      --project-stereotype=<projectStereotype>
                             The project stereotype.
      --project-version=<projectVersion>
                             The project version.
      --project-version-pattern=<projectVersionPattern>
                             The project version pattern.
      --release-name=<releaseName>
                             The release name.
      --signing-armored      Generate ascii armored signatures.
      --signing-enabled      Sign files.
      --skip-release         Skip creating a release.
      --skip-tag             Skip tagging the release.
      --tag-name=<tagName>   The release tag.
      --update               Update an existing release.
      --update-section=<section>
                             Release section to be updated. Repeatable.
      --username=<username>  Git username.

Documentation found at https://jreleaser.org
----

There are two usage modes:

 * auto config
 * with explicit configuration file

*AutoConfig*

If `--basedir` is undefined then the command assumes it's the same directory where the command is run.

The `--file` parameter is repeatable.

The `--glob` parameter must be quote, for example `--glob "target/*.jar"`.

*Explicit Configuration file*

If `--config-file` is undefined then the command assumes the file is named `jreleaser.[yml|toml|json]` and it's
found at the current directory.

If `--basedir` is undefined then the command assumes it's the same directory that contains the resolved config file.

The value of `--distribution` and `--exclude-distribution` must match the name of a configured distribution found
in the xref:configuration:distributions.adoc[distribution] section.

IMPORTANT: None of the command flags that override model properties can be used in this mode.

NOTE: Use `--dry-run` during development to verify your configuration settings. No network uploads nor repository
mutations should occur when this mode is activated.

=== prepare

[source]
----
$ jreleaser prepare -h
Prepare all distributions.

Usage: jreleaser prepare [-ghiqVw] [-grs] [-scp] [-b=<basedir>]
                         [-c=<configFile>] [-od=<outputdir>]
                         [-D=<key=value>]... [-P=<key=value>]...
                         [-sp=<platform>]... [[[-d=<distribution>]...
                         [-p=<packager>]...] | [[-xd=<distribution>]...
                         [-xp=<packager>]...]]

Options:
  -b, --basedir=<basedir>   Base directory.
  -c, --config-file=<configFile>
                            The config file.
  -D=<key=value>            Sets a System property. Repeatable.
  -g, --debug               Set log level to debug.
      -grs, --git-root-search
                            Searches for the Git root.
  -h, --help                Show this help message and exit.
  -i, --info                Set log level to info.
      -od, --output-directory=<outputdir>
                            Output directory.
  -P, --set-property=<key=value>
                            Sets the value of a property. Repeatable.
  -q, --quiet               Log errors only.
      -scp, --select-current-platform
                            Activates paths matching the current platform.
      -sp, --select-platform=<platform>
                            Activates paths matching the given platform.
                              Repeatable.
  -V, --version             Print version information and exit.
  -w, --warn                Set log level to warn.

Include Filter:
  -d, --distribution=<distribution>
                            Include a distribution. Repeatable.
  -p, --packager=<packager> Include a packager. Repeatable.

Exclude Filter:
      -xd, --exclude-distribution=<distribution>
                            Exclude a distribution. Repeatable.
      -xp, --exclude-packager=<packager>
                            Exclude a packager. Repeatable.

Documentation found at https://jreleaser.org
----

If `--config-file` is undefined then the command assumes the file is named `jreleaser.[yml|toml|json]` and it's
found at the current directory.

If `--basedir` is undefined then the command assumes it's the same directory that contains the resolved config file.

The value of `--distribution` and `--exclude-distribution` must match the name of a configured
xref:configuration:distributions.adoc[distribution].

The value of `--packager` and `--exclude-packager` must match any of the available
xref:configuration:packagers/index.adoc[].

You may invoke this command in the following ways:

Prepare all distributions:
[source]
----
$ jreleaser prepare
----

Prepare a single distribution with all configured tools:
[source]
----
$ jreleaser prepare --distribution-name app
----

Prepare all distributions with a single tool:
[source]
----
$ jreleaser prepare --packager-name brew
----

Prepare a single distribution with a single tool:
[source]
----
$ jreleaser prepare --distribution-name app --packager-name brew
----

=== package

[source]
----
$ jreleaser package -h
Package all distributions.

Usage: jreleaser package [-ghiqVw] [--dry-run] [-grs] [-scp] [-b=<basedir>]
                         [-c=<configFile>] [-od=<outputdir>]
                         [-D=<key=value>]... [-P=<key=value>]...
                         [-sp=<platform>]... [[[-d=<distribution>]...
                         [-p=<packager>]...] | [[-xd=<distribution>]...
                         [-xp=<packager>]...]]

Options:
  -b, --basedir=<basedir>   Base directory.
  -c, --config-file=<configFile>
                            The config file.
  -D=<key=value>            Sets a System property. Repeatable.
      --dry-run             Skip remote operations.
  -g, --debug               Set log level to debug.
      -grs, --git-root-search
                            Searches for the Git root.
  -h, --help                Show this help message and exit.
  -i, --info                Set log level to info.
      -od, --output-directory=<outputdir>
                            Output directory.
  -P, --set-property=<key=value>
                            Sets the value of a property. Repeatable.
  -q, --quiet               Log errors only.
      -scp, --select-current-platform
                            Activates paths matching the current platform.
      -sp, --select-platform=<platform>
                            Activates paths matching the given platform.
                              Repeatable.
  -V, --version             Print version information and exit.
  -w, --warn                Set log level to warn.

Include Filter:
  -d, --distribution=<distribution>
                            Include a distribution. Repeatable.
  -p, --packager=<packager> Include a packager. Repeatable.

Exclude Filter:
      -xd, --exclude-distribution=<distribution>
                            Exclude a distribution. Repeatable.
      -xp, --exclude-packager=<packager>
                            Exclude a packager. Repeatable.

Documentation found at https://jreleaser.org
----

If `--config-file` is undefined then the command assumes the file is named `jreleaser.[yml|toml|json]` and it's
found at the current directory.

If `--basedir` is undefined then the command assumes it's the same directory that contains the resolved config file.

The value of `--distribution` and `--exclude-distribution` must match the name of a configured
xref:configuration:distributions.adoc[distribution].

The value of `--packager` and `--exclude-packager` must match any of the available
xref:configuration:packagers/index.adoc[].

You may invoke this command in the following ways:

Package all distributions:
[source]
----
$ jreleaser package
----

Package a single distribution with all configured tools:
[source]
----
$ jreleaser package --distribution-name app
----

Package all distributions with a single tool:
[source]
----
$ jreleaser package --packager-name brew
----

Package a single distribution with a single tool:
[source]
----
$ jreleaser package --distribution-name app --packager-name brew
----

NOTE: Use `--dry-run` during development to verify your configuration settings. No network uploads nor repository
mutations should occur when this mode is activated.

=== publish

[source]
----
$ jreleaser publish -h
Publish all distributions.

Usage: jreleaser publish [-ghiqVw] [--dry-run] [-grs] [-scp] [-b=<basedir>]
                         [-c=<configFile>] [-od=<outputdir>]
                         [-D=<key=value>]... [-P=<key=value>]...
                         [-sp=<platform>]... [[[-d=<distribution>]...
                         [-p=<packager>]...] | [[-xd=<distribution>]...
                         [-xp=<packager>]...]]

Options:
  -b, --basedir=<basedir>   Base directory.
  -c, --config-file=<configFile>
                            The config file.
  -D=<key=value>            Sets a System property. Repeatable.
      --dry-run             Skip remote operations.
  -g, --debug               Set log level to debug.
      -grs, --git-root-search
                            Searches for the Git root.
  -h, --help                Show this help message and exit.
  -i, --info                Set log level to info.
      -od, --output-directory=<outputdir>
                            Output directory.
  -P, --set-property=<key=value>
                            Sets the value of a property. Repeatable.
  -q, --quiet               Log errors only.
      -scp, --select-current-platform
                            Activates paths matching the current platform.
      -sp, --select-platform=<platform>
                            Activates paths matching the given platform.
                              Repeatable.
  -V, --version             Print version information and exit.
  -w, --warn                Set log level to warn.

Include Filter:
  -d, --distribution=<distribution>
                            Include a distribution. Repeatable.
  -p, --packager=<packager> Include a packager. Repeatable.

Exclude Filter:
      -xd, --exclude-distribution=<distribution>
                            Exclude a distribution. Repeatable.
      -xp, --exclude-packager=<packager>
                            Exclude a packager. Repeatable.

Documentation found at https://jreleaser.org
----
 
If `--config-file` is undefined then the command assumes the file is named `jreleaser.[yml|toml|json]` and it's
found at the current directory.

If `--basedir` is undefined then the command assumes it's the same directory that contains the resolved config file.

The value of `--distribution` and `--exclude-distribution` must match the name of a configured
xref:configuration:distributions.adoc[distribution].

The value of `--packager` and `--exclude-packager` must match any of the available
xref:configuration:packagers/index.adoc[].

You may invoke this command in the following ways:

Publish all distributions:
[source]
----
$ jreleaser publish
----

Publish a single distribution with all configured tools:
[source]
----
$ jreleaser publish --distribution-name app
----

Publish all distributions with a single tool:
[source]
----
$ jreleaser publish --packager-name brew
----

Publish a single distribution with a single tool:
[source]
----
$ jreleaser publish --distribution-name app --packager-name brew
----

NOTE: Use `--dry-run` during development to verify your configuration settings. No network uploads nor repository
mutations should occur when this mode is activated.

=== announce

[source]
----
$ jreleaser announce -h
Announce a release.

Usage: jreleaser announce [-ghiqVw] [--dry-run] [-grs] [-scp] [-b=<basedir>]
                          [-c=<configFile>] [-od=<outputdir>]
                          [-D=<key=value>]... [-P=<key=value>]...
                          [-sp=<platform>]... [[[-a=<announcer>]...] |
                          [[-xa=<announcer>]...]]

Options:
  -b, --basedir=<basedir>   Base directory.
  -c, --config-file=<configFile>
                            The config file.
  -D=<key=value>            Sets a System property. Repeatable.
      --dry-run             Skip remote operations.
  -g, --debug               Set log level to debug.
      -grs, --git-root-search
                            Searches for the Git root.
  -h, --help                Show this help message and exit.
  -i, --info                Set log level to info.
      -od, --output-directory=<outputdir>
                            Output directory.
  -P, --set-property=<key=value>
                            Sets the value of a property. Repeatable.
  -q, --quiet               Log errors only.
      -scp, --select-current-platform
                            Activates paths matching the current platform.
      -sp, --select-platform=<platform>
                            Activates paths matching the given platform.
                              Repeatable.
  -V, --version             Print version information and exit.
  -w, --warn                Set log level to warn.

Include Filter:
  -a, --announcer=<announcer>
                            Include an announcer. Repeatable.

Exclude Filter:
      -xa, --exclude-announcer=<announcer>
                            Exclude an announcer. Repeatable.

Documentation found at https://jreleaser.org
----

If `--config-file` is undefined then the command assumes the file is named `jreleaser.[yml|toml|json]` and it's
found at the current directory.

If `--basedir` is undefined then the command assumes it's the same directory that contains the resolved config file.

The value of `--announcer` and `--exclude-announcer` must match any of the available
xref:configuration:announce/index.adoc[announcers].

You may invoke this command in the following ways:

Announce with all configured announcers:
[source]
----
$ jreleaser announce
----

Announce with a single announcer:
[source]
----
$ jreleaser announce --announcer-name brew
----

NOTE: Use `--dry-run` during development to verify your configuration settings. No network uploads nor repository
mutations should occur when this mode is activated.

=== full-release

[source]
----
$ jreleaser full-release -h
Perform a full release.

Usage: jreleaser full-release [-ghiqVw] [--dry-run] [-grs] [-scp]
                              [-b=<basedir>] [-c=<configFile>]
                              [-od=<outputdir>] [-D=<key=value>]...
                              [-P=<key=value>]... [-sp=<platform>]...
                              [[[-y=<deployer>]... [-yn=<name>]...
                              [-u=<uploader>]... [-un=<name>]...
                              [-d=<distribution>]... [-p=<packager>]...
                              [-a=<announcer>]...] | [[-xy=<deployer>]...
                              [-xyn=<name>]... [-xu=<uploader>]...
                              [-xun=<name>]... [-xd=<distribution>]...
                              [-xp=<packager>]... [-xa=<announcer>]...]]

Options:
  -b, --basedir=<basedir>   Base directory.
  -c, --config-file=<configFile>
                            The config file.
  -D=<key=value>            Sets a System property. Repeatable.
      --dry-run             Skip remote operations.
  -g, --debug               Set log level to debug.
      -grs, --git-root-search
                            Searches for the Git root.
  -h, --help                Show this help message and exit.
  -i, --info                Set log level to info.
      -od, --output-directory=<outputdir>
                            Output directory.
  -P, --set-property=<key=value>
                            Sets the value of a property. Repeatable.
  -q, --quiet               Log errors only.
      -scp, --select-current-platform
                            Activates paths matching the current platform.
      -sp, --select-platform=<platform>
                            Activates paths matching the given platform.
                              Repeatable.
  -V, --version             Print version information and exit.
  -w, --warn                Set log level to warn.

Include Filter:
  -a, --announcer=<announcer>
                            Include an announcer. Repeatable.
  -d, --distribution=<distribution>
                            Include a distribution. Repeatable.
  -p, --packager=<packager> Include a packager. Repeatable.
  -u, --uploader=<uploader> Include an uploader by type. Repeatable.
      -un, --uploader-name=<name>
                            Include an uploader by name. Repeatable.
  -y, --deployer=<deployer> Include a deployer by type. Repeatable.
      -yn, --deployer-name=<name>
                            Include a deployer by name. Repeatable.

Exclude Filter:
      -xa, --exclude-announcer=<announcer>
                            Exclude an announcer. Repeatable.
      -xd, --exclude-distribution=<distribution>
                            Exclude a distribution. Repeatable.
      -xp, --exclude-packager=<packager>
                            Exclude a packager. Repeatable.
      -xu, --exclude-uploader=<uploader>
                            Exclude an uploader by type. Repeatable.
      -xun, --exclude-uploader-name=<name>
                            Exclude an uploader by name. Repeatable.
      -xy, --exclude-deployer=<deployer>
                            Exclude a deployer by type. Repeatable.
      -xyn, --exclude-deployer-name=<name>
                            Exclude a deployer by name. Repeatable.

Documentation found at https://jreleaser.org
----

If `--config-file` is undefined then the command assumes the file is named `jreleaser.[yml|toml|json]` and it's
found at the current directory.

If `--basedir` is undefined then the command assumes it's the same directory that contains the resolved config file.

NOTE: Use `--dry-run` during development to verify your configuration settings. No network uploads nor repository
mutations should occur when this mode is activated.

=== generate-completion

[source]
----
$ jreleaser jreleaser generate-completion -h
JReleaser is a release automation tool for Java projects.

Usage: jreleaser generate-completion [-hV]
Generate bash/zsh completion script for jreleaser.
Run the following command to give `jreleaser` TAB completion in the current
shell:

  source <(jreleaser generate-completion)


Options:
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.

Documentation found at https://jreleaser.org
----

=== json-schema

[source]
----
$ jreleaser json-schema -h
Generate JSON schema.

Usage: jreleaser json-schema [-hV] [-D=<key=value>]...

Options:
  -D=<key=value>    Sets a System property. Repeatable.
  -h, --help        Show this help message and exit.
  -V, --version     Print version information and exit.

Documentation found at https://jreleaser.org
----
