= JReleaser Maven Plugin

Executes a JReleaser workflow as a Maven plugin.

== Install

[source,xml]
[subs="verbatim,attributes"]
.pom.xml
----
<plugin>
  <groupId>org.jreleaser</groupId>
  <artifactId>jreleaser-maven-plugin</artifactId>
  <version>{jreleaser-version}</version>
  <inherited>false</inherited>
</plugin>
----

WARNING: Maven plugins are inherited by default. Make sure to set `<inherited>false</inherited>` when configuring this
plugin in a multi-module setup.

== Configuration

JReleaser may be configured using the Maven DSL shown at xref:reference:index.adoc[]. Alternatively, an external
configuration file may be used if the `<configFile>` field or `jreleaser.config.file` property is set.

=== Defaults

The following values will be taken directly from the `pom.xml` file and added to JReleaser's configuration when
the matching JReleaser element has not been explicitly configured:

[%header, cols="<1,<1", width="100%"]
|===
| POM                      | JReleaser
| project.artifactId       | project.name
| project.version          | project.version
| project.description      | project.description
| project.url              | project.links.homepage
| project.organization.url | project.links.homepage
| project.groupId          | project.java.groupId
| project.artifactId       | project.java.artifactId
| project.inceptionYear    | project.inceptionYear
|===

The value of `project.java.multiProject` will be set to true if the current Maven session has more than 1 project.

The value of `project.authors` will be resolved by matching all `<developer>` entries that have an `author` role. If no
developer entries are found then all developers will be added as authors. The value of `<developer><name>` will be queried
first, if not found then `<developer><id>` will be used as fallback.

The value of `project.license` will be resolved from `<licenses>` with the first `<license>` that defines `<name>`.

The value of `project.java.version` will be determined following these expressions in order:

 * `${maven.compiler.release}`
 * `${maven.compiler.target}`
 * `${maven.compiler.source}`
 * `System.getProperty("java.version")`

== Environment Variables

The following settings may also be specified via environment variables

[options="header", cols="3*"]
|===
| Setting                 | Environment Variable              | Default
|                         | JRELEASER_BASEDIR                 | <current-execution-directory>
| <dryrun>                | JRELEASER_DRY_RUN                 | false
| <strict>                | JRELEASER_STRICT                  | false
| <yolo>                  | JRELEASER_YOLO                    | false
| <gitRootSearch>         | JRELEASER_GIT_ROOT_SEARCH         | false
| <selectCurrentPlatform> | JRELEASER_SELECT_CURRENT_PLATFORM | false
| <selectPlatforms>       | JRELEASER_SELECT_PLATFORMS        | <empty-string>
| <rejectPlatforms>       | JRELEASER_REJECT_PLATFORMS        | <empty-string>
|                         | JRELEASER_DEFAULT_GIT_REMOTE      | origin
|===

`JRELEASER_SELECT_PLATFORMs` and `JRELEASER_REJECT_PLATFORMs` may define a command separated list of values such as
`osx-x86_64,linux-x86_64`.

These additional environment variables are supported as well:

[options="header", cols="2*"]
|===
| Environment Variable | Description
| NO_COLOR             | disable colors in output
| JRELEASER_NO_COLOR   | disable colors in output
|===

== Filtering Artifacts

Many commands let you filter (include or exclude) artifacts using a combination of properties or environment variables.
This filter capability allows you to test out a release configuration on a node where not all artifacts may be available.
For example, when building on `linux-x86_64` while also having `osx-x86_64` and `windows-x86_64`.

.Include only for the current platform

Use the `JRELEASER_SELECT_CURRENT_PLATFORM` environment variable or the `jreleaser.select.current.platform` property.

[source]
----
$ JRELEASER_SELECT_CURRENT_PLATFORM mvn jreleaser-checksum
$ mvn jreleaser-checksum -Djreleaser.select.current.platform=true
----

.Include a specific platform

Use the `JRELEASER_SELECT_PLATFORMS` environment variable or the `jreleaser.select.platforms` property, i.e,

[source]
----
$ JRELEASER_SELECT_PLATFORMS=osx-x86_64 mvn jreleaser-checksum
$ mvn jreleaser-checksum --Djreleaser.select.platforms=osx-x86_64
----

Every artifact whose platform property *does not* match the given platform will end up filtered out.

.Exclude a specific platform

Use the `JRELEASER_REJECT_PLATFORMS` environment variable or the `jreleaser.reject.platforms` property, i.e,

[source]
----
$ JRELEASER_REJECT_PLATFORMS=windows-x86_64 mvn jreleaser-checksum
$ mvn jreleaser-checksum -Djreleaser.reject.platforms=windows-x86_64
----

Every artifact whose platform property *matches* the given platform will end up filtered out.

== Goals

None of the exposed MOJOs are bound to a specific life-cycle phase, letting you decide when and how that
should happen in your build.

The following MOJOs are provided:

=== jreleaser:env

Display environment variable names.

Available parameters:

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

 * skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.env.skip`

=== jreleaser:init

Create a jreleaser config file.

Available parameters:

 * format +
   Configuration file format +
   Type: String +
   User property: `jreleaser.init.format`

 * outputDirectory (Default: ${project.basedir}) +
   Type: File +
   User property: `jreleaser.output.directory`

 * overwrite +
   Overwrite existing files. +
   Type: boolean +
   User property: `jreleaser.init.overwrite`

 * skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.init.skip`

=== jreleaser:config

Display current configuration.

Available parameters:

 * announce +
   Display announce configuration. +
   Type: boolean +
   User property: `jreleaser.config.announce`

 * assembly +
   Display assembly configuration. +
   Type: boolean +
   User property: `jreleaser.config.assembly`

 * configFile +
   External configuration file. +
   Type: File +
   User property: `jreleaser.config.file`

 * changelog +
   Display changelog configuration. +
   Type: boolean +
   User property: `jreleaser.config.changelog`

 * deploy +
   Display deploy configuration. +
   Type: boolean +
   User property: `jreleaser.config.deploy`

 * download +
   Display download configuration. +
   Type: boolean +
   User property: `jreleaser.config.download`

 * full +
   Display full configuration. +
   Type: boolean +
   User property: `jreleaser.config.full`

 * gitRootSearch +
   Searches for the Git root. +
   Type: boolean +
   User property: `jreleaser.git.root.search`

 * rejectPlatforms +
   Activates paths not matching the given platform. +
   Type: String[] +
   User property: jreleaser.reject.platforms

 * selectCurrentPlatform +
   Activates paths matching the current platform. +
   Type: boolean +
   User property: jreleaser.select.current.platform

 * selectPlatforms +
   Activates paths matching the given platform. +
   Type: String[] +
   User property: jreleaser.select.platforms

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

 * skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.config.skip`

 * strict +
   Enable strict mode. +
   Type: boolean +
   User property: `jreleaser.strict`

 * yolo +
   Skips non-configured operations. +
   Type: boolean +
   User property: `jreleaser.yolo`

=== jreleaser:template-generate

Generate a packager/announcer template.

Available parameters:

 * announcerName +
   The name of the announcer +
   Type: String +
   User property: `jreleaser.announcer.name`

 * assemblerName +
   The name of the assembler +
   Type: String +
   User property: `jreleaser.assembler.name`

 * assemblerType +
   The type of the assembler +
   Type: String +
   User property: `jreleaser.assembler.type`

 * distributionName +
   The name of the distribution +
   Type: String +
   User property: `jreleaser.template.distribution.name`

 * distributionType (Default: JAVA_BINARY) +
   The type of the distribution +
   Type: Distributio.DistributionType +
   User property: `jreleaser.template.distribution.type`

 * outputDirectory (Default: ${project.build.directory}/jreleaser) +
   Type: File +
   User property: `jreleaser.output.directory`

 * overwrite +
   Overwrite existing files. +
   Type: boolean +
   User property: `jreleaser.template.overwrite`

 * packagerName +
   The name of the packager. +
   Type: String +
   User property: `jreleaser.template.packager.name`

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

 * skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.template.skip`

 * snapshot +
   Use snapshot templates. +
   Type: boolean +
   User property: `jreleaser.template.snapshot`

 * yolo +
   Skips non-configured operations. +
   Type: boolean +
   User property: `jreleaser.yolo`

=== jreleaser:template-eval

Evaluate a template or templates.

Available parameters:

 * announce +
   Display announce configuration. +
   Type: boolean +
   User property: `jreleaser.config.announce`

 * assembly +
   Display assembly configuration. +
   Type: boolean +
   User property: `jreleaser.config.assembly`

 * configFile +
   External configuration file. +
   Type: File +
   User property: `jreleaser.config.file`

 * changelog +
   Display changelog configuration. +
   Type: boolean +
   User property: `jreleaser.config.changelog`

 * download +
   Display download configuration. +
   Type: boolean +
   User property: `jreleaser.config.download`

 * gitRootSearch +
   Searches for the Git root. +
   Type: boolean +
   User property: `jreleaser.git.root.search`

 * inputFile +
   An input template file. +
   Type: File +
   User property: `jreleaser.template.input.file`

 * inputDirectory +
   A directory with input templates. +
   Type: File +
   User property: `jreleaser.template.input.directory`

 * rejectPlatforms +
   Activates paths not matching the given platform. +
   Type: String[] +
   User property: jreleaser.reject.platforms

 * selectCurrentPlatform +
   Activates paths matching the current platform. +
   Type: boolean +
   User property: jreleaser.select.current.platform

 * selectPlatforms +
   Activates paths matching the given platform. +
   Type: String[] +
   User property: jreleaser.select.platforms

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

* skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.template.skip`

 * strict +
   Enable strict mode. +
   Type: boolean +
   User property: `jreleaser.strict`

 * targetDirectory +
   Directory where evaluated template(s) will be placed. +
   Type: File +
   User property: `jreleaser.template.target.directory`

 * yolo +
   Skips non-configured operations. +
   Type: boolean +
   User property: `jreleaser.yolo`

=== jreleaser:download

Downloads assets. +
Executes the xref:concepts:workflow.adoc#_download[Download] workflow step.

Available parameters:

 * configFile +
   External configuration file. +
   Type: File +
   User property: `jreleaser.config.file`

 * dryrun +
   Skips remote operations. +
   Type: boolean +
   User property: `jreleaser.dry.run`

 * excludedDownloaderNames +
   Exclude an downloader by name. +
   Type: String[] +
   User property: jreleaser.excluded.downloader.names

 * excludedDownloaders +
   Exclude an downloader by type. +
   Type: String[] +
   User property: jreleaser.excluded.downloaders

 * gitRootSearch +
   Searches for the Git root. +
   Type: boolean +
   User property: `jreleaser.git.root.search`

 * includedDownloaderNames +
   Include an downloader by name. +
   Type: String[] +
   User property: jreleaser.downloader.names

 * includedDownloaders +
   Include an downloader by type. +
   Type: String[] +
   User property: jreleaser.downloaders

 * outputDirectory (Default: ${project.build.directory}/jreleaser) +
   Type: File +
   User property: `jreleaser.output.directory`

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

* skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.download.skip`

 * strict +
   Enable strict mode. +
   Type: boolean +
   User property: `jreleaser.strict`

 * yolo +
   Skips non-configured operations. +
   Type: boolean +
   User property: `jreleaser.yolo`

=== jreleaser:assemble

Assemble all distributions. +
Executes the xref:concepts:workflow.adoc#_assemble[Assemble] workflow step.

Available parameters:

 * configFile +
   External configuration file. +
   Type: File +
   User property: `jreleaser.config.file`

 * excludedAssemblers +
   Exclude an assembler. +
   Type: String[] +
   User property: jreleaser.excluded.assemblers

 * excludedDistributions +
   Exclude a distribution. +
   Type: String[] +
   User property: jreleaser.excluded.distributions

 * gitRootSearch +
   Searches for the Git root. +
   Type: boolean +
   User property: `jreleaser.git.root.search`

 * includedAssemblers +
   Include an assembler. +
   Type: String[] +
   User property: jreleaser.assemblers

 * includedDistributions +
   Include a distribution. +
   Type: String[] +
   User property: jreleaser.distributions

 * outputDirectory (Default: ${project.build.directory}/jreleaser) +
   Type: File +
   User property: `jreleaser.output.directory`

 * rejectPlatforms +
   Activates paths not matching the given platform. +
   Type: String[] +
   User property: jreleaser.reject.platforms

 * selectCurrentPlatform +
   Activates paths matching the current platform. +
   Type: boolean +
   User property: jreleaser.select.current.platform

 * selectPlatforms +
   Activates paths matching the given platform. +
   Type: String[] +
   User property: jreleaser.select.platforms

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

* skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.assemble.skip`

 * strict +
   Enable strict mode. +
   Type: boolean +
   User property: `jreleaser.strict`

 * yolo +
   Skips non-configured operations. +
   Type: boolean +
   User property: `jreleaser.yolo`

=== jreleaser:changelog

Calculate the changelog. +
Executes the xref:concepts:workflow.adoc#_changelog[Changelog] workflow step.

Available parameters:

 * configFile +
   External configuration file. +
   Type: File +
   User property: `jreleaser.config.file`

 * gitRootSearch +
   Searches for the Git root. +
   Type: boolean +
   User property: `jreleaser.git.root.search`

 * outputDirectory (Default: ${project.build.directory}/jreleaser) +
   Type: File +
   User property: `jreleaser.output.directory`

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

* skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.changelog.skip`

 * strict +
   Enable strict mode. +
   Type: boolean +
   User property: `jreleaser.strict`

 * yolo +
   Skips non-configured operations. +
   Type: boolean +
   User property: `jreleaser.yolo`

=== jreleaser:catalog

Catalogs all distributions and files. +
Executes the xref:concepts:workflow.adoc#_catalog[Catalog] workflow step.

Available parameters:

 * configFile +
   External configuration file. +
   Type: File +
   User property: `jreleaser.config.file`

 * distributionName +
   The name of the distribution. +
   Type: String +
   User property: `jreleaser.distribution.name`

 * dryrun +
   Skips remote operations. +
   Type: boolean +
   User property: `jreleaser.dry.run`

 * excludedCatalogers +
   Exclude a cataloger. +
   Type: String[] +
   User property: jreleaser.excluded.catalogers

 * excludedDistributions +
   Exclude a distribution. +
   Type: String[] +
   User property: jreleaser.excluded.distributions

 * gitRootSearch +
   Searches for the Git root. +
   Type: boolean +
   User property: `jreleaser.git.root.search`

 * includedCatalogers +
   Include a cataloger. +
   Type: String[] +
   User property: jreleaser.catalogers

 * includedDistributions +
   Include a distribution. +
   Type: String[] +
   User property: jreleaser.distributions

 * outputDirectory (Default: ${project.build.directory}/jreleaser) +
   Type: File +
   User property: `jreleaser.output.directory`

 * rejectPlatforms +
   Activates paths not matching the given platform. +
   Type: String[] +
   User property: jreleaser.reject.platforms

 * selectCurrentPlatform +
   Activates paths matching the current platform. +
   Type: boolean +
   User property: jreleaser.select.current.platform

 * selectPlatforms +
   Activates paths matching the given platform. +
   Type: String[] +
   User property: jreleaser.select.platforms

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

* skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.catalog.skip`

 * strict +
   Enable strict mode. +
   Type: boolean +
   User property: `jreleaser.strict`

 * yolo +
   Skips non-configured operations. +
   Type: boolean +
   User property: `jreleaser.yolo`

=== jreleaser:checksum

Calculate checksums. +
Executes the xref:concepts:workflow.adoc#_checksum[Checksum] workflow step.

Available parameters:

 * configFile +
   External configuration file. +
   Type: File +
   User property: `jreleaser.config.file`

 * excludedDistributions +
   Exclude a distribution. +
   Type: String[] +
   User property: jreleaser.excluded.distributions

 * gitRootSearch +
   Searches for the Git root. +
   Type: boolean +
   User property: `jreleaser.git.root.search`

 * includedDistributions +
   Include a distribution. +
   Type: String[] +
   User property: jreleaser.distributions

 * outputDirectory (Default: ${project.build.directory}/jreleaser) +
   Type: File +
   User property: `jreleaser.output.directory`

 * rejectPlatforms +
   Activates paths not matching the given platform. +
   Type: String[] +
   User property: jreleaser.reject.platforms

 * selectCurrentPlatform +
   Activates paths matching the current platform. +
   Type: boolean +
   User property: jreleaser.select.current.platform

 * selectPlatforms +
   Activates paths matching the given platform. +
   Type: String[] +
   User property: jreleaser.select.platforms

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

* skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.checksum.skip`

 * strict +
   Enable strict mode. +
   Type: boolean +
   User property: `jreleaser.strict`

 * yolo +
   Skips non-configured operations. +
   Type: boolean +
   User property: `jreleaser.yolo`

=== jreleaser:sign

Sign release artifacts. +
Executes the xref:concepts:workflow.adoc#_sign[Sign] workflow step.

Available parameters:

 * configFile +
   External configuration file. +
   Type: File +
   User property: `jreleaser.config.file`

 * excludedDistributions +
   Exclude a distribution. +
   Type: String[] +
   User property: jreleaser.excluded.distributions

 * gitRootSearch +
   Searches for the Git root. +
   Type: boolean +
   User property: `jreleaser.git.root.search`

 * includedDistributions +
   Include a distribution. +
   Type: String[] +
   User property: jreleaser.distributions

 * outputDirectory (Default: ${project.build.directory}/jreleaser) +
   Type: File +
   User property: `jreleaser.output.directory`

 * rejectPlatforms +
   Activates paths not matching the given platform. +
   Type: String[] +
   User property: jreleaser.reject.platforms

 * selectCurrentPlatform +
   Activates paths matching the current platform. +
   Type: boolean +
   User property: jreleaser.select.current.platform

 * selectPlatforms +
   Activates paths matching the given platform. +
   Type: String[] +
   User property: jreleaser.select.platforms

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

* skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.sign.skip`

 * strict +
   Enable strict mode. +
   Type: boolean +
   User property: `jreleaser.strict`

 * yolo +
   Skips non-configured operations. +
   Type: boolean +
   User property: `jreleaser.yolo`

=== jreleaser:deploy

Deploys all staged artifacts. +
Executes the xref:concepts:workflow.adoc#_deploy[Deploy] workflow step.

Available parameters:

 * configFile +
   External configuration file. +
   Type: File +
   User property: `jreleaser.config.file`

 * dryrun +
   Skips remote operations. +
   Type: boolean +
   User property: `jreleaser.dry.run`

 * excludedDeployers +
   Exclude a deployer by type. +
   Type: String[] +
   User property: jreleaser.excluded.deployers

 * excludedDeployerNames +
   Exclude a deployer by name. +
   Type: String[] +
   User property: jreleaser.excluded.deployer.names

 * gitRootSearch +
   Searches for the Git root. +
   Type: boolean +
   User property: `jreleaser.git.root.search`

 * includedDeployers +
   Include a deployer by type. +
   Type: String[] +
   User property: jreleaser.deployers

 * includedDeployerNames +
   Include a deployer by name. +
   Type: String[] +
   User property: jreleaser.deployer.names

 * outputDirectory (Default: ${project.build.directory}/jreleaser) +
   Type: File +
   User property: `jreleaser.output.directory`

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

* skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.deploy.skip`

 * strict +
   Enable strict mode. +
   Type: boolean +
   User property: `jreleaser.strict`

 * yolo +
   Skips non-configured operations. +
   Type: boolean +
   User property: `jreleaser.yolo`

=== jreleaser:upload

Uploads all artifacts. +
Executes the xref:concepts:workflow.adoc#_upload[Upload] workflow step.

Available parameters:

 * configFile +
   External configuration file. +
   Type: File +
   User property: `jreleaser.config.file`

 * dryrun +
   Skips remote operations. +
   Type: boolean +
   User property: `jreleaser.dry.run`

 * excludedCatalogers +
   Exclude a cataloger. +
   Type: String[] +
   User property: `jreleaser.excluded.catalogers`
   
 * excludedDistributions +
   Exclude a distribution. +
   Type: String[] +
   User property: jreleaser.excluded.distributions

 * excludedUploaderNames +
   Exclude an uploader by name. +
   Type: String[] +
   User property: jreleaser.excluded.uploader.names

 * excludedUploaders +
   Exclude an uploader by type. +
   Type: String[] +
   User property: jreleaser.excluded.uploaders

 * gitRootSearch +
   Searches for the Git root. +
   Type: boolean +
   User property: `jreleaser.git.root.search`

 * includedCatalogers +
   Include a cataloger. +
   Type: String[] +
   User property: `jreleaser.catalogers`

 * includedDistributions +
   Include a distribution. +
   Type: String[] +
   User property: jreleaser.distributions

 * includedUploaderNames +
   Include an uploader by name. +
   Type: String[] +
   User property: jreleaser.uploader.names

 * includedUploaders +
   Include an uploader by type. +
   Type: String[] +
   User property: jreleaser.uploaders

 * outputDirectory (Default: ${project.build.directory}/jreleaser) +
   Type: File +
   User property: `jreleaser.output.directory`

 * rejectPlatforms +
   Activates paths not matching the given platform. +
   Type: String[] +
   User property: jreleaser.reject.platforms

 * selectCurrentPlatform +
   Activates paths matching the current platform. +
   Type: boolean +
   User property: jreleaser.select.current.platform

 * selectPlatforms +
   Activates paths matching the given platform. +
   Type: String[] +
   User property: jreleaser.select.platforms

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

* skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.upload.skip`

 * strict +
   Enable strict mode. +
   Type: boolean +
   User property: `jreleaser.strict`

 * yolo +
   Skips non-configured operations. +
   Type: boolean +
   User property: `jreleaser.yolo`

=== jreleaser:release

Create or update a release. +
Executes the xref:concepts:workflow.adoc#_release[Release] workflow step.

Available parameters:

 * configFile +
   External configuration file. +
   Type: File +
   User property: `jreleaser.config.file`

 * dryrun +
   Skips remote operations. +
   Type: boolean +
   User property: `jreleaser.dry.run`

 * excludedCatalogers +
   Exclude a cataloger. +
   Type: String[] +
   User property: `jreleaser.excluded.catalogers`
   
 * excludedDeployers +
   Exclude a deployer by type. +
   Type: String[] +
   User property: jreleaser.excluded.deployers

 * excludedDeployerNames +
   Exclude a deployer by name. +
   Type: String[] +
   User property: jreleaser.excluded.deployer.names
   User property: jreleaser.excluded.deployer.names

 * excludedDistributions +
   Exclude a distribution. +
   Type: String[] +
   User property: jreleaser.excluded.distributions

 * excludedUploaderNames +
   Exclude an uploader by name. +
   Type: String[] +
   User property: jreleaser.excluded.uploader.names

 * excludedUploaders +
   Exclude an uploader by type. +
   Type: String[] +
   User property: jreleaser.excluded.uploaders

 * gitRootSearch +
   Searches for the Git root. +
   Type: boolean +
   User property: `jreleaser.git.root.search`

 * includedDeployers +
   Include a deployer by type. +
   Type: String[] +
   User property: jreleaser.deployers

 * includedDeployerNames +
   Include a deployer by name. +
   Type: String[] +
   User property: jreleaser.deployer.names

 * includedCatalogers +
   Include a cataloger. +
   Type: String[] +
   User property: `jreleaser.catalogers`

 * includedDistributions +
   Include a distribution. +
   Type: String[] +
   User property: jreleaser.distributions

 * includedUploaderNames +
   Include an uploader by name. +
   Type: String[] +
   User property: jreleaser.uploader.names

 * includedUploaders +
   Include an uploader by type. +
   Type: String[] +
   User property: jreleaser.uploaders

 * outputDirectory (Default: ${project.build.directory}/jreleaser) +
   Type: File +
   User property: `jreleaser.output.directory`

 * rejectPlatforms +
   Activates paths not matching the given platform. +
   Type: String[] +
   User property: jreleaser.reject.platforms

 * selectCurrentPlatform +
   Activates paths matching the current platform. +
   Type: boolean +
   User property: jreleaser.select.current.platform

 * selectPlatforms +
   Activates paths matching the given platform. +
   Type: String[] +
   User property: jreleaser.select.platforms

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

* skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.release.skip`

 * strict +
   Enable strict mode. +
   Type: boolean +
   User property: `jreleaser.strict`

 * yolo +
   Skips non-configured operations. +
   Type: boolean +
   User property: `jreleaser.yolo`

=== jreleaser:prepare

Prepare all distributions. +
Executes the xref:concepts:workflow.adoc#_prepare[Prepare] workflow step.

Available parameters:

 * configFile +
   External configuration file. +
   Type: File +
   User property: `jreleaser.config.file`

 * distributionName +
   The name of the distribution. +
   Type: String +
   User property: `jreleaser.distribution.name`

 * dryrun +
   Skips remote operations. +
   Type: boolean +
   User property: `jreleaser.dry.run`

 * excludedDistributions +
   Exclude a distribution. +
   Type: String[] +
   User property: jreleaser.excluded.distributions

 * excludedPackagers +
   Exclude a packager. +
   Type: String[] +
   User property: jreleaser.excluded.packagers

 * gitRootSearch +
   Searches for the Git root. +
   Type: boolean +
   User property: `jreleaser.git.root.search`

 * includedDistributions +
   Include a distribution. +
   Type: String[] +
   User property: jreleaser.distributions

 * includedPackagers +
   Include a packager. +
   Type: String[] +
   User property: jreleaser.packagers

 * outputDirectory (Default: ${project.build.directory}/jreleaser) +
   Type: File +
   User property: `jreleaser.output.directory`

 * rejectPlatforms +
   Activates paths not matching the given platform. +
   Type: String[] +
   User property: jreleaser.reject.platforms

 * selectCurrentPlatform +
   Activates paths matching the current platform. +
   Type: boolean +
   User property: jreleaser.select.current.platform

 * selectPlatforms +
   Activates paths matching the given platform. +
   Type: String[] +
   User property: jreleaser.select.platforms

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

* skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.prepare.skip`

 * strict +
   Enable strict mode. +
   Type: boolean +
   User property: `jreleaser.strict`

 * yolo +
   Skips non-configured operations. +
   Type: boolean +
   User property: `jreleaser.yolo`

=== jreleaser:package

Package all distributions. +
Executes the xref:concepts:workflow.adoc#_package[Package] workflow step.

Available parameters:

 * configFile +
   External configuration file. +
   Type: File +
   User property: `jreleaser.config.file`

 * distributionName +
   The name of the distribution. +
   Type: String +
   User property: `jreleaser.distribution.name`

 * dryrun +
   Skips remote operations. +
   Type: boolean +
   User property: `jreleaser.dry.run`

 * excludedDistributions +
   Exclude a distribution. +
   Type: String[] +
   User property: jreleaser.excluded.distributions

 * excludedPackagers +
   Exclude a packager. +
   Type: String[] +
   User property: jreleaser.excluded.packagers

 * gitRootSearch +
   Searches for the Git root. +
   Type: boolean +
   User property: `jreleaser.git.root.search`

 * includedDistributions +
   Include a distribution. +
   Type: String[] +
   User property: jreleaser.distributions

 * includedPackagers +
   Include a packager. +
   Type: String[] +
   User property: jreleaser.packagers

 * outputDirectory (Default: ${project.build.directory}/jreleaser) +
   Type: File +
   User property: `jreleaser.output.directory`

 * rejectPlatforms +
   Activates paths not matching the given platform. +
   Type: String[] +
   User property: jreleaser.reject.platforms

 * selectCurrentPlatform +
   Activates paths matching the current platform. +
   Type: boolean +
   User property: jreleaser.select.current.platform

 * selectPlatforms +
   Activates paths matching the given platform. +
   Type: String[] +
   User property: jreleaser.select.platforms

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

* skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.package.skip`

 * strict +
   Enable strict mode. +
   Type: boolean +
   User property: `jreleaser.strict`

 * yolo +
   Skips non-configured operations. +
   Type: boolean +
   User property: `jreleaser.yolo`

=== jreleaser:publish

Publish all distributions. +
Executes the xref:concepts:workflow.adoc#_publish[Publish] workflow step.

Available parameters:

 * configFile +
   External configuration file. +
   Type: File +
   User property: `jreleaser.config.file`

 * distributionName +
   The name of the distribution. +
   Type: String +
   User property: `jreleaser.distribution.name`

 * dryrun +
   Skips remote operations. +
   Type: boolean +
   User property: `jreleaser.dry.run`

 * excludedDistributions +
   Exclude a distribution. +
   Type: String[] +
   User property: jreleaser.excluded.distributions

 * excludedPackagers +
   Exclude a packager. +
   Type: String[] +
   User property: jreleaser.excluded.packagers

 * gitRootSearch +
   Searches for the Git root. +
   Type: boolean +
   User property: `jreleaser.git.root.search`

 * includedDistributions +
   Include a distribution. +
   Type: String[] +
   User property: jreleaser.distributions

 * includedPackagers +
   Include a packager. +
   Type: String[] +
   User property: jreleaser.packagers

 * outputDirectory (Default: ${project.build.directory}/jreleaser) +
   Type: File +
   User property: `jreleaser.output.directory`

 * rejectPlatforms +
   Activates paths not matching the given platform. +
   Type: String[] +
   User property: jreleaser.reject.platforms

 * selectCurrentPlatform +
   Activates paths matching the current platform. +
   Type: boolean +
   User property: jreleaser.select.current.platform

 * selectPlatforms +
   Activates paths matching the given platform. +
   Type: String[] +
   User property: jreleaser.select.platforms

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

* skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.publish.skip`

 * strict +
   Enable strict mode. +
   Type: boolean +
   User property: `jreleaser.strict`

 * yolo +
   Skips non-configured operations. +
   Type: boolean +
   User property: `jreleaser.yolo`

=== jreleaser:announce

Announce a release. +
Executes the xref:concepts:workflow.adoc#_announce[Announce] workflow step.

Available parameters:

 * configFile +
   External configuration file. +
   Type: File +
   User property: `jreleaser.config.file`

 * dryrun +
   Skips remote operations. +
   Type: boolean +
   User property: `jreleaser.dry.run`

 * gitRootSearch +
   Searches for the Git root. +
   Type: boolean +
   User property: `jreleaser.git.root.search`

 * includedAnnouncers +
   Include an announcer. +
   Type: String[] +
   User property: `jreleaser.announcers`

 * outputDirectory (Default: ${project.build.directory}/jreleaser) +
   Type: File +
   User property: `jreleaser.output.directory`

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

* skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.announce.skip`

 * strict +
   Enable strict mode. +
   Type: boolean +
   User property: `jreleaser.strict`

 * yolo +
   Skips non-configured operations. +
   Type: boolean +
   User property: `jreleaser.yolo`

=== jreleaser:full-release

Perform a full release. +
Executes the xref:concepts:workflow.adoc#_full_release[Full Release] workflow step.

Available parameters:

 * configFile +
   External configuration file. +
   Type: File +
   User property: `jreleaser.config.file`

 * dryrun +
   Skips remote operations. +
   Type: boolean +
   User property: `jreleaser.dry.run`

 * excludedAnnouncers +
   Exclude an announcer. +
   Type: String[] +
   User property: `jreleaser.excluded.announcers`

 * excludedCatalogers +
   Exclude a cataloger. +
   Type: String[] +
   User property: `jreleaser.excluded.catalogers`
   
 * excludedDeployers +
   Exclude a deployer by type. +
   Type: String[] +
   User property: jreleaser.excluded.deployers

 * excludedDeployerNames +
   Exclude a deployer by name. +
   Type: String[] +
   User property: jreleaser.excluded.deployer.names

 * excludedDistributions +
   Exclude a distribution. +
   Type: String[] +
   User property: jreleaser.excluded.distributions

 * excludedPackagers +
   Exclude a packager. +
   Type: String[] +
   User property: jreleaser.excluded.packagers

 * excludedUploaderNames +
   Exclude an uploader by name. +
   Type: String[] +
   User property: jreleaser.excluded.uploader.names

 * excludedUploaders +
   Exclude an uploader by type. +
   Type: String[] +
   User property: jreleaser.excluded.uploaders

 * gitRootSearch +
   Searches for the Git root. +
   Type: boolean +
   User property: `jreleaser.git.root.search`

 * includedAnnouncers +
   Include an announcer. +
   Type: String[] +
   User property: `jreleaser.announcers`

 * includedCatalogers +
   Include a cataloger. +
   Type: String[] +
   User property: `jreleaser.catalogers`
   
 * includedDeployers +
   Include a deployer by type. +
   Type: String[] +
   User property: jreleaser.deployers

 * includedDeployerNames +
   Include a deployer by name. +
   Type: String[] +
   User property: jreleaser.deployer.names

 * includedDistributions +
   Include a distribution. +
   Type: String[] +
   User property: jreleaser.distributions

 * includedPackagers +
   Include a packager. +
   Type: String[] +
   User property: jreleaser.packagers

 * includedUploaderNames +
   Include an uploader by name. +
   Type: String[] +
   User property: jreleaser.uploader.names

 * includedUploaders +
   Include an uploader by type. +
   Type: String[] +
   User property: jreleaser.uploaders

 * outputDirectory (Default: ${project.build.directory}/jreleaser) +
   Type: File +
   User property: `jreleaser.output.directory`

 * rejectPlatforms +
   Activates paths not matching the given platform. +
   Type: String[] +
   User property: jreleaser.reject.platforms

 * selectCurrentPlatform +
   Activates paths matching the current platform. +
   Type: boolean +
   User property: jreleaser.select.current.platform

 * selectPlatforms +
   Activates paths matching the given platform. +
   Type: String[] +
   User property: jreleaser.select.platforms

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

* skip +
   Skip execution. +
   Type: boolean +
   User property: `jreleaser.full.release.skip`

 * strict +
   Enable strict mode. +
   Type: boolean +
   User property: `jreleaser.strict`

 * yolo +
   Skips non-configured operations. +
   Type: boolean +
   User property: `jreleaser.yolo`

=== jreleaser:auto-config-release

Create or update a release with auto-config enabled.

Available parameters:

 * authors +
   The project authors. +
   Type: String[] +
   User property: `jreleaser.authors`

 * armored +
   Generate ascii armored signatures. +
   Type: boolean +
   User property: `jreleaser.armored`

 * branch +
   The release branch. +
   Type: String +
   User property: `jreleaser.release.branch`

 * changelog +
   Path to changelog file. +
   Type: String +
   User property: `jreleaser.changelog`

 * changelogFormatted +
   Format generated changelog. +
   Type: boolean +
   User property: `jreleaser.changelog.formatted`

 * commitAuthorEmail +
   Commit author e-mail. +
   Type: String +
   User property: `jreleaser.commit.author.email`

 * commitAuthorName +
   Commit author name. +
   Type: String +
   User property: `jreleaser.commit.author.name`

 * draft +
   If the release is a draft. +
   Type: boolean +
   User property: `jreleaser.draft`

 * dryrun +
   Skips remote operations. +
   Type: boolean +
   User property: `jreleaser.dry.run`

 * files +
   Input file(s) to be uploaded. +
   Type: String[] +
   User property: `jreleaser.files`

 * gitRootSearch +
   Searches for the Git root. +
   Type: boolean +
   User property: `jreleaser.git.root.search`

 * globs +
   Input file(s) to be uploaded (as globs). +
   Type: String[] +
   User property: `jreleaser.globs`

 * milestoneName +
   The milestone name. +
   Type: String +
   User property: `jreleaser.milestone.name`

 * outputDirectory (Default: ${project.build.directory}/jreleaser) +
   Type: File +
   User property: `jreleaser.output.directory`

 * overwrite +
   Overwrite an existing release. +
   Type: boolean +
   User property: `jreleaser.overwrite`

 * prerelease +
   If the release is a prerelease. +
   Type: boolean +
   User property: `jreleaser.prerelease`

 * prereleasePattern +
   The prerelease pattern. +
   Type: String +
   User property: `jreleaser.prerelease.pattern`

 * projectCopyright +
   The project copyright. +
   Type: String +
   User property: `jreleaser.project.copyright`

 * projectDescription +
   The project description. +
   Type: String +
   User property: `jreleaser.project.description`

 * projectInceptionYear +
   The project inception year. +
   Type: String +
   User property: `jreleaser.project.inception.year`

 * projectName (Default: ${project.artifactId}) +
   The project name. +
   Type: String +
   User property: `jreleaser.project.name`

 * projectSnapshotLabel +
   The project snapshot label. +
   Type: String +
   User property: `jreleaser.project.snapshot.label`

 * projectSnapshotPattern (Default: .*-SNAPSHOT) +
   The project snapshot pattern. +
   Type: String +
   User property: `jreleaser.project.snapshot.pattern`

 * projectSnapshotFullChangelog +
   Calculate full changelog since last non-snapshot release. +
   Type: boolean +
   User property: `jreleaser.project.snapshot.full.changelog`

 * projectStereotype +
   The project stereotype. +
   Type: String +
   User property: `jreleaser.project.stereotype`

 * projectVersion (Default: ${project.version}) +
   The project version. +
   Type: String +
   User property: `jreleaser.project.version`

 * projectVersionPattern +
   The project version pattern. +
   Type: String +
   User property: `jreleaser.project.version.pattern`

 * releaseName +
   The release name. +
   Type: String +
   User property: `jreleaser.release.name`

 * rejectPlatforms +
   Activates paths not matching the given platform. +
   Type: String[] +
   User property: jreleaser.reject.platforms

 * selectCurrentPlatform +
   Activates paths matching the current platform. +
   Type: boolean +
   User property: jreleaser.select.current.platform

 * selectPlatforms +
   Activates paths matching the given platform. +
   Type: String[] +
   User property: jreleaser.select.platforms

 * settingsFile +
   The settings file. +
   Type: File +
   User property: `jreleaser.settings.file`

* signing +
   Sign files. +
   Type: boolean +
   User property: `jreleaser.signing`

 * skipChecksums +
   Skip creating checksums. +
   Type: boolean +
   User property: `jreleaser.skip.checksums`

 * skipRelease +
   Skip creating a release. +
   Type: boolean +
   User property: `jreleaser.skip.release`

 * skipTag +
   Skip tagging the release. +
   Type: boolean +
   User property: `jreleaser.skip.tag`

 * strict +
   Enable strict mode. +
   Type: boolean +
   User property: `jreleaser.strict`

 * tagName +
   The release tag. +
   Type: String +
   User property: `jreleaser.tag.name`

 * update +
   Update an existing release. +
   Type: boolean +
   User property: `jreleaser.update`

 * updateSections +
   Release section(s) to be updated. +
   Type: UpdateSection +
   User property: jreleaser.update.sections

 * username +
   Git username. +
   Type: String +
   User property: `jreleaser.username`

=== jreleaser:json-schema

Generate JSON schema.
