= JReleaser Maven Plugin

Executes a JReleaser workflow as a Maven plugin.

== Install

[source,xml]
[subs="verbatim,attributes"]
.pom.xml
----
<plugin>
  <groupId>org.jreleaser</groupId>
  <artifactId>jreleaser-maven-plugin</artifactId>
  <version>{jreleaser-version}</version>
</plugin>
----

== Configuration

JReleaser must be configured using the Maven DSL shown at xref:configuration:index.adoc[].

== Goals

None of the exposed MOJOs are bound to a specific life-cycle phase, letting you decide when and how that
should happen in your build.

The following MOJOs are provided:

=== jreleaser:config

Display current configuration.

*full*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.config.full
Required:: false
Description:: Displays full configuration.

*assembly*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.config.assembly
Required:: false
Description:: Displays assembly configuration.

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.config.skip
Required:: false
Description:: Skips execution of this MOJO.

=== jreleaser:template

Generate a tool/announcer template.

*announcerName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.announcer.name
Required:: false
Description:: The name of the announcer to be used.

---

*distributionName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.template.distribution.name
Required:: true
Description:: The name of the distribution.

---

*distributionType*
[horizontal]
Type:: Distribution.DistributionType
Default value:: JAVA_BINARY
Property:: jreleaser.template.distribution.type
Required:: false
Description:: The name of the distribution.

---

*toolName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.template.tool.name
Required:: true
Description:: The name of the tool.

---

*overwrite*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.overwrite
Required:: false
Description:: Overwrites existing template files.

---

*snapshot*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.snapshot
Required:: false
Description:: Lookup snapshot specific template files.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.template.skip
Required:: false
Description:: Skips execution of this MOJO.

=== jreleaser:assemble

Assemble distributions.

*distributionName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.distribution.name
Required:: true
Description:: The name of the distribution.

---

*assemblerName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.assembler.name
Required:: true
Description:: The name of the assembler.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.assemble.skip
Required:: false
Description:: Skips execution of this MOJO.

=== jreleaser:changelog

Calculate the changelog.

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.changelog.skip
Required:: false
Description:: Skips execution of this MOJO.

=== jreleaser:checksum

Calculate checksums.

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.checksum.skip
Required:: false
Description:: Skips execution of this MOJO.

=== jreleaser:sign

Sign release artifacts.

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.sign.skip
Required:: false
Description:: Skips execution of this MOJO.

=== jreleaser:release

Create or update a release.

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dryrun
Required:: false
Description: Skips remote operations.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.release.skip
Required:: false
Description:: Skips execution of this MOJO.

=== jreleaser:prepare

Prepare all distributions.

*distributionName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.distribution.name
Required:: false
Description:: The name of the distribution to be prepared.

---

*toolName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.tool.name
Required:: false
Description:: The name of the tool for preparing distributions.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.prepare.skip
Required:: false
Description:: Skips execution of this MOJO.

=== jreleaser:package

Package all distributions.

*distributionName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.distribution.name
Required:: false
Description:: The name of the distribution to be packaged.

---

*toolName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.tool.name
Required:: false
Description:: The name of the tool for packaging distributions.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dryrun
Required:: false
Description: Skips remote operations.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.package.skip
Required:: false
Description:: Skips execution of this MOJO.

=== jreleaser:upload

Upload all distributions.

*distributionName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.distribution.name
Required:: false
Description:: The name of the distribution to be upload.

---

*toolName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.tool.name
Required:: false
Description:: The name of the tool for uploading distributions.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dryrun
Required:: false
Description: Skips remote operations.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.upload.skip
Required:: false
Description:: Skips execution of this MOJO.

=== jreleaser:announce

Announce a release.

*announcerName*
[horizontal]
Type:: String
Default value:: <none>
Property:: jreleaser.announcer.name
Required:: false
Description:: The name of the announcer to be used.

---

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dryrun
Required:: false
Description: Skips remote operations.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.announce.skip
Required:: false
Description:: Skips execution of this MOJO.

=== jreleaser:full-release

Perform a full release.

*dryrun*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.dryrun
Required:: false
Description: Skips remote operations.

---

*skip*
[horizontal]
Type:: boolean
Default value:: false
Property:: jreleaser.full.release.skip
Required:: false
Description:: Skips execution of this MOJO.

