= Signing

Signing ensures that the artifacts have been generated by yourself and your users can verify that by comparing the
generated signature with your public signing key.

JReleaser can sign all files, including distribution archives and any extra files attached to the project. This section
must be configured if you intend to sign commits as well. You may sign using PGP, link:https://www.sigstore.dev/[Sigstore]'s cosign,
or link:https://jedisct1.github.io/minisign/[minisign].

Use the following options to customize how files may be signed:

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros"]
----
# icon:dot-circle[]
signing:
  # Enables or disables file signing.
  # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
  # Defaults to `NEVER`.
  # icon:dot-circle[] icon:eye-slash[]
  active: ALWAYS

  # Generates an armored signature.
  # Defaults to `false`.
  # icon:dot-circle[]
  armored: true

  # Verify signature files.
  # If `false` then `publicKey` may be ommitted.
  # Defaults to `true`.
  # icon:dot-circle[]
  verify: false

  # How should GPG keys be handled.
  # Supported values are [`MEMORY`, `FILE`, `COMMAND`, `COSIGN`, `MINISIGN`].
  # Defaults to `MEMORY`.
  # icon:dot-circle[]
  mode: MEMORY

  # The passphrase required to read secret keys.
  # If not set and mode = `COMMAND`, the command may ask for the passphrase interactively.
  # icon:dot-circle[] icon:eye-slash[]
  passphrase: __USE_ENVIRONMENT_VARIABLE__

  # The public GPG (ascii armored) used to sign files and commits.
  # Required when mode = `MEMORY` || `FILE`.
  # icon:exclamation-triangle[] icon:eye-slash[]
  publicKey: __USE_ENVIRONMENT_VARIABLE__

  # The private GPG (ascii armored) used to sign files and commits.
  # Required when mode = `MEMORY` || `FILE`.
  # icon:exclamation-triangle[] icon:eye-slash[]
  secretKey: __USE_ENVIRONMENT_VARIABLE__

  # Sign files.
  # Defaults to `true`.
  # icon:dot-circle[]
  files: true

  # Sign distribution artifacts.
  # Defaults to `true`.
  # icon:dot-circle[]
  artifacts: true

  # Sign checksum files.
  # Defaults to `true`.
  # icon:dot-circle[]
  checksums: true

  # Settings used when mode = `COMMAND`.
  # icon:dot-circle[]
  command:
    # The executable used for signing.
    # Defaults to `gpg[.exe]`.
    # When mode = `COMMAND`.
    # icon:dot-circle[] icon:eye-slash[]
    executable: gpg

    # The directory from which gpg will load keyrings.
    # Defaults to empty.
    # When mode = `COMMAND`.
    # icon:dot-circle[] icon:eye-slash[]
    homeDir: /home/users/duke/.gnugpg

    # The "name" of the key to sign with.
    # Defaults to empty.
    # When mode = `COMMAND`.
    # icon:dot-circle[] icon:eye-slash[]
    keyName: 0CB28B71EF50

    # The path to a public keyring to add to the list of keyrings.
    # Defaults to empty.
    # When mode = `COMMAND`.
    # icon:dot-circle[] icon:eye-slash[]
    publicKeyring: my-pubring.gpg

    # Whether to add the default keyrings from gpg's home directory to the list of used keyrings.
    # Defaults to `true`.
    # When mode = `COMMAND`.
    # icon:dot-circle[]
    defaultKeyring: true

    # Sets the arguments to be passed to gpg.
    # When mode = `COMMAND`.
    # icon:dot-circle[]
    args:
      - '--no-random-seed-file'

  # Settings used when mode = `COSIGN`.
  # icon:dot-circle[]
  cosign:
    # Tool version.
    # icon:exclamation-triangle[]
    version: 1.4.1

    # The private cosign key.
    # icon:exclamation-triangle[] icon:eye-slash[]
    privateKeyFile: __USE_ENVIRONMENT_VARIABLE__

    # The public cosign key.
    # icon:exclamation-triangle[] icon:eye-slash[]
    publicKeyFile: __USE_ENVIRONMENT_VARIABLE__

  # Settings used when mode = `MINISIGN`.
  # icon:dot-circle[]
  minisign:
    # Tool version.
    # icon:exclamation-triangle[]
    version: 0.12

    # The secret minisign key.
    # Defaults to `~/.minisign/minisign.key`.
    # icon:exclamation-triangle[] icon:eye-slash[]
    secretKeyFile: __USE_ENVIRONMENT_VARIABLE__

    # The public minisign key.
    # Defaults to `{{basedir}}/minisign.pub`.
    # icon:exclamation-triangle[] icon:eye-slash[]
    publicKeyFile: __USE_ENVIRONMENT_VARIABLE__
----
--
TOML::
+
--
[source,toml]
[subs="+macros"]
----
# icon:dot-circle[]
[signing]
  # Enables or disables file signing.
  # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
  # Defaults to `NEVER`.
  # icon:dot-circle[] icon:eye-slash[]
  active = "ALWAYS"

  # Generates an armored signature.
  # Defaults to `false`.
  # icon:dot-circle[]
  armored = true

  # Verify signature files.
  # If `false` then `publicKey` may be ommitted.
  # Defaults to `true`.
  # icon:dot-circle[]
  verify = false

  # How should GPG keys be handled.
  # Supported values are [`MEMORY`, `FILE`, `COMMAND`, `COSIGN`, `MINISIGN`].
  # Defaults to `MEMORY`.
  # icon:dot-circle[]
  mode = 'MEMORY'

  # The passphrase required to read secret keys.
  # If not set and mode = `COMMAND`, the command may ask for the passphrase interactively.
  # icon:dot-circle[] icon:eye-slash[]
  passphrase = "__USE_ENVIRONMENT_VARIABLE__"

  # The public GPG (ascii armored) used to sign files and commits.
  # Required when mode = `MEMORY` || `FILE`.
  # icon:exclamation-triangle[] icon:eye-slash[]
  publicKey = "__USE_ENVIRONMENT_VARIABLE__"

  # The private GPG (ascii armored) used to sign files and commits.
  # Required when mode = `MEMORY` || `FILE`.
  # icon:exclamation-triangle[] icon:eye-slash[]
  secretKey = "__USE_ENVIRONMENT_VARIABLE__"

  # Sign files.
  # Defaults to `true`.
  # icon:dot-circle[]
  files = true

  # Sign distribution artifacts.
  # Defaults to `true`.
  # icon:dot-circle[]
  artifacts = true

  # Sign checksum files.
  # Defaults to `true`.
  # icon:dot-circle[]
  checksums = true

  # Settings used when mode = `COMMAND`.
  # icon:dot-circle[]

  # The executable used for signing.
  # Defaults to `gpg[.exe]`.
  # When mode = `COMMAND`.
  # icon:dot-circle[] icon:eye-slash[]
  command.executable = "gpg"

  # The directory from which gpg will load keyrings.
  # Defaults to empty.
  # When mode = `COMMAND`.
  # icon:dot-circle[] icon:eye-slash[]
  command.homeDir = "/home/users/duke/.gnugpg"

  # The "name" of the key to sign with.
  # Defaults to empty.
  # When mode = `COMMAND`.
  # icon:dot-circle[] icon:eye-slash[]
  command.keyName = "0CB28B71EF50"

  # The path to a public keyring to add to the list of keyrings.
  # Defaults to empty.
  # When mode = `COMMAND`.
  # icon:dot-circle[] icon:eye-slash[]
  command.publicKeyring = "my-pubring.gpg"

  # Whether to add the default keyrings from gpg's home directory to the list of used keyrings.
  # Defaults to `true`.
  # When mode = `COMMAND`.
  # icon:dot-circle[]
  command.defaultKeyring = "true"

  # Sets the arguments to be passed to gpg.
  # When mode = `COMMAND`.
  # icon:dot-circle[]
  command.args = ["--no-random-seed-file"]

  # Settings used when mode = `COSIGN`.
  # icon:dot-circle[]

  # Tool version.
  # icon:exclamation-triangle[]
  cosign.version = "1.4.1"

  # The private cosign key.
  # icon:exclamation-triangle[] icon:eye-slash[]
  cosign.privateKeyFile = "__USE_ENVIRONMENT_VARIABLE__"

  # The public cosign key.
  # icon:exclamation-triangle[] icon:eye-slash[]
  cosign.publicKeyFile = "__USE_ENVIRONMENT_VARIABLE__"

  # Tool version.
  # icon:exclamation-triangle[]
  minisign.version = "0.12"

  # The secret minisign key.
  # Defaults to `~/.minisign/minisign.key`.
  # icon:exclamation-triangle[] icon:eye-slash[]
  minisign.secretKeyFile = "__USE_ENVIRONMENT_VARIABLE__"

  # The public minisign key.
  # Defaults to `{{basedir}}/minisign.pub`.
  # icon:exclamation-triangle[] icon:eye-slash[]
  minisign.publicKeyFile = "__USE_ENVIRONMENT_VARIABLE__"
----
--
JSON::
+
--
[source,json]
[subs="+macros"]
----
{
  // icon:dot-circle[]
  "signing": {
    // Enables or disables file signing.
    // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
    // Defaults to `NEVER`.
    // icon:dot-circle[] icon:eye-slash[]
    "active": "ALWAYS",

    // Generates an armored signature.
    // Defaults to `false`.
    // icon:dot-circle[]
    "armored": true,

    // Verify signature files.
    // If `false` then `publicKey` may be ommitted.
    // Defaults to `true`.
    // icon:dot-circle[]
    "verify": false,

    // How should GPG keys be handled.
    // Supported values are [`MEMORY`, `FILE`, `COMMAND`, `COSIGN`, `MINISIGN`].
    // Defaults to `MEMORY`.
    // icon:dot-circle[]
    "mode": "MEMORY",

    // The passphrase required to read secret keys.
    // If not set and mode = `COMMAND`, the command may ask for the passphrase interactively.
    // icon:dot-circle[] icon:eye-slash[]
    "passphrase": "__USE_ENVIRONMENT_VARIABLE__",

    // The public GPG (ascii armored) used to sign files and commits.
    // Required when mode = `MEMORY` || `FILE`.
    // icon:exclamation-triangle[] icon:eye-slash[]
    "publicKey": "__USE_ENVIRONMENT_VARIABLE__",

    // The private GPG (ascii armored) used to sign files and commits.
    // Required when mode = `MEMORY` || `FILE`.
    // icon:exclamation-triangle[] icon:eye-slash[]
    "secretKey": "__USE_ENVIRONMENT_VARIABLE__",

    // Sign files.
    // Defaults to `true`.
    // icon:dot-circle[]
    "files": true,

    // Sign distribution artifacts.
    // Defaults to `true`.
    // icon:dot-circle[]
    "artifacts": true,

    // Sign checksum files.
    // Defaults to `true`.
    // icon:dot-circle[]
    "checksums": true,

    // Settings used when mode = `COMMAND`.
    // icon:dot-circle[]
    "command": {

      // The executable used for signing.
      // Defaults to `gpg[.exe]`.
      // When mode = `COMMAND`.
      // icon:dot-circle[] icon:eye-slash[]
      "executable": "gpg",

      // The directory from which gpg will load keyrings.
      // Defaults to empty.
      // When mode = `COMMAND`.
      // icon:dot-circle[] icon:eye-slash[]
      "homeDir": "/home/users/duke/.gnugpg",

      // The "name" of the key to sign with.
      // Defaults to empty.
      // When mode = `COMMAND`.
      // icon:dot-circle[] icon:eye-slash[]
      "keyName": "0CB28B71EF50",

      // The path to a public keyring to add to the list of keyrings.
      // Defaults to empty.
      // When mode = `COMMAND`.
      // icon:dot-circle[] icon:eye-slash[]
      "publicKeyring": "my-pubring.gpg",

      // Whether to add the default keyrings from gpg's home directory to the list of used keyrings.
      // Defaults to `true`.
      // When mode = `COMMAND`.
      // icon:dot-circle[]
      "defaultKeyring": true,

      // Sets the arguments to be passed to gpg.
      // When mode = `COMMAND`.
      // icon:dot-circle[]
      "args": [
        "--no-random-seed-file"
      ]
    },

    // Settings used when mode = `COSIGN`.
    // icon:dot-circle[]
    "cosign": {
      // Tool version.
      // icon:exclamation-triangle[]
      "version": "1.4.1",

      // The private cosign key.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "privateKeyFile": "__USE_ENVIRONMENT_VARIABLE__",

      // The public cosign key.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "publicKeyFile": "__USE_ENVIRONMENT_VARIABLE__"
    },

    // Settings used when mode = `MINISIGN`.
    // icon:dot-circle[]
    "minisign": {
      // Tool version.
      // icon:exclamation-triangle[]
      "version": "0.12",

      // The secret minisign key.
      // Defaults to `~/.minisign/minisign.key`.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "secretKeyFile": "__USE_ENVIRONMENT_VARIABLE__",

      // The public minisign key.
      // Defaults to `{{basedir}}/minisign.pub`.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "publicKeyFile": "__USE_ENVIRONMENT_VARIABLE__"
    }
  }
}
----
--
Maven::
+
--
[source,xml]
[subs="+macros,verbatim"]
----
<jreleaser>
  <!--
    icon:dot-circle[]
  -->
  <signing>

    <!--
      Enables or disables file signing.
      Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
      Defaults to `NEVER`.
      icon:dot-circle[] icon:eye-slash[]
    -->
    <active>ALWAYS</active>

    <!--
      Generates an armored signature.
      Defaults to `false`.
      icon:dot-circle[]
    -->
    <armored>true</armored>

    <!--
      Verify signature files.
      If `false` then `publicKey` may be ommitted.
      Defaults to `true`.
      icon:dot-circle[]
    -->
    <verify>false</verify>

    <!--
      How should GPG keys be handled.
      Supported values are [`MEMORY`, `FILE`, `COMMAND`, `COSIGN`, `MINISIGN`].
      Defaults to `MEMORY`.
      icon:dot-circle[]
    -->
    <mode>MEMORY</mode>

    <!--
      The passphrase required to read secret keys.
      Required when mode = `MEMORY` || `FILE`.
      If not set and mode = `COMMAND`, the command may ask for the passphrase interactively.
      icon:dot-circle[] icon:eye-slash[]
    -->  
    <passphrase>__USE_ENVIRONMENT_VARIABLE__</passphrase>

    <!--
      The public GPG (ascii armored) used to sign files and commits.
      Required when mode = `MEMORY` || `FILE`.
      icon:exclamation-triangle[] icon:eye-slash[]
    -->
    <publicKey>__USE_ENVIRONMENT_VARIABLE__</publicKey>

    <!--
      The private GPG (ascii armored) used to sign files and commits.
      icon:exclamation-triangle[] icon:eye-slash[]
    -->
    <secretKey>__USE_ENVIRONMENT_VARIABLE__</secretKey>

    <!--
      Sign files.
      Defaults to `true`.
      icon:dot-circle[]
    -->
    <files>true</files>

    <!--
      Sign distribution artifacts.
      Defaults to `true`.
      icon:dot-circle[]
    -->
    <artifacts>true</artifacts>

    <!--
      Sign checksum files.
      Defaults to `true`.
      icon:dot-circle[]
    -->
    <checksums>true</checksums>

    <!--
      Settings used when mode = `COMMAND`.
      icon:dot-circle[]
    -->
    <command>
      <!--
        The executable used for signing.
        Defaults to `gpg[.exe]`.
        When mode = `COMMAND`.
        icon:dot-circle[] icon:eye-slash[]
      -->
      <executable>gpg</executable>

      <!--
        The directory from which gpg will load keyrings.
        Defaults to empty.
        When mode = `COMMAND`.
        icon:dot-circle[] icon:eye-slash[]
      -->
      <homeDir>/home/users/duke/.gnugpg</homeDir>

      <!--
        The "name" of the key to sign with.
        Defaults to empty.
        When mode = `COMMAND`.
        icon:dot-circle[] icon:eye-slash[]
      -->
      <keyName>0CB28B71EF50</keyName>

      <!--
        The path to a public keyring to add to the list of keyrings.
        Defaults to empty.
        When mode = `COMMAND`.
        icon:dot-circle[] icon:eye-slash[]
      -->
      <publicKeyring>my-pubring.gpg</publicKeyring>

      <!--
        Whether to add the default keyrings from gpg's home directory to the list of used keyrings.
        Defaults to `true`.
        When mode = `COMMAND`.
        icon:dot-circle[]
      -->
      <defaultKeyring>true</defaultKeyring>

      <!--
        Sets the arguments to be passed to gpg.
        When mode = `COMMAND`.
        icon:dot-circle[]
      -->
      <args>
        <arg>--no-random-seed-file</arg>
      </args>
    </command>

    <!--
      Settings used when mode = `COSIGN`.
      icon:dot-circle[]
    -->
    <cosign>
      <!--
        Tool version.
        icon:exclamation-triangle[]
      -->
      <version>1.4.1</version>

      <!--
        The private cosign key.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <privateKeyFile>__USE_ENVIRONMENT_VARIABLE__</privateKeyFile>

      <!--
        The public cosign key.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <publicKeyFile>__USE_ENVIRONMENT_VARIABLE__</publicKeyFile>
    </cosign>

    <!--
      Settings used when mode = `MINISIGN`.
      icon:dot-circle[]
    -->
    <minisign>
      <!--
        Tool version.
        icon:exclamation-triangle[]
      -->
      <version>0.12</version>

      <!--
        The secret minisign key.
        Defaults to `~/.minisign/minisign.key`.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <secretKeyFile>__USE_ENVIRONMENT_VARIABLE__</secretKeyFile>

      <!--
        The public minisign key.
        Defaults to `{{basedir}}/minisign.pub`.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <publicKeyFile>__USE_ENVIRONMENT_VARIABLE__</publicKeyFile>
    </minisign>
  </signing>
</jreleaser>
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros"]
----
jreleaser {
  // icon:dot-circle[]
  signing {
    // Enables or disables file signing.
    // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
    // Defaults to `NEVER`.
    // icon:dot-circle[] icon:eye-slash[]
    active = 'ALWAYS'

    // Generates an armored signature.
    // Defaults to `false`.
    // icon:dot-circle[]
    armored = true

    // Verify signature files.
    // If `false` then `publicKey` may be ommitted.
    // Defaults to `true`.
    // icon:dot-circle[]
    verify = false

    // How should GPG keys be handled.
    // Supported values are [`MEMORY`, `FILE`, `COMMAND`, `COSIGN`, `MINISIGN`].
    // Defaults to `MEMORY`.
    // icon:dot-circle[]
    mode = 'MEMORY'

    // The passphrase required to read secret keys.
    // If not set and mode = `COMMAND`, the command may ask for the passphrase interactively.
    // icon:dot-circle[] icon:eye-slash[]
    passphrase = '__USE_ENVIRONMENT_VARIABLE__'

    // The public GPG (ascii armored) used to sign files and commits.
    // Required when mode = `MEMORY` || `FILE`.
    // icon:exclamation-triangle[] icon:eye-slash[]
    publicKey = '__USE_ENVIRONMENT_VARIABLE__'

    // The private GPG (ascii armored) used to sign files and commits.
    // Required when mode = `MEMORY` || `FILE`.
    // icon:exclamation-triangle[] icon:eye-slash[]
    secretKey = '__USE_ENVIRONMENT_VARIABLE__'

    // Sign files.
    // Defaults to `true`.
    // icon:dot-circle[]
    files = true

    // Sign distribution artifacts.
    // Defaults to `true`.
    // icon:dot-circle[]
    artifacts = true

    // Sign checksum files.
    // Defaults to `true`.
    // icon:dot-circle[]
    checksums = true

    // Settings used when mode = `COMMAND`.
    // icon:dot-circle[]
    command {
      // The executable used for signing.
      // Defaults to `gpg[.exe]`.
      // When mode = `COMMAND`.
      // icon:dot-circle[] icon:eye-slash[]
      executable = 'gpg'

      // The directory from which gpg will load keyrings.
      // Defaults to empty.
      // When mode = `COMMAND`.
      // icon:dot-circle[] icon:eye-slash[]
      homeDir = '/home/users/duke/.gnugpg'

      // The "name" of the key to sign with.
      // Defaults to empty.
      // When mode = `COMMAND`.
      // icon:dot-circle[] icon:eye-slash[]
      keyName = '0CB28B71EF50'

      // The path to a public keyring to add to the list of keyrings.
      // Defaults to empty.
      // When mode = `COMMAND`.
      // icon:dot-circle[] icon:eye-slash[]
      publicKeyring = 'my-pubring.gpg'

      // Whether to add the default keyrings from gpg's home directory to the list of used keyrings.
      // Defaults to `true`.
      // When mode = `COMMAND`.
      // icon:dot-circle[]
      defaultKeyring = true

      // Sets the arguments to be passed to gpg.
      // When mode = `COMMAND`.
      // icon:dot-circle[]
      args = ['--no-random-seed-file']
    }

    // Settings used when mode = `COSIGN`.
    // icon:dot-circle[]
    cosign {
      // Tool version.
      // icon:exclamation-triangle[]
      version = '1.4.1'

      // The private cosign key.
      // icon:exclamation-triangle[] icon:eye-slash[]
      privateKeyFile = '__USE_ENVIRONMENT_VARIABLE__'

      // The public cosign key.
      // icon:exclamation-triangle[] icon:eye-slash[]
      publicKeyFile = '__USE_ENVIRONMENT_VARIABLE__'
    }

    // Settings used when mode = `MINISIGN`.
    // icon:dot-circle[]
    minisign {
      // Tool version.
      // icon:exclamation-triangle[]
      version = '1.4.1'

      // The secret minisign key.
      // Defaults to `~/.minisign/minisign.key`.
      // icon:exclamation-triangle[] icon:eye-slash[]
      secretKeyFile = '__USE_ENVIRONMENT_VARIABLE__'

      // The public minisign key.
      // Defaults to `{{basedir}}/minisign.pub`.
      // icon:exclamation-triangle[] icon:eye-slash[]
      publicKeyFile = '__USE_ENVIRONMENT_VARIABLE__'
    }
  }
}
----
--
====

WARNING: Prefer the use of xref:reference:environment.adoc[] if the configuration is stored at a public repository.

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property         | Environment Variable
2+| *active*| jreleaser.signing.active     | JRELEASER_SIGNING_ACTIVE
2+| *passphrase*
| jreleaser.cosign.password +
| jreleaser.minisign.password +
  jreleaser.gpg.passphrase
| JRELEASER_COSIGN_PASSWORD +
| JRELEASER_MINISIGN_PASSWORD +
  JRELEASER_GPG_PASSPHRASE +
2+| *publicKey*
| jreleaser.gpg.public.key     | JRELEASER_GPG_PUBLIC_KEY
2+| *secretKey*
| jreleaser.gpg.secret.key     | JRELEASER_GPG_SECRET_KEY
2+| *command.executable*
| jreleaser.gpg.executable     | JRELEASER_GPG_EXECUTABLE
2+| *command.homeDir*
| jreleaser.gpg.homedir        | JRELEASER_GPG_HOMEDIR
2+| *command.keyName*
| jreleaser.gpg.keyname        | JRELEASER_GPG_KEYNAME
2+| *command.publicKeyring*
| jreleaser.gpg.public.keyring | JRELEASER_GPG_PUBLIC_KEYRING
2+| *cosign.publicKeyFile*
| jreleaser.cosign.public.key  | JRELEASER_COSIGN_PUBLIC_KEY
2+| *cosign.privateKeyFile*
| jreleaser.cosign.private.key | JRELEASER_COSIGN_PRIVATE_KEY
2+| *minisign.publicKeyFile*
| jreleaser.minisign.public.key  | JRELEASER_MINISIGN_PUBLIC_KEY
2+| *minisign.secretKeyFile*
| jreleaser.minisign.secret.key | JRELEASER_MINISIGN_SECRET_KEY
|===

== Mode

When the mode is set to `MEMORY` (the default) then the values of `JRELEASER_GPG_PUBLIC_KEY` and
`JRELEASER_GPG_SECRET_KEY` are treated as the actual contents for each key.

When the mode is set to `FILE` then the values of `JRELEASER_GPG_PUBLIC_KEY` and
`JRELEASER_GPG_SECRET_KEY` are treated as file paths pointing to files that the keys.

When the mode is set to `COMMAND` then JReleaser expects appropriate command settings to be configured, such as the
signing executable (`gpg` by default). Signing and verification will be invoked in non-interactive mode.

== Cosign

You may sign artifacts, files, and checksums using Sigstore's link:https://github.com/sigstore/cosign[cosign] however
you *can not* sign commits nor tags when `COSIGN` mode is active.

You may use `JRELEASER_COSIGN_PASSWORD` instead of `JRELEASER_GPG_PASSPHRASE` to define the password required by cosign.

You must define a value for the version property. JReleaser will check if a matching binary exists in the system or
download a binary  that matches the current platform. If you do not have existing private/public keys then JReleaser
will generate a key pair for you and store them in `$JRELEASER_USER_HOME` which matches `~/.jreleaser` by default.

The public cosign key file will automatically be uploaded as a release asset.

== Minisign

You may sign artifacts, files, and checksums using link:https://jedisct1.github.io/minisign/[minisign] however
you *can not* sign commits nor tags when `MINISIGN` mode is active.

You may use `JRELEASER_MINISIGN_PASSWORD` instead of `JRELEASER_GPG_PASSPHRASE` to define the password required by minisign.

You must define a value for the version property. JReleaser will check if a matching binary exists in the system or
download a binary  that matches the current platform.

The public minisign key file will automatically be uploaded as a release asset.

== Skip Signing

Distributions and Artifacts may define an extra property that may stop them from being signed. The name of this property
must match `skipSigning` and be set to `true`. Setting this property on a distribution skips all of its artifacts.

== Skip Signature Verification

If the `verify` property is set to `false` then no signature verification will be performed, in which case you may ommit
setting a value for `publicKey` as well.

NOTE: `COSIGN` mode does require both `publicKeyFile` and `privateKeyFile` regardless of the value set in `verify`.
