= Article
:tool_id:       article
:tool_name:     Article
:tool_tap_name: duke-docs
:tool_manifest: templates
:announcer_sys_key: article
:announcer_env_key: ARTICLE
:tap_basename_sys: article
:tap_basename_env: ARTICLE

Processes file templates suitable for publication as {tool_id}s, blogs, pages, etc.

Processed files may be uploaded to a Git repository of your choosing.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
announce:
  # icon:dot-circle[]
  article:

    # Enable or disable this announcer.
    # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
    # Defaults to `NEVER`.
    # icon:dot-circle[] icon:eye-slash[]
    active: ALWAYS

    # Directory with file templates.
    # Defaults to `src/jreleaser/templates/article`.
    # Path must exist.
    # icon:dot-circle[]
    templateDirectory: src/jreleaser/templates/article

    # Defines a list of files.
    # Each entry must define a path: field.
    # The path may be relative to templateDirectory or absolute.
    # icon:exclamation-triangle[] icon:file-alt[]
    files:
      - path: path/to/some/file.md

include::partial$packagers/yaml/commitauthor.adoc[]

include::partial$packagers/yaml/tap.adoc[]

    # Additional properties used when evaluating templates.
    # icon:dot-circle[] icon:file-alt[]
    extraProperties:
      # Key will be capitalized and prefixed with `article`, i.e, `articleFoo`.
      foo: bar
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
# icon:dot-circle[]
[announce.article]

  # Enable or disable this announcer.
  # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
  # Defaults to `NEVER`.
  # icon:dot-circle[] icon:eye-slash[]
  active = "ALWAYS"

  # Directory with file templates.
  # Defaults to `src/jreleaser/templates/article`.
  # Path must exist.
  # icon:dot-circle[]
  templateDirectory = "src/jreleaser/templates/article"

  # Defines a list of files.
  # Each entry must define a path: field.
  # The path may be relative to templateDirectory or absolute.
  # icon:exclamation-triangle[] icon:file-alt[]
  files = [
    { path = "path/to/some/file.md" }
  ]

include::partial$packagers/toml/commitauthor.adoc[]

include::partial$packagers/toml/tap.adoc[]

  # Additional properties used when evaluating templates.
  # icon:dot-circle[] icon:file-alt[]
  extraProperties.foo = "bar"
  # Key will be capitalized and prefixed with `article`, i.e, `articleFoo`.
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
{
  "announce": {
    // icon:dot-circle[]
    "article": {

      // Enable or disable this announcer.
      // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
      // Defaults to `NEVER`.
      // icon:dot-circle[] icon:eye-slash[]
      "active": "ALWAYS",

      // Directory with file templates.
      // Defaults to `src/jreleaser/templates/article`.
      // Path must exist.
      // icon:dot-circle[]
      "templateDirectory": "src/jreleaser/templates/article",

      // Defines a list of files.
      // Each entry must define a path: field.
      // The path may be relative to templateDirectory or absolute.
      // icon:exclamation-triangle[] icon:file-alt[]
      "files": [
        {
          "path": "path/to/some/file.md"
        }
      ]

include::partial$packagers/json/commitauthor.adoc[]

include::partial$packagers/json/tap.adoc[]

      // Additional properties used when evaluating templates.
      // icon:dot-circle[] icon:file-alt[]
      "extraProperties": {
        // Key will be capitalized and prefixed with `article`, i.e, `articleFoo`.
        "foo": "bar"
      }
    }
  }
}
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
<jreleaser>
  <!--
    icon:dot-circle[]
  -->
  <announce>
    <!--
      icon:dot-circle[]
    -->
    <article>

      <!--
        Enable or disable this announcer.
        Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
        Defaults to `NEVER`.
        icon:dot-circle[] icon:eye-slash[]
      -->
      <active>ALWAYS</active>

      <!--
        Directory with file templates.
        Defaults to `src/jreleaser/templates/article`.
        Path must exist.
        icon:dot-circle[]
      -->
      <templateDirectory>src/jreleaser/templates/article</templateDirectory>

      <!--
        Defines a list of files.
        Each entry must define a path: field.
        The path may be relative to templateDirectory or absolute.
        icon:exclamation-triangle[] icon:file-alt[]
      -->
      <files>
        <files>
          <path>path/to/some/file.md</path>
        <file>
      </files>

include::partial$packagers/maven/commitauthor.adoc[]

include::partial$packagers/maven/tap.adoc[]

      <!--
        Additional properties used when evaluating templates.
        icon:dot-circle[] icon:file-alt[]
      -->
      <extraProperties>
        <!--
          Key will be capitalized and prefixed with `article`, i.e, `articleFoo`.
        -->
        <foo>bar</foo>
      </extraProperties>
    </article>
  </announce>
</jreleaser>
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
jreleaser {
  announce {
    // icon:dot-circle[]
    article {

      // Enable or disable this announcer.
      // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
      // Defaults to `NEVER`.
      // icon:dot-circle[] icon:eye-slash[]
      active = 'ALWAYS'

      // Directory with file templates.
      // Defaults to `src/jreleaser/templates/article`.
      // Path must exist.
      // icon:dot-circle[]
      templateDirectory = 'src/jreleaser/templates/article'

      // Defines a list of files.
      // Each entry must define a path: field.
      // The path may be relative to templateDirectory or absolute.
      // icon:exclamation-triangle[] icon:file-alt[]
      file {
        path = 'path/to/some/file.md'
      }

include::partial$packagers/gradle/commitauthor.adoc[]

include::partial$packagers/gradle/tap.adoc[]

      // Additional properties used when evaluating templates.
      // Key will be capitalized and prefixed with `article`, i.e, `articleFoo`.
      // icon:dot-circle[] icon:file-alt[]
      extraProperties.put('foo', 'bar')
    }
  }
}
----
--
====

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property                               | Environment Variable
2+| *active*
| jreleaser.announce.{announcer_sys_key}.active | JRELEASER_ANNOUNCE_{announcer_env_key}_ACTIVE
2+| *repository.active*
| jreleaser.announce.{announcer_sys_key}.repository.active
| JRELEASER_ANNOUNCE_{announcer_env_key}_REPOSITORY_ACTIVE
2+| *repository.username*
| jreleaser.announce.{announcer_sys_key}.repository.username +
  jreleaser.{tap_basename_sys}.github.username +
  jreleaser.{tap_basename_sys}.gitlab.username +
  jreleaser.{tap_basename_sys}.gitea.username +
  jreleaser.{tap_basename_sys}.codeberg.username +
  jreleaser.github.username +
  jreleaser.gitlab.username +
  jreleaser.gitea.username +
  jreleaser.codeberg.username
| JRELEASER_ANNOUNCE_{announcer_env_key}_REPOSITORY_USERNAME +
  JRELEASER_{tap_basename_env}_GITHUB_USERNAME +
  JRELEASER_{tap_basename_env}_GITLAB_USERNAME +
  JRELEASER_{tap_basename_env}_GITEA_USERNAME +
  JRELEASER_{tap_basename_env}_CODEBERG_USERNAME +
  JRELEASER_GITHUB_USERNAME +
  JRELEASER_GITLAB_USERNAME +
  JRELEASER_GITEA_USERNAME +
  JRELEASER_CODEBERG_USERNAME
2+| *repository.token*
| jreleaser.announce.{announcer_sys_key}.repository.token +
  jreleaser.{tap_basename_sys}.github.token +
  jreleaser.{tap_basename_sys}.gitlab.token +
  jreleaser.{tap_basename_sys}.gitea.token +
  jreleaser.{tap_basename_sys}.codeberg.token +
  jreleaser.github.token +
  jreleaser.gitlab.token +
  jreleaser.gitea.token +
  jreleaser.codeberg.token
| JRELEASER_ANNOUNCE_{announcer_env_key}_REPOSITORY_TOKEN +
  JRELEASER_{tap_basename_env}_GITHUB_TOKEN +
  JRELEASER_{tap_basename_env}_GITLAB_TOKEN +
  JRELEASER_{tap_basename_env}_GITEA_TOKEN +
  JRELEASER_{tap_basename_env}_CODEBERG_TOKEN +
  JRELEASER_GITHUB_TOKEN +
  JRELEASER_GITLAB_TOKEN +
  JRELEASER_GITEA_TOKEN +
  JRELEASER_CODEBERG_TOKEN
2+| *repository.branch*
| jreleaser.announce.{announcer_sys_key}.repository.branch +
  jreleaser.{tap_basename_sys}.github.branch +
  jreleaser.{tap_basename_sys}.gitlab.branch +
  jreleaser.{tap_basename_sys}.gitea.branch +
  jreleaser.{tap_basename_sys}.codeberg.branch +
  jreleaser.github.branch +
  jreleaser.gitlab.branch +
  jreleaser.gitea.branch +
  jreleaser.codeberg.branch
| JRELEASER_ANNOUNCE_{announcer_env_key}_REPOSITORY_BRANCH +
  JRELEASER_{tap_basename_env}_GITHUB_BRANCH +
  JRELEASER_{tap_basename_env}_GITLAB_BRANCH +
  JRELEASER_{tap_basename_env}_GITEA_BRANCH +
  JRELEASER_{tap_basename_env}_CODEBERG_BRANCH +
  JRELEASER_GITHUB_BRANCH +
  JRELEASER_GITLAB_BRANCH +
  JRELEASER_GITEA_BRANCH +
  JRELEASER_CODEBERG_BRANCH
2+| *repository.branchPush*
| jreleaser.announce.{announcer_sys_key}.repository.branch.push +
  jreleaser.{tap_basename_sys}.github.branch.push +
  jreleaser.{tap_basename_sys}.gitlab.branch.push +
  jreleaser.{tap_basename_sys}.gitea.branch.push +
  jreleaser.{tap_basename_sys}.codeberg.branch.push +
  jreleaser.github.branch.push +
  jreleaser.gitlab.branch.push +
  jreleaser.gitea.branch.push +
  jreleaser.codeberg.branch.push
| JRELEASER_ANNOUNCE_{announcer_env_key}_REPOSITORY_BRANCH_PUSH +
  JRELEASER_{tap_basename_env}_GITHUB_BRANCH_PUSH +
  JRELEASER_{tap_basename_env}_GITLAB_BRANCH_PUSH +
  JRELEASER_{tap_basename_env}_GITEA_BRANCH_PUSH +
  JRELEASER_{tap_basename_env}_CODEBERG_BRANCH_PUSH +
  JRELEASER_GITHUB_BRANCH_PUSH +
  JRELEASER_GITLAB_BRANCH_PUSH +
  JRELEASER_GITEA_BRANCH_PUSH +
  JRELEASER_CODEBERG_BRANCH_PUSH
|===

== Example

Given a project configured as

[source,yaml]
[subs="+macros"]
.jreleaser.yml
----
project:
  version: 1.2.3
  description: Sample application
  longDescription: Sample application
  authors:
    - Duke
  license: Apache-2.0
  links:
    homepage: pass:[https://github.com/duke/app]
  java:
    groupId: com.acme
    version: 8
    mainClass: com.acme.Main
  inceptionYear: 2021

releaser:
  github:
    owner: duke

distributions:
  app:
    artifacts:
      - path: 'target/distributions/{{distributionName}}/{{distributionName}}-{{projectVersion}}.zip'

announce:
  article:
    active: ALWAYS
    repository:
      name: docs
    files:
      - path: 'post.adoc'
        transform: '_posts/{{#f_now}}YYYY-MM-dd{{/f_now}}/{{projectName}}-{{#f_dash}}{{projectVersion}}{{/f_dash}}-released.adoc'
----

And file named `post.adoc` located at `src/jreleaser/templates/article`

[source]
----
---
layout: post
title: '{{projectNameCapitalized}} {{projectEffectiveVersion}} released'
date: {{#f_now}}YYYY-MM-dd{{/f_now}}
tags: release
synopsis: {{projectEffectiveVersion}} is the latest release.
author: duke
---

We just released {{projectNameCapitalized}} {{projectEffectiveVersion}} with a new round of bugfixes and documentation improvements.

== Full changelog

You can get {{releaseNotesUrl}}[the full changelog of {{projectEffectiveVersion}} on GitHub].
----

Generates the following file structure

[source]
----
out
└── jreleaser
    ├── output.properties
    ├── prepare
    │   └── article
    │       └── _posts
    │           └── 2021-07-26
    │               └── app-1-0-0-released.adoc
    ├── release
    │   └── CHANGELOG.md
    └── trace.log
----

The contents of the parsed template look like this

[source]
----
---
layout: post
title: 'App 1.2.3 released'
date: 2021-07-26
tags: release
synopsis: 1.0.0 is the latest release.
author: duke
---

We just released App 1.2.3 with a new round of bugfixes and documentation improvements.

== Full changelog

You can get https://github.com/duke/app/releases/tag/v1.2.3[the full changelog of 1.2.3 on GitHub].
----

This file will be uploaded to the pass:[https://github.com/duke/docs] repository as 
`_posts/2021-07-26/app-1-0-0-released.adoc`.

