= GitHub Discussions
:announcer_id:      discussions
:announcer_name:    Discussions
:announcer_sys_key: discussions
:announcer_env_key: DISCUSSIONS

Posts a message to link:https://docs.github.com/en/discussions[GitHub Discussions]. You must provide a GitHub token with
the `write:discussion` scope enabled. Will use the same token set in xref:reference:release/github.adoc[].

NOTE: GitHub discussions are currently only possible for repositories that belong to organizations. If you would like to
link a release with a discussion then see the use of the `discussionCategoryName` in the
xref:reference:release/github.adoc[] releaser.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$announce/yaml/common-head.adoc[]

    # The GitHub organization that owns the discussion.
    # icon:exclamation-triangle[]
    organization: some-org

    # The GitHub team that owns the discussion.
    # icon:exclamation-triangle[]
    team: some-team

    # The messages' title.
    # Review the available xref:reference:name-templates.adoc[].
    # icon:dot-circle[] icon:file-alt[]
    title: '{{projectNameCapitalized}} {{projectVersion}} released!'

    # The announcement message.
    # Review the available xref:reference:name-templates.adoc[].
    # icon:dot-circle[] icon:file-alt[]
    message: '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

    # Path to a template file that contains the message.
    # Review the available xref:reference:name-templates.adoc[].
    # Defaults to `src/jreleaser/templates/discussions.tpl`.
    # icon:dot-circle[]
    messageTemplate: path/to/template/discussions.tpl
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$announce/toml/common-head.adoc[]

  # The GitHub organization that owns the discussion.
  # icon:exclamation-triangle[]
  organization = "some-org"

  # The GitHub team that owns the discussion.
  # icon:exclamation-triangle[]
  team = "some-team"

  # The messages' title.
  # Review the available xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  title = "{{projectNameCapitalized}} {{projectVersion}} released!"

  # The announcement message.
  # Review the available xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  message = "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}"

  # Path to a template file that contains the message.
  # Review the available xref:reference:name-templates.adoc[].
  # Defaults to `src/jreleaser/templates/discussions.tpl`.
  # icon:dot-circle[]
  messageTemplate = "path/to/template/discussions.tpl"
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$announce/json/common-head.adoc[]

      // The GitHub organization that owns the discussion.
      // icon:exclamation-triangle[]
      "organization": "some-org",

      // The GitHub team that owns the discussion.
      // icon:exclamation-triangle[]
      "team": "some-team",

      // The messages' title.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      "title": "{{projectNameCapitalized}} {{projectVersion}} released!",

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      "message": "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}",

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/discussions.tpl`.
      // icon:dot-circle[]
      "messageTemplate": "path/to/template/discussions.tpl"
include::partial$announce/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$announce/maven/common-head.adoc[]

      <!--
        The GitHub organization that owns the discussion.
        icon:exclamation-triangle[]
      -->
      <organization>some-org</organization>

      <!--
        The GitHub team that owns the discussion.
        icon:exclamation-triangle[]
      -->
      <team>some-team</team>

      <!--
        The messages' title.
        Review the available xref:reference:name-templates.adoc[].
        icon:dot-circle[] icon:file-alt[]
      -->
      <title>{{projectNameCapitalized}} {{projectVersion}} released!</title>

      <!--
        The announcement message.
        Review the available xref:reference:name-templates.adoc[].
        icon:dot-circle[] icon:file-alt[]
      -->
      <message>🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}</message>

      <!--
        Path to a template file that contains the message.
        Review the available xref:reference:name-templates.adoc[].
        Defaults to `src/jreleaser/templates/discussions.tpl`.
        icon:dot-circle[]
      -->
      <messageTemplate>path/to/template/discussions.tpl</messageTemplate>
include::partial$announce/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$announce/gradle/common-head.adoc[]

      // The GitHub organization that owns the discussion.
      // icon:exclamation-triangle[]
      organization = 'some-org'

      // The GitHub team that owns the discussion.
      // icon:exclamation-triangle[]
      team = 'some-team'

      // The messages' title.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      title = '{{projectNameCapitalized}} {{projectVersion}} released!'

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      message = '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/discussions.tpl`.
      // icon:dot-circle[]
      messageTemplate = 'path/to/template/discussions.tpl'
include::partial$announce/gradle/common-footer.adoc[]
----
--
====

You may define either `message` or `messageTemplate`, with the former taking precedence over the latter.

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1,<1", width="100%"]
|===
| Property | System Property                               | Environment Variable
| active   | jreleaser.announce.{announcer_sys_key}.active | JRELEASER_ANNOUNCE_{announcer_env_key}_ACTIVE
|===

== Templates

The default location for templates is:

`src/jreleaser/templates`

The following list shows the filenames that may be used to override default templates:

* `discussions.tpl`

Templates may be initialized using the `template` command

 * xref:tools:jreleaser-cli.adoc#_template_generate[{icon_cli_s} template generate]
 * xref:tools:jreleaser-maven.adoc#_jreleasertemplate_generate[{icon_maven_s} jreleaser:template-generate]
 * xref:tools:jreleaser-gradle.adoc#_jreleasertemplategenerate[{icon_gradle_s} jreleaserTemplategGenerate]
 * xref:tools:jreleaser-ant.adoc#_jreleaser_template_generate[{icon_ant_s} jreleaser-template-generate]
