= Discourse
:announcer_id:      discourse
:announcer_name:    Discourse
:announcer_sys_key: discourse
:announcer_env_key: DISCOURSE

Posts a message to a link:https://www.discourse.org/[Discourse] server. You must procure a username and apiKey to use
this announcer.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$announce/yaml/common-head.adoc[]

    # The Discourse server endpoint.
    # icon:exclamation-triangle[]
    host: pass:[https://my.discourseserver.com]

    # The Discourse username to use.
    # If left unspecified, the `JRELEASER_DISCOURSE_USERNAME`
    # environment variable must be defined.
    # icon:exclamation-triangle[] icon:eye-slash[]
    username: duke

    # The ApiKey associated with the given username.
    # If left unspecified, the `JRELEASER_DISCOURSE_API_KEY`
    # environment variable must be defined.
    # icon:exclamation-triangle[] icon:eye-slash[]
    apiKey: __USE_ENVIRONMENT_VARIABLE__

    # The categoryName where the message will be sent to
    # If left unspecified, the `JRELEASER_DISCOURSE_CATEGORY_NAME`
    # environment variable must be defined.
    # icon:exclamation-triangle[] icon:eye-slash[]
    categoryName: announce

    # The message's title.
    # Review the available xref:reference:name-templates.adoc[].
    # icon:dot-circle[] icon:file-alt[]
    title: '{{projectNameCapitalized}} {{projectVersion}} released!'

    # The announcement message.
    # Review the available xref:reference:name-templates.adoc[].
    # icon:dot-circle[] icon:file-alt[]
    message: '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

    # Path to a template file that contains the message.
    # Review the available xref:reference:name-templates.adoc[].
    # Defaults to `src/jreleaser/templates/discourse.tpl`.
    # icon:dot-circle[]
    messageTemplate: path/to/template/discourse.tpl
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$announce/toml/common-head.adoc[]

  # The Discourse server endpoint.
  # icon:exclamation-triangle[]
  host = "pass:[https://my.discourseserver.com]"

  # The Discourse username to use.
  # If left unspecified, the `JRELEASER_DISCOURSE_USERNAME`
  # environment variable must be defined.
  # icon:exclamation-triangle[] icon:eye-slash[]
  username = "duke"

  # The ApiKey associated with the given username.
  # If left unspecified, the `JRELEASER_DISCOURSE_API_KEY`
  # environment variable must be defined.
  # icon:exclamation-triangle[] icon:eye-slash[]
  apiKey = "__USE_ENVIRONMENT_VARIABLE__"

  # The categoryName where the message will be sent to
  # If left unspecified, the `JRELEASER_DISCOURSE_CATEGORY_NAME`
  # environment variable must be defined.
  # icon:exclamation-triangle[] icon:eye-slash[]
  categoryName = "announce"

  # The message's title.
  # Review the available xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  title = "{{projectNameCapitalized}} {{projectVersion}} released!"

  # The announcement message.
  # Review the available xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  message = "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}"

  # Path to a template file that contains the message.
  # Review the available xref:reference:name-templates.adoc[].
  # Defaults to `src/jreleaser/templates/discourse.tpl`.
  # icon:dot-circle[]
  messageTemplate = "path/to/template/discourse.tpl"
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$announce/json/common-head.adoc[]

      // The Discourse server endpoint.
      // icon:exclamation-triangle[]
      "host": "pass:[https://my.discourseserver.com]",

      // The Discourse username to use.
      // If left unspecified, the `JRELEASER_DISCOURSE_USERNAME`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "username": "duke",

      // The ApiKey associated with the given username.
      // If left unspecified, the `JRELEASER_DISCOURSE_API_KEY`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "apiKey": "__USE_ENVIRONMENT_VARIABLE__",

      // The categoryName where the message will be sent to
      // If left unspecified, the `JRELEASER_DISCOURSE_CATEGORY_NAME`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "categoryName": "announce",

      // The message's title.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[]
      "title": "{{projectNameCapitalized}} {{projectVersion}} released!",

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      "message": "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}",

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/discourse.tpl`.
      // icon:dot-circle[]
      "messageTemplate": "path/to/template/discourse.tpl"
include::partial$announce/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$announce/maven/common-head.adoc[]

      <!--
        The Discourse server endpoint.
        icon:exclamation-triangle[]
      -->
      <host>pass:[https://my.discourseserver.com]</host>

      <!--
        The Discourse username to use.
        If left unspecified, the `JRELEASER_DISCOURSE_USERNAME`
        environment variable must be defined.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <username>duke</username>

      <!--
        The ApiKey associated with the given username.
        If left unspecified, the `JRELEASER_DISCOURSE_API_KEY`
        environment variable must be defined.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <apiKey>__USE_ENVIRONMENT_VARIABLE__</apiKey>

      <!--
        The categoryName where the message will be sent to
        If left unspecified, the `JRELEASER_DISCOURSE_CATEGORY_NAME`
        environment variable must be defined.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <categoryName>announce</categoryName>

      <!--
        The message's title.
        Review the available xref:reference:name-templates.adoc[].
        icon:dot-circle[]
      -->
      <title>{{projectNameCapitalized}} {{projectVersion}} released!</title>

      <!--
        The announcement message.
        Review the available xref:reference:name-templates.adoc[].
        icon:dot-circle[] icon:file-alt[]
      -->
      <message>🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}</message>

      <!--
        Path to a template file that contains the message.
        Review the available xref:reference:name-templates.adoc[].
        Defaults to `src/jreleaser/templates/discourse.tpl`.
        icon:dot-circle[]
      -->
      <messageTemplate>path/to/template/discourse.tpl</messageTemplate>
include::partial$announce/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$announce/gradle/common-head.adoc[]

      // The Discourse server endpoint.
      // icon:exclamation-triangle[]
      host = 'pass:[https://my.discourseserver.com]'

      // The Discourse username to use.
      // If left unspecified, the `JRELEASER_DISCOURSE_USERNAME`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      username = 'duke'

      // The ApiKey associated with the given username.
      // If left unspecified, the `JRELEASER_DISCOURSE_API_KEY`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      apiKey = '__USE_ENVIRONMENT_VARIABLE__'

      // The categoryName where the message will be sent to
      // If left unspecified, the `JRELEASER_DISCOURSE_CATEGORY_NAME`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      categoryName = 'announce'

      // The message's title.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[]
      title = '{{projectNameCapitalized}} {{projectVersion}} released!'

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      message = '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/discourse.tpl`.
      // icon:dot-circle[]
      messageTemplate = 'path/to/template/discourse.tpl'
include::partial$announce/gradle/common-footer.adoc[]
----
--
====

You may define either `message` or `messageTemplate`, with the former taking precedence over the latter.

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property                               | Environment Variable
2+| *active*
| jreleaser.announce.{announcer_sys_key}.active | JRELEASER_ANNOUNCE_{announcer_env_key}_ACTIVE
2+| *username*
| jreleaser.announce.{announcer_sys_key}.username +
  jreleaser.{announcer_sys_key}.username
| JRELEASER_ANNOUNCE_{announcer_env_key}_USERNAME +
  JRELEASER_{announcer_env_key}_USERNAME
2+| *apiKey*
| jreleaser.announce.{announcer_sys_key}.api.key +
  jreleaser.{announcer_sys_key}.api.key
| JRELEASER_ANNOUNCE_{announcer_env_key}_API_KEY +
  JRELEASER_{announcer_env_key}_API_KEY
2+| *category*
| jreleaser.announce.{announcer_sys_key}.category +
  jreleaser.{announcer_sys_key}.category
| JRELEASER_ANNOUNCE_{announcer_env_key}_CATEGORY +
  JRELEASER_{announcer_env_key}_CATEGORY
|===

== Templates

The default location for templates is:

`src/jreleaser/templates`

The following list shows the filenames that may be used to override default templates:

* `discourse.tpl`

Templates may be initialized using the `template` command

 * xref:tools:jreleaser-cli.adoc#_template_generate[{icon_cli_s} template generate]
 * xref:tools:jreleaser-maven.adoc#_jreleasertemplate_generate[{icon_maven_s} jreleaser:template-generate]
 * xref:tools:jreleaser-gradle.adoc#_jreleasertemplategenerate[{icon_gradle_s} jreleaserTemplateGenerate]
 * xref:tools:jreleaser-ant.adoc#_jreleaser_template_generate[{icon_ant_s} jreleaser-template-generate]
