= Linkedin
:announcer_id:      linkedin
:announcer_name:    Linkedin
:announcer_sys_key: linkedin
:announcer_env_key: LINKEDIN

Shares a post to link:https://linkedin.com/[Linkedin]. You must obtain an link:https://developer.linkedin.com/[Oauth access token]
with the following permissions:

 * r_emailaddress, 
 * r_liteprofile, 
 * w_member_social
 
== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$announce/yaml/common-head.adoc[]

    # The OAuth access token.
    # icon:exclamation-triangle[] icon:eye-slash[]
    token: __USE_ENVIRONMENT_VARIABLE__

    # The URN identifying the actor that can post a share.
    # icon:dot-circle[] icon:eye-slash[]
    owner: __USE_ENVIRONMENT_VARIABLE__

    # The post subject.
    # Review the available xref:reference:name-templates.adoc[].
    # icon:dot-circle[] icon:file-alt[]
    subject: '{{projectNameCapitalized}} {{projectVersion}} released'

    # The announcement message.
    # Review the available xref:reference:name-templates.adoc[].
    # icon:dot-circle[] icon:file-alt[]
    message: '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

    # Path to a template file that contains the message.
    # Review the available xref:reference:name-templates.adoc[].
    # Defaults to `src/jreleaser/templates/linkedin.tpl`.
    # icon:dot-circle[]
    messageTemplate: path/to/template/linkedin.tpl
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$announce/toml/common-head.adoc[]

  # The OAuth access token.
  # icon:exclamation-triangle[] icon:eye-slash[]
  token = "__USE_ENVIRONMENT_VARIABLE__"

  # The URN identifying the actor that can post a share.
  # icon:dot-circle[] icon:eye-slash[]
  owner = "__USE_ENVIRONMENT_VARIABLE__"

  # The post subject.
  # Review the available xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  subject = "{{projectNameCapitalized}} {{projectVersion}} released"

  # The announcement message.
  # Review the available xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  message = "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}"

  # Path to a template file that contains the message.
  # Review the available xref:reference:name-templates.adoc[].
  # Defaults to `src/jreleaser/templates/linkedin.tpl`.
  # icon:dot-circle[]
  messageTemplate = "path/to/template/linkedin.tpl"
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$announce/json/common-head.adoc[]

      // The OAuth access token.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "token": "__USE_ENVIRONMENT_VARIABLE__",

      // The URN identifying the actor that can post a share.
      // icon:dot-circle[] icon:eye-slash[]
      "owner": "__USE_ENVIRONMENT_VARIABLE__",

      // The post subject.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      "subject": "{{projectNameCapitalized}} {{projectVersion}} released"

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      "message": "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}",

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/linkedin.tpl`.
      // icon:dot-circle[]
      "messageTemplate": "path/to/template/linkedin.tpl"
include::partial$announce/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$announce/maven/common-head.adoc[]

      <!--
        The OAuth access token.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <token>__USE_ENVIRONMENT_VARIABLE__</token>

      <!--
        The URN identifying the actor that can post a share.
        icon:dot-circle[] icon:eye-slash[]
      -->
      <owner>__USE_ENVIRONMENT_VARIABLE__</owner>

      <!--
        The post subject.
        Review the available xref:reference:name-templates.adoc[].
        icon:dot-circle[] icon:file-alt[]
      -->
      <subject>{{projectNameCapitalized}} {{projectVersion}} released</subject>

      <!--
        The announcement message.
        Review the available xref:reference:name-templates.adoc[].
        icon:dot-circle[] icon:file-alt[]
      -->
      <message>🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}</message>

      <!--
        Path to a template file that contains the message.
        Review the available xref:reference:name-templates.adoc[].
        Defaults to `src/jreleaser/templates/linkedin.tpl`.
        icon:dot-circle[]
      -->
      <messageTemplate>path/to/template/linkedin.tpl</messageTemplate>
include::partial$announce/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$announce/gradle/common-head.adoc[]

      // The OAuth access token.
      // icon:exclamation-triangle[] icon:eye-slash[]
      token = '__USE_ENVIRONMENT_VARIABLE__'

      // The URN identifying the actor that can post a share.
      // icon:dot-circle[] icon:eye-slash[]
      owner = '__USE_ENVIRONMENT_VARIABLE__'

      // The post subject.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      subject = '{{projectNameCapitalized}} {{projectVersion}} released'

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      message = '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/linkedin.tpl`.
      // icon:dot-circle[]
      messageTemplate = 'path/to/template/linkedin.tpl'
include::partial$announce/gradle/common-footer.adoc[]
----
--
====

You may define either `message` or `messageTemplate`, with the former taking precedence over the latter.

NOTE: Use `messageTemplate` to define a custom JSON payload.

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property                               | Environment Variable
2+| *active*
| jreleaser.announce.{announcer_sys_key}.active | JRELEASER_ANNOUNCE_{announcer_env_key}_ACTIVE
2+| *token*
| jreleaser.announce.{announcer_sys_key}.access.token +
  jreleaser.{announcer_sys_key}.access.token
| JRELEASER_ANNOUNCE_{announcer_env_key}_ACCESS_TOKEN +
  JRELEASER_{announcer_env_key}_ACCESS_TOKEN
2+| *owner*
| jreleaser.announce.{announcer_sys_key}.owner +
  jreleaser.{announcer_sys_key}.owner
| JRELEASER_ANNOUNCE_{announcer_env_key}_OWNER +
  JRELEASER_{announcer_env_key}_OWNER
|===

== Templates

The default location for templates is:

`src/jreleaser/templates`

The following list shows the filenames that may be used to override default templates:

* `linkedin.tpl`

Templates may be initialized using the `template` command

 * xref:tools:jreleaser-cli.adoc#_template_generate[{icon_cli_s} template generate]
 * xref:tools:jreleaser-maven.adoc#_jreleasertemplate_generate[{icon_maven_s} jreleaser:template-generate]
 * xref:tools:jreleaser-gradle.adoc#_jreleasertemplategenerate[{icon_gradle_s} jreleaserTemplateGenerate]
 * xref:tools:jreleaser-ant.adoc#_jreleaser_template_generate[{icon_ant_s} jreleaser-template-generate]
