= Sdkman
:tool_id:           sdkman
:announcer_id:      sdkman
:announcer_name:    Sdkman
:announcer_sys_key: sdkman
:announcer_env_key: SDKMAN

Publishes a release to link:https://sdkman.io[Sdkman]. Please follow the instructions at
link:https://sdkman.io/vendors[] to register your project as a candidate and obtain publishing credentials.

NOTE: If this announcer is enabled but no xref:reference:packagers/sdkman.adoc[] packager is active in a distribution
then the whole project will be released and announced.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$announce/yaml/common-head.adoc[]

    # The name of the candidate registered in thew Sdkman database.
    # If unspecified, will use `#{project.name}`.
    # icon:dot-circle[]
    candidate: app

    # Sdkman command to use.
    # Supported values are [`MAJOR`, `MINOR`]
    # Defaults to `MAJOR`.
    # icon:dot-circle[]
    command: MAJOR

    # The release notes URL to use.
    # Defaults to `#{release.${releaser}.releaseNotesUrl}`.
    # icon:dot-circle[] icon:file-alt[]
    releaseNotesUrl: pass:[https://host.com/{{projectName}}/{{tagName}}]

    # Custom download URL.
    # icon:dot-circle[] icon:file-alt[]
    downloadUrl: pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFile}}]

    # The consumer key for publishing to Sdkman.
    # icon:exclamation-triangle[] icon:eye-slash[]
    consumerKey: __USE_ENVIRONMENT_VARIABLE__

    # The consumer token for publishing to Sdkman.
    # icon:exclamation-triangle[] icon:eye-slash[]
    consumerToken: __USE_ENVIRONMENT_VARIABLE__
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$announce/toml/common-head.adoc[]

  # The name of the candidate registered in thew Sdkman database.
  # If unspecified, will use `#{project.name}`.
  # icon:dot-circle[]
  candidate = "app"

  # The release notes URL to use.
  # Defaults to `#{release.${releaser}.releaseNotesUrl}`.
  # icon:dot-circle[] icon:file-alt[]
  releaseNotesUrl = "pass:[https://host.com/{{projectName}}/{{tagName}}]"

  # Custom download URL.
  # icon:dot-circle[] icon:file-alt[]
  downloadUrl = "pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFile}}]"

  # Sdkman command to use.
  # Supported values are [`MAJOR`, `MINOR`]
  # Defaults to `MAJOR`.
  # icon:dot-circle[]
  command = "MAJOR"

  # The consumer key for publishing to Sdkman.
  # icon:exclamation-triangle[] icon:eye-slash[]
  consumerKey = "__USE_ENVIRONMENT_VARIABLE__"

  # The consumer token for publishing to Sdkman.
  # icon:exclamation-triangle[] icon:eye-slash[]
  consumerToken = "__USE_ENVIRONMENT_VARIABLE__"
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$announce/json/common-head.adoc[]

      // The name of the candidate registered in thew Sdkman database.
      // If unspecified, will use `#{project.name}`.
      // icon:dot-circle[]
      "candidate": "app",

      // The release notes URL to use.
      // Defaults to `#{release.${releaser}.releaseNotesUrl}`.
      // icon:dot-circle[] icon:file-alt[]
      "releaseNotesUrl": "pass:[https://host.com/{{projectName}}/{{tagName}}]",

      // Custom download URL.
      // icon:dot-circle[] icon:file-alt[]
      "downloadUrl": "pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFile}}]",

      // Sdkman command to use.
      // Supported values are [`MAJOR`, `MINOR`]
      // Defaults to `MAJOR`.
      // icon:dot-circle[]
      "command": "MAJOR",

      // The consumer key for publishing to Sdkman.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "consumerKey": "__USE_ENVIRONMENT_VARIABLE__",

      // The consumer token for publishing to Sdkman.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "consumerToken": "__USE_ENVIRONMENT_VARIABLE__"
include::partial$announce/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$announce/maven/common-head.adoc[]

      <!--
        The name of the candidate registered in thew Sdkman database.
        If unspecified, will use `#{project.name}`.
        icon:dot-circle[]
      -->
      <candidate>app</candidate>

      <!--
        The release notes URL to use.
        Defaults to `#{release.${releaser}.releaseNotesUrl}`.
        icon:dot-circle[] icon:file-alt[]
      -->
      <releaseNotesUrl>pass:[https://host.com/{{projectName}}/{{tagName}}]</releaseNotesUrl>

      <!--
        Custom download URL.
        icon:dot-circle[] icon:file-alt[]
      -->
      <downloadUrl>pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFile}}]</downloadUrl>

      <!--
        Sdkman command to use.
        Supported values are [`MAJOR`, `MINOR`]
        Defaults to `MAJOR`.
        icon:dot-circle[]
      -->
      <command>MAJOR</command>

      <!--
        The consumer key for publishing to Sdkman.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <consumerKey>__USE_ENVIRONMENT_VARIABLE__</consumerKey>

      <!--
        The consumer token for publishing to Sdkman.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <consumerToken>__USE_ENVIRONMENT_VARIABLE__</consumerToken>
include::partial$announce/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$announce/gradle/common-head.adoc[]

      // The name of the candidate registered in thew Sdkman database.
      // If unspecified, will use `#{project.name}`.
      // icon:dot-circle[]
      candidate = 'app'

      // The release notes URL to use.
      // Defaults to `#{release.${releaser}.releaseNotesUrl}`.
      // icon:dot-circle[] icon:file-alt[]
      releaseNotesUrl = 'pass:[https://host.com/{{projectName}}/{{tagName}}]'

      // Custom download URL.
      // icon:dot-circle[] icon:file-alt[]
      downloadUrl = 'pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFile}}]'

      // Sdkman command to use.
      // Supported values are [`MAJOR`, `MINOR`]
      // Defaults to `MAJOR`.
      // icon:dot-circle[]
      command = 'MAJOR'

      // The consumer key for publishing to Sdkman.
      // icon:exclamation-triangle[] icon:eye-slash[]
      consumerKey = '__USE_ENVIRONMENT_VARIABLE__'

      // The consumer token for publishing to Sdkman.
      // icon:exclamation-triangle[] icon:eye-slash[]
      consumerToken = '__USE_ENVIRONMENT_VARIABLE__'
include::partial$announce/gradle/common-footer.adoc[]
----
--
====

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property                               | Environment Variable
2+| *active*
| jreleaser.announce.{announcer_sys_key}.active | JRELEASER_ANNOUNCE_{announcer_env_key}_ACTIVE
2+| *consumerKey*
| jreleaser.announce.{announcer_sys_key}.consumer.key +
  jreleaser.{announcer_sys_key}.consumer.key
| JRELEASER_ANNOUNCE_{announcer_env_key}_CONSUMER_KEY +
  JRELEASER_{announcer_env_key}_CONSUMER_KEY
2+| *consumerToken*
| jreleaser.announce.{announcer_sys_key}.consumer.token +
  jreleaser.{announcer_sys_key}.consumer.token
| JRELEASER_ANNOUNCE_{announcer_env_key}_CONSUMER_TOKEN +
  JRELEASER_{announcer_env_key}_CONSUMER_TOKEN
|===

== Requirements

This announcer has the following requirements:

* No snapshot releases are supported.
* Only `zip` artifacts are supported.
* The default platform is set to `UNIVERSAL` if the artifact did not define a value for its `platform` field.
* If there's more than one artifact then each artifact requires distinct `platform` values, otherwise the latest
 artifact will override any previous matches by platform.
* You may explicitly skip a distribution or artifact by defining an extra property named `skipSdkman` with a `true` value.
* Announcing will be skipped if no suitable artifacts are found.

Supported platform values are:

* `mac`, `osx`.
* `win`, `windows`.
* `linux`.

== Command

You may set the `command` property to either `MAJOR` or `MINOR`. A `MINOR` release publishes a new version and posts an
announcement. A `MAJOR` release performs the same actions as `MINOR` plus setting the recently published version as default.
Thus, the only difference between `MINOR` and `MAJOR` is setting a given version as default.

include::partial$packagers/downloadUrl.adoc[]
