= Slack
:announcer_id:      slack
:announcer_name:    Slack
:announcer_sys_key: slack
:announcer_env_key: SLACK

Posts a message to link:https://slack.com/[Slack]. You must provide either a bot or a personal token with the following
scopes set:

* channels:join
* chat:write
* chat:write.public

1. Log into the target Slack workspace.
2. Create a link:https://api.slack.com/apps/new[Slack app].
3. Click on Incoming Webhooks.
4. Create a new webhook.
5. Copy the generated webhook URL.

IMPORTANT: Webhooks are not protected, anyone with access to the webhook URI can send messages to the target room. Prefer
setting the `JRELEASER_SLACK_WEBHOOK` environment variable over explicitly setting a value in the configuration DSL.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$announce/yaml/common-head.adoc[]

    # The ApiKey associated with the given account.
    # icon:exclamation-triangle[] icon:eye-slash[]
    token: __USE_ENVIRONMENT_VARIABLE__

    # The webhook associated with a specific Slack channel.
    # icon:exclamation-triangle[] icon:eye-slash[]
    webhook: __USE_ENVIRONMENT_VARIABLE__

    # The channel where the message will be sent to
    # Defaults to `#announce`.
    # icon:dot-circle[]
    channel: '#announce'

    # The announcement message.
    # Review the available xref:reference:name-templates.adoc[].
    # icon:dot-circle[] icon:file-alt[]
    message: '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

    # Path to a template file that contains the message.
    # Review the available xref:reference:name-templates.adoc[].
    # Defaults to `src/jreleaser/templates/slack.tpl`.
    # icon:dot-circle[]
    messageTemplate: path/to/template/slack.tpl
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$announce/toml/common-head.adoc[]

  # The ApiKey associated with the given account.
  # icon:exclamation-triangle[] icon:eye-slash[]
  token = "__USE_ENVIRONMENT_VARIABLE__"

  # The webhook associated with a specific Slack channel.
  # icon:exclamation-triangle[] icon:eye-slash[]
  webhook = "__USE_ENVIRONMENT_VARIABLE__"

  # The channel where the message will be sent to
  # Defaults to `#announce`.
  # icon:dot-circle[]
  channel = "#announce"

  # The announcement message.
  # Review the available xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  message = "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}"

  # Path to a template file that contains the message.
  # Review the available xref:reference:name-templates.adoc[].
  # Defaults to `src/jreleaser/templates/slack.tpl`.
  # icon:dot-circle[]
  messageTemplate = "path/to/template/slack.tpl"
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$announce/json/common-head.adoc[]

      // The ApiKey associated with the given account.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "token": "__USE_ENVIRONMENT_VARIABLE__",

      // The webhook associated with a specific Slack channel.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "webhook": "__USE_ENVIRONMENT_VARIABLE__",

      // The channel where the message will be sent to
      // Defaults to `#announce`.
      // icon:dot-circle[]
      "channel": "#announce",

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      "message": "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}",

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/slack.tpl`.
      // icon:dot-circle[]
      "messageTemplate": "path/to/template/slack.tpl"
include::partial$announce/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$announce/maven/common-head.adoc[]

      <!--
        The ApiKey associated with the given account.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <token>__USE_ENVIRONMENT_VARIABLE__</token>

      <!--
        The webhook associated with a specific Slack channel.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <webhook>__USE_ENVIRONMENT_VARIABLE__</webhook>

      <!--
        The channel where the message will be sent to
        Defaults to `#announce`.
        icon:dot-circle[]
      -->
      <channel>#announce</channel>

      <!--
        The announcement message.
        Review the available xref:reference:name-templates.adoc[].
        icon:dot-circle[] icon:file-alt[]
      -->
      <message>🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}</message>

      <!--
        Path to a template file that contains the message.
        Review the available xref:reference:name-templates.adoc[].
        Defaults to `src/jreleaser/templates/slack.tpl`.
        icon:dot-circle[]
      -->
      <messageTemplate>path/to/template/slack.tpl</messageTemplate>
include::partial$announce/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$announce/gradle/common-head.adoc[]

      // The ApiKey associated with the given account.
      // icon:exclamation-triangle[] icon:eye-slash[]
      token = '__USE_ENVIRONMENT_VARIABLE__'

      // The webhook associated with a specific Slack channel.
      // icon:exclamation-triangle[] icon:eye-slash[]
      webhook = '__USE_ENVIRONMENT_VARIABLE__'

      // The channel where the message will be sent to
      // Defaults to `#announce`.
      // icon:dot-circle[]
      channel = '#announce'

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      message = '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/slack.tpl`.
      // icon:dot-circle[]
      messageTemplate = 'path/to/template/slack.tpl'
include::partial$announce/gradle/common-footer.adoc[]
----
--
====

You may define either `message` or `messageTemplate`, with the former taking precedence over the latter.

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property                               | Environment Variable
2+| *active*
| jreleaser.announce.{announcer_sys_key}.active | JRELEASER_ANNOUNCE_{announcer_env_key}_ACTIVE
2+| *token*
| jreleaser.announce.{announcer_sys_key}.token +
  jreleaser.{announcer_sys_key}.token
| JRELEASER_ANNOUNCE_{announcer_env_key}_TOKEN +
  JRELEASER_{announcer_env_key}_TOKEN
include::partial$announce/webhook-envvars.adoc[]
|===

== Templates

The default location for templates is:

`src/jreleaser/templates`

The following list shows the filenames that may be used to override default templates:

* `slack.tpl`

Templates may be initialized using the `template` command

 * xref:tools:jreleaser-cli.adoc#_template_generate[{icon_cli_s} template generate]
 * xref:tools:jreleaser-maven.adoc#_jreleasertemplate_generate[{icon_maven_s} jreleaser:template-generate]
 * xref:tools:jreleaser-gradle.adoc#_jreleasertemplategenerate[{icon_gradle_s} jreleaserTemplategGenerate]
 * xref:tools:jreleaser-ant.adoc#_jreleaser_template_generate[{icon_ant_s} jreleaser-template-generate]
