= Teams
:announcer_id:      teams
:announcer_name:    Teams
:announcer_sys_key: teams
:announcer_env_key: TEAMS

WARNING: This announcer has been deprecated in `v1.4.0` and will be removed in `v2.0.0`. Use xref:reference:announce/webhooks.adoc[]
instead as shown xref:reference:announce/webhooks.adoc#_teams[here].

Posts a message to a link:https://www.microsoft.com/en-ww/microsoft-teams[Teams] room. You must create a custom webhook for this announcer to work.

1. Log into Teams.
2. Click on the `Apps` icon.
3. Click on the `Connectors` menu item.
4. Click on `Incoming Webhook` and add it to a team.
5. Configure the webhook.
6. Copy the generated webhook URL.

IMPORTANT: Webhooks are not protected, anyone with access to the webhook URI can send messages to the target room. Prefer
setting the `JRELEASER_TEAMS_WEBHOOK` environment variable over explicitly setting a value in the configuration DSL.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$announce/yaml/common-head.adoc[]

    # The webhook associated with a specific Teams room.
    # icon:exclamation-triangle[] icon:eye-slash[]
    webhook: __USE_ENVIRONMENT_VARIABLE__

    # Path to a template file that contains the message.
    # Review the available xref:reference:name-templates.adoc[].
    # Defaults to `src/jreleaser/templates/teams.tpl`.
    # icon:exclamation-triangle[]
    messageTemplate: path/to/template/teams.tpl
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$announce/toml/common-head.adoc[]

  # The webhook associated with a specific Teams room.
  # icon:exclamation-triangle[] icon:eye-slash[]
  webhook = "__USE_ENVIRONMENT_VARIABLE__"

  # Path to a template file that contains the message.
  # Review the available xref:reference:name-templates.adoc[].
  # Defaults to `src/jreleaser/templates/teams.tpl`.
  # icon:exclamation-triangle[]
  messageTemplate = "path/to/template/teams.tpl"
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$announce/json/common-head.adoc[]

      // The webhook associated with a specific Teams room.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "webhook": "__USE_ENVIRONMENT_VARIABLE__",

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/teams.tpl`.
      // icon:dot-circle[] icon:exclamation-triangle[]
      "messageTemplate": "path/to/template/teams.tpl"
include::partial$announce/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$announce/maven/common-head.adoc[]

      <!--
        The webhook associated with a specific Teams room.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <webhook>__USE_ENVIRONMENT_VARIABLE__</webhook>

      <!--
        Path to a template file that contains the message.
        Review the available xref:reference:name-templates.adoc[].
        Defaults to `src/jreleaser/templates/teams.tpl`.
        icon:dot-circle[] icon:exclamation-triangle[]
      -->
      <messageTemplate>path/to/template/teams.tpl</messageTemplate>
include::partial$announce/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$announce/gradle/common-head.adoc[]

      // The webhook associated with a specific Teams room.
      // icon:exclamation-triangle[] icon:eye-slash[]
      webhook = '__USE_ENVIRONMENT_VARIABLE__'

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/teams.tpl`.
      // icon:dot-circle[] icon:exclamation-triangle[]
      messageTemplate = 'path/to/template/teams.tpl'
include::partial$announce/gradle/common-footer.adoc[]
----
--
====

The message must follow the link:https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card[Adaptive Card]
format.

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property                               | Environment Variable
2+| *active*
| jreleaser.announce.{announcer_sys_key}.active | JRELEASER_ANNOUNCE_{announcer_env_key}_ACTIVE
include::partial$announce/webhook-envvars.adoc[]
|===

== Templates

The default location for templates is:

`src/jreleaser/templates`

The following list shows the filenames that may be used to override default templates:

* `teams.tpl`

Templates may be initialized using the `template` command

 * xref:tools:jreleaser-cli.adoc#_template_generate[{icon_cli_s} template generate]
 * xref:tools:jreleaser-maven.adoc#_jreleasertemplate_generate[{icon_maven_s} jreleaser:template-generate]
 * xref:tools:jreleaser-gradle.adoc#_jreleasertemplategenerate[{icon_gradle_s} jreleaserTemplategGenerate]
 * xref:tools:jreleaser-ant.adoc#_jreleaser_template_generate[{icon_ant_s} jreleaser-template-generate]
