= Telegram
:announcer_id:      telegram
:announcer_name:    Telegram
:announcer_sys_key: telegram
:announcer_env_key: TELEGRAM

Posts a message to a link:https://telegram.org/[Telegram] chat. You must create a link:https://core.telegram.org/bots[Bot]
for this announcer to work. You must also obtain the `chatId` for the particular chat/channel where the message will be sent.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$announce/yaml/common-head.adoc[]

    # The token associated with a Telegram bot.
    # icon:exclamation-triangle[] icon:eye-slash[]
    token: __USE_ENVIRONMENT_VARIABLE__

    # The identifier of the chat where announcemnts will be posted.
    # icon:exclamation-triangle[] icon:eye-slash[]
    chatId: __USE_ENVIRONMENT_VARIABLE__

    # The announcement message.
    # Review the available xref:reference:name-templates.adoc[].
    # icon:dot-circle[] icon:file-alt[]
    message: '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

    # Path to a template file that contains the message.
    # Review the available xref:reference:name-templates.adoc[].
    # Defaults to `src/jreleaser/templates/telegram.tpl`.
    # icon:dot-circle[]
    messageTemplate: path/to/template/telegram.tpl
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$announce/toml/common-head.adoc[]

  # The token associated with a Telegram bot.
  # icon:exclamation-triangle[] icon:eye-slash[]
  token = "__USE_ENVIRONMENT_VARIABLE__"

  # The identifier of the chat where announcemnts will be posted.
  # icon:exclamation-triangle[] icon:eye-slash[]
  chatId = "__USE_ENVIRONMENT_VARIABLE__"

  # The announcement message.
  # Review the available xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  message = "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}"

  # Path to a template file that contains the message.
  # Review the available xref:reference:name-templates.adoc[].
  # Defaults to `src/jreleaser/templates/telegram.tpl`.
  # icon:dot-circle[]
  messageTemplate = "path/to/template/telegram.tpl"
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$announce/json/common-head.adoc[]

      // The token associated with a Telegram bot.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "token": "__USE_ENVIRONMENT_VARIABLE__",

      // The identifier of the chat where announcemnts will be posted.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "chatId": "__USE_ENVIRONMENT_VARIABLE__",

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      "message": "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}",

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/telegram.tpl`.
      // icon:dot-circle[]
      "messageTemplate": "path/to/template/telegram.tpl"
include::partial$announce/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$announce/maven/common-head.adoc[]

      <!--
        The token associated with a Telegram bot.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <token>__USE_ENVIRONMENT_VARIABLE__</token>

      <!--
        The identifier of the chat where announcemnts will be posted.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <chatId>__USE_ENVIRONMENT_VARIABLE__</chatId>

      <!--
        The announcement message.
        Review the available xref:reference:name-templates.adoc[].
        icon:dot-circle[] icon:file-alt[]
      -->
      <message>🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}</message>

      <!--
        Path to a template file that contains the message.
        Review the available xref:reference:name-templates.adoc[].
        Defaults to `src/jreleaser/templates/telegram.tpl`.
        icon:dot-circle[]
      -->
      <messageTemplate>path/to/template/telegram.tpl</messageTemplate>
include::partial$announce/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$announce/gradle/common-head.adoc[]

      // The token associated with a Telegram bot.
      // icon:exclamation-triangle[] icon:eye-slash[]
      token = '__USE_ENVIRONMENT_VARIABLE__'

      // The identifier of the chat where announcemnts will be posted.
      // icon:exclamation-triangle[] icon:eye-slash[]
      chatId = '__USE_ENVIRONMENT_VARIABLE__'

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      message = '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/telegram.tpl`.
      // icon:dot-circle[]
      messageTemplate = 'path/to/template/telegram.tpl'
include::partial$announce/gradle/common-footer.adoc[]
----
--
====

You may define either `message` or `messageTemplate`, with the former taking precedence over the latter.

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property                               | Environment Variable
2+| *active*
| jreleaser.announce.{announcer_sys_key}.active | JRELEASER_ANNOUNCE_{announcer_env_key}_ACTIVE
2+| *token*
| jreleaser.announce.{announcer_sys_key}.token +
  jreleaser.{announcer_sys_key}.token
| JRELEASER_ANNOUNCE_{announcer_env_key}_TOKEN +
  JRELEASER_{announcer_env_key}_TOKEN
2+| *chatId*
| jreleaser.announce.{announcer_sys_key}.chat.id +
  jreleaser.{announcer_sys_key}.chat.id
| JRELEASER_ANNOUNCE_{announcer_env_key}_CHAT_ID +
  JRELEASER_{announcer_env_key}_CHAT_ID
|===

== Templates

The default location for templates is:

`src/jreleaser/templates`

The following list shows the filenames that may be used to override default templates:

* `telegram.tpl`

Templates may be initialized using the `template` command

 * xref:tools:jreleaser-cli.adoc#_template_generate[{icon_cli_s} template generate]
 * xref:tools:jreleaser-maven.adoc#_jreleasertemplate_generate[{icon_maven_s} jreleaser:template-generate]
 * xref:tools:jreleaser-gradle.adoc#_jreleasertemplategenerate[{icon_gradle_s} jreleaserTemplateGenerate]
 * xref:tools:jreleaser-ant.adoc#_jreleaser_template_generate[{icon_ant_s} jreleaser-template-generate]
