= Telegram
:announcer_id:   telegram
:announcer_name: Telegram

Posts a message to a link:https://mattermost.com/[Telegram] chat. You must create a link:https://core.telegram.org/bots[Bot]
for this announcer to work. You must also obtain the `chatId` for the particular chat/channel where the message will be sent.

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="attributes,+macros"]
----
include::partial$announce/yaml/common-head.adoc[]

    # The token associated with a Telegram bot.
    # If left unspecified, the `JRELEASER_TELEGRAM_TOKEN`
    # environment variable must be defined.
    # icon:exclamation-triangle[] icon:eye-slash[]
    token: __DO_NOT_SET_HERE__

    # The identifier of the chat where announcemnts will be posted.
    # If left unspecified, the `JRELEASER_TELEGRAM_CHAT_ID`
    # environment variable must be defined.
    # icon:exclamation-triangle[] icon:eye-slash[]
    chatId: __DO_NOT_SET_HERE__

    # The announcement message.
    # Review the available xref:reference:name-templates.adoc[].
    # icon:dot-circle[] icon:file-alt[]
    message: '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

    # Path to a template file that contains the message.
    # Review the available xref:reference:name-templates.adoc[].
    # Defaults to `src/jreleaser/templates/mattermost.tpl`.
    # icon:dot-circle[]
    messageTemplate: path/to/template/mattermost.tpl
----
--
TOML::
+
--
[source,toml]
[subs="attributes,+macros"]
----
include::partial$announce/toml/common-head.adoc[]

  # The token associated with a Telegram bot.
  # If left unspecified, the `JRELEASER_TELEGRAM_TOKEN`
  # environment variable must be defined.
  # icon:exclamation-triangle[] icon:eye-slash[]
  token = "__DO_NOT_SET_HERE__"

  # The identifier of the chat where announcemnts will be posted.
  # If left unspecified, the `JRELEASER_TELEGRAM_CHAT_ID`
  # environment variable must be defined.
  # icon:exclamation-triangle[] icon:eye-slash[]
  chatId = "__DO_NOT_SET_HERE__"

  # The announcement message.
  # Review the available xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  message = "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}"

  # Path to a template file that contains the message.
  # Review the available xref:reference:name-templates.adoc[].
  # Defaults to `src/jreleaser/templates/mattermost.tpl`.
  # icon:dot-circle[]
  messageTemplate = "path/to/template/mattermost.tpl"
----
--
JSON::
+
--
[source,json]
[subs="attributes,+macros"]
----
include::partial$announce/json/common-head.adoc[]

      // The token associated with a Telegram bot.
      // If left unspecified, the `JRELEASER_TELEGRAM_TOKEN`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "token": "__DO_NOT_SET_HERE__",

      // The identifier of the chat where announcemnts will be posted.
      // If left unspecified, the `JRELEASER_TELEGRAM_CHAT_ID`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "chatId": "__DO_NOT_SET_HERE__",

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      "message": "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}",

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/mattermost.tpl`.
      // icon:dot-circle[]
      "messageTemplate": "path/to/template/mattermost.tpl"
include::partial$announce/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="attributes,verbatim,+macros"]
----
include::partial$announce/maven/common-head.adoc[]

      <!--
        The token associated with a Telegram bot.
        If left unspecified, the `JRELEASER_TELEGRAM_TOKEN` environment variable must be defined.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <token>__DO_NOT_SET_HERE__</token>

      <!--
        The identifier of the chat where announcemnts will be posted.
        If left unspecified, the `JRELEASER_TELEGRAM_CHAT_ID`
        environment variable must be defined.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <chatId>__DO_NOT_SET_HERE__</chatId>

      <!--
        The announcement message.
        Review the available xref:reference:name-templates.adoc[].
        icon:dot-circle[] icon:file-alt[]
      -->
      <message>🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}</message>

      <!--
        Path to a template file that contains the message.
        Review the available xref:reference:name-templates.adoc[].
        Defaults to `src/jreleaser/templates/mattermost.tpl`.
        icon:dot-circle[]
      -->
      <messageTemplate>path/to/template/mattermost.tpl</messageTemplate>
include::partial$announce/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="attributes,+macros"]
----
include::partial$announce/gradle/common-head.adoc[]

      // The token associated with a Telegram bot.
      // If left unspecified, the `JRELEASER_TELEGRAM_TOKEN`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      token = '__DO_NOT_SET_HERE__'

      // The identifier of the chat where announcemnts will be posted.
      // If left unspecified, the `JRELEASER_TELEGRAM_CHAT_ID`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      chatId = '__DO_NOT_SET_HERE__'

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      message = '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/mattermost.tpl`.
      // icon:dot-circle[]
      messageTemplate = 'path/to/template/mattermost.tpl'
include::partial$announce/gradle/common-footer.adoc[]
----
--
====

You may define either `message` or `messageTemplate`, with the former taking precedence over the latter.

== Templates

The default location for templates is:

`src/jreleaser/templates`

The following list shows the filenames that may be used to override default templates:

* `telegram.tpl`

Templates may be initialized using the `template` command

xref:tools:jreleaser-cli.adoc#_template[{icon_cli_s} template],
xref:tools:jreleaser-maven.adoc#_jreleasertemplate[{icon_maven_s} jreleaser:template],
xref:tools:jreleaser-gradle.adoc#_jreleasertemplate[{icon_gradle_s} jreleaserTemplate],
xref:tools:jreleaser-ant.adoc#_jreleaser_template[{icon_ant_s} jreleaser-template]
