= Twist
:announcer_id:      twist
:announcer_name:    Twist
:announcer_sys_key: twist
:announcer_env_key: TWIST

Posts a message to link:https://twist.com[Twist]. You must obtain an link:https://developer.twist.com/v3/#oauth-2[OAuth 2 access token]. Requires registering an account and setting up an application (with type 'General Integration').

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$announce/yaml/common-head.adoc[]

    # The OAuth access token for Twist API authentication.
    # icon:exclamation-triangle[] icon:eye-slash[]
    accessToken: __USE_ENVIRONMENT_VARIABLE__

    # The ID of the channel where the message will be posted.
    # Either channelId or threadId must be set (but not both).
    # icon:exclamation-triangle[]
    channelId: 123456

    # The ID of the thread where the message will be posted.
    # Either channelId or threadId must be set (but not both).
    # icon:exclamation-triangle[]
    threadId: 789012

    # The title of the message.
    # Only used when posting to a channel (channelId), not when replying to a thread.
    # Review the available xref:reference:name-templates.adoc[].
    # icon:dot-circle[] icon:file-alt[]
    title: '{{projectNameCapitalized}} {{projectVersion}} released'

    # The announcement message.
    # Review the available xref:reference:name-templates.adoc[].
    # icon:dot-circle[] icon:file-alt[]
    message: '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

    # Path to a template file that contains the message.
    # Review the available xref:reference:name-templates.adoc[].
    # Defaults to `src/jreleaser/templates/twist.tpl`.
    # icon:dot-circle[]
    messageTemplate: path/to/template/twist.tpl
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$announce/toml/common-head.adoc[]

  # The OAuth access token for Twist API authentication.
  # icon:exclamation-triangle[] icon:eye-slash[]
  accessToken = "__USE_ENVIRONMENT_VARIABLE__"

  # The ID of the channel where the message will be posted.
  # Either channelId or threadId must be set (but not both).
  # icon:exclamation-triangle[]
  channelId = 123456

  # The ID of the thread where the message will be posted.
  # Either channelId or threadId must be set (but not both).
  # icon:exclamation-triangle[]
  threadId = 789012

  # The title of the message.
  # Only used when posting to a channel (channelId), not when replying to a thread.
  # Review the available xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  title = "{{projectNameCapitalized}} {{projectVersion}} released"

  # The announcement message.
  # Review the available xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  message = "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}"

  # Path to a template file that contains the message.
  # Review the available xref:reference:name-templates.adoc[].
  # Defaults to `src/jreleaser/templates/twist.tpl`.
  # icon:dot-circle[]
  messageTemplate = "path/to/template/twist.tpl"
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$announce/json/common-head.adoc[]

      // The OAuth access token for Twist API authentication.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "accessToken": "__USE_ENVIRONMENT_VARIABLE__",

      // The ID of the channel where the message will be posted.
      // Either channelId or threadId must be set (but not both).
      // icon:exclamation-triangle[]
      "channelId": 123456,

      // The ID of the thread where the message will be posted.
      // Either channelId or threadId must be set (but not both).
      // icon:exclamation-triangle[]
      "threadId": 789012,

      // The title of the message.
      // Only used when posting to a channel (channelId), not when replying to a thread.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      "title": "{{projectNameCapitalized}} {{projectVersion}} released",

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      "message": "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}",

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/twist.tpl`.
      // icon:dot-circle[]
      "messageTemplate": "path/to/template/twist.tpl"
include::partial$announce/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$announce/maven/common-head.adoc[]

      <!--
        The OAuth access token for Twist API authentication.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <accessToken>__USE_ENVIRONMENT_VARIABLE__</accessToken>

      <!--
        The ID of the channel where the message will be posted.
        Either channelId or threadId must be set (but not both).
        icon:exclamation-triangle[]
      -->
      <channelId>123456</channelId>

      <!--
        The ID of the thread where the message will be posted.
        Either channelId or threadId must be set (but not both).
        icon:exclamation-triangle[]
      -->
      <threadId>789012</threadId>

      <!--
        The title of the message.
        Only used when posting to a channel (channelId), not when replying to a thread.
        Review the available xref:reference:name-templates.adoc[].
        icon:dot-circle[] icon:file-alt[]
      -->
      <title>{{projectNameCapitalized}} {{projectVersion}} released</title>

      <!--
        The announcement message.
        Review the available xref:reference:name-templates.adoc[].
        icon:dot-circle[] icon:file-alt[]
      -->
      <message>🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}</message>

      <!--
        Path to a template file that contains the message.
        Review the available xref:reference:name-templates.adoc[].
        Defaults to `src/jreleaser/templates/twist.tpl`.
        icon:dot-circle[]
      -->
      <messageTemplate>path/to/template/twist.tpl</messageTemplate>
include::partial$announce/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$announce/gradle/common-head.adoc[]

      // The OAuth access token for Twist API authentication.
      // icon:exclamation-triangle[] icon:eye-slash[]
      accessToken = '__USE_ENVIRONMENT_VARIABLE__'

      // The ID of the channel where the message will be posted.
      // Either channelId or threadId must be set (but not both).
      // icon:exclamation-triangle[]
      channelId = 123456

      // The ID of the thread where the message will be posted.
      // Either channelId or threadId must be set (but not both).
      // icon:exclamation-triangle[]
      threadId = 789012

      // The title of the message.
      // Only used when posting to a channel (channelId), not when replying to a thread.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      title = '{{projectNameCapitalized}} {{projectVersion}} released'

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      message = '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/twist.tpl`.
      // icon:dot-circle[]
      messageTemplate = 'path/to/template/twist.tpl'
include::partial$announce/gradle/common-footer.adoc[]
----
--
====

You may define either `message` or `messageTemplate`, with the former taking precedence over the latter.

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property                               | Environment Variable
2+| *active*
| jreleaser.announce.{announcer_sys_key}.active | JRELEASER_ANNOUNCE_{announcer_env_key}_ACTIVE
2+| *accessToken*
| jreleaser.announce.{announcer_sys_key}.access.token +
  jreleaser.{announcer_sys_key}.access.token
| JRELEASER_ANNOUNCE_{announcer_env_key}_ACCESS_TOKEN +
  JRELEASER_{announcer_env_key}_ACCESS_TOKEN
|===

== Templates

The default location for templates is:

`src/jreleaser/templates`

The following list shows the filenames that may be used to override default templates:

* `twist.tpl`

Templates may be initialized using the `template` command

* xref:tools:jreleaser-cli.adoc#_template_generate[{icon_cli_s} template generate]
* xref:tools:jreleaser-maven.adoc#_jreleasertemplate_generate[{icon_maven_s} jreleaser:template-generate]
* xref:tools:jreleaser-gradle.adoc#_jreleasertemplategenerate[{icon_gradle_s} jreleaserTemplateGenerate]
* xref:tools:jreleaser-ant.adoc#_jreleaser_template_generate[{icon_ant_s} jreleaser-template-generate]
