= Twitter
:announcer_id:      twitter
:announcer_name:    Twitter
:announcer_sys_key: twitter
:announcer_env_key: TWITTER

Tweets a new release. You must register a new Twitter application and obtain the set of credentials. Follow the
instructions from link:https://developer.twitter.com/en/portal/projects-and-apps[Twitter] to complete this task.
Note: Remember to set permissions to include Write access and make sure to re-generate access tokens if you changed permissions.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$announce/yaml/common-head.adoc[]

    # The consumer key.
    # icon:exclamation-triangle[] icon:eye-slash[]
    consumerKey: __USE_ENVIRONMENT_VARIABLE__

    # The consumer token.
    # icon:exclamation-triangle[] icon:eye-slash[]
    consumerSecret: __USE_ENVIRONMENT_VARIABLE__

    # The access token.
    # icon:exclamation-triangle[] icon:eye-slash[]
    accessToken: __USE_ENVIRONMENT_VARIABLE__

    # The access token secret.
    # icon:exclamation-triangle[] icon:eye-slash[]
    accessTokenSecret: __USE_ENVIRONMENT_VARIABLE__

    # The announcement message.
    # Review the available xref:reference:name-templates.adoc[].
    # icon:dot-circle[] icon:file-alt[]
    status: '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

    # The announcement messages.
    # Review the available xref:reference:name-templates.adoc[].
    # icon:dot-circle[] icon:file-alt[]
    statuses:
      - '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'
      - 'New and exciting features added to {{projectNameCapitalized}} {{projectVersion}}'

    # Path to a template file that contains a list of statuses.
    # Review the available xref:reference:name-templates.adoc[].
    # icon:dot-circle[] icon:file-alt[]
    statusTemplate: path/to/template/twitter.tpl
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$announce/toml/common-head.adoc[]

  # The consumer key.
  # icon:exclamation-triangle[] icon:eye-slash[]
  consumerKey = "__USE_ENVIRONMENT_VARIABLE__"

  # The consumer token.
  # icon:exclamation-triangle[] icon:eye-slash[]
  consumerSecret = "__USE_ENVIRONMENT_VARIABLE__"

  # The access token.
  # icon:exclamation-triangle[] icon:eye-slash[]
  accessToken = "__USE_ENVIRONMENT_VARIABLE__"

  # The access token secret.
  # icon:exclamation-triangle[] icon:eye-slash[]
  accessTokenSecret = "__USE_ENVIRONMENT_VARIABLE__"

  # The announcement message.
  # Review the available xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  status = "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}"

  # The announcement message.
  # Review the available xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  statuses = ["🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}", "New and exciting featurer added to {{projectNameCapitalized}} {{projectVersion}}"]

  # Path to a template file that contains a list of statuses.
  # Review the available xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  statusTemplate = "path/to/template/twitter.tpl"
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$announce/json/common-head.adoc[]

      // The consumer key.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "consumerKey": "__USE_ENVIRONMENT_VARIABLE__",

      // The consumer token.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "consumerSecret": "__USE_ENVIRONMENT_VARIABLE__",

      // The access token.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "accessToken": "__USE_ENVIRONMENT_VARIABLE__",

      // The access token secret.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "accessTokenSecret": "__USE_ENVIRONMENT_VARIABLE__",

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      "status": "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}"

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      "statuses": [
        "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}",
        "New and exciting featurer added to {{projectNameCapitalized}} {{projectVersion}}"
      ],

      // Path to a template file that contains a list of statuses.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      "statusTemplate": "path/to/template/twitter.tpl"
include::partial$announce/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$announce/maven/common-head.adoc[]

      <!--
        The consumer key.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <consumerKey>__USE_ENVIRONMENT_VARIABLE__</consumerKey>
  
      <!--
        The consumer token.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <consumerSecret>__USE_ENVIRONMENT_VARIABLE__</consumerSecret>
  
      <!--
        The access token.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <accessToken>__USE_ENVIRONMENT_VARIABLE__</accessToken>
  
      <!--
        The access token secret.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <accessTokenSecret>__USE_ENVIRONMENT_VARIABLE__</accessTokenSecret>

      <!--
        The announcement message.
        Review the available xref:reference:name-templates.adoc[].
        icon:dot-circle[] icon:file-alt[]
      -->
      <status>🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}</status>

      <!--
        The announcement message.
        Review the available xref:reference:name-templates.adoc[].
        icon:dot-circle[] icon:file-alt[]
      -->
      <statuses>
        <status>🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}</status>
        <status>New and exciting featurer added to {{projectNameCapitalized}} {{projectVersion}}</status>
      </statuses>

      <!-- Path to a template file that contains a list of statuses.
       Review the available   xref:reference:name-templates.adoc[].
         icon:dot-circle[] icon:file-alt[]
      -->
      <statusTemplate>path/to/template/twitter.tpl</statusTemplate>
include::partial$announce/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$announce/gradle/common-head.adoc[]

      // The consumer key.
      // icon:exclamation-triangle[] icon:eye-slash[]
      consumerKey = '__USE_ENVIRONMENT_VARIABLE__'

      // The consumer token.
      // icon:exclamation-triangle[] icon:eye-slash[]
      consumerSecret = '__USE_ENVIRONMENT_VARIABLE__'

      // The access token.
      // icon:exclamation-triangle[] icon:eye-slash[]
      accessToken = '__USE_ENVIRONMENT_VARIABLE__'

      // The access token secret.
      // icon:exclamation-triangle[] icon:eye-slash[]
      accessTokenSecret = '__USE_ENVIRONMENT_VARIABLE__'

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      status = '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      statuses = [
        '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}',
        'New and exciting featurer added to {{projectNameCapitalized}} {{projectVersion}}'
      ]

      // Path to a template file that contains a list of statuses.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      statusTemplate = 'path/to/template/twitter.tpl'
include::partial$announce/gradle/common-footer.adoc[]
----
--
====

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property                               | Environment Variable
2+| *active*
| jreleaser.announce.{announcer_sys_key}.active | JRELEASER_ANNOUNCE_{announcer_env_key}_ACTIVE
2+| *consumerKey*
| jreleaser.announce.{announcer_sys_key}.consumer.key +
  jreleaser.{announcer_sys_key}.consumer.key
| JRELEASER_ANNOUNCE_{announcer_env_key}_CONSUMER_KEY +
  JRELEASER_{announcer_env_key}_CONSUMER_KEY
2+| *consumerSecret*
| jreleaser.announce.{announcer_sys_key}.consumer.secret +
  jreleaser.{announcer_sys_key}.consumer.secret
| JRELEASER_ANNOUNCE_{announcer_env_key}_CONSUMER_SECRET +
  JRELEASER_{announcer_env_key}_CONSUMER_SECRET
2+| *accessToken*
| jreleaser.announce.{announcer_sys_key}.access.token +
  jreleaser.{announcer_sys_key}.access.token
| JRELEASER_ANNOUNCE_{announcer_env_key}_ACCESS_TOKEN +
  JRELEASER_{announcer_env_key}_ACCESS_TOKEN
2+| *accessTokenSecret*
| jreleaser.announce.{announcer_sys_key}.access.token.secret +
  jreleaser.{announcer_sys_key}.access.token.secret
| JRELEASER_ANNOUNCE_{announcer_env_key}_ACCESS_TOKEN_SECRET +
  JRELEASER_{announcer_env_key}_ACCESS_TOKEN_SECRET
|===
