= Webhooks
:announcer_sys_key: webhooks
:announcer_env_key: WEBHOOKS
:default-message: 🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}

Posts a message to a service that supports incoming webhooks.

IMPORTANT: Webhooks are not protected, anyone with access to the webhook URI can send messages to the target room. Prefer
setting the corresponding environment variable over explicitly setting a value in the configuration DSL.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
announce:
  # icon:dot-circle[]
  webhooks:

    # Webhooks require a name.
    # icon:exclamation-triangle[]
    myWebhook:

      # Enable or disable this announcer.
      # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
      # Defaults to `NEVER`.
      # icon:dot-circle[] icon:eye-slash[]
      active: ALWAYS

      # Defines the connection timeout in seconds.
      # Defaults to `20`.
      # icon:dot-circle[]
      connectTimeout: 20

      # Defines the read timeout in seconds.
      # Defaults to `60`.
      # icon:dot-circle[]
      readTimeout: 60

      # Additional properties used when evaluating templates.
      # icon:dot-circle[] icon:file-alt[]
      extraProperties:
        # Key will be capitalized and prefixed with `webhook`, i.e, `webhookFoo`.
        foo: bar

      # The incoming webhook URL.
      # icon:exclamation-triangle[] icon:eye-slash[]
      webhook: __USE_ENVIRONMENT_VARIABLE__

      # The announcement message.
      # Review the available xref:reference:name-templates.adoc[].
      # icon:dot-circle[] icon:file-alt[]
      message: '{default-message}'

      # The name of the JSON property that contains the message.
      # Defaults to `text`.
      # Ignored if `messageTemplate` is used.
      # icon:dot-circle[]
      messageProperty: text

      # Path to a template file that contains the message.
      # Review the available xref:reference:name-templates.adoc[].
      # Defaults to `src/jreleaser/templates/myWebhook.tpl`.
      # icon:dot-circle[]
      messageTemplate: path/to/template/myWebhook.tpl

      # Whether to send the payload as is or wrap it with the `#{messageProperty}` property.
      # Defaults to `true`.
      # icon:dot-circle[]
      structuredMessage: false
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
# Webhooks require a name.
# icon:exclamation-triangle[]
[announce.webhooks.myWebhook]

  # Enable or disable this announcer.
  # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
  # Defaults to `NEVER`.
  # icon:dot-circle[] icon:eye-slash[]
  active = "ALWAYS"

  # Defines the connection timeout in seconds.
  # Defaults to `20`.
  # icon:dot-circle[]
  connectTimeout = 20

  # Defines the read timeout in seconds.
  # Defaults to `60`.
  # icon:dot-circle[]
  readTimeout = 60

  # Additional properties used when evaluating templates.
  # icon:dot-circle[] icon:file-alt[]
  extraProperties.foo = "bar"
  # Key will be capitalized and prefixed with `webhook`, i.e, `webhookFoo`.

  # The incoming webhook URL.
  # icon:exclamation-triangle[] icon:eye-slash[]
  webhook = "__USE_ENVIRONMENT_VARIABLE__"

  # The announcement message.
  # Review the available xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  message = "{default-message}"

  # The name of the JSON property that contains the message.
  # Defaults to `text`.
  # Ignored if `messageTemplate` is used.
  # icon:dot-circle[]
  messageProperty = "text"

  # Path to a template file that contains the message.
  # Review the available xref:reference:name-templates.adoc[].
  # Defaults to `src/jreleaser/templates/myWebhook.tpl`.
  # icon:dot-circle[]
  messageTemplate = "path/to/template/myWebhook.tpl"

  # Whether to send the payload as is or wrap it with the `#{messageProperty}` property.
  # Defaults to `true`.
  # icon:dot-circle[]
  structuredMessage = false
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
{
  "announce": {
    // icon:dot-circle[]
    "webhooks": {

      // Webhooks require a name.
      // icon:exclamation-triangle[]
      "myWebhook": {

        // Enable or disable this announcer.
        // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
        // Defaults to `NEVER`.
        // icon:dot-circle[] icon:eye-slash[]
        "active": "ALWAYS",

        // Defines the connection timeout in seconds.
        // Defaults to `20`.
        // icon:dot-circle[]
        "connectTimeout": 20,

        // Defines the read timeout in seconds.
        // Defaults to `60`.
        // icon:dot-circle[]
        "readTimeout": 60,

        // Additional properties used when evaluating templates.
        // icon:dot-circle[] icon:file-alt[]
        "extraProperties": {
          // Key will be capitalized and prefixed with `webhook`, i.e, `webhookFoo`.
          "foo": "bar"
        },

        // The incoming webhook URL.
        // icon:exclamation-triangle[] icon:eye-slash[]
        "webhook": "__USE_ENVIRONMENT_VARIABLE__",

        // The announcement message.
        // Review the available xref:reference:name-templates.adoc[].
        // icon:dot-circle[] icon:file-alt[]
        "message": "{default-message}",

        // The name of the JSON property that contains the message.
        // Defaults to `text`.
        // Ignored if `messageTemplate` is used.
        // icon:dot-circle[]
        "messageProperty": "text",

        // Path to a template file that contains the message.
        // Review the available xref:reference:name-templates.adoc[].
        // Defaults to `src/jreleaser/templates/myWebhook.tpl`.
        // icon:dot-circle[]
        "messageTemplate": "path/to/template/myWebhook.tpl",

        // Whether to send the payload as is or wrap it with the `#{messageProperty}` property.
        // Defaults to `true`.
        // icon:dot-circle[]
        "structuredMessage": false
      }
    }
  }
}
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
<jreleaser>
  <!--
    icon:dot-circle[]
  -->
  <announce>
    <!--
      icon:dot-circle[]
    -->
    <webhooks>

      <!--
        Webhooks require a name.
        icon:exclamation-triangle[]
       -->
      <myWebhook>

        <!--
          Enable or disable this announcer.
          Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
          Defaults to `NEVER`.
          icon:dot-circle[] icon:eye-slash[]
        -->
        <active>ALWAYS</active>

        <!--
          Defines the connection timeout in seconds.
          Defaults to `20`.
          icon:dot-circle[]
        -->
        <connectTimeout>20</connectTimeout>

        <!--
          Defines the read timeout in seconds.
          Defaults to `60`.
          icon:dot-circle[]
        -->
        <readTimeout>60</readTimeout>

        <!--
          Additional properties used when evaluating templates.
          icon:dot-circle[] icon:file-alt[]
        -->
        <extraProperties>
          <!--
            Key will be capitalized and prefixed with `webhook`, i.e, `webhookFoo`.
          -->
          <foo>bar</foo>
        </extraProperties>

        <!--
          The incoming webhook URL.
          icon:exclamation-triangle[] icon:eye-slash[]
        -->
        <webhook>__USE_ENVIRONMENT_VARIABLE__</webhook>

        <!--
          The announcement message.
          Review the available xref:reference:name-templates.adoc[].
          icon:dot-circle[] icon:file-alt[]
        -->
        <message>{default-message}</message>

        <!--
          The name of the JSON property that contains the message.
          Defaults to `text`.
          Ignored if `messageTemplate` is used.
          icon:dot-circle[]
        -->
        <messageProperty>text</messageProperty>

        <!--
          Path to a template file that contains the message.
          Review the available xref:reference:name-templates.adoc[].
          Defaults to `src/jreleaser/templates/myWebhook.tpl`.
          icon:dot-circle[]
        -->
        <messageTemplate>path/to/template/myWebhook.tpl</messageTemplate>

        <!--
          Whether to send the payload as is or wrap it with the `#{messageProperty}` property.
          Defaults to `true`.
          icon:dot-circle[]
        -->
        <structuredMessage>false</structuredMessage>
      </myWebhook>
    </webhooks>
  </announce>
</jreleaser>
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
jreleaser {
  announce {
    // icon:dot-circle[]
    webhooks {

      // Webhooks require a name.
      // icon:exclamation-triangle[]
      myWebhook {

        // Enable or disable this announcer.
        // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
        // Defaults to `NEVER`.
        // icon:dot-circle[] icon:eye-slash[]
        active = 'ALWAYS'

        // Defines the connection timeout in seconds.
        // Defaults to `20`.
        // icon:dot-circle[]
        connectTimeout = 20

        // Defines the read timeout in seconds.
        // Defaults to `60`.
        // icon:dot-circle[]
        readTimeout = 60

        // Additional properties used when evaluating templates.
        // Key will be capitalized and prefixed with `webhook`, i.e, `webhookFoo`.
        // icon:dot-circle[] icon:file-alt[]
        extraProperties.put('foo', 'bar')

        // The incoming webhook URL.
        // icon:exclamation-triangle[] icon:eye-slash[]
        webhook = '__USE_ENVIRONMENT_VARIABLE__'

        // The announcement message.
        // Review the available xref:reference:name-templates.adoc[].
        // icon:dot-circle[] icon:file-alt[]
        message = '{default-message}'

        // The name of the JSON property that contains the message.
        // Defaults to `text`.
        // Ignored if `messageTemplate` is used.
        // icon:dot-circle[]
        messageProperty = 'text'

        // Path to a template file that contains the message.
        // Review the available xref:reference:name-templates.adoc[].
        // Defaults to `src/jreleaser/templates/myWebhook.tpl`.
        // icon:dot-circle[]
        messageTemplate = 'path/to/template/myWebhook.tpl'

        // Whether to send the payload as is or wrap it with the `#{messageProperty}` property.
        // Defaults to `true`.
        // icon:dot-circle[]
        structuredMessage = false
      }
    }
  }
}
----
--
====

You may define either `message` or `messageTemplate`, with the former taking precedence over the latter.

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
2+| *active*
| jreleaser.announce.{announcer_sys_key}.${name}.active +
  jreleaser.announce.{announcer_sys_key}.active
| JRELEASER_ANNOUNCE_{announcer_env_key}_${name}_ACTIVE +
  JRELEASER_ANNOUNCE_{announcer_env_key}_ACTIVE
2+| *webhook*
| jreleaser.announce.webhooks.{announcer_sys_key}.${name}.webhook
| JRELEASER_ANNOUNCE_WEBHOOKS_{announcer_env_key}_${name}_WEBHOOK
|===

include::partial$envvars-footer.adoc[]

== Templates

The default location for templates is:

`src/jreleaser/templates`

== Examples

=== Discord

Posts a message to a link:https://discord.com/[Discord] room. You must create a custom webhook for this announcer to work.

1. Log into the target discord server.
2. Select the channel you want to integrate to, click on its settings icon.
3. Click on the `Integrations` menu item.
4. Click on Webhooks.
5. Create a new webhook.
6. Copy the generated webhook URL.

NOTE: Set a `JRELEASER_DISCORD_WEBHOOK` environment variable with the webhook's url as value.

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
announce:
  webhooks:
    discord:
      active: ALWAYS
      message: '{default-message}'
      messageProperty: content
      structuredMessage: true
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
[announce.webhooks.discord]
  active = "ALWAYS"
  message = "{default-message}"
  messageProperty = "content"
  structuredMessage = true
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
{
  "announce": {
    "webhooks": {
      "discord": {
        "active": "ALWAYS",
        "message": "{default-message}",
        "messageProperty": "content",
        "structuredMessage": true
      }
    }
  }
}
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
<jreleaser>
  <announce>
    <webhooks>
      <discord>
        <active>ALWAYS</active>
        <message>{default-message}</message>
        <messageProperty>content</messageProperty>
        <structuredMessage>true</structuredMessage>
      </discord>
    </webhooks>
  </announce>
</jreleaser>
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
jreleaser {
  announce {
    webhooks {
      discord {
        active = 'ALWAYS'
        message = '{default-message}'
        messageProperty = 'text'
        structuredMessage = true
      }
    }
  }
}
----
--
====

=== Gitter

Posts a message to a link:https://gitter.im/[Gitter] room. You must create a custom webhook for this announcer to work.

1. Log into link:https://gitter.im/[Gitter].
2. Browse to the room you want to integrate to.
3. Click on the `Settings` menu and select `Integrations`.
4. Click on the `CUSTOM` button.
5. Copy the generated webhook URL.

NOTE: Set a `JRELEASER_GITTER_WEBHOOK` environment variable with the webhook's url as value.

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
announce:
  webhooks:
    gitter:
      active: ALWAYS
      message: '{default-message}'
      messageProperty: message
      structuredMessage: true
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
[announce.webhooks.gitter]
  active = "ALWAYS"
  message = "{default-message}"
  messageProperty = "message"
  structuredMessage = true
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
{
  "announce": {
    "webhooks": {
      "gitter": {
        "active": "ALWAYS",
        "message": "{default-message}",
        "messageProperty": "message",
        "structuredMessage": true
      }
    }
  }
}
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
<jreleaser>
  <announce>
    <webhooks>
      <gitter>
        <active>ALWAYS</active>
        <message>{default-message}</message>
        <messageProperty>message</messageProperty>
        <structuredMessage>true</structuredMessage>
      </gitter>
    </webhooks>
  </announce>
</jreleaser>
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
jreleaser {
  announce {
    webhooks {
      gitter {
        active = 'ALWAYS'
        message = '{default-message}'
        messageProperty = 'message'
        structuredMessage = true
      }
    }
  }
}
----
--
====

=== GoogleChat

Posts a message to a link:https://chat.google.com/[GoogleChat] room. You must create a custom webhook for this announcer to work.
Follow the instructions at link:https://developers.google.com/chat/how-tos/webhooks[] to register an
incoming webhook.

NOTE: Set a `JRELEASER_GOOGLECHAT_WEBHOOK` environment variable with the webhook's url as value.

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
announce:
  webhooks:
    googleChat:
      active: ALWAYS
      message: '{default-message}'
      messageProperty: text
      structuredMessage: true
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
[announce.webhooks.googleChat]
  active = "ALWAYS"
  message = "{default-message}"
  messageProperty = "text"
  structuredMessage = true
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
{
  "announce": {
    "webhooks": {
      "googleChat": {
        "active": "ALWAYS",
        "message": "{default-message}",
        "messageProperty": "text",
        "structuredMessage": true
      }
    }
  }
}
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
<jreleaser>
  <announce>
    <webhooks>
      <googleChat>
        <active>ALWAYS</active>
        <message>{default-message}</message>
        <messageProperty>text</messageProperty>
        <structuredMessage>true</structuredMessage>
      </googleChat>
    </webhooks>
  </announce>
</jreleaser>
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
jreleaser {
  announce {
    webhooks {
      googleChat {
        active = 'ALWAYS'
        message = '{default-message}'
        messageProperty = 'text'
        structuredMessage = true
      }
    }
  }
}
----
--
====

=== Mattermost

Posts a message to a link:https://mattermost.com/[Mattermost] room. You must create a custom webhook for this announcer to work.

NOTE: Set a `JRELEASER_MATTERMOST_WEBHOOK` environment variable with the webhook's url as value.

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
announce:
  webhooks:
    mattermost:=
      active: ALWAYS
      message: '{default-message}'
      messageProperty: text
      structuredMessage: true
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
[announce.webhooks.mattermost]
  active = "ALWAYS"
  message = "{default-message}"
  messageProperty = "text"
  structuredMessage = true
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
{
  "announce": {
    "webhooks": {
      "mattermost": {
        "active": "ALWAYS",
        "message": "{default-message}",
        "messageProperty": "text",
        "structuredMessage": true
      }
    }
  }
}
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
<jreleaser>
  <announce>
    <webhooks>
      <mattermost>
        <active>ALWAYS</active>
        <message>{default-message}</message>
        <messageProperty>text</messageProperty>
        <structuredMessage>true</structuredMessage>
      </mattermost>
    </webhooks>
  </announce>
</jreleaser>
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
jreleaser {
  announce {
    webhooks {
      mattermost {
        active = 'ALWAYS'
        message = '{default-message}'
        messageProperty = 'text'
        structuredMessage = true
      }
    }
  }
}
----
--
====

=== Teams

Posts a message to a link:https://www.microsoft.com/en-ww/microsoft-teams[Teams] room. You must create a custom webhook for this announcer to work.

1. Log into Teams.
2. Click on the `Apps` icon.
3. Click on the `Connectors` menu item.
4. Click on `Incoming Webhook` and add it to a team.
5. Configure the webhook.
6. Copy the generated webhook URL.

NOTE: Set a `JRELEASER_TEAMS_WEBHOOK` environment variable with the webhook's url as value.

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
announce:
  webhooks:
    teams:
      active: ALWAYS
      messageTemplate: path/to/template/teams.tpl
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
[announce.webhooks.teams]
  active = "ALWAYS"
  messageTemplate = "path/to/template/teams.tpl"
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
{
  "announce": {
    "webhooks": {
      "teams": {
        "active": "ALWAYS",
        "messageTemplate": "path/to/template/teams.tpl"
      }
    }
  }
}
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
<jreleaser>
  <announce>
    <webhooks>
      <teams>
        <active>ALWAYS</active>
        <messageTemplate>path/to/template/teams.tpl</messageTemplate>
      </teams>
    </webhooks>
  </announce>
</jreleaser>
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
jreleaser {
  announce {
    webhooks {
      teams {
        active = 'ALWAYS'
        messageTemplate = 'path/to/template/teams.tpl'
      }
    }
  }
}
----
--
====
