= Zernio
:announcer_id:      zernio
:announcer_name:    Zernio
:announcer_sys_key: zernio
:announcer_env_key: ZERNIO

Posts a message to link:https://zernio.com/[Zernio].

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$announce/yaml/common-head.adoc[]

    # The Zernio server endpoint.
    # icon:exclamation-triangle[] icon:eye-slash[]
    apiHost: pass:[https://zernio.com/api/v1]

    # The token associated with the given account.
    # icon:exclamation-triangle[] icon:eye-slash[]
    token: __USE_ENVIRONMENT_VARIABLE__

    # The user profile to use.
    # icon:dot-circle[]
    profile: 64c573b6ca2a1fb347e1e9c3

    # The announcement message.
    # Review the available xref:reference:name-templates.adoc[].
    # icon:dot-circle[] icon:file-alt[]
    message: 'đźš€ {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

    # Path to a template file that contains the message.
    # Review the available xref:reference:name-templates.adoc[].
    # Defaults to `src/jreleaser/templates/zernio.tpl`.
    # icon:dot-circle[]
    messageTemplate: path/to/template/zernio.tpl
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$announce/toml/common-head.adoc[]

  # The Zernio server endpoint.
  # icon:exclamation-triangle[] icon:eye-slash[]
  apiHost = "pass:[https://zernio.com/api/v1]"

  # The token associated with the given account.
  # icon:exclamation-triangle[] icon:eye-slash[]
  token = "__USE_ENVIRONMENT_VARIABLE__"

  # The user profile to use.
  # icon:dot-circle[]
  profile = "64c573b6ca2a1fb347e1e9c3"

  # The announcement message.
  # Review the available xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  message = "đźš€ {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}"

  # Path to a template file that contains the message.
  # Review the available xref:reference:name-templates.adoc[].
  # Defaults to `src/jreleaser/templates/zernio.tpl`.
  # icon:dot-circle[]
  messageTemplate = "path/to/template/zernio.tpl"
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$announce/json/common-head.adoc[]

      // The Zernio server endpoint.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "apiHost": "pass:[https://zernio.com/api/v1]",

      // The token associated with the given account.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "token": "__USE_ENVIRONMENT_VARIABLE__",

      // The user profile to use.
      // icon:dot-circle[]
      "profile": "64c573b6ca2a1fb347e1e9c3",

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      "message": "đźš€ {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}",

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/zernio.tpl`.
      // icon:dot-circle[]
      "messageTemplate": "path/to/template/zernio.tpl"
include::partial$announce/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$announce/maven/common-head.adoc[]

      <!--
        The Zernio server endpoint.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <apiHost>pass:[https://zernio.com/api/v1]</apiHost>

      <!--
        The token associated with the given account.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <token>__USE_ENVIRONMENT_VARIABLE__</token>

      <!--
        The user profile to use.
        icon:dot-circle[]
      -->
      <profile>64c573b6ca2a1fb347e1e9c3</profile>

      <!--
        The announcement message.
        Review the available xref:reference:name-templates.adoc[].
        icon:dot-circle[] icon:file-alt[]
      -->
      <message>đźš€ {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}</message>

      <!--
        Path to a template file that contains the message.
        Review the available xref:reference:name-templates.adoc[].
        Defaults to `src/jreleaser/templates/zernio.tpl`.
        icon:dot-circle[]
      -->
      <messageTemplate>path/to/template/zernio.tpl</messageTemplate>
include::partial$announce/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$announce/gradle/common-head.adoc[]

      // The Zernio server endpoint.
      // icon:exclamation-triangle[] icon:eye-slash[]
      apiHost = 'pass:[https://zernio.com/api/v1]'

      // The token associated with the given account.
      // icon:exclamation-triangle[] icon:eye-slash[]
      token = '__USE_ENVIRONMENT_VARIABLE__'

      // The user profile to use.
      // icon:dot-circle[]
      profile = '64c573b6ca2a1fb347e1e9c3'

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      message = 'đźš€ {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/zernio.tpl`.
      // icon:dot-circle[]
      messageTemplate = 'path/to/template/zernio.tpl'
include::partial$announce/gradle/common-footer.adoc[]
----
--
====

You may define either `message` or `messageTemplate`, with the former taking precedence over the latter.

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property                               | Environment Variable
2+| *active*
| jreleaser.announce.{announcer_sys_key}.active | JRELEASER_ANNOUNCE_{announcer_env_key}_ACTIVE
2+| *token*
| jreleaser.announce.{announcer_sys_key}.token +
  jreleaser.{announcer_sys_key}.token
| JRELEASER_ANNOUNCE_{announcer_env_key}_TOKEN +
  JRELEASER_{announcer_env_key}_TOKEN
2+| *apiHost*
| jreleaser.announce.{announcer_sys_key}.api.host +
  jreleaser.{announcer_sys_key}.api.host
| JRELEASER_ANNOUNCE_{announcer_env_key}_API_HOST +
  JRELEASER_{announcer_env_key}_API_HOST
|===

== Templates

The default location for templates is:

`src/jreleaser/templates`

The following list shows the filenames that may be used to override default templates:

* `zernio.tpl`

Templates may be initialized using the `template` command

 * xref:tools:jreleaser-cli.adoc#_template_generate[{icon_cli_s} template generate]
 * xref:tools:jreleaser-maven.adoc#_jreleasertemplate_generate[{icon_maven_s} jreleaser:template-generate]
 * xref:tools:jreleaser-gradle.adoc#_jreleasertemplategenerate[{icon_gradle_s} jreleaserTemplateGenerate]
 * xref:tools:jreleaser-ant.adoc#_jreleaser_template_generate[{icon_ant_s} jreleaser-template-generate]
