= Zulip
:announcer_id:      zulip
:announcer_name:    Zulip
:announcer_sys_key: zulip
:announcer_env_key: ZULIP

Posts a message to a link:https://zulip.com/[Zulip] server. You must procure an account and apiKey to use
this announcer.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$announce/yaml/common-head.adoc[]

    # The Zulip account (typically an email address) to use.
    # icon:exclamation-triangle[] icon:eye-slash[]
    account: pass:[announce-bot@my.zulipchat.com]

    # The Zulip server endpoint.
    # icon:exclamation-triangle[] icon:eye-slash[]
    apiHost: pass:[https://my.zulipchat.com/api/v1]

    # The ApiKey associated with the given account.
    # icon:exclamation-triangle[] icon:eye-slash[]
    apiKey: __USE_ENVIRONMENT_VARIABLE__

    # The channel where the message will be sent to
    # Defaults to `announce`.
    # icon:dot-circle[]
    channel: announce

    # The message's subject.
    # Review the available xref:reference:name-templates.adoc[].
    # icon:dot-circle[] icon:file-alt[]
    subject: '{{projectNameCapitalized}} {{projectVersion}} released!'

    # The announcement message.
    # Review the available xref:reference:name-templates.adoc[].
    # icon:dot-circle[] icon:file-alt[]
    message: '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

    # Path to a template file that contains the message.
    # Review the available xref:reference:name-templates.adoc[].
    # Defaults to `src/jreleaser/templates/zulip.tpl`.
    # icon:dot-circle[]
    messageTemplate: path/to/template/zulip.tpl
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$announce/toml/common-head.adoc[]

  # The Zulip account (typically an email address) to use.
  # icon:exclamation-triangle[] icon:eye-slash[]
  account = "pass:[announce-bot@my.zulipchat.com]"

  # The Zulip server endpoint.
  # icon:exclamation-triangle[] icon:eye-slash[]
  apiHost = "pass:[https://my.zulipchat.com/api/v1]"

  # The ApiKey associated with the given account.
  # icon:exclamation-triangle[] icon:eye-slash[]
  apiKey = "__USE_ENVIRONMENT_VARIABLE__"

  # The channel where the message will be sent to
  # Defaults to `announce`.
  # icon:dot-circle[]
  channel = "announce"

  # The message's subject.
  # Review the available xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  subject = "{{projectNameCapitalized}} {{projectVersion}} released!"

  # The announcement message.
  # Review the available xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  message = "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}"

  # Path to a template file that contains the message.
  # Review the available xref:reference:name-templates.adoc[].
  # Defaults to `src/jreleaser/templates/zulip.tpl`.
  # icon:dot-circle[]
  messageTemplate = "path/to/template/zulip.tpl"
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$announce/json/common-head.adoc[]

      // The Zulip account (typically an email address) to use.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "account": "pass:[announce-bot@my.zulipchat.com]",

      // The Zulip server endpoint.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "apiHost": "pass:[https://my.zulipchat.com/api/v1]",

      // The ApiKey associated with the given account.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "apiKey": "__USE_ENVIRONMENT_VARIABLE__",

      // The channel where the message will be sent to
      // Defaults to `announce`.
      // icon:dot-circle[]
      "channel": "announce",

      // The message's subject.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[]
      "subject": "{{projectNameCapitalized}} {{projectVersion}} released!",

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      "message": "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}",

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/zulip.tpl`.
      // icon:dot-circle[]
      "messageTemplate": "path/to/template/zulip.tpl"
include::partial$announce/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$announce/maven/common-head.adoc[]

      <!--
        The Zulip account (typically an email address) to use.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <account>pass:[announce-bot@my.zulipchat.com]</account>

      <!--
        The Zulip server endpoint.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <apiHost>pass:[https://my.zulipchat.com/api/v1]</apiHost>

      <!--
        The ApiKey associated with the given account.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <apiKey>__USE_ENVIRONMENT_VARIABLE__</apiKey>

      <!--
        The channel where the message will be sent to
        Defaults to `announce`.
        icon:dot-circle[]
      -->
      <channel>announce</channel>

      <!--
        The message's subject.
        Review the available xref:reference:name-templates.adoc[].
        icon:dot-circle[]
      -->
      <subject>{{projectNameCapitalized}} {{projectVersion}} released!</subject>

      <!--
        The announcement message.
        Review the available xref:reference:name-templates.adoc[].
        icon:dot-circle[] icon:file-alt[]
      -->
      <message>🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}</message>

      <!--
        Path to a template file that contains the message.
        Review the available xref:reference:name-templates.adoc[].
        Defaults to `src/jreleaser/templates/zulip.tpl`.
        icon:dot-circle[]
      -->
      <messageTemplate>path/to/template/zulip.tpl</messageTemplate>
include::partial$announce/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$announce/gradle/common-head.adoc[]

      // The Zulip account (typically an email address) to use.
      // icon:exclamation-triangle[] icon:eye-slash[]
      account = 'pass:[announce-bot@my.zulipchat.com]'

      // The Zulip server endpoint.
      // icon:exclamation-triangle[] icon:eye-slash[]
      apiHost = 'pass:[https://my.zulipchat.com/api/v1]'

      // The ApiKey associated with the given account.
      // icon:exclamation-triangle[] icon:eye-slash[]
      apiKey = '__USE_ENVIRONMENT_VARIABLE__'

      // The channel where the message will be sent to
      // Defaults to `announce`.
      // icon:dot-circle[]
      channel = 'announce'

      // The message's subject.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[]
      subject = '{{projectNameCapitalized}} {{projectVersion}} released!'

      // The announcement message.
      // Review the available xref:reference:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      message = '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

      // Path to a template file that contains the message.
      // Review the available xref:reference:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/zulip.tpl`.
      // icon:dot-circle[]
      messageTemplate = 'path/to/template/zulip.tpl'
include::partial$announce/gradle/common-footer.adoc[]
----
--
====

You may define either `message` or `messageTemplate`, with the former taking precedence over the latter.

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property                               | Environment Variable
2+| *active*
| jreleaser.announce.{announcer_sys_key}.active | JRELEASER_ANNOUNCE_{announcer_env_key}_ACTIVE
2+| *account*
| jreleaser.announce.{announcer_sys_key}.account +
  jreleaser.{announcer_sys_key}.account
| JRELEASER_ANNOUNCE_{announcer_env_key}_ACCOUNT +
  JRELEASER_{announcer_env_key}_ACCOUNT
2+| *apiKey*
| jreleaser.announce.{announcer_sys_key}.api.key +
  jreleaser.{announcer_sys_key}.api.key
| JRELEASER_ANNOUNCE_{announcer_env_key}_API_KEY +
  JRELEASER_{announcer_env_key}_API_KEY
2+| *apiHost*
| jreleaser.announce.{announcer_sys_key}.api.host +
  jreleaser.{announcer_sys_key}.api.host
| JRELEASER_ANNOUNCE_{announcer_env_key}_API_HOST +
  JRELEASER_{announcer_env_key}_API_HOST
|===

== Templates

The default location for templates is:

`src/jreleaser/templates`

The following list shows the filenames that may be used to override default templates:

* `zulip.tpl`

Templates may be initialized using the `template` command

 * xref:tools:jreleaser-cli.adoc#_template_generate[{icon_cli_s} template generate]
 * xref:tools:jreleaser-maven.adoc#_jreleasertemplate_generate[{icon_maven_s} jreleaser:template-generate]
 * xref:tools:jreleaser-gradle.adoc#_jreleasertemplategenerate[{icon_gradle_s} jreleaserTemplategGenerate]
 * xref:tools:jreleaser-ant.adoc#_jreleaser_template_generate[{icon_ant_s} jreleaser-template-generate]
