= Artifactory

Uploads artifacts, files, and signatures to an Artifactory instance.

.Prerequisites:

 * A running Artifactory instance.
 * A generic repository.
 * A user + password / token with grants to upload an artifact.

IMPORTANT: This feature *does not* support deploying JARs and POMs to a Maven repository.

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
[source,yaml]
[subs="+macros"]
----
# icon:dot-circle[]
upload:
  # icon:dot-circle[]
  artifactories:
    # Uploaders require a name.
    # icon:exclamation-triangle[]
    app:

      # Enables or disables the uploader.
      # Valid values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
      # Defaults to `NEVER`.
      # icon:dot-circle[]
      active: ALWAYS

      # Defines the connection timeout in seconds.
      # Defaults to `20`.
      # icon:dot-circle[]
      connectTimeout: 20

      # Defines the read timeout in seconds.
      # Defaults to `60`.
      # icon:dot-circle[]
      readTimeout: 60

      # URL of the Artifacttory instance + path.
      # The artifact file name will be appended automatically.
      # icon:exclamation-triangle[] icon:file-alt[]
      target: pass:[https://duke.jfrog.io/artifactory/binaries/{{projectName}}/{{projectVersion}}]

      # The username that can write to the repository.
      # If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_USERNAME`
      # environment variable must be defined.
      # icon:exclamation-triangle[] icon:eye-slash[]
      username: __DO_NOT_SET_HERE__

      # Password for login into the repository.
      # If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_PASSWORD`
      # environment variable must be defined.
      # icon:exclamation-triangle[] icon:eye-slash[]
      password: __DO_NOT_SET_HERE__

      # Token for login into the repository.
      # If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_TOKEN`
      # environment variable must be defined.
      # icon:exclamation-triangle[] icon:eye-slash[]
      token: __DO_NOT_SET_HERE__

      # Upload files.
      # Defaults to `true`.
      # icon:dot-circle[]
      files: true

      # Upload distribution artifacts.
      # Defaults to `true`.
      # icon:dot-circle[]
      artifacts: true

      # Upload signatures.
      # Defaults to `true`.
      # icon:dot-circle[]
      signatures: true

      # Additional properties used when evaluating templates.
      # icon:dot-circle[]
      extraProperties:
        # Key will be capitalized and prefixed with `artifactory`, i.e, `artifactoryFoo`.
        foo: bar
----
TOML::
+
[source,toml]
[subs="+macros"]
----
# Uploaders require a name.
# icon:exclamation-triangle[]
[upload.artifactories.app]

  # Enables or disables the uploader.
  # Valid values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
  # Defaults to `NEVER`.
  # icon:dot-circle[]
  active = "ALWAYS"

  # Defines the connection timeout in seconds.
  # Defaults to `20`.
  # icon:dot-circle[]
  connectTimeout = 20

  # Defines the read timeout in seconds.
  # Defaults to `60`.
  # icon:dot-circle[]
  readTimeout = 60

  # URL of the Artifacttory instance + path.
  # The artifact file name will be appended automatically.
  # icon:exclamation-triangle[] icon:file-alt[]
  target = "pass:[https://duke.jfrog.io/artifactory/binaries/{{projectName}}/{{projectVersion}}]"

  # The username that can write to the repository.
  # If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_USERNAME`
  # environment variable must be defined.
  # icon:exclamation-triangle[] icon:eye-slash[]
  username = "__DO_NOT_SET_HERE__"

  # Password for login into the repository..
  # If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_PASSWORD`
  # environment variable must be defined.
  # icon:exclamation-triangle[] icon:eye-slash[]
  password = "__DO_NOT_SET_HERE__"

  # Token for login into the repository.
  # If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_TOKEN`
  # environment variable must be defined.
  # icon:exclamation-triangle[] icon:eye-slash[]
  token = "__DO_NOT_SET_HERE__"

  # Upload files.
  # Defaults to `true`.
  # icon:dot-circle[]
  files = true

  # Upload distribution artifacts.
  # Defaults to `true`.
  # icon:dot-circle[]
  artifacts = true

  # Upload signatures.
  # Defaults to `true`.
  # icon:dot-circle[]
  signatures = true

  # Additional properties used when evaluating templates.
  # icon:dot-circle[]
  extraProperties.foo = "bar"
  # Key will be capitalized and prefixed with `artifactory`, i.e, `artifactoryFoo`.
----
JSON::
+
[source,json]
[subs="+macros"]
----
{
  // icon:dot-circle[]
  "upload": {
    // icon:dot-circle[]
    "artifactories": {
      // Uploaders require a name.
      // icon:exclamation-triangle[]
      "app": {

        // Enables or disables the uploader.
        // Valid values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
        // Defaults to `NEVER`.
        // icon:dot-circle[]
        "active": "ALWAYS",

        // Defines the connection timeout in seconds.
        // Defaults to `20`.
        // icon:dot-circle[]
        "connectTimeout": 20,

        // Defines the read timeout in seconds.
        // Defaults to `60`.
        // icon:dot-circle[]
        "readTimeout": 60,

        // URL of the Artifacttory instance + path.
        // The artifact file name will be appended automatically.
        // icon:exclamation-triangle[] icon:file-alt[]
        "target": "pass:[https://duke.jfrog.io/artifactory/binaries/{{projectName}}/{{projectVersion}}]",

        // The username that can write to the repository.
        // If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_USERNAME`
        // environment variable must be defined.
        // icon:exclamation-triangle[] icon:eye-slash[]
        "username": "__DO_NOT_SET_HERE__",

        // Password for login into the repository.
        // If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_PASSWORD`
        // environment variable must be defined.
        // icon:exclamation-triangle[] icon:eye-slash[]
        "password": "__DO_NOT_SET_HERE__",

        // Token for login into the repository.
        // If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_TOKEN`
        // environment variable must be defined.
        // icon:exclamation-triangle[] icon:eye-slash[]
        "token": "__DO_NOT_SET_HERE__",

        // Upload files.
        // Defaults to `true`.
        // icon:dot-circle[]
        "files": true,

        // Upload distribution artifacts.
        // Defaults to `true`.
        // icon:dot-circle[]
        "artifacts": true,

        // Upload signatures.
        // Defaults to `true`.
        // icon:dot-circle[]
        "signatures": true,

        // Additional properties used when evaluating templates.
        // icon:dot-circle[]
        "extraProperties": {
          // Key will be capitalized and prefixed with `artifactory`, i.e, `artifactoryFoo`.
          "foo": "bar"
        }
      }
    }
  }
}
----
Maven::
+
[source,xml]
[subs="+macros,verbatim"]
----
<jreleaser>
  <upload>
    <!--
      icon:dot-circle[]
    -->
    <artifactories>
      <!--
        Uploaders require a name.
        icon:exclamation-triangle[]
      -->
      <app>
        <!--
          Enables or disables the distribution.
          Valid values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
          Defaults to `ALWAYS`.
          icon:dot-circle[]
        -->
        <active>ALWAYS</active>

        <!--
          Defines the connection timeout in seconds.
          Defaults to `20`.
          icon:dot-circle[]
        -->
        <connectTimeout>20</connectTimeout>

        <!--
          Defines the read timeout in seconds.
          Defaults to `60`.
          icon:dot-circle[]
        -->
        <readTimeout>60</readTimeout>

        <!--
          URL of the Artifacttory instance + path.
          The artifact file name will be appended automatically.
          icon:exclamation-triangle[] icon:file-alt[]
        -->
        <target>pass:[https:my.zulipchat.com/api/v1]</target>

        <!--
          The username that can write to the repository.
          If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_USERNAME`
          environment variable must be defined.
          icon:exclamation-triangle[] icon:eye-slash[]
        -->
        <username>__DO_NOT_SET_HERE__</username>

        <!--
          Password for login into the repository.
          If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_PASSWORD`
          environment variable must be defined.
          icon:exclamation-triangle[] icon:eye-slash[]
        -->
        <password>__DO_NOT_SET_HERE__</password>

        <!--
          Token for login into the repository.
          If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_TOKEN`
          environment variable must be defined.
          icon:exclamation-triangle[] icon:eye-slash[]
        -->
        <token>__DO_NOT_SET_HERE__</token>

        <!--
          Upload files.
          Defaults to `true`.
          icon:dot-circle[]
        -->
        <files>true</files>

        <!--
          Upload distribution artifacts.
          Defaults to `true`.
          icon:dot-circle[]
        -->
        <artifacts>true</artifacts>

        <!--
          Upload signatures.
          Defaults to `true`.
          icon:dot-circle[]
        -->
        <signatures>true</signatures>

        <!--
          Additional properties used when evaluating templates.
          icon:dot-circle[]
        -->
        <extraProperties>
          <!--
            Key will be capitalized and prefixed with `artifactory`, i.e, `artifactoryFoo`.
          -->
          <foo>bar</foo>
        </extraProperties>
      </app>
    </artifactories>
  </upload>
</jreleaser>
----
Gradle::
+
[source,groovy]
[subs="+macros"]
----
jreleaser {
  // icon:dot-circle[]
  upload {
    // icon:dot-circle[]
    artifactories {
      // Uploaders require a name.
      // icon:exclamation-triangle[]
      app {

        // Enables or disables the uploader.
        // Valid values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
        // Defaults to `NEVER`.
        // icon:dot-circle[]
        active = 'ALWAYS'

        // Defines the connection timeout in seconds.
        // Defaults to `20`.
        // icon:dot-circle[]
        connectTimeout = 20

        // Defines the read timeout in seconds.
        // Defaults to `60`.
        // icon:dot-circle[]
        readTimeout = 60

        // URL of the Artifacttory instance + path.
        // The artifact file name will be appended automatically.
        // icon:exclamation-triangle[] icon:file-alt[]
        target = 'pass:[https://duke.jfrog.io/artifactory/binaries/{{projectName}}/{{projectVersion}}]'

        // The username that can write to the repository.
        // If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_USERNAME`
        // environment variable must be defined.
        // icon:exclamation-triangle[] icon:eye-slash[]
        username = '__DO_NOT_SET_HERE__'

        // Password for login into the repository.
        // If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_PASSWORD`
        // environment variable must be defined.
        // icon:exclamation-triangle[] icon:eye-slash[]
        password = '__DO_NOT_SET_HERE__'

        // Token for login into the repository.
        // If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_TOKEN`
        // environment variable must be defined.
        // icon:exclamation-triangle[] icon:eye-slash[]
        token = '__DO_NOT_SET_HERE__'

        // Upload files.
        // Defaults to `true`.
        // icon:dot-circle[]
        files = true

        // Upload distribution artifacts.
        // Defaults to `true`.
        // icon:dot-circle[]
        artifacts = true

        // Upload signatures.
        // Defaults to `true`.
        // icon:dot-circle[]
        signatures = true

        // Additional properties used when evaluating templates.
        // Key will be capitalized and prefixed with `artifactory`, i.e, `artifactoryFoo`.
        // icon:dot-circle[]
        extraProperties.put('foo', 'bar')
      }
    }
  }
}
----
====

TIP: Either set `username`/`password` or `token`.

== Target

The target is the URL to upload the artifacts to (without the name of the artifact).

An example configuration can look like

[source]
----
target: 'http://artifacts.company.com:8081/artifactory/example-repo-local/{{projectName}}/{{projectVersion}}'
----

And will result in a final deployment like
`pass:[http://artifacts.company.com:8081/artifactory/example-repo-local/app/1.0.0/app-1.0.0.zip]`.

== Username

The configured username needs to be authenticated against the Artifactory instance.

You can have the username set in the configuration as shown above or you can have it read from an environment variable.
The configured name of the Artifactory instance will be used to build the environment variable name.
This means that the name per configured instance needs to be unique.

The name of the environment variable will be `JRELEASER_ARTIFACTORY_NAME_USERNAME`. If your instance is named `production`,
you can store the username in the environment variable `JRELEASER_ARTIFACTORY_PRODUCTION_USERNAME`. The name will be
transformed to uppercase.

If a configured username is found in the configuration file, then the environment variable is not used at all.

== Password

The password will be stored in a environment variable. The configured name of the Artifactory instance will
be used. This means that the name per configured instance needs to be unique.

The name of the environment variable will be `JRELEASER_ARTIFACTORY_NAME_PASSWORD`. If your instance is named `production`,
you need to store the secret in the environment variable `JRELEASER_ARTIFACTORY_PRODUCTION_PASSWORD`. The name will be
transformed to uppercase.

== Token

The token will be stored in a environment variable. The configured name of the Artifactory instance will
be used. This means that the name per configured instance needs to be unique.

The name of the environment variable will be `JRELEASER_ARTIFACTORY_NAME_TOKEN`. If your instance is named `production`,
you need to store the secret in the environment variable `JRELEASER_ARTIFACTORY_PRODUCTION_TOKEN`. The name will be
transformed to uppercase.

