= Artifactory

Uploads artifacts, files, and signatures to an Artifactory instance.

.Prerequisites:

 * A running Artifactory instance.
 * A generic repository.
 * A user + password / token with grants to upload an artifact.

IMPORTANT: This feature *does not* support deploying JARs and POMs to a Maven repository.

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros"]
----
# icon:dot-circle[]
upload:
  # icon:dot-circle[]
  artifactory:
    # Uploaders require a name.
    # icon:exclamation-triangle[]
    app:

      # Enables or disables the uploader.
      # Valid values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
      # Defaults to `NEVER`.
      # icon:dot-circle[]
      active: ALWAYS

      # Defines the connection timeout in seconds.
      # Defaults to `20`.
      # icon:dot-circle[]
      connectTimeout: 20

      # Defines the read timeout in seconds.
      # Defaults to `60`.
      # icon:dot-circle[]
      readTimeout: 60

      # URL of the Artifactory instance + path + artifact.
      # icon:exclamation-triangle[] icon:file-alt[]
      uploadUrl: pass:[https://duke.jfrog.io/artifactory/binaries/{{projectName}}/{{projectVersion}}/{{artifactFileName}}]

      # URL of the Artifactory instance + path + artifact.
      # If undefined, will use the same value as `uploadUrl`.
      # icon:exclamation-triangle[] icon:file-alt[]
      downloadUrl: pass:[https://duke.jfrog.io/artifactory/binaries/{{projectName}}/{{projectVersion}}/{{artifactFileName}}]

      # The username that can write to the repository.
      # If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_USERNAME`
      # environment variable must be defined.
      # icon:exclamation-triangle[] icon:eye-slash[]
      username: __DO_NOT_SET_HERE__

      # Password for login into the repository.
      # If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_PASSWORD`
      # environment variable must be defined.
      # icon:exclamation-triangle[] icon:eye-slash[]
      password: __DO_NOT_SET_HERE__

      # The authorization method to use.
      # Valid values are [`BASIC`, `BEARER`].
      # `Basic` requires both username & password.
      # `BEARER` requires a token (set as password).
      # Defaults to `BEARER`.
      # icon:dot-circle[]
      authorization: BASIC

      # Upload files.
      # Defaults to `true`.
      # icon:dot-circle[]
      files: true

      # Upload distribution artifacts.
      # Defaults to `true`.
      # icon:dot-circle[]
      artifacts: true

      # Upload signatures.
      # Defaults to `true`.
      # icon:dot-circle[]
      signatures: true

      # Additional properties used when evaluating templates.
      # icon:dot-circle[]
      extraProperties:
        # Key will be capitalized and prefixed with `artifactory`, i.e, `artifactoryFoo`.
        foo: bar
----
--
TOML::
+
--
[source,toml]
[subs="+macros"]
----
# Uploaders require a name.
# icon:exclamation-triangle[]
[upload.artifactory.app]

  # Enables or disables the uploader.
  # Valid values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
  # Defaults to `NEVER`.
  # icon:dot-circle[]
  active = "ALWAYS"

  # Defines the connection timeout in seconds.
  # Defaults to `20`.
  # icon:dot-circle[]
  connectTimeout = 20

  # Defines the read timeout in seconds.
  # Defaults to `60`.
  # icon:dot-circle[]
  readTimeout = 60

  # URL of the Artifactory instance + path + artifact.
  # icon:exclamation-triangle[] icon:file-alt[]
  uploadUrl = "pass:[https://duke.jfrog.io/artifactory/binaries/{{projectName}}/{{projectVersion}}/{{artifactFileName}}]"

  # URL of the Artifactory instance + path + artifact.
  # If undefined, will use the same value as `uploadUrl`.
  # icon:exclamation-triangle[] icon:file-alt[]
  downloadUrl = "pass:[https://duke.jfrog.io/artifactory/binaries/{{projectName}}/{{projectVersion}}/{{artifactFileName}}]"

  # The username that can write to the repository.
  # If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_USERNAME`
  # environment variable must be defined.
  # icon:exclamation-triangle[] icon:eye-slash[]
  username = "__DO_NOT_SET_HERE__"

  # Password for login into the repository..
  # If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_PASSWORD`
  # environment variable must be defined.
  # icon:exclamation-triangle[] icon:eye-slash[]
  password = "__DO_NOT_SET_HERE__"

  # The authorization method to use.
  # Valid values are [`BASIC`, `BEARER`].
  # `Basic` requires both username & password.
  # `BEARER` requires a token (set as password).
  # Defaults to `BEARER`.
  # icon:dot-circle[]
  authorization = "BASIC"

  # Upload files.
  # Defaults to `true`.
  # icon:dot-circle[]
  files = true

  # Upload distribution artifacts.
  # Defaults to `true`.
  # icon:dot-circle[]
  artifacts = true

  # Upload signatures.
  # Defaults to `true`.
  # icon:dot-circle[]
  signatures = true

  # Additional properties used when evaluating templates.
  # icon:dot-circle[]
  extraProperties.foo = "bar"
  # Key will be capitalized and prefixed with `artifactory`, i.e, `artifactoryFoo`.
----
--
JSON::
+
--
[source,json]
[subs="+macros"]
----
{
  // icon:dot-circle[]
  "upload": {
    // icon:dot-circle[]
    "artifactory": {
      // Uploaders require a name.
      // icon:exclamation-triangle[]
      "app": {

        // Enables or disables the uploader.
        // Valid values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
        // Defaults to `NEVER`.
        // icon:dot-circle[]
        "active": "ALWAYS",

        // Defines the connection timeout in seconds.
        // Defaults to `20`.
        // icon:dot-circle[]
        "connectTimeout": 20,

        // Defines the read timeout in seconds.
        // Defaults to `60`.
        // icon:dot-circle[]
        "readTimeout": 60,

        // URL of the Artifactory instance + path + artifact.
        // icon:exclamation-triangle[] icon:file-alt[]
        "uploadUrl": "pass:[https://duke.jfrog.io/artifactory/binaries/{{projectName}}/{{projectVersion}}/{{artifactFileName}}]",

        // URL of the Artifactory instance + path + artifact.
        // If undefined, will use the same value as `uploadUrl`.
        // icon:exclamation-triangle[] icon:file-alt[]
        "downloadUrl": "pass:[https://duke.jfrog.io/artifactory/binaries/{{projectName}}/{{projectVersion}}/{{artifactFileName}}]",

        // The username that can write to the repository.
        // If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_USERNAME`
        // environment variable must be defined.
        // icon:exclamation-triangle[] icon:eye-slash[]
        "username": "__DO_NOT_SET_HERE__",

        // Password for login into the repository.
        // If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_PASSWORD`
        // environment variable must be defined.
        // icon:exclamation-triangle[] icon:eye-slash[]
        "password": "__DO_NOT_SET_HERE__",

        // The authorization method to use.
        // Valid values are [`BASIC`, `BEARER`].
        // `Basic` requires both username & password.
        // `BEARER` requires a token (set as password).
        // Defaults to `BEARER`.
        // icon:dot-circle[]
        "authorization": "BEARER",

        // Upload files.
        // Defaults to `true`.
        // icon:dot-circle[]
        "files": true,

        // Upload distribution artifacts.
        // Defaults to `true`.
        // icon:dot-circle[]
        "artifacts": true,

        // Upload signatures.
        // Defaults to `true`.
        // icon:dot-circle[]
        "signatures": true,

        // Additional properties used when evaluating templates.
        // icon:dot-circle[]
        "extraProperties": {
          // Key will be capitalized and prefixed with `artifactory`, i.e, `artifactoryFoo`.
          "foo": "bar"
        }
      }
    }
  }
}
----
--
Maven::
+
--
[source,xml]
[subs="verbatim,+macros"]
----
<jreleaser>
  <!--
    icon:dot-circle[]
  -->
  <upload>
    <!--
      icon:dot-circle[]
    -->
    <artifactory>
      <!--
        Uploaders require a name.
        icon:exclamation-triangle[]
      -->
      <app>
        <!--
          Enables or disables the distribution.
          Valid values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
          Defaults to `ALWAYS`.
          icon:dot-circle[]
        -->
        <active>ALWAYS</active>

        <!--
          Defines the connection timeout in seconds.
          Defaults to `20`.
          icon:dot-circle[]
        -->
        <connectTimeout>20</connectTimeout>

        <!--
          Defines the read timeout in seconds.
          Defaults to `60`.
          icon:dot-circle[]
        -->
        <readTimeout>60</readTimeout>

        <!--
          URL of the Artifactory instance + path + artifact.
          icon:exclamation-triangle[] icon:file-alt[]
        -->
        <uploadUrl>pass:[https://duke.jfrog.io/artifactory/binaries/{{projectName}}/{{projectVersion}}/{{artifactFileName}}]</uploadUrl>

        <!--
          URL of the Artifactory instance + path + artifact.
          If undefined, will use the same value as `uploadUrl`.
          icon:exclamation-triangle[] icon:file-alt[]
        -->
        <downloadUrl>pass:[https://duke.jfrog.io/artifactory/binaries/{{projectName}}/{{projectVersion}}/{{artifactFileName}}]</downloadUrl>

        <!--
          The username that can write to the repository.
          If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_USERNAME`
          environment variable must be defined.
          icon:exclamation-triangle[] icon:eye-slash[]
        -->
        <username>__DO_NOT_SET_HERE__</username>

        <!--
          Password for login into the repository.
          If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_PASSWORD`
          environment variable must be defined.
          icon:exclamation-triangle[] icon:eye-slash[]
        -->
        <password>__DO_NOT_SET_HERE__</password>

        <!--
          The authorization method to use.
          Valid values are [`BASIC`, `BEARER`].
          `Basic` requires both username & password.
          `BEARER` requires a token (set as password).
          Defaults to `BEARER`.
          icon:dot-circle[]
        -->
        <authorization>BEARER</authorization>

        <!--
          Upload files.
          Defaults to `true`.
          icon:dot-circle[]
        -->
        <files>true</files>

        <!--
          Upload distribution artifacts.
          Defaults to `true`.
          icon:dot-circle[]
        -->
        <artifacts>true</artifacts>

        <!--
          Upload signatures.
          Defaults to `true`.
          icon:dot-circle[]
        -->
        <signatures>true</signatures>

        <!--
          Additional properties used when evaluating templates.
          icon:dot-circle[]
        -->
        <extraProperties>
          <!--
            Key will be capitalized and prefixed with `artifactory`, i.e, `artifactoryFoo`.
          -->
          <foo>bar</foo>
        </extraProperties>
      </app>
    </artifactory>
  </upload>
</jreleaser>
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros"]
----
jreleaser {
  // icon:dot-circle[]
  upload {
    // icon:dot-circle[]
    artifactory {
      // Uploaders require a name.
      // icon:exclamation-triangle[]
      app {

        // Enables or disables the uploader.
        // Valid values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
        // Defaults to `NEVER`.
        // icon:dot-circle[]
        active = 'ALWAYS'

        // Defines the connection timeout in seconds.
        // Defaults to `20`.
        // icon:dot-circle[]
        connectTimeout = 20

        // Defines the read timeout in seconds.
        // Defaults to `60`.
        // icon:dot-circle[]
        readTimeout = 60

        // URL of the Artifactory instance + path + artifact.
        // icon:exclamation-triangle[] icon:file-alt[]
        uploadUrl = 'pass:[https://duke.jfrog.io/artifactory/binaries/{{projectName}}/{{projectVersion}}/{{artifactFileName}}]'

        // URL of the Artifactory instance + path + artifact.
        // If undefined, will use the same value as `uploadUrl`.
        // icon:exclamation-triangle[] icon:file-alt[]
        downloadUrl = 'pass:[https://duke.jfrog.io/artifactory/binaries/{{projectName}}/{{projectVersion}}/{{artifactFileName}}]'

        // The username that can write to the repository.
        // If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_USERNAME`
        // environment variable must be defined.
        // icon:exclamation-triangle[] icon:eye-slash[]
        username = '__DO_NOT_SET_HERE__'

        // Password for login into the repository.
        // If left unspecified, the `JRELEASER_ARTIFACTORY_${name}_PASSWORD`
        // environment variable must be defined.
        // icon:exclamation-triangle[] icon:eye-slash[]
        password = '__DO_NOT_SET_HERE__'

        // The authorization method to use.
        // Valid values are [`BASIC`, `BEARER`].
        // `Basic` requires both username & password.
        // `BEARER` requires a token (set as password).
        // Defaults to `BEARER`.
        // icon:dot-circle[]
        authorization = 'BEARER'

        // Upload files.
        // Defaults to `true`.
        // icon:dot-circle[]
        files = true

        // Upload distribution artifacts.
        // Defaults to `true`.
        // icon:dot-circle[]
        artifacts = true

        // Upload signatures.
        // Defaults to `true`.
        // icon:dot-circle[]
        signatures = true

        // Additional properties used when evaluating templates.
        // Key will be capitalized and prefixed with `artifactory`, i.e, `artifactoryFoo`.
        // icon:dot-circle[]
        extraProperties.put('foo', 'bar')
      }
    }
  }
}
----
--
====

== UploadUrl

The uploadUrl is the URL to upload the artifacts to.

An example configuration may look like
`uploadUrl: 'https://artifacts.company.com:8081/artifactory/example-repo-local/{{projectName}}/{{projectVersion}}/{{artifactFileName}}'`.

And will result in a final deployment like
`pass:[https://artifacts.company.com:8081/artifactory/example-repo-local/app/1.0.0/app-1.0.0.zip]`.

== DownloadUrl

The downloadUrl is the URL used to download artifacts from.

An example configuration may look like
`downloadUrl: 'https://artifacts.company.com:8081/artifactory/example-repo-local/{{projectName}}/{{projectVersion}}/{{artifactFileName}}'`.

And will result in a final deployment like
`pass:[https://artifacts.company.com:8081/artifactory/example-repo-local/app/1.0.0/app-1.0.0.zip]`.

== Username

The configured username needs to be authenticated against the Artifactory instance.

You can have the username set in the configuration as shown above or you can have it read from an environment variable.
The configured name of the Artifactory instance will be used to build the environment variable name.
This means that the name per configured instance needs to be unique.

The name of the environment variable will be `JRELEASER_ARTIFACTORY_NAME_USERNAME`. If your instance is named `production`,
you can store the username in the environment variable `JRELEASER_ARTIFACTORY_PRODUCTION_USERNAME`. The name will be
transformed to uppercase.

If a configured username is found in the configuration file, then the environment variable is not used at all.

== Password

The password will be stored in an environment variable. The configured name of the Artifactory instance will
be used. This means that the name per configured instance needs to be unique.

The name of the environment variable will be `JRELEASER_ARTIFACTORY_NAME_PASSWORD`. If your instance is named `production`,
you need to store the secret in the environment variable `JRELEASER_ARTIFACTORY_PRODUCTION_PASSWORD`. The name will be
transformed to uppercase.

== Skip Upload

Distributions and Artifacts may define extra properties that may stop them from being uploaded. These properties must
conform to the following rules:

* `skipUpload`: skipped from all uploaders.
* `skipUpload<type>`: skipped from the typed uploader.
* `skipUpload<type><name>`: skipped from the typed and named uploader.

Where `<type>` resolves to `Artifactory` and `<name>` resolves to the capitalized name of the artifactory instance, such
that:

* if the name is `foo` the resulting property key is `skipUploadArtifactoryFoo`.
* if the name is `fooBar` the resulting property key is `skipUploadArtifactoryFooBar`.
* if the name is `foo-bar` the resulting property key is `skipUploadArtifactoryFooBar`.

