= Http
:uploader_id:   http
:uploader_name: HTTP

Uploads artifacts, files, and signatures to an {uploader_name}/HTTPS server

.Prerequisites:

 * A HTTP/HTTPS server that accepts POST/PUT requests.
 * Username + Password/Token if authorization is required.

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="attributes,+macros"]
----
include::partial$upload/yaml/common-head.adoc[]

      # URL of the HTTP/HTTPS server + path + artifact.
      # icon:exclamation-triangle[] icon:file-alt[]
      uploadUrl: pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFileName}}]

      # URL of the HTTP/HTTPS server + path + artifact.
      # If undefined, will use the same value as `uploadUrl`.
      # icon:exclamation-triangle[] icon:file-alt[]
      downloadUrl: pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFileName}}]

      # The username required for authorization.
      # If left unspecified, the `JRELEASER_HTTP_${name}_USERNAME`
      # environment variable must be defined.
      # icon:dot-circle[] icon:eye-slash[]
      username: __DO_NOT_SET_HERE__

      # Password for login into the repository.
      # If left unspecified, the `JRELEASER_HTTP_${name}_PASSWORD`
      # environment variable must be defined.
      # icon:dot-circle[] icon:eye-slash[]
      password: __DO_NOT_SET_HERE__

      # The authorization method to use.
      # Valid values are [`NONE`, `BASIC`, `BEARER`].
      # `Basic` requires both username & password.
      # `BEARER` requires a token (set as password).
      # Defaults to `NONE`.
      # icon:dot-circle[]
      authorization: BASIC

      # The method to use for uploading artifacts.
      # Valid values are [`POST`, `PUT`].
      # Defaults to `PUT`.
      # icon:dot-circle[]
      method: POST

      # Additional headers to be sent to the server.
      # Values accept xref:configuration:name-templates.adoc[].
      # icon:dot-circle[] icon:file-alt[]
      headers:
        'X-ARTIFACT-PLATFORM': '{{artifactPlatform}}'
----
--
TOML::
+
--
[source,toml]
[subs="attributes,+macros"]
----
include::partial$upload/toml/common-head.adoc[]

  # URL of the HTTP/HTTPS server + path + artifact.
  # icon:exclamation-triangle[] icon:file-alt[]
  uploadUrl = "pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFileName}}]"

  # URL of the HTTP/HTTPS server + path + artifact.
  # If undefined, will use the same value as `uploadUrl`.
  # icon:exclamation-triangle[] icon:file-alt[]
  downloadUrl = "pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFileName}}]"

  # The username required for authorization.
  # If left unspecified, the `JRELEASER_HTTP_${name}_USERNAME`
  # environment variable must be defined.
  # icon:dot-circle[] icon:eye-slash[]
  username = "__DO_NOT_SET_HERE__"

  # Password for login into the repository..
  # If left unspecified, the `JRELEASER_HTTP_${name}_PASSWORD`
  # environment variable must be defined.
  # icon:dot-circle[] icon:eye-slash[]
  password = "__DO_NOT_SET_HERE__"

  # The authorization method to use.
  # Valid values are [`NONE`, `BASIC`, `BEARER`].
  # `Basic` requires both username & password.
  # `BEARER` requires a token (set as password).
  # Defaults to `NONE`.
  # icon:dot-circle[]
  authorization = "BASIC"

  # The method to use for uploading artifacts.
  # Valid values are [`POST`, `PUT`].
  # Defaults to `PUT`.
  # icon:dot-circle[]
  method = "POST"

  # Additional headers to be sent to the server.
  # Values accept xref:configuration:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  headers."X-ARTIFACT-PLATFORM" = "{{artifactPlatform}}"
----
--
JSON::
+
--
[source,json]
[subs="attributes,+macros"]
----
include::partial$upload/json/common-head.adoc[]

        // URL of the HTTP/HTTPS server + path + artifact.
        // icon:exclamation-triangle[] icon:file-alt[]
        "uploadUrl": "pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFileName}}]",

        // URL of the HTTP/HTTPS server + path + artifact.
        // If undefined, will use the same value as `uploadUrl`.
        // icon:exclamation-triangle[] icon:file-alt[]
        "downloadUrl": "pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFileName}}]",

        // The username required for authorization.
        // If left unspecified, the `JRELEASER_HTTP_${name}_USERNAME`
        // environment variable must be defined.
        // icon:dot-circle[] icon:eye-slash[]
        "username": "__DO_NOT_SET_HERE__",

        // Password for login into the repository.
        // If left unspecified, the `JRELEASER_HTTP_${name}_PASSWORD`
        // environment variable must be defined.
        // icon:dot-circle[] icon:eye-slash[]
        "password": "__DO_NOT_SET_HERE__",

        // The authorization method to use.
        // Valid values are [`NONE`, `BASIC`, `BEARER`].
        // `Basic` requires both username & password.
        // `BEARER` requires a token (set as password).
        // Defaults to `NONE`.
        // icon:dot-circle[]
        "authorization": "BASIC",

        // The method to use for uploading artifacts.
        // Valid values are [`POST`, `PUT`].
        // Defaults to `PUT`.
        // icon:dot-circle[]
        "method": "POST",

        // Additional headers to be sent to the server.
        // Values accept xref:configuration:name-templates.adoc[].
        // icon:dot-circle[] icon:file-alt[]
        "headers": {
          "X-ARTIFACT-PLATFORM": "{{artifactPlatform}}"
        }
include::partial$upload/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="attributes,verbatim,+macros"]
----
include::partial$upload/maven/common-head.adoc[]

        <!--
          URL of the HTTP/HTTPS server + path + artifact.
          icon:exclamation-triangle[] icon:file-alt[]
        -->
        <uploadUrl>pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFileName}}]</uploadUrl>

        <!--
          URL of the HTTP/HTTPS server + path + artifact.
          If undefined, will use the same value as `uploadUrl`.
          icon:exclamation-triangle[] icon:file-alt[]
        -->
        <downloadUrl>pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFileName}}]</downloadUrl>

        <!--
          The username required for authorization.
          If left unspecified, the `JRELEASER_HTTP_${name}_USERNAME`
          environment variable must be defined.
          icon:dot-circle[] icon:eye-slash[]
        -->
        <username>__DO_NOT_SET_HERE__</username>

        <!--
          Password for login into the repository.
          If left unspecified, the `JRELEASER_HTTP_${name}_PASSWORD`
          environment variable must be defined.
          icon:dot-circle[] icon:eye-slash[]
        -->
        <password>__DO_NOT_SET_HERE__</password>

        <!--
          The authorization method to use.
          Valid values are [`NONE`, `BASIC`, `BEARER`].
          `Basic` requires both username & password.
          `BEARER` requires a token (set as password).
          Defaults to `NONE`.
          icon:dot-circle[]
        -->
        <authorization>BASIC</authorization>

        <!--
          The method to use for uploading artifacts.
          Valid values are [`POST`, `PUT`].
          Defaults to `PUT`.
          icon:dot-circle[]
        -->
        <method>POST</method>

        <!--
          Additional headers to be sent to the server.
          Values accept xref:configuration:name-templates.adoc[].
          icon:dot-circle[] icon:file-alt[]
        -->
        <headers>
          <X-ARTIFACT-PLATFORM>{{artifactPlatform}}</X-ARTIFACT-PLATFORM>
        </headers>
include::partial$upload/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="attributes,+macros"]
----
include::partial$upload/gradle/common-head.adoc[]

        // URL of the HTTP/HTTPS server + path + artifact.
        // icon:exclamation-triangle[] icon:file-alt[]
        uploadUrl = 'pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFileName}}]'

        // URL of the HTTP/HTTPS server + path + artifact.
        // If undefined, will use the same value as `uploadUrl`.
        // icon:exclamation-triangle[] icon:file-alt[]
        downloadUrl = 'pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFileName}}]'

        // The username required for authorization.
        // If left unspecified, the `JRELEASER_HTTP_${name}_USERNAME`
        // environment variable must be defined.
        // icon:dot-circle[] icon:eye-slash[]
        username = '__DO_NOT_SET_HERE__'

        // Password for login into the repository.
        // If left unspecified, the `JRELEASER_HTTP_${name}_PASSWORD`
        // environment variable must be defined.
        // icon:dot-circle[] icon:eye-slash[]
        password = '__DO_NOT_SET_HERE__'

        // The authorization method to use.
        // Valid values are [`NONE`, `BASIC`, `BEARER`].
        // `Basic` requires both username & password.
        // `BEARER` requires a token (set as password).
        // Defaults to `NONE`.
        // icon:dot-circle[]
        authorization = 'BASIC'

        // The method to use for uploading artifacts.
        // Valid values are [`POST`, `PUT`].
        // Defaults to `PUT`.
        // icon:dot-circle[]
        method = 'POST'

        // Additional headers to be sent to the server.
        // Values accept xref:configuration:name-templates.adoc[].
        // icon:dot-circle[] icon:file-alt[]
        headers.put('X-ARTIFACT-PLATFORM', '{{artifactPlatform}}')
include::partial$upload/gradle/common-footer.adoc[]
----
--
====

== UploadUrl

The uploadUrl is the URL to upload the artifacts to.

An example configuration may look like
`uploadUrl: 'https://artifacts.company.com:8081/upload/{{projectName}}/{{tagName}}/{{artifactFileName}}'`.

And will result in a final deployment like
`pass:[https://artifacts.company.com:8081/upload/app/v1.0.0/app-1.0.0.zip]`.

== DownloadUrl

The downloadUrl is the URL used to download artifacts from.

An example configuration may look like
`downloadUrl: 'https://artifacts.company.com:8081/upload/{{projectName}}/{{tagName}}/{{artifactFileName}}'`.

And will result in a final deployment like
`pass:[https://artifacts.company.com:8081/upload/app/v1.0.0/app-1.0.0.zip]`.

== Username

You can have the username set in the configuration as shown above or you can have it read from an environment variable.
The configured name of the HTTP server will be used to build the environment variable name.
This means that the name per configured instance needs to be unique.

The name of the environment variable will be `JRELEASER_HTTP_NAME_USERNAME`. If your instance is named `production`,
you can store the username in the environment variable `JRELEASER_HTTP_PRODUCTION_USERNAME`. The name will be
transformed to uppercase.

If a configured username is found in the configuration file, then the environment variable is not used at all.

== Password

The password will be stored in an environment variable. The configured name of the HTTP server will
be used. This means that the name per configured instance needs to be unique.

The name of the environment variable will be `JRELEASER_HTTP_NAME_PASSWORD`. If your instance is named `production`,
you need to store the secret in the environment variable `JRELEASER_HTTP_PRODUCTION_PASSWORD`. The name will be
transformed to uppercase.

== Skip Upload

Distributions and Artifacts may define extra properties that may stop them from being uploaded. These properties must
conform to the following rules:

* `skipUpload`: skipped from all uploaders.
* `skipUpload<type>`: skipped from the typed uploader.
* `skipUpload<type><name>`: skipped from the typed and named uploader.

Where `<type>` resolves to `Http` and `<name>` resolves to the capitalized name of the http instance, such
that:

* if the name is `foo` the resulting property key is `skipUploadHttpFoo`.
* if the name is `fooBar` the resulting property key is `skipUploadHttpFooBar`.
* if the name is `foo-bar` the resulting property key is `skipUploadHttpFooBar`.

