
= Getting Started
:jbake-type:   page
:jbake-status: published

Once JReleaser is installed you may initialize its config file by invoking the following command:

[source]
----
$ jreleaser init --format yml
[INFO]  Writing file /Home/duke/app/.jreleaser.yml
[INFO]  JReleaser initialized at /Home/duke/app
----

This generates a `.jreleaser.yml` file with the following configuration

[source,yaml]
..jreleaser.yml
----
project:
  name: app
  groupId: com.acme
  version: 0.0.0-SNAPSHOT
  description: Awesome App
  longDescription: Awesome App
  website: https://acme.com/app
  authors:
    - Duke
  license: Apache-2
  javaVersion: 8

release:
  github:
    owner: duke

distributions:
  app:
    artifacts:
      - path: path/to/{{distributionName}}-{{projectVersion}}.zip
----

Edit the file to suite your needs. JReleaser does not create artifact files for you. It assumes those are created using
other tools; JReleaser only cares if the resolved artifact paths exist. Once you have edited the file you may verify its
configuration by invoking

[source]
----
$ jreleaser config
----

At any time you may invoke any of the other commands, but when it's time to make a release you have to invoke

[source]
----
$ jreleaser full-release
----

This command performs the following actions:

* checksums all artifacts.
* signs all files (if signing is enabled).
* creates a release at the chosen Git repository.
* prepares, packages, and uploads configured packagers (brew, jbang, etc).
* announces the release.

