
= Distributions
:jbake-type:   page
:jbake-status: published

Distributions define artifacts that may be published using supported packages and announced with supported announcers.

Each distribution is responsible for defining a unique name and a list of artifacts that belong to it.

JReleaser requires at least 1 distribution to be configured. A distribution requires at least 1 artifact to be listed.

Distributions inherit the configuration specified in the <<_packagers,packagers>> block and may override it.

[source,yaml]
[subs="+macros"]
----
# [required]
distributions:
  # A named distribution
  # [required]
  app:

    # Enables or disables the distribution.
    # Defaults to `true`.
    # [optional]
    enabled: true

    # The distribution type.
    # Used to determine packager templates.
    # Supported values are: [BINARY].
    # [required]
    type: BINARY

    # Name of the executable launcher.
    # If left undefined, will use {$distribution.name}.
    # [optional]
    executable: app

    # The minimum Java version required by consumers to run the application.
    # If left undefined, will use {project.javaVersion}.
    # [optional]
    javaVersion: 8

    # Maven coordinates: groupId.
    # f left undefined, will use {project.groupId}
    # [optional]
    groupId: com.acme

    # Maven coordinates: artifactId.
    # f left undefined, will use {project.artifactId}
    # [optional]
    artifactId: app

    # The application's entry point.
    # Required by <<_jbang,jbang>>.
    # [optional]
    mainClass: com.acme.Main

    # A list of tags.
    # [optional]
    tags:
      - cli
      - awesome

    # Additional properties used when evaluating templates.
    # [optional]
    extraProperties:
      # Key will be capitalized and prefixed with `distribution`, i.e, `distributionFoo`.
      foo: bar

    # A list of artifacts.
    # At least on entry must be present
    # [required]
    artifacts:
      - path: path/to/{{distributionName}}-{{projectVersion}}.zip
        # If left undefined, will use {distribution.javaVersion}.
        javaVersion: 8
      - path: path/to/{{distributionName}}-{{projectVersion}}-mac.zip
        platform: osx
      - path: path/to/{{distributionName}}-{{projectVersion}}-win.zip
        platform: windows
----

It's recommended to list universal artifacts first, then platform specific.

The value of `platform` is dictated by the normalized values detected by
link:https://github.com/trustin/os-maven-plugin[os-maven-plugin]. You may use the plain `platform` value or append a
`arch` classifier. The following values are currently recognized

[horizontal]
platform:: `aix`, `hpux`, `os400`, `linux`, `osx`, `freebsd`, `openbsd`, `netbsd`, `sunos`, `windows`, `zos`.
arch:: `x86_64`, `x86_32`, `itanium_64`, `itanium_32`, `sparc_32`, `sparc_64`, `arm_32`, `aarch_64`, `mips_32`,
`mipsel_32`, `mips_64`, `mipsel_64`, `ppc_32`, `ppcle_32`, `ppc_64`, `ppcle_64`, `s390_32`, `s390_64`, `riscv`

Examples:

* `osx`
* `osx-arm`
* `windows`
* `linux`
* `linux-x86_32`


