== Tokens

NOTE: The {tool_tap} token environment variable must match with the chosen xref:release/index.adoc[] service.

[WARNING]
====
On GitHub, you can't use the default `secrets.GITHUB_TOKEN` as this token only works for the repository that's
running the workflow. You must configure a link:https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token[Personal Access Token] (PAT) instead. It is recommended that you use "fine-grained" PATs, rather than "classic" ones. The token must have:

* Access to your tap repository; if this repository is part of a GitHub organization, make sure to choose that organization as the resource owner; if that organization doesn't show up in the "resource owner" drop-down, contact your organization adminstrator and ask them to https://docs.github.com/en/organizations/managing-programmatic-access-to-your-organization/setting-a-personal-access-token-policy-for-your-organization[enable PAT access] for that repository
* The "Contents read and write" repository permission
====
