= Chocolatey
:tool_id:       chocolatey
:tool_name:     Chocolatey
:tool_env_var:  CHOCOLATEY
:tool_tap:      bucket
:tool_tap_name: chocolatey-bucket
:tool_manifest: manifest

Publishes packages to link:https://chocolatey.org[].

NOTE: At the moment, only artifacts with `.zip` extension may be packaged with Chocolatey.

WARNING: Local publication of packages is currently not supported. Please set `remoteBuild` to `true` and trigger a
build on CI. Local publication will be added at a later release.

WARNING: Snapshots are *not* supported.

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="attributes,+macros"]
----
include::partial$packagers/yaml/common-head.adoc[]

include::partial$packagers/yaml/template-directory.adoc[]

include::partial$packagers/yaml/commitauthor.adoc[]

include::partial$packagers/yaml/tap.adoc[]

    # The username that can publish Chocolatey packages.
    # If left unspecified, the release owner will be used.
    # icon:exclamation-triangle[]
    username: duke

    # Whether to build the package on a remote server or locally.
    # Defaults to `false`.
    # icon:dot-circle[]
    remoteBuild: false
----
--
TOML::
+
--
[source,toml]
[subs="attributes,+macros"]
----
include::partial$packagers/toml/common-head.adoc[]

include::partial$packagers/toml/template-directory.adoc[]

include::partial$packagers/toml/commitauthor.adoc[]

include::partial$packagers/toml/tap.adoc[]

  # The username that can publish Chocolatey packages.
  # If left unspecified, the release owner will be used.
  # icon:exclamation-triangle[]
  username = "duke"

  # Whether to build the package on a remote server or locally.
  # Defaults to `false`.
  # icon:dot-circle[]
  remoteBuild = false
----
--
JSON::
+
--
[source,json]
[subs="attributes,+macros"]
----
include::partial$packagers/json/common-head.adoc[]

include::partial$packagers/json/template-directory.adoc[]

include::partial$packagers/json/commitauthor.adoc[]

include::partial$packagers/json/tap.adoc[]

      // The username that can publish Chocolatey packages.
      // If left unspecified, the release owner will be used.
      // icon:exclamation-triangle[]
      "username": "duke",

      // Whether to build the package on a remote server or locally.
      // Defaults to `false`.
      // icon:dot-circle[]
      "remoteBuild": false
include::partial$packagers/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="attributes,verbatim,+macros"]
----
include::partial$packagers/maven/common-head.adoc[]

include::partial$packagers/maven/template-directory.adoc[]

include::partial$packagers/maven/commitauthor.adoc[]

include::partial$packagers/maven/tap.adoc[]

      <!--
        The username that can publish Chocolatey packages.
        If left unspecified, the release owner will be used.
        icon:exclamation-triangle[]
      -->
      <username>duke</username>

      <!--
        Whether to build the package on a remote server or locally.
        Defaults to `false`.
        icon:dot-circle[]
      -->
      <remoteBuild>false</remoteBuild>
include::partial$packagers/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="attributes,+macros"]
----
include::partial$packagers/gradle/common-head.adoc[]

include::partial$packagers/gradle/template-directory.adoc[]

include::partial$packagers/gradle/commitauthor.adoc[]

include::partial$packagers/gradle/tap.adoc[]

      // The username that can publish Chocolatey packages.
      // If left unspecified, the release owner will be used.
      // icon:exclamation-triangle[]
      username = 'duke'

      // Whether to build the package on a remote server or locally.
      // Defaults to `false`.
      // icon:dot-circle[]
      remoteBuild = false
include::partial$packagers/gradle/common-footer.adoc[]
----
--
====

Template files may be initialized using the `template` command.

NOTE: The bucket token environment variable must match with the chosen xref:release/index.adoc[] service, that is, it must
be one of [`JRELEASER_CHOCOLATEY_GITHUB_TOKEN`, `JRELEASER_CHOCOLATEY_GITLAB_TOKEN`, `JRELEASER_CHOCOLATEY_GITEA_TOKEN`].

Assuming that the current version is `1.2.3`, and a distribution named `app`, the above configuration will generate
the following files which will be published to `duke/chocolatey-bucket/app`

[source,xml]
[subs="verbatim"]
.app.nuspec
----
<?xml version="1.0" encoding="utf-8"?>
<!-- Do not remove this test for UTF-8: if “Ω” doesn’t appear as greek uppercase omega letter enclosed in quotation marks, you should use an editor that supports UTF-8, not this one. -->
<package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
  <metadata>
    <!-- required -->
    <id>app</id>
    <version>1.2.3</version>
    <authors>Duke</authors>
    <description>Sample app</description>
    <!-- optional -->
    <title>app</title>
    <projectUrl>https://acme.com/app</projectUrl>
    <license type="expression">Apache-2.0</license>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <tags></tags>
    <summary>Sample app</summary>
    <releaseNotes>https://github.com/duke/app/releases/tag/v1.2.3</releaseNotes>
  </metadata>
  <files>
    <file src="tools\**" target="tools" />
  </files>
</package>
----

[source]
.tools/chocolateyinstall.ps1
----
$tools = Split-Path $MyInvocation.MyCommand.Definition
$package = Split-Path $tools
$app_home = Join-Path $package 'app-1.2.3'
$app_bat = Join-Path $app_home 'bin/app.cmd'

Install-ChocolateyZipPackage `
    -PackageName 'app' `
    -Url 'https://github.com/duke/app/releases/download/v1.2.3/app-1.2.3.zip' `
    -Checksum '812121a64bbd3f49286f7b0be3c9209068f71fcf9541f313708979602e8de466' `
    -ChecksumType 'sha256' `
    -UnzipLocation $package

Install-BinFile -Name 'app' -Path $app_bat
----

[source]
.tools/chocolateyuninstall.ps1
----
$tools = Split-Path $MyInvocation.MyCommand.Definition
$package = Split-Path $tools
$app_home = Join-Path $package 'app-1.2.3'
$app_bat = Join-Path $app_home 'bin/app.cmd'

Uninstall-BinFile -Name 'app' -Path $app_bat
----

== Templates

The default location for templates is:

`src/jreleaser/distributions/<distribution-name>/chocolatey`

The following list shows the filenames that may be used to override default templates:

* `binary.nuspec.tpl`
* `tools/chocolateyinstall.ps1.tpl`
* `tools/chocolateyuninstall.ps1.tpl`

Any additional files found in the template directories will be copied as is unless their filename ends with `.tpl` in
which case xref:name-templates.adoc[] substitution will take place.