= Chocolatey
:tool_id:       chocolatey
:tool_name:     Chocolatey
:tool_env_var:  CHOCOLATEY
:tool_tap:      bucket
:tool_tap_name: chocolatey-bucket
:tool_manifest: manifest
:tool_package:  ${distribution.name}

Publishes packages to link:https://chocolatey.org[].

The following artifact extensions are supported by this packager:

* `.zip`
* `.exe`
* `.msi`

Local publication of packages requires running on Windows, have `powershell` and `choco` installed.
If you rather package and push on CI then set `remoteBuild` to `true`.

WARNING: Publication of snapshots is *not* allowed.

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="attributes,+macros"]
----
include::partial$packagers/yaml/common-head.adoc[]

include::partial$packagers/yaml/template-directory.adoc[]

include::partial$packagers/yaml/commitauthor.adoc[]

include::partial$packagers/yaml/tap.adoc[]

include::partial$packagers/yaml/package-name.adoc[]

    # The username that can publish Chocolatey packages.
    # If left unspecified, the release owner will be used.
    # icon:exclamation-triangle[]
    username: duke

    # The ApiKey associated with the given account.
    # If left unspecified, the `JRELEASER_CHOCOLATEY_API_KEY`
    # environment variable must be defined.
    # icon:exclamation-triangle[] icon:eye-slash[]
    apiKey: __DO_NOT_SET_HERE__

    # The source to push the package to.
    # If left unspecified, will use `https://push.chocolatey.org/`.
    # icon:dot-circle[]
    source: https://push.chocolatey.org/

    # Whether to build the package on a remote server or locally.
    # Defaults to `false`.
    # icon:dot-circle[]
    remoteBuild: false

    # The title of the spec.
    # If left unspecified, will use `${project.name}`.
    # icon:dot-circle[]
    title: Duke

    # The icon's Url.
    # Refer to link:https://docs.chocolatey.org/en-us/create/create-packages#package-icon-guidelines[]
    # icon:dot-circle[] icon:file-alt[]
    iconUrl: https://rawcdn.githack.com/duke/app/0934fa1fa3f0bd09c0c8c39fbdeb5df2ce507457/icon.png
----
--
TOML::
+
--
[source,toml]
[subs="attributes,+macros"]
----
include::partial$packagers/toml/common-head.adoc[]

include::partial$packagers/toml/template-directory.adoc[]

include::partial$packagers/toml/commitauthor.adoc[]

include::partial$packagers/toml/tap.adoc[]

include::partial$packagers/toml/package-name.adoc[]

  # The username that can publish Chocolatey packages.
  # If left unspecified, the release owner will be used.
  # icon:exclamation-triangle[]
  username = "duke"

  # The ApiKey associated with the given account.
  # If left unspecified, the `JRELEASER_CHOCOLATEY_API_KEY`
  # environment variable must be defined.
  # icon:exclamation-triangle[] icon:eye-slash[]
  apiKey = "__DO_NOT_SET_HERE__"

  # The source to push the package to.
  # If left unspecified, will use `https://push.chocolatey.org/`.
  # icon:dot-circle[]
  source = "https://push.chocolatey.org/"

  # Whether to build the package on a remote server or locally.
  # Defaults to `false`.
  # icon:dot-circle[]
  remoteBuild = false

  # The title of the spec.
  # If left unspecified, will use `${project.name}`.
  # icon:dot-circle[]
  title = "Duke"

  # The icon's Url.
  # Refer to link:https://docs.chocolatey.org/en-us/create/create-packages#package-icon-guidelines[]
  # icon:dot-circle[] icon:file-alt[]
  iconUrl = "https://rawcdn.githack.com/duke/app/0934fa1fa3f0bd09c0c8c39fbdeb5df2ce507457/icon.png"
----
--
JSON::
+
--
[source,json]
[subs="attributes,+macros"]
----
include::partial$packagers/json/common-head.adoc[]

include::partial$packagers/json/template-directory.adoc[]

include::partial$packagers/json/commitauthor.adoc[]

include::partial$packagers/json/tap.adoc[]

include::partial$packagers/json/package-name.adoc[]

      // The username that can publish Chocolatey packages.
      // If left unspecified, the release owner will be used.
      // icon:exclamation-triangle[]
      "username": "duke",

      // The ApiKey associated with the given account.
      // If left unspecified, the `JRELEASER_CHOCOLATEY_API_KEY`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "apiKey": "__DO_NOT_SET_HERE__",

      // The source to push the package to.
      // If left unspecified, will use `https://push.chocolatey.org/`.
      // icon:dot-circle[]
      "source": "https://push.chocolatey.org/",

      // Whether to build the package on a remote server or locally.
      // Defaults to `false`.
      // icon:dot-circle[]
      "remoteBuild": false,

      // The title of the spec.
      // If left unspecified, will use `${project.name}`.
      // icon:dot-circle[]
      "title": "Duke",

      // The icon's Url.
      // Refer to link:https://docs.chocolatey.org/en-us/create/create-packages#package-icon-guidelines[]
      // icon:dot-circle[] icon:file-alt[]
      "iconUrl": "https://rawcdn.githack.com/duke/app/0934fa1fa3f0bd09c0c8c39fbdeb5df2ce507457/icon.png"
include::partial$packagers/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="attributes,verbatim,+macros"]
----
include::partial$packagers/maven/common-head.adoc[]

include::partial$packagers/maven/template-directory.adoc[]

include::partial$packagers/maven/commitauthor.adoc[]

include::partial$packagers/maven/tap.adoc[]

include::partial$packagers/maven/package-name.adoc[]

      <!--
        The username that can publish Chocolatey packages.
        If left unspecified, the release owner will be used.
        icon:exclamation-triangle[]
      -->
      <username>duke</username>

      <!--
        The ApiKey associated with the given account.
        If left unspecified, the `JRELEASER_CHOCOLATEY_API_KEY`
        environment variable must be defined.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <apiKey>__DO_NOT_SET_HERE__</apiKey>

      <!--
        The source to push the package to.
        If left unspecified, will use `https://push.chocolatey.org/`.
        icon:dot-circle[]
      -->
      <source>https://push.chocolatey.org/</source>

      <!--
        Whether to build the package on a remote server or locally.
        Defaults to `false`.
        icon:dot-circle[]
      -->
      <remoteBuild>false</remoteBuild>

      <!--
        The title of the spec.
        If left unspecified, will use `${project.name}`.
        icon:dot-circle[]
      -->
      <title>Duke</title>

      <!--
        The icon's Url.
        Refer to link:https://docs.chocolatey.org/en-us/create/create-packages#package-icon-guidelines[]
        icon:dot-circle[] icon:file-alt[]
      -->
      <iconUrl>https://rawcdn.githack.com/duke/app/0934fa1fa3f0bd09c0c8c39fbdeb5df2ce507457/icon.png</iconUrl>
include::partial$packagers/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="attributes,+macros"]
----
include::partial$packagers/gradle/common-head.adoc[]

include::partial$packagers/gradle/template-directory.adoc[]

include::partial$packagers/gradle/commitauthor.adoc[]

include::partial$packagers/gradle/tap.adoc[]

include::partial$packagers/gradle/package-name.adoc[]

      // The username that can publish Chocolatey packages.
      // If left unspecified, the release owner will be used.
      // icon:exclamation-triangle[]
      username = 'duke'

      // The ApiKey associated with the given account.
      // If left unspecified, the `JRELEASER_CHOCOLATEY_API_KEY`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      apiKey = '__DO_NOT_SET_HERE__'

      // The source to push the package to.
      // If left unspecified, will use `https://push.chocolatey.org/`.
      // icon:dot-circle[]
      source = 'https://push.chocolatey.org/'

      // Whether to build the package on a remote server or locally.
      // Defaults to `false`.
      // icon:dot-circle[]
      remoteBuild = false

      // The title of the spec.
      // If left unspecified, will use `${project.name}`.
      // icon:dot-circle[]
      title = 'Duke'

      // The icon's Url.
      // Refer to link:https://docs.chocolatey.org/en-us/create/create-packages#package-icon-guidelines[]
      // icon:dot-circle[] icon:file-alt[]
      iconUrl = 'https://rawcdn.githack.com/duke/app/0934fa1fa3f0bd09c0c8c39fbdeb5df2ce507457/icon.png'
include::partial$packagers/gradle/common-footer.adoc[]
----
--
====

include::partial$packagers/token.adoc[]

include::partial$packagers/downloadUrl.adoc[]

== Example

Assuming the current version is `1.2.3`, and a distribution named `app`, the above configuration will generate
the following files which will be published to `duke/chocolatey-bucket/app`

[source,xml]
[subs="verbatim"]
.app.nuspec
----
<?xml version="1.0" encoding="utf-8"?>
<!-- Do not remove this test for UTF-8: if “Ω” doesn’t appear as greek uppercase omega letter enclosed in quotation marks, you should use an editor that supports UTF-8, not this one. -->
<package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
  <metadata>
    <!-- required -->
    <id>app</id>
    <version>1.2.3</version>
    <authors>Duke</authors>
    <description>Sample app</description>
    <!-- optional -->
    <title>app</title>
    <projectUrl>https://acme.com/app</projectUrl>
    <copyright>2021 Duke</copyright>
    <licenseUrl>https://github.com/duke/app/blob/main/LICENSE</licenseUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <tags>app</tags>
    <summary>Sample app</summary>
    <projectSourceUrl>https://github.com/duke/app</projectSourceUrl>
    <packageSourceUrl>https://github.com/duke/chocolatey-bucket</packageSourceUrl>
    <docsUrl>https://acme.com/app</docsUrl>
    <bugTrackerUrl>https://github.com/duke/app/issues</bugTrackerUrl>
    <iconUrl>https://rawcdn.githack.com/duke/app/0934fa1fa3f0bd09c0c8c39fbdeb5df2ce507457/icon.png</iconUrl>
    <releaseNotes>https://github.com/duke/app/releases/tag/v1.2.3</releaseNotes>
  </metadata>
  <files>
    <file src="tools\**" target="tools" />
  </files>
</package>
----

[source]
.tools/chocolateyinstall.ps1
----
$tools = Split-Path $MyInvocation.MyCommand.Definition
$package = Split-Path $tools
$app_home = Join-Path $package 'app-1.2.3'
$app_bat = Join-Path $app_home 'bin/app.bat'

Install-ChocolateyZipPackage `
    -PackageName 'app' `
    -Url 'https://github.com/duke/app/releases/download/v1.2.3/app-1.2.3.zip' `
    -Checksum '812121a64bbd3f49286f7b0be3c9209068f71fcf9541f313708979602e8de466' `
    -ChecksumType 'sha256' `
    -UnzipLocation $package

Install-BinFile -Name 'app' -Path $app_bat
----

[source]
.tools/chocolateyuninstall.ps1
----
$tools = Split-Path $MyInvocation.MyCommand.Definition
$package = Split-Path $tools
$app_home = Join-Path $package 'app-1.2.3'
$app_bat = Join-Path $app_home 'bin/app.bat'

Uninstall-BinFile -Name 'app' -Path $app_bat
----

== Skip Artifacts

If there is more than one matching artifact in a given distribution you may add a `skipChocolatey` extra property to the target
artifact to mark it as skipped for packaging with Chocolatey.

== Remote Build

It's expected that you take care of creating a nuget package and publish it to the desired location if `remoteBuild` is
set to `true`. Templates for GitHub Actions will be available when the chosen releaser is xref:configuration:release/github.adoc[].

The `Push` workflow triggers whenever a new tag is pushed to the bucket repository. +
The `Trigger` workflow is triggered manually, use for the first publication or if the automatic workflow fails for some
reason.

== Templates

The default location for templates is:

`src/jreleaser/distributions/<distribution-name>/chocolatey`

The following list shows the filenames that may be used to override default templates:

* `binary.nuspec.tpl`
* `tools/chocolateyinstall.ps1.tpl`
* `tools/chocolateyuninstall.ps1.tpl`
* `.github/workflows/push.yml.tpl`
* `.github/workflows/trigger.yml.tpl`

Any additional files found in the template directories will be copied as is unless their filename ends with `.tpl` in
which case xref:name-templates.adoc[] substitution will take place.

Templates may be initialized using the `template` command

xref:tools:jreleaser-cli.adoc#_template[{icon_cli_s} template],
xref:tools:jreleaser-maven.adoc#_jreleasertemplate[{icon_maven_s} jreleaser:template],
xref:tools:jreleaser-gradle.adoc#_jreleasertemplate[{icon_gradle_s} jreleaserTemplate],
xref:tools:jreleaser-ant.adoc#_jreleaser_template[{icon_ant_s} jreleaser-template]
