= Macports
:tool_id:       macports
:tool_name:     Macports
:tool_env_var:  MACPORTS
:tool_tap:      repository
:tool_tap_name: macports
:tool_manifest: portfile

JReleaser can generate and publish a link:https://www.macports.org/[Macports] Portfile into a repository that you have
access to.

The `macports` section specifies how the Portfile should be created.

NOTE: Only artifacts with `.zip` extension may be packaged with Macports.

WARNING: Snapshots are *not* supported.

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="attributes,+macros"]
----
include::partial$packagers/yaml/common-head.adoc[]

include::partial$packagers/yaml/template-directory.adoc[]

include::partial$packagers/yaml/commitauthor.adoc[]

include::partial$packagers/yaml/tap.adoc[]

    # URL used to check the latest version.
    # Defaults to `0`.
    # icon:dot-circle[]
    revision: 0

    # List of categories to use.
    # Defaults to `[devel]`.
    # icon:exclamation-triangle[]
    categories:
      - 'devel'

    # List of maintainers.
    # Accepted values described at link:https://guide.macports.org/#reference.keywords.maintainers[]
    # Defaults to `[@${release.username}]`.
    # icon:exclamation-triangle[]
    maintainers:
      - 'nomaintainer'
----
--
TOML::
+
--
[source,toml]
[subs="attributes,+macros"]
----
include::partial$packagers/toml/common-head.adoc[]

include::partial$packagers/toml/template-directory.adoc[]

include::partial$packagers/toml/commitauthor.adoc[]

include::partial$packagers/toml/tap.adoc[]

  # URL used to check the latest version.
  # Defaults to `0`.
  # icon:dot-circle[]
  revision = 0

  # List of categories to use.
  # Defaults to `[devel]`.
  # icon:exclamation-triangle[]
  categories = ["devel"]

  # List of maintainers.
  # Accepted values described at link:https://guide.macports.org/#reference.keywords.maintainers[]
  # Defaults to `[@${release.username}]`.
  # icon:exclamation-triangle[]
  maintainers = ["nomaintainer"]
----
--
JSON::
+
--
[source,json]
[subs="attributes,+macros"]
----
include::partial$packagers/json/common-head.adoc[]

include::partial$packagers/json/template-directory.adoc[]

include::partial$packagers/json/commitauthor.adoc[]

include::partial$packagers/json/tap.adoc[]

      // URL used to check the latest version.
      // Defaults to `0`.
      // icon:dot-circle[]
      "revision": 0,

      // List of categories to use.
      // Defaults to `[devel]`.
      // icon:exclamation-triangle[]
      "categories": ["devel"],

      // List of maintainers.
      // Accepted values described at link:https://guide.macports.org/#reference.keywords.maintainers[]
      // Defaults to `[@${release.username}]`.
      // icon:exclamation-triangle[]
      "maintainers": ["nomaintainer"]
include::partial$packagers/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="attributes,verbatim,+macros"]
----
include::partial$packagers/maven/common-head.adoc[]

include::partial$packagers/maven/template-directory.adoc[]

include::partial$packagers/maven/commitauthor.adoc[]

include::partial$packagers/maven/tap.adoc[]

      <!--
        URL used to check the latest version.
        Defaults to `0`.
        icon:dot-circle[]
      -->
      <revision>0</revision>

      <!--
        List of categories to use.
        Defaults to `[devel]`.
        icon:exclamation-triangle[]
      -->
      <categories>devel</categories>

      <!--
        List of maintainers.
        Accepted values described at link:https://guide.macports.org/#reference.keywords.maintainers[]
        Defaults to `[@${release.username}]`.
        icon:exclamation-triangle[]
      -->
      <maintainers>nomaintainer</maintainers>
include::partial$packagers/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="attributes,+macros"]
----
include::partial$packagers/gradle/common-head.adoc[]

include::partial$packagers/gradle/template-directory.adoc[]

include::partial$packagers/gradle/commitauthor.adoc[]

include::partial$packagers/gradle/tap.adoc[]

      // URL used to check the latest version.
      // Defaults to `0`.
      // icon:dot-circle[]
      revision = 0

      // List of categories to use.
      // Defaults to `[devel]`.
      // icon:exclamation-triangle[]
      categories = ['devel']

      // List of maintainers.
      // Accepted values described at link:https://guide.macports.org/#reference.keywords.maintainers[]
      // Defaults to `[@${release.username}]`.
      // icon:exclamation-triangle[]
      maintainers = ['nomaintainer']
include::partial$packagers/gradle/common-footer.adoc[]
----
--
====

Template files may be initialized using the `template` command.

NOTE: The repository token environment variable must match with the chosen xref:release/index.adoc[] service, that is, it must
be one of [`JRELEASER_MACPORTS_GITHUB_TOKEN`, `JRELEASER_MACPORTS_GITLAB_TOKEN`, `JRELEASER_MACPORTS_GITEA_TOKEN`].

Assuming that the current version is `1.2.3`, and a distribution named `app`, the above configuration will generate
a `ports/devel/app/Porfile` file in the `duke/macports` repository:

[source,tcl]
----
# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4

PortSystem       1.0
PortGroup        java 1.0

name             app
version          1.2.3
revision         0

categories       devel java
license          Apache-2.0
maintainers      @duke
platforms        darwin
supported_archs  noarch

description      Awesome App
long_description Awesome App

homepage         https://acme.com/app

master_sites     https://github.com/duke/app/releases/download/v1.0.0/
use_zip          yes

checksums        rmd160 f7e88b1c323b5c1772ebce05837a7cfd4ceda09d \
                 sha256 53e89097573fb807adcf410169f117532ae17a4cd72066f9e40420eaf0d13147 \
                 size   6481

java.version     1.8.+

use_configure    no

build {}

destroot {
    set target ${destroot}${prefix}/share/java/${name}

    # Create the target java directory
    xinstall -m 755 -d ${target}

    # Copy over the needed elements of our directory tree
    foreach d { bin lib } {
        copy ${worksrcpath}/${d} ${target}
    }

    # Remove extraneous bat files
    foreach f [glob -directory ${target}/bin *.bat] {
        delete ${f}
    }

    ln -s ../share/java/${name}/bin/app ${destroot}${prefix}/bin/app
}

livecheck.type   none
----

You are then responsible for submitting a ticket to MacPorts for updating an existing port of adding a new port.
JReleaser *does not* create a ticker nor a pull request for you.

Please consult the link:https://guide.macports.org/[MacPorts guide] to know more.

== Templates

The default location for templates is:

`src/jreleaser/distributions/<distribution-name>/macports`

The following list shows the filenames that may be used to override default templates:

* `Portfile.tpl`

Any additional files found in the template directories will be copied as is unless their filename ends with `.tpl` in
which case xref:name-templates.adoc[] substitution will take place.

Templates may be initialized using the `template` command

xref:tools:jreleaser-cli.adoc#_template[{icon_cli_s} template],
xref:tools:jreleaser-maven.adoc#_jreleasertemplate[{icon_maven_s} jreleaser:template],
xref:tools:jreleaser-gradle.adoc#_jreleasertemplate[{icon_gradle_s} jreleaserTemplate],
xref:tools:jreleaser-ant.adoc#_jreleaser_template[{icon_ant_s} jreleaser-template]

