= Scoop
:tool_id:       scoop
:tool_name:     Scoop
:tool_env_var:  SCOOP
:tool_tap:      bucket
:tool_tap_name: scoop-duke
:tool_manifest: manifest
:tool_package:  ${distribution.executable}

JReleaser can generate and publish a _Scoop App Manifest_ into a repository that you have access to.

The `scoop` section specifies how the manifest should be created.

The following artifact extensions are supported by this packager:

* `.jar`
* `.zip`
* `.msi`

WARNING: Publication of snapshots is *not* allowed.

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="attributes,+macros"]
----
include::partial$packagers/yaml/common-head.adoc[]

include::partial$packagers/yaml/template-directory.adoc[]

include::partial$packagers/yaml/commitauthor.adoc[]

include::partial$packagers/yaml/tap.adoc[]

include::partial$packagers/yaml/package-name.adoc[]

    # URL used to check the latest version.
    # Defaults to the releaser's `latestReleaseUrl`.
    # icon:dot-circle[] icon:file-alt[]
    checkverUrl: pass:[https://host/path]

    # URL used to download a new version.
    # Defaults to the releaser's `downloadUrl`.
    # icon:dot-circle[] icon:file-alt[]
    autoupdateUrl: pass:[https://host/path]
----
--
TOML::
+
--
[source,toml]
[subs="attributes,+macros"]
----
include::partial$packagers/toml/common-head.adoc[]

include::partial$packagers/toml/template-directory.adoc[]

include::partial$packagers/toml/commitauthor.adoc[]

include::partial$packagers/toml/tap.adoc[]

include::partial$packagers/toml/package-name.adoc[]

  # URL used to check the latest version.
  # Defaults to the releaser's `latestReleaseUrl`.
  # icon:dot-circle[] icon:file-alt[]
  checkverUrl = "pass:[https://host/path]"

  # URL used to download a new version.
  # Defaults to the releaser's `downloadUrl`.
  # icon:dot-circle[] icon:file-alt[]
  autoupdateUrl = "pass:[https://host/path]"
----
--
JSON::
+
--
[source,json]
[subs="attributes,+macros"]
----
include::partial$packagers/json/common-head.adoc[]

include::partial$packagers/json/template-directory.adoc[]

include::partial$packagers/json/commitauthor.adoc[]

include::partial$packagers/json/tap.adoc[]

include::partial$packagers/json/package-name.adoc[]

      // URL used to check the latest version.
      // Defaults to the releaser's `latestReleaseUrl`.
      // icon:dot-circle[] icon:file-alt[]
      "checkverUrl": "pass:[https://host/path]",

      // URL used to download a new version.
      // Defaults to the releaser's `downloadUrl`.
      // icon:dot-circle[] icon:file-alt[]
      "autoupdateUrl": "pass:[https://host/path]"
include::partial$packagers/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="attributes,verbatim,+macros"]
----
include::partial$packagers/maven/common-head.adoc[]

include::partial$packagers/maven/template-directory.adoc[]

include::partial$packagers/maven/commitauthor.adoc[]

include::partial$packagers/maven/tap.adoc[]

include::partial$packagers/maven/package-name.adoc[]

      <!--
        URL used to check the latest version.
        Defaults to the releaser's `latestReleaseUrl`.
        icon:dot-circle[] icon:file-alt[]
      -->
      <checkverUrl>pass:[https://host/path]</checkverUrl>

      <!--
        URL used to download a new version.
        Defaults to the releaser's `downloadUrl`.
        icon:dot-circle[] icon:file-alt[]
      -->
      <autoupdateUrl>pass:[https://host/path]</autoupdateUrl>
include::partial$packagers/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="attributes,+macros"]
----
include::partial$packagers/gradle/common-head.adoc[]

include::partial$packagers/gradle/template-directory.adoc[]

include::partial$packagers/gradle/commitauthor.adoc[]

include::partial$packagers/gradle/tap.adoc[]

include::partial$packagers/gradle/package-name.adoc[]

      // URL used to check the latest version.
      // Defaults to the releaser's `latestReleaseUrl`.
      // icon:dot-circle[] icon:file-alt[]
      checkverUrl = 'pass:[https://host/path]'

      // URL used to download a new version.
      // Defaults to the releaser's `downloadUrl`.
      // icon:dot-circle[] icon:file-alt[]
      autoupdateUrl = 'pass:[https://host/path]'
include::partial$packagers/gradle/common-footer.adoc[]
----
--
====

include::partial$packagers/token.adoc[]

include::partial$packagers/downloadUrl.adoc[]

== Example

Assuming the current version is `1.2.3`, and a distribution named `app`, the above configuration will generate
a `manifest.json` formula in the `duke/scoop-duke` repository:

[source,json]
----
{
  "homepage": "https://acme.com/app",
  "description": "Sample app",
  "version": "1.2.3",
  "license": "Apache-2.0",
  "url": "https://github.com/duke/app/releases/download/v1.2.3/app-1.2.3.zip",
  "hash": "sha256:812121a64bbd3f49286f7b0be3c9209068f71fcf9541f313708979602e8de466",
  "extract_dir": "app-1.2.3",
  "env_add_path": "bin",
  "suggest": {
    "JDK": [
      "java/oraclejdk",
      "java/openjdk"
    ]
  },
  "checkver": {
    "url": "https://github.com/duke/app/releases/latest",
    "re": "v([\\d.]+).zip"
  },
  "autoupdate": {
    "url": "https://github.com/duke/app/releases/download/v1.2.3/app-$version.zip",
    "extract_dir": "app-$version",
    "hash": {
      "url": "$url.sha256"
    }
  }
}
----

Your users can then install your app by doing:

[source]
----
scoop bucket add duke https://github.com/duke/scoop-duke.git
scoop install app
----

IMPORTANT: GitLab does not yet offer an URL that resolves to a latest release. You may need to adapt the value of
`checkverUrl` or update the tool template by removing that section.
Keep an eye on link:https://gitlab.com/gitlab-org/gitlab/-/issues/16821[].

== Skip Artifacts

If there is more than one matching artifact in a given distribution you may add a `skipScoop` extra property to the target
artifact to mark it as skipped for packaging with Scoop.

== Templates

The default location for templates is:

`src/jreleaser/distributions/<distribution-name>/scoop`

The following list shows the filenames that may be used to override default templates:

* `manifest.json.tpl`
* `README.md.tpl`

Any additional files found in the template directories will be copied as is unless their filename ends with `.tpl` in
which case xref:name-templates.adoc[] substitution will take place.

Templates may be initialized using the `template` command

xref:tools:jreleaser-cli.adoc#_template[{icon_cli_s} template],
xref:tools:jreleaser-maven.adoc#_jreleasertemplate[{icon_maven_s} jreleaser:template],
xref:tools:jreleaser-gradle.adoc#_jreleasertemplate[{icon_gradle_s} jreleaserTemplate],
xref:tools:jreleaser-ant.adoc#_jreleaser_template[{icon_ant_s} jreleaser-template]

