= Sdkman
:tool_id:       sdkman
:tool_name:     Sdkman
:tool_env_var:  SDKMAN

Publishes a distribution to link:https://sdkman.io[Sdkman]. Please follow the instructions at
link:https://sdkman.io/vendors[] to register your project as a candidate and obtain publishing credentials.

NOTE: Configuring this packager automatically enables the xref:configuration:announce/sdkman.adoc[] announcer.

WARNING: Snapshots are *not* supported.

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="attributes,+macros"]
----
include::partial$packagers/yaml/common-head.adoc[]

    # Defines the connection timeout in seconds.
    # Defaults to `20`.
    # icon:dot-circle[]
    connectTimeout: 20

    # Defines the read timeout in seconds.
    # Defaults to `60`.
    # icon:dot-circle[]
    readTimeout: 60

    # The name of the candidate registered in thew Sdkman database.
    # If unspecified, will use ${distribution.name}.
    # icon:dot-circle[]
    candidate: app

    # Sdkman command to use.
    # Valid values are [`MAJOR`, `MINOR`]
    # Defaults to `MAJOR`.
    # icon:dot-circle[]
    command: MAJOR

    # The release notes URL to use.
    # Defaults to `${release.<git>.releaseNotesUrl}.
    # icon:dot-circle[] icon:file-alt[]
    releaseNotesUrl: pass:[https://host.com/{{projectName}}/{{tagName}}]

    # The consumer key for publishing to Sdkman.
    # If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_KEY`
    # environment variable must be defined.
    # icon:exclamation-triangle[] icon:eye-slash[]
    consumerKey: __DO_NOT_SET_HERE__

    # The consumer token for publishing to Sdkman.
    # If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_TOKEN`
    # environment variable must be defined.
    # icon:exclamation-triangle[] icon:eye-slash[]
    consumerToken: __DO_NOT_SET_HERE__
----
--
TOML::
+
--
[source,toml]
[subs="attributes,+macros"]
----
include::partial$packagers/toml/common-head.adoc[]

  # Defines the connection timeout in seconds.
  # Defaults to `20`.
  # icon:dot-circle[]
  connectTimeout = 20

  # Defines the read timeout in seconds.
  # Defaults to `60`.
  # icon:dot-circle[]
  readTimeout = 60

  # The name of the candidate registered in thew Sdkman database.
  # If unspecified, will use ${project.name}.
  # icon:dot-circle[]
  candidate = "app"

  # The release notes URL to use.
  # Defaults to `${release.<git>.releaseNotesUrl}.
  # icon:dot-circle[] icon:file-alt[]
  releaseNotesUrl = "pass:[https://host.com/{{projectName}}/{{tagName}}]"

  # Sdkman command to use.
  # Valid values are [`MAJOR`, `MINOR`]
  # Defaults to `MAJOR`.
  # icon:dot-circle[]
  command = "MAJOR"

  # The consumer key for publishing to Sdkman.
  # If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_KEY`
  # environment variable must be defined.
  # icon:exclamation-triangle[] icon:eye-slash[]
  consumerKey = "__DO_NOT_SET_HERE__"

  # The consumer token for publishing to Sdkman.
  # If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_TOKEN`
  # environment variable must be defined.
  # icon:exclamation-triangle[] icon:eye-slash[]
  consumerToken = "__DO_NOT_SET_HERE__"
----
--
JSON::
+
--
[source,json]
[subs="attributes,+macros"]
----
include::partial$packagers/json/common-head.adoc[]

      // Defines the connection timeout in seconds.
      // Defaults to `20`.
      // icon:dot-circle[]
      "connectTimeout": 20,

      // Defines the read timeout in seconds.
      // Defaults to `60`.
      // icon:dot-circle[]
      "readTimeout": 60,

      // The name of the candidate registered in thew Sdkman database.
      // If unspecified, will use ${project.name}.
      // icon:dot-circle[]
      "candidate": "app",

      // The release notes URL to use.
      // Defaults to `${release.<git>.releaseNotesUrl}.
      // icon:dot-circle[] icon:file-alt[]
      "releaseNotesUrl": "pass:[https://host.com/{{projectName}}/{{tagName}}]",

      // Sdkman command to use.
      // Valid values are [`MAJOR`, `MINOR`]
      // Defaults to `MAJOR`.
      // icon:dot-circle[]
      "command": "MAJOR",

      // The consumer key for publishing to Sdkman.
      // If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_KEY`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "consumerKey": "__DO_NOT_SET_HERE__",

      // The consumer token for publishing to Sdkman.
      // If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_TOKEN`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "consumerToken": "__DO_NOT_SET_HERE__"
include::partial$packagers/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="attributes,verbatim,+macros"]
----
include::partial$packagers/maven/common-head.adoc[]

      <!--
        Defines the connection timeout in seconds.
        Defaults to `20`.
        icon:dot-circle[]
      -->
      <connectTimeout>20</connectTimeout>

      <!--
        Defines the read timeout in seconds.
        Defaults to `60`.
        icon:dot-circle[]
      -->
      <readTimeout>60</readTimeout>

      <!--
        The name of the candidate registered in thew Sdkman database.
        If unspecified, will use ${project.name}.
        icon:dot-circle[]
      -->
      <candidate>app</candidate>

      <!--
        The release notes URL to use.
        Defaults to `${release.<git>.releaseNotesUrl}.
        icon:dot-circle[] icon:file-alt[]
      -->
      <releaseNotesUrl>pass:[https://host.com/{{projectName}}/{{tagName}}]</releaseNotesUrl>

      <!--
        Sdkman command to use.
        Valid values are [`MAJOR`, `MINOR`]
        Defaults to `MAJOR`.
        icon:dot-circle[]
      -->
      <command>MAJOR</command>

      <!--
        The consumer key for publishing to Sdkman.
        If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_KEY`
        environment variable must be defined.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <consumerKey>__DO_NOT_SET_HERE__</consumerKey>

      <!--
        The consumer token for publishing to Sdkman.
        If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_TOKEN`
        environment variable must be defined.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <consumerToken>__DO_NOT_SET_HERE__</consumerToken>
include::partial$packagers/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="attributes,+macros"]
----
include::partial$packagers/gradle/common-head.adoc[]

      // Defines the connection timeout in seconds.
      // Defaults to `20`.
      // icon:dot-circle[]
      connectTimeout = 20

      // Defines the read timeout in seconds.
      // Defaults to `60`.
      // icon:dot-circle[]
      readTimeout = 60

      // The name of the candidate registered in thew Sdkman database.
      // If unspecified, will use ${project.name}.
      // icon:dot-circle[]
      candidate = 'app'

      // The release notes URL to use.
      // Defaults to `${release.<git>.releaseNotesUrl}.
      // icon:dot-circle[] icon:file-alt[]
      releaseNotesUrl = 'pass:[https://host.com/{{projectName}}/{{tagName}}]'

      // Sdkman command to use.
      // Valid values are [`MAJOR`, `MINOR`]
      // Defaults to `MAJOR`.
      // icon:dot-circle[]
      command = 'MAJOR'

      // The consumer key for publishing to Sdkman.
      // If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_KEY`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      consumerKey = '__DO_NOT_SET_HERE__'

      // The consumer token for publishing to Sdkman.
      // If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_TOKEN`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      consumerToken = '__DO_NOT_SET_HERE__'
include::partial$packagers/gradle/common-footer.adoc[]
----
--
====

NOTE: The catalog token environment variable must match with the chosen xref:release/index.adoc[] service, that is, it must
be one of [`JRELEASER_JBANG_GITHUB_TOKEN`, `JRELEASER_JBANG_GITLAB_TOKEN`, `JRELEASER_JBANG_GITEA_TOKEN`].

IMPORTANT: Candidate names must be unique!

== Requirements

This packager has the following requirements:

* Only `zip` artifacts are supported.
* The default platform is set to `UNIVERSAL` if the artifact did not define a value for its `platform` field.
* If there's more than one artifact then each artifact requires distinct `platform` values, otherwise the latest
 artifact will override any previous matches by platform.
* You may explicitly skip an artifact by defining an extra property named `skipSdkman` with a `true` value.
* Publishing will be skipped if no suitable artifacts are found.

Supported platform values are:

* `mac`, `osx`.
* `win`, `windows`.
* `linux`.

