= Binary

Distributions of this type provide a platform specific native binary, as a consequence you *must* specify a platform value
for each one of their artifacts.

Distributions of this type conform to the following file structure:

[source]
----
.
├── LICENSE
├── README
└── bin
    └── executable
----

== Creating a Distribution

You can use any tool/language at your disposal to create a distribution of this type as long as the file structure is
followed and the final artifact packaged as a Zip or Tar file.

Alternatively, you may also configure a xref:configuration:assemble/archive.adoc[] assembler to create an archive.

== Packager Support

[%header, cols="<,^"]
|===
| Packager                                       | Supported
| xref:configuration:packagers/chocolatey.adoc[] | {icon_req_y}
| xref:configuration:packagers/docker.adoc[]     | {icon_req_y}
| xref:configuration:packagers/gofish.adoc[]     | {icon_req_y}
| xref:configuration:packagers/homebrew.adoc[]   | {icon_req_y}
| xref:configuration:packagers/jbang.adoc[]      | {icon_req_n}
| xref:configuration:packagers/macports.adoc[]   | {icon_req_y}
| xref:configuration:packagers/scoop.adoc[]      | {icon_req_y}
| xref:configuration:packagers/sdkman.adoc[]     | {icon_req_n}
| xref:configuration:packagers/snap.adoc[]       | {icon_req_y}
| xref:configuration:packagers/spec.adoc[]       | {icon_req_y}
|===



