= Native Package

Distributions of this type provide a platform specific native installers or packagers. These installers may be created
using the `jpackage` tool available since JDK 16. Supported artifact file extensions are the same as those supported by
the `jpackage` tool, that is:

 * .dmg
 * .pkg
 * .deb
 * .rpm
 * .msi
 * .exe

== Creating a Distribution

We recommend using the `link:https://docs.oracle.com/en/java/javase/16/jpackage/packaging-overview.html[jpackage]` tool
create native packages however you may use any other tool that produces a native package.

Alternatively, you may also configure a xref:configuration:assemble/jpackage.adoc[] assembler.

== Packager Support

[%header, cols="<,^"]
|===
| Packager                                       | Supported
| xref:configuration:packagers/chocolatey.adoc[] | {icon_req_y}
| xref:configuration:packagers/docker.adoc[]     | {icon_req_n}
| xref:configuration:packagers/homebrew.adoc[]   | {icon_req_y}
| xref:configuration:packagers/jbang.adoc[]      | {icon_req_n}
| xref:configuration:packagers/macports.adoc[]   | {icon_req_y}
| xref:configuration:packagers/scoop.adoc[]      | {icon_req_y}
| xref:configuration:packagers/sdkman.adoc[]     | {icon_req_n}
| xref:configuration:packagers/snap.adoc[]       | {icon_req_y}
| xref:configuration:packagers/spec.adoc[]       | {icon_req_n}
|===



