= Command Hooks

Defines command or script hooks to be executed before or after a JReleaser step.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros"]
----
# icon:dot-circle[]
hooks:
  # Enable or disable all hooks.
  # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
  # Defaults to `ALWAYS`.
  # icon:dot-circle[] icon:eye-slash[]
  active: ALWAYS

  # icon:dot-circle[]
  command:
    # Enable or disable all before, success, and failure hooks.
    # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
    # Defaults to `ALWAYS`.
    # icon:dot-circle[] icon:eye-slash[]
    active: ALWAYS

    # The type of hook
    # Valid entries are `before`, `success`, `failure`.
    # icon:dot-circle[]
    before:
        # Let the release continue if the hook fails.
        # Defaults to `false`.
        # icon:dot-circle[]
      - continueOnError: true

        # Enable or disable this hook.
        # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
        # Defaults to `ALWAYS`.
        # icon:dot-circle[] icon:eye-slash[]
        active: ALWAYS

        # The command to be invoked.
        # icon:exclamation-triangle[] icon:file-alt[]
        cmd: '{{basedir}}/notifier.sh {{event.name}} {{event.type}} {{projectVersion}}'

        # Filters this hook based on the given step.
        # icon:dot-circle[]
        filter:
          includes: ['release']
          excludes: ['publish']

        # Filters this hook based on the current platform.
        # Use a `!` prefix to exclude a platform
        # icon:dot-circle[]
        platforms:
          - linux
          - !windows
----
--
TOML::
+
--
[source,toml]
[subs="+macros"]
----
# icon:dot-circle[]
[hooks]
  # Enable or disable all hooks.
  # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
  # Defaults to `ALWAYS`.
  # icon:dot-circle[] icon:eye-slash[]
  active = "ALWAYS"

  # icon:dot-circle[]
  [hooks.command]
    # Enable or disable all before, success, and failure hooks.
    # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
    # Defaults to `ALWAYS`.
    # icon:dot-circle[] icon:eye-slash[]
    active = "ALWAYS"

    # The type of hook
    # Valid entries are `before`, `success`, `failure`.
    # icon:dot-circle[]
    [[hooks.command.before]]
      # Let the release continue if the hook fails.
      # Defaults to `false`.
      # icon:dot-circle[]
      continueOnError = true

      # Enable or disable this hook.
      # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
      # Defaults to `ALWAYS`.
      # icon:dot-circle[] icon:eye-slash[]
      active = "ALWAYS"

      # The command to be invoked.
      # icon:exclamation-triangle[] icon:file-alt[]
      cmd = "{{basedir}}/notifier.sh {{event.name}} {{event.type}} {{projectVersion}}"

      # Filters this hook based on the given step.
      # icon:dot-circle[]
      filter.includes = ["release"]
      filter.excludes = ["publish"]

      # Filters this hook based on the current platform.
      # Use a `!` prefix to exclude a platform
      # icon:dot-circle[]
      platforms = ["linux", "!windows"]
----
--
JSON::
+
--
[source,json]
[subs="+macros"]
----
{
  // icon:dot-circle[]
  "hooks": {
    // Enable or disable all hooks.
    // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
    // Defaults to `ALWAYS`.
    // icon:dot-circle[] icon:eye-slash[]
    "active": "ALWAYS",

    // icon:dot-circle[]
    "command": {
      // Enable or disable all before, success, and failure hooks.
      // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
      // Defaults to `ALWAYS`.
      // icon:dot-circle[] icon:eye-slash[]
      "active": "ALWAYS",

      // The type of hook
      // Valid entries are `before`, `success`, `failure`.
      // icon:dot-circle[]
      "before": [
        {
          // Let the release continue if the hook fails.
          // Defaults to `false`.
          // icon:dot-circle[]
          "continueOnError": true,

          // Enable or disable this hook.
          // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
          // Defaults to `ALWAYS`.
          // icon:dot-circle[] icon:eye-slash[]
          "active": "ALWAYS",

          // The command to be invoked.
          // icon:exclamation-triangle[] icon:file-alt[]
          "cmd": "{{basedir}}/notifier.sh {{event.name}} {{event.type}} {{projectVersion}}",

          // Filters this hook based on the given step.
          // icon:dot-circle[]
          "filter": {
            "includes": ["release"],
            "excludes": ["publish"]
          },

          // Filters this hook based on the current platform.
          // Use a `!` prefix to exclude a platform
          // icon:dot-circle[]
          "platforms": [
            "linux",
            "!windows"
          ]
        }
      ]
    }
  }
}
----
--
Maven::
+
--
[source,xml]
[subs="+macros,verbatim"]
----
<jreleaser>
  <!--
    icon:dot-circle[]
  -->
  <hooks>
    <!--
      Enable or disable all hooks.
      Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
      Defaults to `ALWAYS`.
      icon:dot-circle[] icon:eye-slash[]
    -->
    <active>ALWAYS</active>

    <!--
      icon:dot-circle[]
    -->
    <command>
      <!--
        Enable or disable all before, success, and failure hooks.
        Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
        Defaults to `ALWAYS`.
        icon:dot-circle[] icon:eye-slash[]
      -->
      <active>ALWAYS</active>

      <!--
        The type of hook
        Valid entries are `before`, `success`, `failure`.
        icon:dot-circle[]
      -->
      <before>
        <commandHook>
          <!--
            Let the release continue if the hook fails.
            Defaults to `false`.
            icon:dot-circle[]
          -->
          <continueOnError>true</continueOnError>
          <!--
            Enable or disable this hook.
            Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
            Defaults to `ALWAYS`.
            icon:dot-circle[] icon:eye-slash[]
          -->
          <active>ALWAYS</active>

          <!--
            The command to be invoked.
            icon:exclamation-triangle[] icon:file-alt[]
          -->
          <cmd>{{basedir}}/notifier.sh {{event.name}} {{event.type}} {{projectVersion}}</cmd>

          <!--
            Filters this hook based on the given step.
            icon:dot-circle[]
          -->
          <filter>
            <includes>release</include>
            <excludes>publish</excludes>
          </filter>

          <!--
            Filters this hook based on the current platform.
            Use a `!` prefix to exclude a platform
            icon:dot-circle[]
          -->
          <platforms>
            <platform>linux</platform>
            <platform>!windows</platform>
          </platforms>
        </commandHook>
      </before>
    </command>
  </hooks>
</jreleaser>
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros"]
----
jreleaser {
  // icon:dot-circle[]
  hooks {
    // Enable or disable all hooks.
    // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
    // Defaults to `ALWAYS`.
    // icon:dot-circle[] icon:eye-slash[]
    active = 'ALWAYS'

    // icon:dot-circle[]
    command {
      // Enable or disable all before, success, and failure hooks.
      // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
      // Defaults to `ALWAYS`.
      // icon:dot-circle[] icon:eye-slash[]
      active: ALWAYS

      // The type of hook
      // Valid entries are `before`, `success`, `failure`.
      // icon:dot-circle[]
      before {
        // Let the release continue if the hook fails.
        // Defaults to `false`.
        // icon:dot-circle[]
        continueOnError = true

        // Enable or disable this hook.
        // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
        // Defaults to `ALWAYS`.
        // icon:dot-circle[] icon:eye-slash[]
        active = 'ALWAYS'

        // The command to be invoked.
        // icon:exclamation-triangle[] icon:file-alt[]
        cmd = "{{basedir}}/notifier.sh {{event.name}} {{event.type}} {{projectVersion}}"

        // Filters this hook based on the given step.
        // icon:dot-circle[]
        filter {
          includes = ["release"]
          excludes = ["publish"]
        }

        // Filters this hook based on the current platform.
        // Use a `!` prefix to exclude a platform
        // icon:dot-circle[]
        platform('linux')
        platform('!windows')
      }
    }
  }
}
----
--
====

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
2+| *active*
| jreleaser.hooks.command.active
| JRELEASER_HOOKS_COMMAND_ACTIVE
|===

**Before hooks**
[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
2+| *active*
| jreleaser.hooks.command.before.${index}.active
| JRELEASER_HOOKS_COMMAND_BEFORE_${index}_ACTIVE
|===

**Success hooks**
[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
2+| *active*
| jreleaser.hooks.command.success.${index}.active
| JRELEASER_HOOKS_COMMAND_SUCCESS_${index}_ACTIVE
|===

**Failure hooks**
[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
2+| *active*
| jreleaser.hooks.command.failure.${index}.active
| JRELEASER_HOOKS_COMMAND_FAILURE_${index}_ACTIVE
|===

== Step Names

The following step names may be used when filtering hooks:

* `download`
* `assemble`
* `changelog`
* `catalog`
* `checksum`
* `sign`
* `upload`
* `deploy`
* `release`
* `prepare`
* `package`
* `publish`
* `announce`

== Template Names

The following template names are also available:

[horizontal]
{{event.type}}:: One of [`before`, `success`, `failure`].
{{event.name}}:: One of the previously mentioned steps.

== Output

Command hooks have the option to provide key/value pairs as input for other steps in the current workflow. Simply
use `JRELEASER_OUTPUT:` as prefix in the command's output followed by `key=value`. For example, the following configuration
adds a key named `foo` with a value `bar` before the `changelog` step is invoked:

[source,yaml]
----
hooks:
  command:
    before:
      - filter:
          includes: [changelog]
        cmd: 'echo JRELEASER_OUTPUT:foo=bar'
----

