= Script Hooks

Defines script hooks to be executed before or after a JReleaser step.

NOTE: Script hooks are executed before xref:reference:hooks/command.adoc[].

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros"]
----
# icon:dot-circle[]
hooks:
  # Enable or disable all hooks.
  # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
  # Defaults to `ALWAYS`.
  # icon:dot-circle[] icon:eye-slash[]
  active: ALWAYS

  # icon:dot-circle[]
  script:
    # Enable or disable all before, success, and failure hooks.
    # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
    # Defaults to `ALWAYS`.
    # icon:dot-circle[] icon:eye-slash[]
    active: ALWAYS

    # The type of hook
    # Valid entries are `before`, `success`, `failure`.
    # icon:dot-circle[]
    before:
        # Let the release continue if the hook fails.
        # Defaults to `false`.
        # icon:dot-circle[]
      - continueOnError: true

        # Print script out/err to log.
        # Defaults to `false`.
        # icon:dot-circle[]
        verbose: true

        # Enable or disable this hook.
        # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
        # Defaults to `ALWAYS`.
        # icon:dot-circle[] icon:eye-slash[]
        active: ALWAYS

        # Shell settings for executing the script.
        # Supported values are [`BASH`, `SH`, `CMD`, `PWSH`, `POWERSHELL`].
        # Defaults to `BASH`.
        # icon:dot-circle[]
        shell: BASH

        # The script to be invoked.
        # icon:exclamation-triangle[] icon:file-alt[]
        run: '{{basedir}}/notifier.sh {{event.name}} {{event.type}} {{projectVersion}}'

        # Filters this hook based on the given step.
        # icon:dot-circle[]
        filter:
          includes: ['release']
          excludes: ['publish']

        # Filters this hook based on the current platform.
        # Use a `!` prefix to exclude a platform
        # icon:dot-circle[]
        platforms:
          - linux
          - !windows
----
--
TOML::
+
--
[source,toml]
[subs="+macros"]
----
# icon:dot-circle[]
[hooks]
  # Enable or disable all hooks.
  # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
  # Defaults to `ALWAYS`.
  # icon:dot-circle[] icon:eye-slash[]
  active = "ALWAYS"

  # icon:dot-circle[]
  [hooks.script]
    # Enable or disable all before, success, and failure hooks.
    # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
    # Defaults to `ALWAYS`.
    # icon:dot-circle[] icon:eye-slash[]
    active = "ALWAYS"

    # The type of hook
    # Valid entries are `before`, `success`, `failure`.
    # icon:dot-circle[]
    [[hooks.script.before]]
      # Let the release continue if the hook fails.
      # Defaults to `false`.
      # icon:dot-circle[]
      continueOnError = true

      # Print script out/err to log.
      # Defaults to `false`.
      # icon:dot-circle[]
      verbose = true

      # Enable or disable this hook.
      # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
      # Defaults to `ALWAYS`.
      # icon:dot-circle[] icon:eye-slash[]
      active = "ALWAYS"

      # Shell settings for executing the script.
      # Supported values are [`BASH`, `SH`, `CMD`, `PWSH`, `POWERSHELL`].
      # Defaults to `BASH`.
      # icon:dot-circle[]
      shell = "BASH"

      # The script to be invoked.
      # icon:exclamation-triangle[] icon:file-alt[]
      run = "{{basedir}}/notifier.sh {{event.name}} {{event.type}} {{projectVersion}}"

      # Filters this hook based on the given step.
      # icon:dot-circle[]
      filter.includes = ["release"]
      filter.excludes = ["publish"]

      # Filters this hook based on the current platform.
      # Use a `!` prefix to exclude a platform
      # icon:dot-circle[]
      platforms = ["linux", "!windows"]
----
--
JSON::
+
--
[source,json]
[subs="+macros"]
----
{
  // icon:dot-circle[]
  "hooks": {
    // Enable or disable all hooks.
    // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
    // Defaults to `ALWAYS`.
    // icon:dot-circle[] icon:eye-slash[]
    "active": "ALWAYS",

    // icon:dot-circle[]
    "script": {
      // Enable or disable all before, success, and failure hooks.
      // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
      // Defaults to `ALWAYS`.
      // icon:dot-circle[] icon:eye-slash[]
      "active": "ALWAYS",

      // The type of hook
      // Valid entries are `before`, `success`, `failure`.
      // icon:dot-circle[]
      "before": [
        {
          // Let the release continue if the hook fails.
          // Defaults to `false`.
          // icon:dot-circle[]
          "continueOnError": true,

          // Print script out/err to log.
          // Defaults to `false`.
          // icon:dot-circle[]
          "verbose": true,

          // Enable or disable this hook.
          // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
          // Defaults to `ALWAYS`.
          // icon:dot-circle[] icon:eye-slash[]
          "active": "ALWAYS",

          // Shell settings for executing the script.
          // Supported values are [`BASH`, `SH`, `CMD`, `PWSH`, `POWERSHELL`].
          // Defaults to `BASH`.
          // icon:dot-circle[]
          "shell": "BASH",

          // The script to be invoked.
          // icon:exclamation-triangle[] icon:file-alt[]
          "run": "{{basedir}}/notifier.sh {{event.name}} {{event.type}} {{projectVersion}}",

          // Filters this hook based on the given step.
          // icon:dot-circle[]
          "filter": {
            "includes": ["release"],
            "excludes": ["publish"]
          },

          // Filters this hook based on the current platform.
          // Use a `!` prefix to exclude a platform
          // icon:dot-circle[]
          "platforms": [
            "linux",
            "!windows"
          ]
        }
      ]
    }
  }
}
----
--
Maven::
+
--
[source,xml]
[subs="+macros,verbatim"]
----
<jreleaser>
  <!--
    icon:dot-circle[]
  -->
  <hooks>
    <!--
      Enable or disable all hooks.
      Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
      Defaults to `ALWAYS`.
      icon:dot-circle[] icon:eye-slash[]
    -->
    <active>ALWAYS</active>

    <!--
      icon:dot-circle[]
    -->
    <script>
      <!--
        Enable or disable all before, success, and failure hooks.
        Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
        Defaults to `ALWAYS`.
        icon:dot-circle[] icon:eye-slash[]
      -->
      <active>ALWAYS</active>

      <!--
        The type of hook
        Valid entries are `before`, `success`, `failure`.
        icon:dot-circle[]
      -->
      <before>
        <commandHook>
          <!--
            Let the release continue if the hook fails.
            Defaults to `false`.
            icon:dot-circle[]
          -->
          <continueOnError>true</continueOnError>

          <!--
            Print script out/err to log.
            Defaults to `false`.
            icon:dot-circle[]
          -->
          <verbose>true</verbose>

          <!--
            Enable or disable this hook.
            Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
            Defaults to `ALWAYS`.
            icon:dot-circle[] icon:eye-slash[]
          -->
          <active>ALWAYS</active>

          <!--
            Shell settings for executing the script.
            Supported values are [`BASH`, `SH`, `CMD`, `PWSH`, `POWERSHELL`].
            Defaults to `BASH`.
            icon:dot-circle[]
          -->
          <shell>BASH</shell>

          <!--
            The script to be invoked.
            icon:exclamation-triangle[] icon:file-alt[]
          -->
          <run>{{basedir}}/notifier.sh {{event.name}} {{event.type}} {{projectVersion}}</run>

          <!--
            Filters this hook based on the given step.
            icon:dot-circle[]
          -->
          <filter>
            <includes>release</include>
            <excludes>publish</excludes>
          </filter>

          <!--
            Filters this hook based on the current platform.
            Use a `!` prefix to exclude a platform
            icon:dot-circle[]
          -->
          <platforms>
            <platform>linux</platform>
            <platform>!windows</platform>
          </platforms>
        </commandHook>
      </before>
    </script>
  </hooks>
</jreleaser>
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros"]
----
jreleaser {
  // icon:dot-circle[]
  hooks {
    // Enable or disable all hooks.
    // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
    // Defaults to `ALWAYS`.
    // icon:dot-circle[] icon:eye-slash[]
    active = 'ALWAYS'

    // icon:dot-circle[]
    script {
      // Enable or disable all before, success, and failure hooks.
      // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
      // Defaults to `ALWAYS`.
      // icon:dot-circle[] icon:eye-slash[]
      active: ALWAYS

      // The type of hook
      // Valid entries are `before`, `success`, `failure`.
      // icon:dot-circle[]
      before {
        // Let the release continue if the hook fails.
        // Defaults to `false`.
        // icon:dot-circle[]
        continueOnError = true

        // Print script out/err to log.
        // Defaults to `false`.
        // icon:dot-circle[]
        verbose = true

        // Enable or disable this hook.
        // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
        // Defaults to `ALWAYS`.
        // icon:dot-circle[] icon:eye-slash[]
        active = 'ALWAYS'

        // Shell settings for executing the script.
        // Supported values are [`BASH`, `SH`, `CMD`, `PWSH`, `POWERSHELL`].
        // Defaults to `BASH`.
        // icon:dot-circle[]
        shell = 'BASH'

        // The script to be invoked.
        // icon:exclamation-triangle[] icon:file-alt[]
        run = "{{basedir}}/notifier.sh {{event.name}} {{event.type}} {{projectVersion}}"

        // Filters this hook based on the given step.
        // icon:dot-circle[]
        filter {
          includes = ["release"]
          excludes = ["publish"]
        }

        // Filters this hook based on the current platform.
        // Use a `!` prefix to exclude a platform
        // icon:dot-circle[]
        platform('linux')
        platform('!windows')
      }
    }
  }
}
----
--
====

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
2+| *active*
| jreleaser.hooks.script.active
| JRELEASER_HOOKS_SCRIPT_ACTIVE
|===

**Before hooks**
[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
2+| *active*
| jreleaser.hooks.script.before.${index}.active
| JRELEASER_HOOKS_SCRIPT_BEFORE_${index}_ACTIVE
|===

**Success hooks**
[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
2+| *active*
| jreleaser.hooks.script.success.${index}.active
| JRELEASER_HOOKS_SCRIPT_SUCCESS_${index}_ACTIVE
|===

**Failure hooks**
[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
2+| *active*
| jreleaser.hooks.script.failure.${index}.active
| JRELEASER_HOOKS_SCRIPT_FAILURE_${index}_ACTIVE
|===

== Step Names

The following step names may be used when filtering hooks:

* `download`
* `assemble`
* `changelog`
* `catalog`
* `checksum`
* `sign`
* `upload`
* `deploy`
* `release`
* `prepare`
* `package`
* `publish`
* `announce`

== Template Names

The following template names are also available:

[horizontal]
{{event.type}}:: One of [`before`, `success`, `failure`].
{{event.name}}:: One of the previously mentioned steps.

== Shell

The default shell is `BASH`. The shell command that is run internally executes a temporary file that contains the commands
specified in the `run` property. The following shell expressions will be used depending on the set value of the `shell`
property:

[%header, cols="<,<2,<2", width="100%"]
|===
| Shell | Description | Expression
| BASH
| JReleaser appends the extension `.sh` to the script name and substitutes for `{0}`
| `bash --noprofile --norc -eo pipefail {0}`
| SH
| JReleaser appends the extension `.sh` to the script name and substitutes for `{0}`
| `sh -e {0}`
| CMD
| The extension `.cmd` is appended to the script name and substitutes for `{0}`
| `%ComSpec% /D /E:ON /V:OFF /S /C "CALL "{0}""`
| PWSH
| The PowerShell Core. JReleaser appends the extension `.ps1` to the script name and substitutes for `{0}`
| `pwsh -command ". '{0}'"`
| POWERSHELL
| The PowerShell Desktop. JReleaser appends the extension `.ps1` to the script name and substitutes for `{0}`
| `powershell -command ". '{0}'"`
|===

== Fail Fast

`BASH` sets `set -eo pipefail` by default while `SH` does not. In `PWSH` and `POWERSHELL` JReleaser prepends
`$ErrorActionPreference = 'stop'` to script contents. It also appends `if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) { exit $LASTEXITCODE }`
 to powershell scripts to reflect the script's last exit code.

== Output

Command hooks have the option to provide key/value pairs as input for other steps in the current workflow. Simply
use `JRELEASER_OUTPUT:` as prefix in the script's output followed by `key=value`. For example, the following configuration
adds a key named `foo` with a value `bar` before the `changelog` step is invoked:

[source,yaml]
----
hooks:
  script:
    before:
      - filter:
          includes: [changelog]
        run: 'echo JRELEASER_OUTPUT:foo=bar'
----

