= Install

There are multiple choices depending on your preference.

== CLI
The xref:tools:cli.adoc[CLI] can be installed in the following ways:

[tabs]
====
Windows::
+
--
*scoop*:
[source]
----
scoop bucket add jreleaser https://github.com/jreleaser/scoop-bucket.git
scoop install jreleaser
----

*sdkman*
[source]
----
sdk install jreleaser
----

*jbang*
[source]
----
// Download, cache, and run
jbang jreleaser@jreleaser <args>
----

*manually*

Download the pre-compiled binary from the link:https://github.com/jreleaser/jreleaser/releases[releases page],
uncompress and copy to the desired location.
--
Linux::
+
--
*sdkman*
[source]
----
sdk install jreleaser
----

*jbang*
[source]
----
// Download, cache, and run
jbang jreleaser@jreleaser <args>
----

*manually*

Download the pre-compiled binary from the link:https://github.com/jreleaser/jreleaser/releases[releases page],
uncompress and copy to the desired location.
--
Mac::
+
--
*homebrew tap*
[source]
----
brew install jreleaser/tap/jreleaser
----

*sdkman*
[source]
----
sdk install jreleaser
----

*jbang*
[source]
----
// Download, cache, and run
jbang jreleaser@jreleaser <args>
----

*manually*

Download the pre-compiled binary from the link:https://github.com/jreleaser/jreleaser/releases[releases page],
uncompress and copy to the desired location.
--
====

== Maven
Configure the xref:tools:maven.adoc[jreleaser-maven-plugin] in your POM file

[source,xml]
[subs="verbatim,attributes"]
.pom.xml
----
<plugin>
  <groupId>org.jreleaser</groupId>
  <artifactId>jreleaser-maven-plugin</artifactId>
  <version>{jreleaser-version}</version>
</plugin>
----

== Gradle
Configure the xref:tools:gradle.adoc[jreleaser-gradle-plugin] in your `build.gradle` or `settings.gradle` file

[source,groovy]
[subs="attributes"]
.build.gradle
----
plugins {
    id 'org.jreleaser' version '{jreleaser-version}'
}
----

== Ant
Download the xref:tools:ant.adoc[jreleaser-ant-tasks] ZIP bundle from the
link:https://github.com/jreleaser/jreleaser/releases[releases page] and unzip it in your project. Place all JARs inside
the `lib` folder. Create this folder if there is none. Add the following elements to your `build.xml` file

[source,xml]
[subs="verbatim,attributes"]
.build.xml
----
<path id="jreleaser.classpath">
    <fileset dir="lib">
        <include name="jreleaser-ant-tasks-{jreleaser-version}/*.jar"/>
    </fileset>
</path>

<import>
  <javaresource name="org/jreleaser/ant/targets.xml"
                classpathref="jreleaser.classpath"/>
</import>
----

