= Sponsors

Do you or your company use JReleaser? You can help keep the project snappy and feature rich by sponsoring the project and its maintainers.

== GitHub Sponsors

GitHub Sponsors is a great way to contribute directly to the main maintainer, link:https://github.com/aalmiray[aalmiray].

This money usually goes to buying chocolate, better hardware, and, hopefully, one day, paying the bills.

++++
<iframe src="https://github.com/sponsors/aalmiray/button" title="Sponsor aalmiray" style="border: 0;" width="116" height="35"></iframe>
++++

You can sponsor and see who's sponsoring Andres link:https://github.com/sponsors/aalmiray[here].

== Patreon

Patreon is another way to contribute directly to the main maintainer, link:https://twitter.com/aalmiray[aalmiray].

Andres works and maintains a series of Open Source projects besides JReleaser. Money raised in this way will help him
get better tools to continue his work.

You can become Andres' patron link:https://www.patreon.com/join/aalmiray[here].

== OpenCollective

OpenCollective is a great way to send some money towards the JReleaser organization.

Funds will be used to buy/renew domains, keep servers up, print stickers and send swag among other things.

You can start sponsoring at the link:https://opencollective.com/jreleaser[JReleaser OpenCollective page].

== Sponsored Features

If you or your company require a feature and would like to pay for the work feel free to reach out to Andres on
Twitter (link:https://twitter.com/aalmiray[@aalmiray]), GitHub (link:https://github.com/aalmiray[aalmiray]).

icon:star[] Thank you for your support! icon:star[]
