= Publishing to Maven Central
:central_url:      pass:[https://central.sonatype.com/api/v1/publisher]
:deployer_url:     pass:[https://s01.oss.sonatype.org/service/local]
:deployer_old_url: pass:[https://oss.sonatype.org/service/local]
:deployer_snapshot_url: pass:[https://s01.oss.sonatype.org/content/repositories/snapshots/]

Maven Central is the defacto artifact repository for JVM based projects. Anyone can publish artifacts to it as long as
they follow the rules. Follow this link:https://central.sonatype.org/publish/publish-guide/[guide] to register an account.
You also must comply with all link:https://central.sonatype.org/publish/requirements/#review-requirements[requirements]
otherwise deployment will fail. Fortunately JReleaser can verify many of those requirements before any artifacts are
deployed.

IMPORTANT: Before continuing make sure that all artifacts to be deployed have been xref:maven/staging-artifacts.adoc[staged].
Missing this step will make the deployment phase fail! We recommend performing deployments from a *clean* state.

Maven Central requires artifacts to be signed with PGP. The xref:reference:deploy/maven/maven-central.adoc[] deployer
automatically enables `applyMavenCentralRules`. The xref:reference:deploy/maven/nexus2.adoc[] deployer
automatically enables `applyMavenCentralRules` when the publication url contains `oss.sonatype.org`. This setting
performs the following tasks:

- verify POMs comply with publication rules (using link:https://kordamp.org/pomchecker/pomchecker-cli/index.html[PomChecker]).
- assert that matching `-sources.jar` and `-javadoc.jar` artifacts have been staged (when applicable).
- calculate `md5`, `sha1`, `sha256`, and `sha512` checksums for all staged artifacts.
- sign all staged artifacts.

You have the option to close and release the staged repository automatically right after deployment, or keep the staged
repository open and perform close and release operations using the UI. You must login into Sonatype OSSRH using your
Sonatype account to do so.

== Different Work-flows

The Maven project has a long history and is going through some evolutions to create, upload, manage, and use Java libraries. As a result, there are two approaches to publish artifacts to the repository:

- Traditional OSSRH way, also known as the Maven Central Nexus Repository. The UI can be accessed via https://oss.sonatype.org.
- New API approach via the Maven Central Repository, creating a login and managing your artifacts can be done via https://central.sonatype.com/

=== Portal Publisher API

Publishing using the Portal Publisher API requires using the xref:reference:deploy/maven/maven-central.adoc[] deployer.

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
signing:
  active: ALWAYS
  armored: true

deploy:
  maven:
    mavenCentral:
      sonatype:
        active: ALWAYS
        url: {central_url}
        stagingRepositories:
          - target/staging-deploy
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
[signing]
  active = "ALWAYS"
  armored = true

[deploy.maven.mavenCentral.sonatype]
  active = "ALWAYS"
  url = "{central_url}"
  stagingRepositories = ["target/staging-deploy"]
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
{
  "jreleaser": {
    "signing": {
      "active": "ALWAYS",
      "armored": true
    },
    "deploy": {
      "maven": {
        "mavenCentral": {
          "sonatype": {
            "active": "ALWAYS",
            "url": "{central_url}",
            "stagingRepositories": [
              "target/staging-deploy"
            ]
          }
        }
      }
    }
  }
}
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
<jreleaser>
  <signing>
    <active>ALWAYS</active>
    <armored>true</armored>
  </signing>
  <deploy>
    <maven>
      <mavenCentral>
        <sonatype>
          <active>ALWAYS</active>
          <url>{central_url}</url>
          <stagingRepositories>target/staging-deploy</stagingRepositories>
        </sonatype>
      </mavenCentral>
    </maven>
  </deploy>
</jreleaser>
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
jreleaser {
  signing {
    active = 'ALWAYS'
    armored = true
  }
  deploy {
    maven {
      mavenCentral {
        sonatype {
          active = 'ALWAYS'
          url = '{central_url}'
          stagingRepository('target/staging-deploy')
        }
      }
    }
  }
}
----
--
====

=== OSSRH

Publishing to OSSRH requires using the xref:reference:deploy/maven/nexus2.adoc[] deployer.

NOTE: We recommend setting `releaseRepository` to `false` for the first time. This lets you review staged artifacts in the
Sonatype UI. You'll have to perform a manual release on the UI. Once you're happy with the settings and the release is
successful you may switch this property to `true`.

CAUTION: As described https://central.sonatype.org/publish/release/#login-into-ossrh[here], Sonatype projects created
before February 2021 may need to use "{deployer_old_url}" instead of "{deployer_url}". Using incorrect url may cause
a 'Could not find a staging profile matching ...' error.

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
signing:
  active: ALWAYS
  armored: true

deploy:
  maven:
    nexus2:
      maven-central:
        active: ALWAYS
        url: {deployer_url}
        snapshotUrl: {deployer_snapshot_url}
        closeRepository: true
        releaseRepository: false
        stagingRepositories:
          - target/staging-deploy
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
[signing]
  active = "ALWAYS"
  armored = true

[deploy.maven.nexus2.maven-central]
  active = "ALWAYS"
  url = "{deployer_url}"
  snapshotUrl = "{deployer_snapshot_url}"
  closeRepository = true
  releaseRepository = false
  stagingRepositories = ["target/staging-deploy"]
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
{
  "jreleaser": {
    "signing": {
      "active": "ALWAYS",
      "armored": true
    },
    "deploy": {
      "maven": {
        "nexus2": {
          "maven-central": {
            "active": "ALWAYS",
            "url": "{deployer_url}",
            "snapshotUrl": "{deployer_snapshot_url}",
            "closeRepository": true,
            "releaseRepository": false,
            "stagingRepositories": [
              "target/staging-deploy"
            ]
          }
        }
      }  
    }
  }
}
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
<jreleaser>
  <signing>
    <active>ALWAYS</active>
    <armored>true</armored>
  </signing>
  <deploy>
    <maven>
      <nexus2>
        <maven-central>
          <active>ALWAYS</active>
          <url>{deployer_url}</url>
          <snapshotUrl>{deployer_snapshot_url}</snapshotUrl>
          <closeRepository>true</closeRepository>
          <releaseRepository>false</releaseRepository>
          <stagingRepositories>target/staging-deploy</stagingRepositories>
        </maven-central>
      </nexus2>
    </maven>
  </deploy>
</jreleaser>
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
jreleaser {
  signing {
    active = 'ALWAYS'
    armored = true
  }
  deploy {
    maven {
      nexus2 {
        'maven-central' {
          active = 'ALWAYS'
          url = '{deployer_url}'
          snapshotUrl = '{deployer_snapshot_url}'
          closeRepository = true
          releaseRepository = false
          stagingRepository('target/staging-deploy')
        }
      }
    }
  }
}
----
--
====

The following secrets must be configured either using environment variables or the xref:reference:environment.adoc[secrets configuration]
file:

- `JRELEASER_GPG_PUBLIC_KEY`, unless `signing.verify` is set to `false`.
- `JRELEASER_GPG_SECRET_KEY`
- `JRELEASER_GPG_PASSPHRASE`

If using the xref:reference:deploy/maven/maven-central.adoc[] deployer:

- `JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME` or  `JRELEASER_MAVENCENTRAL_USERNAME`
- `JRELEASER_MAVENCENTRAL_SONATYPE_PASSWORD` or  `JRELEASER_MAVENCENTRAL_PASSWORD`

Alternatively, you may set these for link:https://central.sonatype.org/publish/generate-token/[token based authentication]:

- `JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME` or  `JRELEASER_MAVENCENTRAL_USERNAME`
- `JRELEASER_MAVENCENTRAL_SONATYPE_TOKEN` or  `JRELEASER_MAVENCENTRAL_TOKEN`

If using the xref:reference:deploy/maven/nexus2.adoc[] deployer:

- `JRELEASER_NEXUS2_MAVEN_CENTRAL_USERNAME` or  `JRELEASER_NEXUS2_USERNAME`
- `JRELEASER_NEXUS2_MAVEN_CENTRAL_PASSWORD` or  `JRELEASER_NEXUS2_PASSWORD`

Alternatively, you may set these for link:https://central.sonatype.org/publish/generate-token/[token based authentication]:

- `JRELEASER_NEXUS2_MAVEN_CENTRAL_USERNAME` or  `JRELEASER_NEXUS2_USERNAME`
- `JRELEASER_NEXUS2_MAVEN_CENTRAL_TOKEN` or  `JRELEASER_NEXUS2_TOKEN`

== Maven

The following `pom.xml` file shows the minimum required configuration

.pom.xml
[source,xml]
[subs="+macros,attributes,verbatim"]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.acme</groupId>
    <artifactId>app</artifactId>
    <version>1.0.0</version>

    <name>app</name>
    <description>Sample application</description>
    <url>pass:[https://github.com/aalmiray/app]</url>
    <inceptionYear>2021</inceptionYear>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>11</maven.compiler.release>
    </properties>

    <licenses>
        <license>
            <name>Apache-2.0</name>
            <url>pass:[https://spdx.org/licenses/Apache-2.0.html]</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>aalmiray</id>
            <name>Andres Almiray</name>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:https://github.com/aalmiray/app.git</connection>
        <developerConnection>scm:git:https://github.com/aalmiray/app.git</developerConnection>
        <url>pass:[https://github.com/aalmiray/app.git]</url>
        <tag>HEAD</tag>
    </scm>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>3.1.1</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.13.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>3.6.3</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>3.3.1</version>
                </plugin>
                <plugin>
                    <groupId>org.jreleaser</groupId>
                    <artifactId>jreleaser-maven-plugin</artifactId>
                    <version>{jreleaser-version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.jreleaser</groupId>
                <artifactId>jreleaser-maven-plugin</artifactId>
                <configuration>
                    <jreleaser>
                        <signing>
                            <active>ALWAYS</active>
                            <armored>true</armored>
                        </signing>
                        <deploy>
                            <maven>
                                <nexus2>
                                    <maven-central>
                                        <active>ALWAYS</active>
                                        <url>{deployer_url}</url>
                                        <snapshotUrl>{deployer_snapshot_url}</snapshotUrl>
                                        <closeRepository>true</closeRepository>
                                        <releaseRepository>true</releaseRepository>
                                        <stagingRepositories>target/staging-deploy</stagingRepositories>
                                    </maven-central>
                                </nexus2>
                                <!-- Portal Publisher API
                                <mavenCentral>
                                    <sonatype>
                                        <active>ALWAYS</active>
                                        <url>{central_url}</url>
                                        <stagingRepositories>target/staging-deploy</stagingRepositories>
                                    </sonatype>
                                </mavenCentral>
                                -->
                            </maven>
                        </deploy>
                    </jreleaser>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>publication</id>
            <properties>
                <altDeploymentRepository>local::file:./target/staging-deploy</altDeploymentRepository>
            </properties>
            <build>
                <defaultGoal>deploy</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                                <configuration>
                                    <attach>true</attach>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                                <configuration>
                                    <attach>true</attach>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
----

Store secrets in xref:reference:environment.adoc[~/.jreleaser/config.toml]. The TOML format is chosen as it allows multiline
strings which are required for defining both public and secret keys. You may opt instead to use the YAML format in which
case be aware of indentation or use environment variables.

.~/.jreleaser/config.toml
[source,toml]
----
JRELEASER_MAVENCENTRAL_USERNAME = "<your-publisher-portal-username>"
JRELEASER_MAVENCENTRAL_PASSWORD = "<your-publisher-portal-password>"
JRELEASER_NEXUS2_USERNAME = "<your-sonatype-account-username>"
JRELEASER_NEXUS2_PASSWORD = "<your-sonatype-account-password>"
JRELEASER_GPG_PASSPHRASE = "<your-pgp-passphrase>"

JRELEASER_GPG_PUBLIC_KEY="""-----BEGIN PGP PUBLIC KEY BLOCK-----

<contents-of-your-public-key>

-----END PGP PUBLIC KEY BLOCK-----"""

JRELEASER_GPG_SECRET_KEY="""-----BEGIN PGP PRIVATE KEY BLOCK-----

<contents-of-your-private-key>

-----END PGP PRIVATE KEY BLOCK-----"""
----

You may export public and private keys with the following commands:

[source]
----
$ gpg --output public.pgp --armor --export username@email
$ gpg --output private.pgp --armor --export-secret-key username@email
----

If you do not wish to configure public and private keys in the secrets configuration file you may directly refer to the
exported key files, in which case signing configuration should be updated to the following:

[source,xml]
[subs="+macros,attributes,verbatim"]
----
<jreleaser>
    <signing>
      <active>ALWAYS</active>
      <armored>true</armored>
      <mode>FILE</mode>
      <publicKey>path/to/public.pgp</publicKey>
      <secretKey>path/to/private.pgp</secretKey>
    </signing>
</jreleaser>
----

WARNING: DO NOT commit public and private key files to source control!

Once all configuration is in place you may execute the following commands:

1) Verify release & deploy configuration

[source]
----
$ mvn jreleaser:config
----

2) Ensure a clean deployment

[source]
----
$ mvn clean
----

3) Stage all artifacts to a local directory

[source]
----
$ mvn -Ppublication
----

4) Deploy and release

[source]
----
$ mvn jreleaser:full-release
----

== Gradle

The following `build.gradle` file shows the minimum required configuration

.build.gradle
[source,groovy]
[subs="+macros,attributes"]
----
plugins {
    id 'java-library'
    id 'maven-publish'
    id 'org.jreleaser' version '{jreleaser-version}'
}

java {
    withJavadocJar()
    withSourcesJar()
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'com.acme'
            artifactId = 'app'

            from components.java

            pom {
                name = 'app'
                description = 'Sample application'
                url = 'https://github.com/aalmiray/app'
                inceptionYear = '2021'
                licenses {
                    license {
                        name = 'Apache-2.0'
                        url = 'https://spdx.org/licenses/Apache-2.0.html'
                    }
                }
                developers {
                    developer {
                        id = 'aalmiray'
                        name = 'Andres Almiray'
                    }
                }
                scm {
                    connection = 'scm:git:https://github.com/aalmiray/app.git'
                    developerConnection = 'scm:git:ssh://github.com/aalmiray/app.git'
                    url = 'http://github.com/aalmiray/app'
                }
            }
        }
    }

    repositories {
        maven {
            url = layout.buildDirectory.dir('staging-deploy')
        }
    }
}

jreleaser {
    signing {
        active = 'ALWAYS'
        armored = true
    }
    deploy {
        maven {
            nexus2 {
                'maven-central' {
                    active = 'ALWAYS'
                    url = '{deployer_url}'
                    snapshotUrl = '{deployer_snapshot_url}'
                    closeRepository = true
                    releaseRepository = true
                    stagingRepository('build/staging-deploy')
                }
            }
            /* Portal Publisher API
            mavenCentral {
                sonatype {
                    active = 'ALWAYS'
                    url = '{central_url}'
                    stagingRepository('target/staging-deploy')
                }
            }
            */
        }
    }
}
----

Store secrets in xref:reference:environment.adoc[~/.jreleaser/config.toml]. The TOML format is chosen as it allows multiline
strings which are required for defining both public and secret keys. You may opt instead to use the YAML format in which
case be aware of indentation or use environment variables.

.~/.jreleaser/config.toml
[source,toml]
----
JRELEASER_MAVENCENTRAL_USERNAME = "<your-publisher-portal-username>"
JRELEASER_MAVENCENTRAL_PASSWORD = "<your-publisher-portal-password>"
JRELEASER_NEXUS2_USERNAME = "<your-sonatype-account-username>"
JRELEASER_NEXUS2_PASSWORD = "<your-sonatype-account-password>"
JRELEASER_GPG_PASSPHRASE = "<your-pgp-passphrase>"

JRELEASER_GPG_PUBLIC_KEY="""-----BEGIN PGP PUBLIC KEY BLOCK-----

<contents-of-your-public-key>

-----END PGP PUBLIC KEY BLOCK-----"""

JRELEASER_GPG_SECRET_KEY="""-----BEGIN PGP PRIVATE KEY BLOCK-----

<contents-of-your-private-key>

-----END PGP PRIVATE KEY BLOCK-----"""
----

You may export public and private keys with the following commands:

[source]
----
$ gpg --output public.pgp --armor --export username@email
$ gpg --output private.pgp --armor --export-secret-key username@email
----

If you do not wish to configure public and private keys in the secrets configuration file you may directly refer to the
exported key files, in which case signing configuration should be updated to the following:

.build.gradle
[source,groovy]
[subs="+macros,attributes"]
----
jreleaser {
    signing {
        active = 'ALWAYS'
        armored = true
        mode = 'FILE'
        publicKey = 'path/to/public.pgp'
        secretKey = 'path/to/private.pgp'
    }
}
----

WARNING: DO NOT commit public and private key files to source control!

Once all configuration is in place you may execute the following commands:

1) Verify release & deploy configuration

[source]
----
$ ./gradlew jreleaserConfig
----

2) Ensure a clean deployment

[source]
----
$ ./gradlew clean
----

3) Stage all artifacts to a local directory

[source]
----
$ ./gradlew publish
----

4) Deploy and release

[source]
----
$ ./gradlew jreleaserFullRelease
----
