= Publishing to Maven Central
:deployer_url:  https://s01.oss.sonatype.org/service/local
:deployer_old_url:  https://oss.sonatype.org/service/local

Maven Central is the defacto artifact repository for JVM based projects. Anyone can publish artifacts to it as long as
they follow the rules. Follow this link:https://central.sonatype.org/publish/publish-guide/[guide] to register an account.
You also must comply with all link:https://central.sonatype.org/publish/requirements/#review-requirements[requirements]
otherwise deployment will fail. Fortunately JReleaser can verify many of those requirements before any artifacts are
deployed.

Before continuing make sure that all artifacts to be deployed have been xref:maven/staging-artifacts.adoc[staged].

Maven Central requires artifacts to be signed with PGP. The xref:reference:deploy/maven/nexus2.adoc[] deployer
automatically enables `applyMavenCentralRules` when the publication url contains `oss.sonatype.org`. This setting
performs the following tasks:

- verify POMs comply with publication rules (using link:https://kordamp.org/pomchecker/pomchecker-cli/index.html[PomChecker]).
- assert that matching `-sources.jar` and `-javadoc.jar` artifacts have been staged (when applicable).
- calculate `md5`, `sha1`, `sha256`, and `sha512` checksums for all staged artifacts.
- sign all staged artifacts.

You have the option to close and release the staged repository automatically right after deployment, or keep the staged
repository open and perform close and release operations using the UI. You must login into Sonatype OSSRH using your
Sonatype account to do so.

CAUTION: As described https://central.sonatype.org/publish/release/#login-into-ossrh[here], Sonatype projects created before February 2021 may need to use "{deployer_old_url}" instead of "{deployer_url}". Using incorrect url may cause 'Could not find a staging profile matching ...' error.

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="attributes,+macros"]
----
signing:
  active: ALWAYS
  armored: true

deploy:
  maven:
    nexus2:
      maven-central:
        active: ALWAYS
        url: {deployer_url}
        closeRepository: true
        releaseRepository: true
        stagingRepositories:
          - target/staging-deploy
----
--
TOML::
+
--
[source,toml]
[subs="attributes,+macros"]
----
[signing]
  active = "ALWAYS"
  armored = true

[deploy.maven.nexus2.maven-central]
  active = "ALWAYS"
  url = "{deployer_url}"
  closeRepository = true
  releaseRepository = true
  stagingRepositories = ["target/staging-deploy"]
----
--
JSON::
+
--
[source,json]
[subs="attributes,+macros"]
----
{
  "jreleaser": {
    "signing": {
      "active": "ALWAYS",
      "armored": true
    },
    "deploy": {
      "maven": {
        "nexus2": {
          "maven-central": {
            "active": "ALWAYS",
            "url": "{deployer_url}",
            "closeRepository": true,
            "releaseRepository": true,
            "stagingRepositories": [
              "target/staging-deploy"
            ]
          }
        }
      }  
    }
  }
}
----
--
Maven::
+
--
[source,xml]
[subs="attributes,verbatim,+macros"]
----
<jreleaser>
  <signing>
    <active>ALWAYS</active>
    <armored>true</armored>
  </signing>
  <deploy>
    <maven>
      <nexus2>
        <maven-central>
          <active>ALWAYS</active>
          <url>{deployer_url}</url>
          <closeRepository>true</closeRepository>
          <releaseRepository>true</releaseRepository>
          <stagingRepositories>target/staging-deploy</stagingRepositories>
        </maven-central>
      </nexus2>
    </maven>
  </deploy>
</jreleaser>
----
--
Gradle::
+
--
[source,groovy]
[subs="attributes,+macros"]
----
jreleaser {
  signing {
    active = 'ALWAYS'
    armored = true
  }
  deploy {
    maven {
      nexus2 {
        maven-central {
          active = 'ALWAYS'
          url = '{deployer_url}'
          closeRepository = true
          releaseRepository = true
          stagingRepository('target/staging-deploy')
        }
      }
    }
  }
}
----
--
====

The following secrets must be configured either using environment variables or the xref:reference:environment.adoc[secrets configuration]
file:

- `JRELEASER_GPG_PUBLIC_KEY`
- `JRELEASER_GPG_SECRET_KEY`
- `JRELEASER_GPG_PASSPHRASE`
- `JRELEASER_NEXUS2_MAVEN_CENTRAL_PASSWORD` or  `JRELEASER_NEXUS2_USERNAME`
