= Assemble

Some distribution types may be assembled by JReleaser.

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros"]
----
# icon:dot-circle[]
assemble:
  # Enable or disable all configured assemblers.
  # Valid values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
  # Defaults to `ALWAYS`.
  # icon:dot-circle[]
  active: ALWAYS
----
--
TOML::
+
--
[source,toml]
[subs="+macros"]
----
# icon:dot-circle[]
[assemble]

  # Enable or disable all configured assemblers.
  # Valid values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
  # Defaults to `ALWAYS`.
  # icon:dot-circle[]
  active = "ALWAYS"
----
--
JSON::
+
--
[source,json]
[subs="+macros"]
----
{
  // icon:dot-circle[]
  "assemble": {
    // Enable or disable all configured assemblers.
    // Valid values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
    // Defaults to `ALWAYS`.
    // icon:dot-circle[]
    "active": "ALWAYS"
  }
}
----
--
Maven::
+
--
[source,xml]
[subs="verbatim,+macros"]
----
<jreleaser>
  <!--
    icon:dot-circle[]
  -->
  <assemble>
    <!--
      Enable or disable all configured assemblers.
      Valid values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
      Defaults to `ALWAYS`.
      icon:dot-circle[]
    -->
    <active>ALWAYS</active>
  </assemble>
</jreleaser>
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros"]
----
jreleaser {
  // icon;dot-circle[]
  assemble {
    // Enable or disable all configured assemblers.
    // Valid values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
    // Defaults to `ALWAYS`.
    // icon:dot-circle[]
    active = 'ALWAYS'
  }
}
----
--
====


Assemblers will configure a matching distribution by name if it exists and if the assembler exports its artifacts
(`true` by default), otherwise they'll create a new distribution with their respective name. Assemblers may configure
the following distribution properties:

 * active
 * artifacts
 * extraProperties
 * java
 * executable

You may skip resolving outputs for all assemblers or assemblers per type by defining any of the following properties
with a `true` value inside xref:configuration:environment.adoc[] properties or as a property on the command line:

* `skipAssembleResolvers`
* `skipArchiveResolver`
* `skipJlinkResolver`
* `skipJpackageResolver`
* `skipNativeImageResolver`
