= CycloneDX
:cataloger_id:   cyclonedx
:cataloger_name: Cyclonedx
:cataloger_sys_key: cyclonedx
:cataloger_env_key: CYCLONEDX

Generates SBOMs using link:https://github.com/CycloneDX/cyclonedx-cli[CycloneDX]. Multiple formats may be used at the same time.

Catalogs may be xref:checksum.adoc[checksumed] and xref:signing.adoc[signed] when packed.

Individual and/or packed catalogs may be xref:upload/index.adoc[uploaded] and xref:release/index.adoc[released].

WARNING: Snapshots are *not* allowed.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$catalog/sbom/yaml/common-head.adoc[]

        # Version of tool to use.
        # If unspecified, will use {syft-version}.
        # icon:dot-circle[]
        version: {cyclonedx-version}

        # Target SBOM format(s).
        # If unspecified, [`JSON`].
        # icon:dot-circle[]
        formats:
          - JSON
          - XML
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$catalog/sbom/toml/common-head.adoc[]

  # Version of tool to use.
  # If unspecified, will use {syft-version}.
  # icon:dot-circle[]
  version = "{cyclonedx-version}"

  # Target SBOM format(s).
  # If unspecified, [`JSON`].
  # icon:dot-circle[]
  formats = ["JSON", "XML"]
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$catalog/sbom/json/common-head.adoc[]

          // Version of tool to use.
          // If unspecified, will use {syft-version}.
          // icon:dot-circle[]
          "version": "{cyclonedx-version}",

          // Target SBOM format(s).
          // If unspecified, [`JSON`].
          // icon:dot-circle[]
          "formats": [
            "JSON",
            "XML"
          ]
include::partial$catalog/sbom/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$catalog/sbom/maven/common-head.adoc[]

          <!--
            Version of tool to use.
            If unspecified, will use {syft-version}.
            icon:dot-circle[]
          -->
          <version>{cyclonedx-version}</version>

          <!--
            Target SBOM format(s).
            If unspecified, [`JSON`].
            icon:dot-circle[]
          -->
          <formats>
            <format>JSON</format>
            <format>XML</format>
          </formats>
include::partial$catalog/sbom/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$catalog/sbom/gradle/common-head.adoc[]

          // Version of tool to use.
          // If unspecified, will use {syft-version}.
          // icon:dot-circle[]
          version = '{cyclonedx-version}'

          // Target SBOM format(s).
          // If unspecified, [`JSON`].
          // icon:dot-circle[]
          format('JSON')
          format('XML')
include::partial$catalog/sbom/gradle/common-footer.adoc[]
----
--
====

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
include::partial$catalog/sbom/envvars.adoc[]
|===

== Formats

The {cataloger_name} cataloger supports the following formats:

 - `JSON`
 - `XML`
 - `PROTOBUF`

== Skip Cataloging

Distributions and artifacts may define extra properties that may stop them from being cataloged. These properties must
conform to the following rules:

* `skipSbom`: skipped from all catalogers.
* `skipSbomCyclonedx`: skipped from this cataloger.
