= Artifactory
:uploader_id:   artifactory
:uploader_name: Artifactory
:upload_url:    pass:[https://duke.jfrog.io/artifactory/binaries/{{projectName}}/{{projectVersion}}/{{artifactFile}}]
:uploader_sys_key: artifactory
:uploader_env_key: ARTIFACTORY
:group_sys_key: upload
:group_env_key: UPLOAD
:actor_sys_key: {uploader_sys_key}
:actor_env_key: {uploader_env_key}

Uploads artifacts, files, and signatures to a link:https://jfrog.com/artifactory/[JFrog {uploader_name}] instance.

.Prerequisites:

 * A running Artifactory instance.
 * A generic repository.
 * A user + password / token with grants to upload an artifact.

IMPORTANT: This feature *does not* support deploying JARs and POMs to a Maven repository.

TIP: You may use this uploader with link:https://www.sonatype.com[Sonatype] Nexus as well, just configure the right host,
credentials, and path matching your settings.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$upload/yaml/common-head.adoc[]

      # URL of the Artifactory host.
      # icon:exclamation-triangle[] icon:file-alt[]
      host: pass:[https://host.com/artifactory]

      # The username that can write to the repository.
      # icon:exclamation-triangle[] icon:eye-slash[]
      username: __USE_ENVIRONMENT_VARIABLE__

      # Password for login into the repository.
      # icon:exclamation-triangle[] icon:eye-slash[]
      password: __USE_ENVIRONMENT_VARIABLE__

      # The authorization method to use.
      # Supported values are [`BASIC`, `BEARER`].
      # `Basic` requires both username & password.
      # `BEARER` requires a token (set as password).
      # Defaults to `BEARER`.
      # icon:dot-circle[]
      authorization: BASIC
      
      # List of repositories where artifacts will be uploaded.
      # icon:exclamation-triangle[]
      repositories:

          # Path where the artifact will be uploaded to.
          # icon:exclamation-triangle[] icon:eye-slash[]
        - path: 'binaries/{{projectName}}/{{projectVersion}}/{{artifactFile}}'

          # Enables or disables the repository.
          # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
          # Defaults to the active setting of the containing artifactory.
          # icon:dot-circle[]
          active: ALWAYS

          # Set of supported file types.
          # icon:dot-circle[]
          fileTypes:
            - ZIP
            - TGZ
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$upload/toml/common-head.adoc[]

  # URL of the Artifactory host.
  # icon:exclamation-triangle[] icon:file-alt[]
  host = "pass:[https://host.com/artifactory]"

  # The username that can write to the repository.
  # icon:exclamation-triangle[] icon:eye-slash[]
  username = "__USE_ENVIRONMENT_VARIABLE__"

  # Password for login into the repository.
  # icon:exclamation-triangle[] icon:eye-slash[]
  password = "__USE_ENVIRONMENT_VARIABLE__"

  # The authorization method to use.
  # Supported values are [`BASIC`, `BEARER`].
  # `Basic` requires both username & password.
  # `BEARER` requires a token (set as password).
  # Defaults to `BEARER`.
  # icon:dot-circle[]
  authorization = "BASIC"

  # List of repositories where artifacts will be uploaded.
  # icon:exclamation-triangle[]
  pass:[[[upload.artifactory.app.repositories]]]

    # Path where the artifact will be uploaded to.
    # icon:exclamation-triangle[] icon:eye-slash[]
    path = "binaries/{{projectName}}/{{projectVersion}}/{{artifactFile}}"

   # Enables or disables the uploader.
   # Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
   # Defaults to the active setting of the containing artifactory.
   # icon:dot-circle[]
   active = "ALWAYS"

    # Set of supported file types.
    # icon:dot-circle[]
    fileTypes = ["ZIP", "TGZ"]
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$upload/json/common-head.adoc[]

        // URL of the Artifactory host.
        // icon:exclamation-triangle[] icon:file-alt[]
        "host": "pass:[https://host.com/artifactory]",

        // The username that can write to the repository.
        // icon:exclamation-triangle[] icon:eye-slash[]
        "username": "__USE_ENVIRONMENT_VARIABLE__",

        // Password for login into the repository.
        // icon:exclamation-triangle[] icon:eye-slash[]
        "password": "__USE_ENVIRONMENT_VARIABLE__",

        // The authorization method to use.
        // Supported values are [`BASIC`, `BEARER`].
        // `Basic` requires both username & password.
        // `BEARER` requires a token (set as password).
        // Defaults to `BEARER`.
        // icon:dot-circle[]
        "authorization": "BEARER",

        // List of repositories where artifacts will be uploaded.
        // icon:exclamation-triangle[]
        "repositories": [
          {
            // Path where the artifact will be uploaded to.
            // icon:exclamation-triangle[] icon:eye-slash[]
            "path": "binaries/{{projectName}}/{{projectVersion}}/{{artifactFile}}",

            // Enables or disables the uploader.
            // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
            // Defaults to the active setting of the containing artifactory.
            // icon:dot-circle[]
            "active": "ALWAYS",

            // Set of supported file types.
            // icon:dot-circle[]
            "fileTypes": [
              "ZIP",
              "TGZ"
             ]
          }
        ]
include::partial$upload/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$upload/maven/common-head.adoc[]

        <!--
          URL of the Artifactory host.
          icon:exclamation-triangle[] icon:file-alt[]
        -->
        <host>pass:[https://host.com/artifactory]</host>

        <!--
          The username that can write to the repository.
          icon:exclamation-triangle[] icon:eye-slash[]
        -->
        <username>__USE_ENVIRONMENT_VARIABLE__</username>

        <!--
          Password for login into the repository.
          icon:exclamation-triangle[] icon:eye-slash[]
        -->
        <password>__USE_ENVIRONMENT_VARIABLE__</password>

        <!--
          The authorization method to use.
          Supported values are [`BASIC`, `BEARER`].
          `Basic` requires both username & password.
          `BEARER` requires a token (set as password).
          Defaults to `BEARER`.
          icon:dot-circle[]
        -->
        <authorization>BEARER</authorization>

        <!--
          List of repositories where artifacts will be uploaded.
          icon:exclamation-triangle[]
        -->
        <repositories>
          <repository>

          <!--
            Path where the artifact will be uploaded to.
            icon:exclamation-triangle[] icon:eye-slash[]
          -->
          <path>binaries/{{projectName}}/{{projectVersion}}/{{artifactFile}}</path>

          <!--
            Enables or disables the distribution.
            Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
            Defaults to the active setting of the containing artifactory.
            icon:dot-circle[]
          -->
          <active>ALWAYS</active>

          <!--
            Set of supported file types.
            icon:dot-circle[]
          -->
          <fileTypes>ZIP,TGZ</fileTypes>
          </repository>
        </repositories>
include::partial$upload/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$upload/gradle/common-head.adoc[]

        // URL of the Artifactory host.
        // icon:exclamation-triangle[] icon:file-alt[]
        host = 'pass:[https://host.com/artifactory]'

        // The username that can write to the repository.
        // icon:exclamation-triangle[] icon:eye-slash[]
        username = '__USE_ENVIRONMENT_VARIABLE__'

        // Password for login into the repository.
        // icon:exclamation-triangle[] icon:eye-slash[]
        password = '__USE_ENVIRONMENT_VARIABLE__'

        // The authorization method to use.
        // Supported values are [`BASIC`, `BEARER`].
        // `Basic` requires both username & password.
        // `BEARER` requires a token (set as password).
        // Defaults to `BEARER`.
        // icon:dot-circle[]
        authorization = 'BEARER'

        // List of repositories where artifacts will be uploaded.
        // icon:exclamation-triangle[]
        repository {
          // Path where the artifact will be uploaded to.
          // icon:exclamation-triangle[] icon:eye-slash[]
          path = 'binaries/{{projectName}}/{{projectVersion}}/{{artifactFile}}'

          // Enables or disables the uploader.
          // Supported values are [`NEVER`, `ALWAYS`, `RELEASE`, `SNAPSHOT`].
          // Defaults to the active setting of the containing artifactory.
          // icon:dot-circle[]
          active = 'ALWAYS'

          // Set of supported file types.
          // icon:dot-circle[]
          fileType = 'ZIP'
          fileType = 'TGZ'
include::partial$upload/gradle/common-footer.adoc[]
----
--
====

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1,<1", width="100%"]
|===
| Property | System Property | Environment Variable
include::partial$named-envvars/active.adoc[]
include::partial$named-envvars/host.adoc[]
include::partial$named-envvars/username.adoc[]
include::partial$named-envvars/password.adoc[]
|===

include::partial$envvars-footer.adoc[]

== File Types

Supported files types are:

 * `DEB`
 * `DMG`
 * `EXE`
 * `JAR`
 * `MSI`
 * `NUGET`
 * `PKG`
 * `RPM`
 * `TAR`
 * `TAR_BZ2`
 * `TAR_GZ`
 * `TAR_XZ`
 * `TAR_ZST`
 * `TBZ2`
 * `TGZ`
 * `TXZ`
 * `ZIP`

If a repository does not define any file types then all file types are accepted.

== Skip Upload

Distributions and Artifacts may define extra properties that may stop them from being uploaded. These properties must
conform to the following rules:

* `skipUpload`: skipped from all uploaders.
* `skipUpload<type>`: skipped from the typed uploader.
* `skipUpload<type><name>`: skipped from the typed and named uploader.

Where `<type>` resolves to `Artifactory` and `<name>` resolves to the capitalized name of the artifactory instance, such
that:

* if the name is `foo` the resulting property key is `skipUploadArtifactoryFoo`.
* if the name is `fooBar` the resulting property key is `skipUploadArtifactoryFooBar`.
* if the name is `foo-bar` the resulting property key is `skipUploadArtifactoryFooBar`.

== Example

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
upload:
  artifactory:
    duke:
      active: ALWAYS
      host: 'pass:[https://host.com/artifactory]'
      repository:
        - path: 'binaries/{{projectName}}/{{projectVersion}}/{{artifactFile}}'
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
[upload.artifactory.duke]
  active = "ALWAYS"
  host = "pass:[https://host.com/artifactory]"
  pass:[[[upload.artifactory.duke.repositories]]]
    path = "binaries/{{projectName}}/{{projectVersion}}/{{artifactFile}}"
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
{
  "jreleaser": {
    "upload": {
      "artifactory": {
        "duke": {
          "active": "ALWAYS",
          "host": "pass:[https://host.com/artifactory]",
          "repositories": [
            {
              "path": "binaries/{{projectName}}/{{projectVersion}}/{{artifactFile}}"
            }
          ]
        }
      }
    }
  }
}
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
<jreleaser>
  <upload>
    <artifactory>
      <duke>
        <active>ALWAYS</active>
        <host>pass:[https://host.com/artifactory]</host>
        <repositories>
          <repository>
            <path>binaries/{{projectName}}/{{projectVersion}}/{{artifactFile}}</path>
          </repository>
        </repositories>
      </duke>
    </artifactory>
  </upload>
</jreleaser>
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
jreleaser {
  upload {
    artifactory {
      duke {
        active = 'ALWAYS'
        host = 'pass:[https://host.com/artifactory]'
        repository {
          path = "binaries/{{projectName}}/{{projectVersion}}/{{artifactFile}}"
        }
      }
    }
  }
}
----
--
====

The following environment variables must be defined:

* `JRELEASER_ARTIFACTORY_DUKE_USERNAME`
* `JRELEASER_ARTIFACTORY_DUKE_PASSWORD`

