= Http
:uploader_id:   http
:uploader_name: HTTP

Uploads artifacts, files, and signatures to an {uploader_name}/HTTPS server.

.Prerequisites:

 * A HTTP/HTTPS server that accepts POST/PUT requests.
 * Username + Password/Token if authorization is required.

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="attributes,+macros"]
----
include::partial$upload/yaml/common-head.adoc[]

      # URL of the HTTP/HTTPS server + path + artifact.
      # icon:exclamation-triangle[] icon:file-alt[]
      uploadUrl: pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFile}}]

      # URL of the HTTP/HTTPS server + path + artifact.
      # If undefined, will use the same value as `uploadUrl`.
      # icon:exclamation-triangle[] icon:file-alt[]
      downloadUrl: pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFile}}]

include::partial$upload/yaml/upa.adoc[]

      # The method to use for uploading artifacts.
      # Supported values are [`POST`, `PUT`].
      # Defaults to `PUT`.
      # icon:dot-circle[]
      method: POST

      # Additional headers to be sent to the server.
      # Values accept xref:reference:name-templates.adoc[].
      # icon:dot-circle[] icon:file-alt[]
      headers:
        'X-ARTIFACT-PLATFORM': '{{artifactPlatform}}'
----
--
TOML::
+
--
[source,toml]
[subs="attributes,+macros"]
----
include::partial$upload/toml/common-head.adoc[]

  # URL of the HTTP/HTTPS server + path + artifact.
  # icon:exclamation-triangle[] icon:file-alt[]
  uploadUrl = "pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFile}}]"

  # URL of the HTTP/HTTPS server + path + artifact.
  # If undefined, will use the same value as `uploadUrl`.
  # icon:exclamation-triangle[] icon:file-alt[]
  downloadUrl = "pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFile}}]"

include::partial$upload/toml/upa.adoc[]

  # The method to use for uploading artifacts.
  # Supported values are [`POST`, `PUT`].
  # Defaults to `PUT`.
  # icon:dot-circle[]
  method = "POST"

  # Additional headers to be sent to the server.
  # Values accept xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  headers."X-ARTIFACT-PLATFORM" = "{{artifactPlatform}}"
----
--
JSON::
+
--
[source,json]
[subs="attributes,+macros"]
----
include::partial$upload/json/common-head.adoc[]

        // URL of the HTTP/HTTPS server + path + artifact.
        // icon:exclamation-triangle[] icon:file-alt[]
        "uploadUrl": "pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFile}}]",

        // URL of the HTTP/HTTPS server + path + artifact.
        // If undefined, will use the same value as `uploadUrl`.
        // icon:exclamation-triangle[] icon:file-alt[]
        "downloadUrl": "pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFile}}]",

include::partial$upload/json/upa.adoc[]

        // The method to use for uploading artifacts.
        // Supported values are [`POST`, `PUT`].
        // Defaults to `PUT`.
        // icon:dot-circle[]
        "method": "POST",

        // Additional headers to be sent to the server.
        // Values accept xref:reference:name-templates.adoc[].
        // icon:dot-circle[] icon:file-alt[]
        "headers": {
          "X-ARTIFACT-PLATFORM": "{{artifactPlatform}}"
        }
include::partial$upload/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="attributes,verbatim,+macros"]
----
include::partial$upload/maven/common-head.adoc[]

        <!--
          URL of the HTTP/HTTPS server + path + artifact.
          icon:exclamation-triangle[] icon:file-alt[]
        -->
        <uploadUrl>pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFile}}]</uploadUrl>

        <!--
          URL of the HTTP/HTTPS server + path + artifact.
          If undefined, will use the same value as `uploadUrl`.
          icon:exclamation-triangle[] icon:file-alt[]
        -->
        <downloadUrl>pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFile}}]</downloadUrl>

include::partial$upload/maven/upa.adoc[]

        <!--
          The method to use for uploading artifacts.
          Supported values are [`POST`, `PUT`].
          Defaults to `PUT`.
          icon:dot-circle[]
        -->
        <method>POST</method>

        <!--
          Additional headers to be sent to the server.
          Values accept xref:reference:name-templates.adoc[].
          icon:dot-circle[] icon:file-alt[]
        -->
        <headers>
          <X-ARTIFACT-PLATFORM>{{artifactPlatform}}</X-ARTIFACT-PLATFORM>
        </headers>
include::partial$upload/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="attributes,+macros"]
----
include::partial$upload/gradle/common-head.adoc[]

        // URL of the HTTP/HTTPS server + path + artifact.
        // icon:exclamation-triangle[] icon:file-alt[]
        uploadUrl = 'pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFile}}]'

        // URL of the HTTP/HTTPS server + path + artifact.
        // If undefined, will use the same value as `uploadUrl`.
        // icon:exclamation-triangle[] icon:file-alt[]
        downloadUrl = 'pass:[https://my.server.com/{{projectName}}/{{tagName}}/{{artifactFile}}]'

include::partial$upload/gradle/upa.adoc[]

        // The method to use for uploading artifacts.
        // Supported values are [`POST`, `PUT`].
        // Defaults to `PUT`.
        // icon:dot-circle[]
        method = 'POST'

        // Additional headers to be sent to the server.
        // Values accept xref:reference:name-templates.adoc[].
        // icon:dot-circle[] icon:file-alt[]
        headers.put('X-ARTIFACT-PLATFORM', '{{artifactPlatform}}')
include::partial$upload/gradle/common-footer.adoc[]
----
--
====

include::partial$http/username.adoc[]

include::partial$http/password.adoc[]

== UploadUrl

The uploadUrl is the URL to upload the artifacts to.

An example configuration may look like
`uploadUrl: 'https://artifacts.company.com:8081/upload/{{projectName}}/{{tagName}}/{{artifactFile}}'`.

And will result in a final deployment like
`pass:[https://artifacts.company.com:8081/upload/app/v1.0.0/app-1.0.0.zip]`.

== DownloadUrl

The downloadUrl is the URL used to download artifacts from.

An example configuration may look like
`downloadUrl: 'https://artifacts.company.com:8081/upload/{{projectName}}/{{tagName}}/{{artifactFile}}'`.

And will result in a final URL like
`pass:[https://artifacts.company.com:8081/upload/app/v1.0.0/app-1.0.0.zip]`.

== Skip Upload

Distributions and Artifacts may define extra properties that may stop them from being uploaded. These properties must
conform to the following rules:

* `skipUpload`: skipped from all uploaders.
* `skipUpload<type>`: skipped from the typed uploader.
* `skipUpload<type><name>`: skipped from the typed and named uploader.

Where `<type>` resolves to `Http` and `<name>` resolves to the capitalized name of the http instance, such
that:

* if the name is `foo` the resulting property key is `skipUploadHttpFoo`.
* if the name is `fooBar` the resulting property key is `skipUploadHttpFooBar`.
* if the name is `foo-bar` the resulting property key is `skipUploadHttpFooBar`.

