= AWS S3
:uploader_id:   s3
:uploader_name: AWS S3
:uploader_sys_key: s3
:uploader_env_key: S3
:group_sys_key: upload
:group_env_key: UPLOAD
:actor_sys_key: {uploader_sys_key}
:actor_env_key: {uploader_env_key}

Uploads artifacts, files, and signatures to an {uploader_name} bucket.

.Prerequisites:

 * An AWS account with S3 access.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$upload/yaml/common-head.adoc[]

      # The region where the S3 bucket is located.
      # icon:exclamation-triangle[] icon:eye-slash[]
      region: us-east-2

      # The name of the bucket.
      # icon:exclamation-triangle[] icon:eye-slash[]
      bucket: releases

      # The artifact path within the bucket.
      # icon:dot-circle[] icon:file-alt[] icon:eye-slash[]
      path: '{{projectName}}/{{tagName}}/{{artifactFile}}'

      # Custom download URL.
      # Required if a custom endpoint is defined.
      # icon:dot-circle[] icon:file-alt[] icon:eye-slash[]
      downloadUrl: 'pass:[https://{{bucket}}.s3.{{region}}.amazonaws.com/{{projectName}}/{{tagName}}/{{artifactFile}}]'

      # The accessKeyId required for authorization.
      # icon:dot-circle[] icon:eye-slash[]
      accessKeyId: __USE_ENVIRONMENT_VARIABLE__

      # The secretKey required for authorization.
      # icon:dot-circle[] icon:eye-slash[]
      secretKey: __USE_ENVIRONMENT_VARIABLE__

      # The AWS sessionToken when you use temporal credentials.
      # icon:dot-circle[] icon:eye-slash[]
      sessionToken: __USE_ENVIRONMENT_VARIABLE__
      
      # The endpoint to use for S3 service in case some other S3 compatible service is used.
      # icon:dot-circle[] icon:eye-slash[]
      endpoint: 's3.{{region}}.example.com'
      
      # Additional headers to be sent to the server.
      # Values accept xref:reference:name-templates.adoc[].
      # icon:dot-circle[] icon:file-alt[]
      headers:
        'X-ARTIFACT-PLATFORM': '{{artifactPlatform}}'
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$upload/toml/common-head.adoc[]

  # The region where the S3 bucket is located.
  # icon:exclamation-triangle[] icon:eye-slash[]
  region = "us-east-2"

  # The name of the bucket.
  # icon:exclamation-triangle[] icon:eye-slash[]
  bucket = "releases"

  # The artifact path within the bucket.
  # icon:dot-circle[] icon:file-alt[] icon:eye-slash[]
  path = "{{projectName}}/{{tagName}}/{{artifactFile}}"

  # Custom download URL.
  # Required if a custom endpoint is defined.
  # icon:dot-circle[] icon:file-alt[] icon:eye-slash[]
  downloadUrl = "pass:[https://{{bucket}}.s3.{{region}}.amazonaws.com/{{projectName}}/{{tagName}}/{{artifactFile}}]"

  # The accessKeyId required for authorization.
  # icon:dot-circle[] icon:eye-slash[]
  accessKeyId = "__USE_ENVIRONMENT_VARIABLE__"

  # The secretKey required for authorization.
  # icon:dot-circle[] icon:eye-slash[]
  secretKey = "__USE_ENVIRONMENT_VARIABLE__"

  # The AWS sessionToken when you use temporal credentials.
  # icon:dot-circle[] icon:eye-slash[]
  sessionToken = "__USE_ENVIRONMENT_VARIABLE__"

  # The endpoint to use for S3 service in case some other S3 compatible service is used.
  # icon:dot-circle[] icon:eye-slash[]
  endpoint = "s3.{{region}}.example.com"

  # Additional headers to be sent to the server.
  # Values accept xref:reference:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  headers."X-ARTIFACT-PLATFORM" = "{{artifactPlatform}}"
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$upload/json/common-head.adoc[]

        // The region where the S3 bucket is located.
        // icon:exclamation-triangle[] icon:eye-slash[]
        "region": "us-east-2",

        // The name of the bucket.
        // icon:exclamation-triangle[] icon:eye-slash[]
        "bucket": "releases",

        // The artifact path within the bucket.
        // icon:dot-circle[] icon:file-alt[] icon:eye-slash[]
        "path": "{{projectName}}/{{tagName}}/{{artifactFile}}",

        // Custom download URL.
        // Required if a custom endpoint is defined.
        // icon:dot-circle[] icon:file-alt[] icon:eye-slash[]
        "downloadUrl": "pass:[https://{{bucket}}.s3.{{region}}.amazonaws.com/{{projectName}}/{{tagName}}/{{artifactFile}}]",

        // The accessKeyId required for authorization.
        // icon:dot-circle[] icon:eye-slash[]
        "accessKeyId": "__USE_ENVIRONMENT_VARIABLE__",

        // The secretKey required for authorization.
        // icon:dot-circle[] icon:eye-slash[]
        "secretKey": "__USE_ENVIRONMENT_VARIABLE__",

        // The AWS sessionToken when you use temporal credentials.
        // icon:dot-circle[] icon:eye-slash[]
        "sessionToken": "__USE_ENVIRONMENT_VARIABLE__",
        
        // The endpoint to use for S3 service in case some other S3 compatible service is used.
        // icon:dot-circle[] icon:eye-slash[]
        "endpoint": "s3.{{region}}.example.com",
        
        // Additional headers to be sent to the server.
        // Values accept xref:reference:name-templates.adoc[].
        // icon:dot-circle[] icon:file-alt[]
        "headers": {
          "X-ARTIFACT-PLATFORM": "{{artifactPlatform}}"
        }
include::partial$upload/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$upload/maven/common-head.adoc[]

        <!--
          The region where the S3 bucket is located.
          icon:exclamation-triangle[] icon:eye-slash[]
        -->
        <region>us-east-2</region>

        <!--
          The name of the bucket.
          icon:exclamation-triangle[] icon:eye-slash[]
        -->
        <bucket>releases</bucket>

        <!--
          The artifact path within the bucket.
          icon:dot-circle[] icon:file-alt[] icon:eye-slash[]
        -->
        <path>{{projectName}}/{{tagName}}/{{artifactFile}}</path>

        <!--
          Custom download URL.
          Required if a custom endpoint is defined.
          icon:dot-circle[] icon:file-alt[] icon:eye-slash[]
        -->
        <downloadUrl>pass:[https://{{bucket}}.s3.{{region}}.amazonaws.com/{{projectName}}/{{tagName}}/{{artifactFile}}]</downloadUrl>

        <!--
          The accessKeyId required for authorization.
          icon:dot-circle[] icon:eye-slash[]
        -->
        <accessKeyId>__USE_ENVIRONMENT_VARIABLE__</accessKeyId>

        <!--
          The secretKey required for authorization.
          icon:dot-circle[] icon:eye-slash[]
        -->
        <secretKey>__USE_ENVIRONMENT_VARIABLE__</secretKey>

        <!--
          The AWS sessionToken when you use temporal credentials.
          icon:dot-circle[] icon:eye-slash[]
        -->
        <sessionToken>__USE_ENVIRONMENT_VARIABLE__</sessionToken>
        
        <!--
          The endpoint to use for S3 service in case some other S3 compatible service is used.
          icon:dot-circle[] icon:eye-slash[]
        -->
        <endpoint>s3.{{region}}.example.com</endpoint>
        
        <!--
          Additional headers to be sent to the server.
          Values accept xref:reference:name-templates.adoc[].
          icon:dot-circle[] icon:file-alt[]
        -->
        <headers>
          <X-ARTIFACT-PLATFORM>{{artifactPlatform}}</X-ARTIFACT-PLATFORM>
        </headers>
include::partial$upload/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$upload/gradle/common-head.adoc[]

        // The region where the S3 bucket is located.
        // icon:exclamation-triangle[] icon:eye-slash[]
        region = 'us-east-2'

        // The name of the bucket.
        // icon:exclamation-triangle[] icon:eye-slash[]
        bucket = 'releases'

        // The artifact path within the bucket.
        // icon:dot-circle[] icon:file-alt[] icon:eye-slash[]
        path = '{{projectName}}/{{tagName}}/{{artifactFile}}'

        // Custom download URL.
        // Required if a custom endpoint is defined.
        // icon:dot-circle[] icon:file-alt[] icon:eye-slash[]
        downloadUrl = 'pass:[https://{{bucket}}.s3.{{region}}.amazonaws.com/{{projectName}}/{{tagName}}/{{artifactFile}}]'

        // The accessKeyId required for authorization.
        // icon:dot-circle[] icon:eye-slash[]
        accessKeyId = '__USE_ENVIRONMENT_VARIABLE__'

        // The secretKey required for authorization.
        // icon:dot-circle[] icon:eye-slash[]
        secretKey = '__USE_ENVIRONMENT_VARIABLE__'

        // The AWS sessionToken when you use temporal credentials.
        // icon:dot-circle[] icon:eye-slash[]
        sessionToken = '__USE_ENVIRONMENT_VARIABLE__'

        // The endpoint to use for S3 service in case some other S3 compatible service is used.
        // icon:dot-circle[] icon:eye-slash[]
        endpoint = 's3.{{region}}.example.com'

        // Additional headers to be sent to the server.
        // Values accept xref:reference:name-templates.adoc[].
        // icon:dot-circle[] icon:file-alt[]
        headers.put('X-ARTIFACT-PLATFORM', '{{artifactPlatform}}')
include::partial$upload/gradle/common-footer.adoc[]
----
--
====

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
include::partial$named-envvars/active.adoc[]
2+| *region*
| jreleaser.{group_sys_key}.{actor_sys_key}.${name}.region +
  jreleaser.{group_sys_key}.{actor_sys_key}.region +
  jreleaser.{actor_sys_key}.${name}.region +
  jreleaser.{actor_sys_key}.region
| JRELEASER_{group_env_key}_{actor_env_key}_${name}_REGION +
  JRELEASER_{group_env_key}_{actor_env_key}_REGION +
  JRELEASER_{actor_env_key}_${name}_REGION +
  JRELEASER_{actor_env_key}_REGION
2+| *bucket*
| jreleaser.{group_sys_key}.{actor_sys_key}.${name}.bucket +
  jreleaser.{group_sys_key}.{actor_sys_key}.bucket +
  jreleaser.{actor_sys_key}.${name}.bucket +
  jreleaser.{actor_sys_key}.bucket
| JRELEASER_{group_env_key}_{actor_env_key}_${name}_BUCKET +
  JRELEASER_{group_env_key}_{actor_env_key}_BUCKET +
  JRELEASER_{actor_env_key}_${name}_BUCKET +
  JRELEASER_{actor_env_key}_BUCKET
2+| *accessKeyId*
| jreleaser.{group_sys_key}.{actor_sys_key}.${name}.access.key.id +
  jreleaser.{group_sys_key}.{actor_sys_key}.access.key.id +
  jreleaser.{actor_sys_key}.${name}.access.key.id +
  jreleaser.{actor_sys_key}.access.key.id
| JRELEASER_{group_env_key}_{actor_env_key}_${name}_ACCESS_KEY_ID +
  JRELEASER_{group_env_key}_{actor_env_key}_ACCESS_KEY_ID +
  JRELEASER_{actor_env_key}_${name}_ACCESS_KEY_ID +
  JRELEASER_{actor_env_key}_ACCESS_KEY_ID
2+| *secretKey*
| jreleaser.{group_sys_key}.{actor_sys_key}.${name}.secret.key +
  jreleaser.{group_sys_key}.{actor_sys_key}.secret.key +
  jreleaser.{actor_sys_key}.${name}.secret.key +
  jreleaser.{actor_sys_key}.secret.key
| JRELEASER_{group_env_key}_{actor_env_key}_${name}_SECRET_KEY +
  JRELEASER_{group_env_key}_{actor_env_key}_SECRET_KEY +
  JRELEASER_{actor_env_key}_${name}_SECRET_KEY +
  JRELEASER_{actor_env_key}_SECRET_KEY
2+| *sessionToken*
| jreleaser.{group_sys_key}.{actor_sys_key}.${name}.session.token +
  jreleaser.{group_sys_key}.{actor_sys_key}.session.token +
  jreleaser.{actor_sys_key}.${name}.session.token +
  jreleaser.{actor_sys_key}.session.token
| JRELEASER_{group_env_key}_{actor_env_key}_${name}_SESSION_TOKEN +
  JRELEASER_{group_env_key}_{actor_env_key}_SESSION_TOKEN +
  JRELEASER_{actor_env_key}_${name}_SESSION_TOKEN +
  JRELEASER_{actor_env_key}_SESSION_TOKEN
2+| *path*
| jreleaser.{group_sys_key}.{actor_sys_key}.${name}.path +
  jreleaser.{group_sys_key}.{actor_sys_key}.path +
  jreleaser.{actor_sys_key}.${name}.path +
  jreleaser.{actor_sys_key}.path
| JRELEASER_{group_env_key}_{actor_env_key}_${name}_PATH +
  JRELEASER_{group_env_key}_{actor_env_key}_PATH +
  JRELEASER_{actor_env_key}_${name}_PATH +
  JRELEASER_{actor_env_key}_PATH
2+| *downloadUrl*
| jreleaser.{group_sys_key}.{actor_sys_key}.${name}.download.url +
  jreleaser.{group_sys_key}.{actor_sys_key}.download.url +
  jreleaser.{actor_sys_key}.${name}.download.url +
  jreleaser.{actor_sys_key}.download.url
| JRELEASER_{group_env_key}_{actor_env_key}_${name}_DOWNLOAD_URL +
  JRELEASER_{group_env_key}_{actor_env_key}_DOWNLOAD_URL +
  JRELEASER_{actor_env_key}_${name}_DOWNLOAD_URL +
  JRELEASER_{actor_env_key}_DOWNLOAD_URL
2+| *endpoint*
| jreleaser.{group_sys_key}.{actor_sys_key}.${name}.endpoint +
  jreleaser.{group_sys_key}.{actor_sys_key}.endpoint +
  jreleaser.{actor_sys_key}.${name}.endpoint +
  jreleaser.{actor_sys_key}.endpoint
| JRELEASER_{group_env_key}_{actor_env_key}_${name}_ENDPOINT +
  JRELEASER_{group_env_key}_{actor_env_key}_ENDPOINT +
  JRELEASER_{actor_env_key}_${name}_ENDPOINT +
  JRELEASER_{actor_env_key}_ENDPOINT
|===

include::partial$envvars-footer.adoc[]

== DownloadUrl

The downloadUrl is the URL used to download artifacts from.

An example configuration may look like
`downloadUrl: 'pass:[https://s3.amazonaws.com/{{projectName}}/downloads/{{projectVersion}}/{{artifactFile}}]'`.

And will result in a final URL like
`pass:[https://s3.amazonaws.com/app/downloads/1.0.0/app-1.0.0.zip]`.

If a custom endpoint is defined then this property must be set as well.

Artifacts may define an extra property following the `<uploaderType><capitalizedUploaderName>Path` format to override
the default path within the bucket. This **does not** work for custom endpoints. For example

```
upload:
  s3:
    app:
      active: ALWAYS

distributions:
  app:
    artifacts:
    - path: target/distributions/{{distributionName}}/{{distributionName}}-{{projectVersion}}.zip
      extraProperties:
        s3AppPath: 'releases/{{artifactFile}}'
    - path: target/distributions/{{distributionName}}/{{distributionName}}-{{projectVersion}}.tar.gz
```

These settings will upload `app-1.0.0.zip` and `app-1.0.0.zip.asc` to `releases/app-1.0.0.zip` and `releases/app-1.0.0.zip.asc`
respectively while `app-1.0.0.tar.gz` and `app-1.0.0.tar.gz.asc` will be uploaded to their default paths, those being
`app/v1.0.0/app-1.0.0.tar.gz` and `app/v1.0.0/app-1.0.0.tar.gz.asc` respectively.

== Credentials

JReleaser uses the link:http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html[DefaultAWSCredentialsProviderChain]
 to look up the AWS credentials. If you want to override the credentials feel free to set `accessKeyId` and `secretKey`
 and (optionally depends on configuration) `sessionToken`. If these properties are set then JReleaser will ignore `DefaultAWSCredentialsProviderChain`.

== Skip Upload

Distributions and Artifacts may define extra properties that may stop them from being uploaded. These properties must
conform to the following rules:

* `skipUpload`: skipped from all uploaders.
* `skipUpload<type>`: skipped from the typed uploader.
* `skipUpload<type><name>`: skipped from the typed and named uploader.

Where `<type>` resolves to `S3` and `<name>` resolves to the capitalized name of the S3 instance, such
that:

* if the name is `foo` the resulting property key is `skipUploadS3Foo`.
* if the name is `fooBar` the resulting property key is `skipUploadS3FooBar`.
* if the name is `foo-bar` the resulting property key is `skipUploadS3FooBar`.

