= Sftp
:uploader_id:   sftp
:uploader_name: SFTP
:prefix:        {uploader_name}
:default_host:  uploads.acme.com
:default_port:  22
:uploader_sys_key: sftp
:uploader_env_key: SFTP
:group_sys_key: upload
:group_env_key: UPLOAD
:actor_sys_key: {uploader_sys_key}
:actor_env_key: {uploader_env_key}

Uploads artifacts, files, and signatures to a {uploader_name} server.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$upload/yaml/common-head.adoc[]

include::partial$upload/yaml/hpup.adoc[]

include::partial$upload/yaml/ssh.adoc[]

      # Path where artifacts will be uploaded.
      # icon:exclamation-triangle[] icon:file-alt[]
      path: '/uploads/{{projectName}}/{{tagName}}/{{artifactFile}}'

include::partial$upload/yaml/download-url.adoc[]
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$upload/toml/common-head.adoc[]

include::partial$upload/toml/hpup.adoc[]

include::partial$upload/toml/ssh.adoc[]

  # Path where artifacts will be uploaded.
  # icon:exclamation-triangle[] icon:file-alt[]
  path = "/uploads/{{projectName}}/{{tagName}}/{{artifactFile}}"

include::partial$upload/toml/download-url.adoc[]
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$upload/json/common-head.adoc[]

include::partial$upload/json/hpup.adoc[]

include::partial$upload/json/ssh.adoc[]

        // Path where artifacts will be uploaded.
        // icon:exclamation-triangle[] icon:file-alt[]
        "path": "/uploads/{{projectName}}/{{tagName}}/{{artifactFile}}",

include::partial$upload/json/download-url.adoc[]
include::partial$upload/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$upload/maven/common-head.adoc[]

include::partial$upload/maven/hpup.adoc[]

include::partial$upload/maven/ssh.adoc[]

        <!--
          Path where artifacts will be uploaded.
          icon:exclamation-triangle[] icon:file-alt[]
        -->
        <path>/uploads/{{projectName}}/{{tagName}}/{{artifactFile}}</path>

include::partial$upload/maven/download-url.adoc[]
include::partial$upload/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$upload/gradle/common-head.adoc[]

include::partial$upload/gradle/hpup.adoc[]

include::partial$upload/gradle/ssh.adoc[]

        // Path where artifacts will be uploaded.
        // icon:exclamation-triangle[] icon:file-alt[]
        path: '/uploads/{{projectName}}/{{tagName}}/{{artifactFile}}'

include::partial$upload/gradle/download-url.adoc[]
include::partial$upload/gradle/common-footer.adoc[]
----
--
====

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1,<1", width="100%"]
|===
| Property | System Property | Environment Variable
include::partial$named-envvars/active.adoc[]
include::partial$named-envvars/ssh-host.adoc[]
include::partial$named-envvars/ssh-port.adoc[]
include::partial$named-envvars/ssh-username.adoc[]
include::partial$named-envvars/ssh-password.adoc[]
include::partial$named-envvars/ssh-public-key.adoc[]
include::partial$named-envvars/ssh-private-key.adoc[]
include::partial$named-envvars/ssh-passphrase.adoc[]
include::partial$named-envvars/ssh-fingerprint.adoc[]
|===

include::partial$envvars-footer.adoc[]

== Path

The path where artifacts will be uploaded to.

An example configuration may look like
`path: '/uploads/{{projectName}}/{{tagName}}/{{artifactFile}}'`.

And will result in a final deployment like
`/uploads/app/v1.0.0/app-1.0.0.zip`.

== DownloadUrl

The downloadUrl is the URL used to download artifacts from. This property is optional but should be set if artifacts
are available for download.

An example configuration may look like
`downloadUrl: 'https://artifacts.acme.com:8081/upload/{{projectName}}/{{tagName}}/{{artifactFile}}'`.

And will result in a final URL like
`pass:[https://artifacts.acme.com:8081/upload/app/v1.0.0/app-1.0.0.zip]`.

== Skip Upload

Distributions and Artifacts may define extra properties that may stop them from being uploaded. These properties must
conform to the following rules:

* `skipUpload`: skipped from all uploaders.
* `skipUpload<type>`: skipped from the typed uploader.
* `skipUpload<type><name>`: skipped from the typed and named uploader.

Where `<type>` resolves to `Sftp` and `<name>` resolves to the capitalized name of the sftp instance, such
that:

* if the name is `foo` the resulting property key is `skipUploadSftpFoo`.
* if the name is `fooBar` the resulting property key is `skipUploadSftpFooBar`.
* if the name is `foo-bar` the resulting property key is `skipUploadSftpFooBar`.