= Discord
:announcer_id:   discord
:announcer_name: discord

Posts a message to a link:https://discord.com/[Discord] room. You must create a custom webhook for this announcer to work.

1. Log into the target discord server.
2. Select the channel you want to integrate to, click on its settings icon.
3. Click on the `Integrations` menu item.
4. Click on Webhooks.
5. Create a new webhook.
6. Copy the generated webhook URL.

IMPORTANT: Webhooks are not protected, anyone with access to the webhook URI can send messages to the target room. Prefer
setting the `JRELEASER_DISCORD_WEBHOOK` environment variable over explicitly setting a value in the configuration DSL.

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="attributes,+macros"]
----
include::partial$announce/yaml/common-head.adoc[]

    # The webhook associated with a specific Discord room.
    # If left unspecified, the `JRELEASER_DISCORD_WEBHOOK`
    # environment variable must be defined.
    # icon:exclamation-triangle[] icon:eye-slash[]
    webhook: __DO_NOT_SET_HERE__

    # The announcement message.
    # Review the available xref:configuration:name-templates.adoc[].
    # icon:dot-circle[] icon:file-alt[]
    message: '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

    # Path to a template file that contains the message.
    # Review the available xref:configuration:name-templates.adoc[].
    # Defaults to `src/jreleaser/templates/discord.tpl`.
    # icon:dot-circle[]
    messageTemplate: path/to/template/discord.tpl
----
--
TOML::
+
--
[source,toml]
[subs="attributes,+macros"]
----
include::partial$announce/toml/common-head.adoc[]

  # The webhook associated with a specific Discord room.
  # If left unspecified, the `JRELEASER_DISCORD_WEBHOOK`
  # environment variable must be defined.
  # icon:exclamation-triangle[] icon:eye-slash[]
  webhook = "__DO_NOT_SET_HERE__"

  # The announcement message.
  # Review the available xref:configuration:name-templates.adoc[].
  # icon:dot-circle[] icon:file-alt[]
  message = "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}"

  # Path to a template file that contains the message.
  # Review the available xref:configuration:name-templates.adoc[].
  # Defaults to `src/jreleaser/templates/discord.tpl`.
  # icon:dot-circle[]
  messageTemplate = "path/to/template/discord.tpl"
----
--
JSON::
+
--
[source,json]
[subs="attributes,+macros"]
----
include::partial$announce/json/common-head.adoc[]

      // The webhook associated with a specific Discord room.
      // If left unspecified, the `JRELEASER_DISCORD_WEBHOOK`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "webhook": "__DO_NOT_SET_HERE__",

      // The announcement message.
      // Review the available xref:configuration:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      "message": "🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}",

      // Path to a template file that contains the message.
      // Review the available xref:configuration:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/discord.tpl`.
      // icon:dot-circle[]
      "messageTemplate": "path/to/template/discord.tpl"
include::partial$announce/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="attributes,verbatim,+macros"]
----
include::partial$announce/maven/common-head.adoc[]

      <!--
        The webhook associated with a specific Discord room.
        If left unspecified, the `JRELEASER_DISCORD_WEBHOOK` environment variable must be defined.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <webhook>__DO_NOT_SET_HERE__</webhook>

      <!--
        The announcement message.
        Review the available xref:configuration:name-templates.adoc[].
        icon:dot-circle[] icon:file-alt[]
      -->
      <message>🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}</message>

      <!--
        Path to a template file that contains the message.
        Review the available xref:configuration:name-templates.adoc[].
        Defaults to `src/jreleaser/templates/discord.tpl`.
        icon:dot-circle[]
      -->
      <messageTemplate>path/to/template/discord.tpl</messageTemplate>
include::partial$announce/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="attributes,+macros"]
----
include::partial$announce/gradle/common-head.adoc[]

      // The webhook associated with a specific Discord room.
      // If left unspecified, the `JRELEASER_DISCORD_WEBHOOK`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      webhook = '__DO_NOT_SET_HERE__'

      // The announcement message.
      // Review the available xref:configuration:name-templates.adoc[].
      // icon:dot-circle[] icon:file-alt[]
      message = '🚀 {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}'

      // Path to a template file that contains the message.
      // Review the available xref:configuration:name-templates.adoc[].
      // Defaults to `src/jreleaser/templates/discord.tpl`.
      // icon:dot-circle[]
      messageTemplate = 'path/to/template/discord.tpl'
include::partial$announce/gradle/common-footer.adoc[]
----
--
====

You may define either `message` or `messageTemplate`, with the former taking precedence over the latter.

The template file may be initialized using the `template` command.
