= Sdkman
:announcer_id:   sdkman
:announcer_name: Sdkman

Publishes a release to link:https://sdkman.io[Sdkman]. Please follow the instructions at
link:https://sdkman.io/vendors[] to register your project as a candidate and obtain publishing credentials.

IMPORTANT: This announcer is configured for the whole project, accepts a single candidate, and aggregates all matching
artifacts into a single release. If you need multiple candidates then consider using the
xref:configuration:packagers/sdkman.adoc[] packager instead.

WARNING: The Sdkman announcer and packager are mutually exclusive.

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="attributes,+macros"]
----
include::partial$announce/yaml/common-head.adoc[]

    # The name of the candidate registered in thew Sdkman database.
    # If unspecified, will use ${project.name}.
    # icon:dot-circle[]
    candidate: app

    # Announce a major release if `true`, minor release if `false`.
    # Defaults to `true`.
    # icon:dot-circle[]
    major: true

    # The release notes URL to use.
    # Defaults to `${release.<git>.releaseNotesUrl}.
    # icon:dot-circle[] icon:file-alt[]
    releaseNotesUrl: pass:[https://host.com/{{projectName}}/{{tagName}}]

    # The consumer key for publishing to Sdkman.
    # If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_KEY`
    # environment variable must be defined.
    # icon:exclamation-triangle[] icon:eye-slash[]
    consumerKey: __DO_NOT_SET_HERE__

    # The consumer token for publishing to Sdkman.
    # If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_TOKEN`
    # environment variable must be defined.
    # icon:exclamation-triangle[] icon:eye-slash[]
    consumerToken: __DO_NOT_SET_HERE__
----
--
TOML::
+
--
[source,toml]
[subs="attributes,+macros"]
----
include::partial$announce/toml/common-head.adoc[]

  # The name of the candidate registered in thew Sdkman database.
  # If unspecified, will use ${project.name}.
  # icon:dot-circle[]
  candidate = "app"

  # The release notes URL to use.
  # Defaults to `${release.<git>.releaseNotesUrl}.
  # icon:dot-circle[] icon:file-alt[]
  releaseNotesUrl = "pass:[https://host.com/{{projectName}}/{{tagName}}]"

  # Announce a major release if `true`, minor release if `false`.
  # Defaults to `true`.
  # icon:dot-circle[]
  major = true

  # The consumer key for publishing to Sdkman.
  # If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_KEY`
  # environment variable must be defined.
  # icon:exclamation-triangle[] icon:eye-slash[]
  consumerKey = "__DO_NOT_SET_HERE__"

  # The consumer token for publishing to Sdkman.
  # If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_TOKEN`
  # environment variable must be defined.
  # icon:exclamation-triangle[] icon:eye-slash[]
  consumerToken = "__DO_NOT_SET_HERE__"
----
--
JSON::
+
--
[source,json]
[subs="attributes,+macros"]
----
include::partial$announce/json/common-head.adoc[]

      // The name of the candidate registered in thew Sdkman database.
      // If unspecified, will use ${project.name}.
      // icon:dot-circle[]
      "candidate": "app",

      // The release notes URL to use.
      // Defaults to `${release.<git>.releaseNotesUrl}.
      // icon:dot-circle[] icon:file-alt[]
      "releaseNotesUrl": "pass:[https://host.com/{{projectName}}/{{tagName}}]",

      // Announce a major release if `true`, minor release if `false`.
      // Defaults to `true`.
      // icon:dot-circle[]
      "major": true,

      // The consumer key for publishing to Sdkman.
      // If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_KEY`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "consumerKey": "__DO_NOT_SET_HERE__",

      // The consumer token for publishing to Sdkman.
      // If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_TOKEN`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "consumerToken": "__DO_NOT_SET_HERE__"
include::partial$announce/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="attributes,verbatim,+macros"]
----
include::partial$announce/maven/common-head.adoc[]

      <!--
        The name of the candidate registered in thew Sdkman database.
        If unspecified, will use ${project.name}.
        icon:dot-circle[]
      -->
      <candidate>app</candidate>

      <!--
        The release notes URL to use.
        Defaults to `${release.<git>.releaseNotesUrl}.
        icon:dot-circle[] icon:file-alt[]
      -->
      <releaseNotesUrl>pass:[https://host.com/{{projectName}}/{{tagName}}]</releaseNotesUrl>

      <!--
        Announce a major release if `true`, minor release if `false`.
        Defaults to `true`.
        icon:dot-circle[]
      -->
      <major>true</major>

      <!--
        The consumer key for publishing to Sdkman.
        If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_KEY`
        environment variable must be defined.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <consumerKey>__DO_NOT_SET_HERE__</consumerKey>

      <!--
        The consumer token for publishing to Sdkman.
        If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_TOKEN`
        environment variable must be defined.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <consumerToken>__DO_NOT_SET_HERE__</consumerToken>
include::partial$announce/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="attributes,+macros"]
----
include::partial$announce/gradle/common-head.adoc[]

      // The name of the candidate registered in thew Sdkman database.
      // If unspecified, will use ${project.name}.
      // icon:dot-circle[]
      candidate = 'app'

      // The release notes URL to use.
      // Defaults to `${release.<git>.releaseNotesUrl}.
      // icon:dot-circle[] icon:file-alt[]
      releaseNotesUrl = 'pass:[https://host.com/{{projectName}}/{{tagName}}]'

      // Announce a major release if `true`, minor release if `false`.
      // Defaults to `true`.
      // icon:dot-circle[]
      major = true

      // The consumer key for publishing to Sdkman.
      // If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_KEY`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      consumerKey = '__DO_NOT_SET_HERE__'

      // The consumer token for publishing to Sdkman.
      // If left unspecified, the `JRELEASER_SDKMAN_CONSUMER_TOKEN`
      // environment variable must be defined.
      // icon:exclamation-triangle[] icon:eye-slash[]
      consumerToken = '__DO_NOT_SET_HERE__'
include::partial$announce/gradle/common-footer.adoc[]
----
--
====


This announcer has the following considerations:

* No snapshot releases are supported.
* Only `zip` artifacts are supported.
* The default platform is set to `UNIVERSAL` if the artifact did not define a value for its `platform` field.
* If there's more than one artifact then each artifact requires distinct `platform` values, otherwise the latest
 artifact will override any previous matches by platform.
* You may explicitly skip a distribution or artifact by defining an extra property named `skipSdkman` with any value.
* Announcing will be skipped if no suitable artifacts are found.

Supported platform values are:

* `mac`, `osx`.
* `win`, `windows`.
* `linux`.

