== Issues

Upon release, JReleaser may attach a label and post a comment on every matching issue found in the changelog.
The following regular expressions will be used to find matching issues:

 - {{issueTrackerUrl}}/(\d+)
 - {{repoOwner}}/{{repoName}}#(\d+)
 - #(\d+)

.Examples

 - pass:c,a[{issue-tracker-url}/123]
 - {repo-owner}/{repo-name}#123
 - #123

The release process applies the following rules to mark issues:

1. Create the target label if it does not exist.
2. Lookup every matching issue. Skip if **not** closed or if it already has the label applied.
3. Apply the label and post a comment.

Additionally, the matching milestone may also be applied to issues. You may set the `applyMilestone` property with any
of the following values:

* `NEVER`. Do not apply the milestone.
* `ALWAYS`. Apply the milestone if the issue has no milestone.
* `WARN`. Do not apply the milestone but warn if there's an existing milestone that does not match the current one.
* `FORCE`. Apply the milestone even if the issue had a different milestone.
