= Jlink

A custom Java Runtime created with link:https://docs.oracle.com/en/java/javase/11/tools/jlink.html[Jlink].
Distributions of this type conform to the following file structure:

[source]
----
.
├── LICENSE
├── README
├── bin
│   ├── app
│   ├── app.bat
│   ├── java
│   └── keytool
└── conf
│    └── /* Java runtime */
└── legal
│    └── /* Java runtime */
└── lib
│    └── /* Java runtime */
└── release
----

Where:

* the `bin` folder contains executable launcher scripts.
* the `lib` folder contains all required JARs.

Jlink distributions *do not require* a suitable Java runtime to be installed on the consumer side as they already bundle
a Java runtime, as a consequence you *must* specify a value for their platform. They are usually packaged as a Zip file.
The archive must contain a root entry, typically following the name of the archive, thus if the archive is named
`app-1.2.3.zip` the root entry should be `app-1.2.3`.

== Creating a Distribution

We recommend using the following plugins to create suitable Java binary distributions:

.Maven

 * link:http://maven.apache.org/plugins/maven-jlink-plugin/[maven-jlink-plugin]: creates a *modular* Java Runtime image.

.Gradle

 * link:https://badass-runtime-plugin.beryx.org/releases/latest/[badass-runtime-plugin] plugin: use it for *non-modular*
applications. Generates distribution files that follow the expected structure. Also, packages the distribution as a Zip.
 * link:https://badass-jlink-plugin.beryx.org/releases/latest/[badass-jlink-plugin] plugin: use it for *modular*
applications. Generates distribution files that follow the expected structure. Also, packages the distribution as a Zip.

Alternatively, you may also configure a xref:reference:assemble/jlink.adoc[] assembler.

== Packager Support

[%header, cols="<,^"]
|===
| Packager                                   | Supported
| xref:reference:packagers/appimage.adoc[]   | {icon_req_y}
| xref:reference:packagers/asdf.adoc[]       | {icon_req_y}
| xref:reference:packagers/chocolatey.adoc[] | {icon_req_y}
| xref:reference:packagers/docker.adoc[]     | {icon_req_y}
| xref:reference:packagers/flatpak.adoc[]    | {icon_req_y}
| xref:reference:packagers/homebrew.adoc[]   | {icon_req_y}
| xref:reference:packagers/jbang.adoc[]      | {icon_req_n}
| xref:reference:packagers/macports.adoc[]   | {icon_req_y}
| xref:reference:packagers/scoop.adoc[]      | {icon_req_y}
| xref:reference:packagers/sdkman.adoc[]     | {icon_req_y}
| xref:reference:packagers/snap.adoc[]       | {icon_req_y}
| xref:reference:packagers/spec.adoc[]       | {icon_req_y}
| xref:reference:packagers/winget.adoc[]     | {icon_req_y}
|===



