= Native Image

WARNING: This distribution type has been deprecated in `v1.4.0` and will be removed in `v2.0.0`.
Use xref:distributions/binary.adoc[] instead. You must add an extraProperty named `graalVMNativeImage` to the artifact.

Distributions of this type provide a platform specific native binary, as a consequence you *must* specify a platform value
for each one of their artifacts.

Distributions of this type conform to the following file structure:

[source]
----
.
├── LICENSE
├── README
└── bin
    └── executable
----

== Creating a Distribution

Native image binaries can be created in many ways. Frameworks such as Micronaut, Quarkus, and Helidon provide Maven and
Gradle plugins that can create such binaries. The distribution should be packages as a Zip or Tar. The archive must
contain a root entry, typically following the name of the archive, thus if the archive is named `app-1.2.3.zip` the root
entry should be `app-1.2.3`.

.Maven

 * link:https://www.graalvm.org/reference-manual/native-image/NativeImageMavenPlugin/[native-image-maven-plugin]
 * link:http://maven.apache.org/plugins/maven-assembly-plugin/[maven-assembly-plugin]: packages the distribution as a Zip.

.Gradle

 * link:https://docs.gradle.org/current/userguide/distribution_plugin.html[distribution] plugin: packages a distribution as a Zip.

Alternatively, you may also configure a xref:reference:assemble/native-image.adoc[] assembler.

== Packager Support

[%header, cols="<,^"]
|===
| Packager                                   | Supported
| xref:reference:packagers/appimage.adoc[]   | {icon_req_y}
| xref:reference:packagers/asdf.adoc[]       | {icon_req_y}
| xref:reference:packagers/chocolatey.adoc[] | {icon_req_y}
| xref:reference:packagers/docker.adoc[]     | {icon_req_y}
| xref:reference:packagers/flatpak.adoc[]    | {icon_req_y}
| xref:reference:packagers/homebrew.adoc[]   | {icon_req_y}
| xref:reference:packagers/jbang.adoc[]      | {icon_req_n}
| xref:reference:packagers/macports.adoc[]   | {icon_req_y}
| xref:reference:packagers/scoop.adoc[]      | {icon_req_y}
| xref:reference:packagers/sdkman.adoc[]     | {icon_req_y}
| xref:reference:packagers/snap.adoc[]       | {icon_req_y}
| xref:reference:packagers/spec.adoc[]       | {icon_req_y}
| xref:reference:packagers/winget.adoc[]     | {icon_req_y}
|===



