= Gitea
:deployer_id:   gitea
:deployer_name: Gitea
:deployer_url:  pass:[https://codeberg.org/api/packages/{{owner}}/maven]
:default_auth:  BEARER
:deployer_sys_key: gitea
:deployer_env_key: GITEA

Deploys staged artifacts to a Gitea instance via its
link:https://docs.gitea.io/en-us/packages/maven/[Maven Packages] option.

IMPORTANT: This feature is primarily intended for deploying artifacts such as JARs and POMs to a Maven compatible repository.
If you need to upload any other binaries then check the xref:reference:upload/gitea.adoc[{deployer_name} Uploader].

WARNING: Publication of snapshots is *not* allowed.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$deploy/maven/yaml/common-head.adoc[]
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$deploy/maven/toml/common-head.adoc[]
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$deploy/maven/json/common-head.adoc[]

include::partial$deploy/maven/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$deploy/maven/maven/common-head.adoc[]
include::partial$deploy/maven/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$deploy/maven/gradle/common-head.adoc[]
include::partial$deploy/maven/gradle/common-footer.adoc[]
----
--
====

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
include::partial$deploy/maven/envvars.adoc[]
|===

include::partial$envvars-footer.adoc[]

== Example

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
deploy:
  maven:
    {deployer_id}:
      app:
        active: ALWAYS
        url: {deployer_url}
        stagingRepositories:
          - target/staging-deploy
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
[deploy.maven.{deployer_id}.app]
  active = "ALWAYS"
  host = "{deployer_url}"
  stagingRepositories = ["target/staging-deploy"]
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
{
  "jreleaser": {
    "deploy": {
      "maven": {
        "{deployer_id}": {
          "app": {
            "active": "ALWAYS",
            "host": "{deployer_url}",
            "stagingRepositories": [
              "target/staging-deploy"
            ]
          }
        }
      }  
    }
  }
}
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
<jreleaser>
  <deploy>
    <maven>
      <{deployer_id}>
        <app>
          <active>ALWAYS</active>
          <host>{deployer_url}</host>
          <stagingRepositories>target/staging-deploy</stagingRepositories>
        </app>
      </{deployer_id}>
    </maven>
  </deploy>
</jreleaser>
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
jreleaser {
  deploy {
    maven {
      {deployer_id} {
        app {
          active = 'ALWAYS'
          host = '{deployer_url}'
          stagingRepository('target/staging-deploy')
        }
      }
    }
  }
}
----
--
====

Any of the following environment variables may be defined to supply values for `username` and `password`:

 * `JRELEASER_DEPLOY_MAVEN_{deployer_env_key}_APP_USERNAME`
 * `JRELEASER_DEPLOY_MAVEN_{deployer_env_key}_USERNAME`
 * `JRELEASER_{deployer_env_key}_APP_USERNAME`
 * `JRELEASER_{deployer_env_key}_USERNAME`
 * `JRELEASER_DEPLOY_MAVEN_{deployer_env_key}_APP_PASSWORD`
 * `JRELEASER_DEPLOY_MAVEN_{deployer_env_key}_APP_TOKEN`
 * `JRELEASER_DEPLOY_MAVEN_{deployer_env_key}_PASSWORD`
 * `JRELEASER_DEPLOY_MAVEN_{deployer_env_key}_TOKEN`
 * `JRELEASER_{deployer_env_key}_APP_PASSWORD`
 * `JRELEASER_{deployer_env_key}_APP_TOKEN`
 * `JRELEASER_{deployer_env_key}_PASSWORD`
 * `JRELEASER_{deployer_env_key}_TOKEN`
