= Gitlab
:deployer_id:   gitlab
:deployer_name: Gitlab
:deployer_url:  pass:[https://gitlab.com/api/v4/projects/12345678/packages/maven]
:default_auth:  BEARER
:deployer_sys_key: gitlab
:deployer_env_key: GITLAB

Deploys staged artifacts to a Gitlab instance via its
link:https://docs.gitlab.com/ee/user/packages/maven_repository/[Maven Packages] option.

IMPORTANT: This feature is primarily intended for deploying artifacts such as JARs and POMs to a Maven compatible repository.
If you need to upload any other binaries then check the xref:reference:upload/gitlab.adoc[{deployer_name} Uploader].

WARNING: Publication of snapshots is *not* allowed.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$deploy/maven/yaml/common-head.adoc[]

        # The id of the GitLab repository.
        # icon:exclamation-triangle[]
        projectIdentifier: 12345678
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$deploy/maven/toml/common-head.adoc[]

  # The id of the GitLab repository.
  # icon:exclamation-triangle[]
  projectIdentifier = "12345678"
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$deploy/maven/json/common-head.adoc[]

          // The id of the GitLab repository.
          // icon:exclamation-triangle[]
          "projectIdentifier": "12345678",

include::partial$deploy/maven/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$deploy/maven/maven/common-head.adoc[]

        <!--
           The id of the GitLab repository.
           icon:exclamation-triangle[]
        -->
        <projectIdentifier>12345678</projectIdentifier>
include::partial$deploy/maven/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$deploy/maven/gradle/common-head.adoc[]

        // The id of the GitLab repository.
        // icon:exclamation-triangle[]
        projectIdentifier = '12345678'

include::partial$deploy/maven/gradle/common-footer.adoc[]
----
--
====

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
include::partial$deploy/maven/envvars.adoc[]
|===

include::partial$envvars-footer.adoc[]

== Example

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
deploy:
  maven:
    {deployer_id}:
      app:
        active: ALWAYS
        url: {deployer_url}
        projectIdentifier: 12345678
        stagingRepositories:
          - target/staging-deploy
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
[deploy.maven.{deployer_id}.app]
  active = "ALWAYS"
  host = "{deployer_url}"
  projectIdentifier = "12345678"
  stagingRepositories = ["target/staging-deploy"]
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
{
  "jreleaser": {
    "deploy": {
      "maven": {
        "{deployer_id}": {
          "app": {
            "active": "ALWAYS",
            "host": "{deployer_url}",
            "projectIdentifier": "12345678",
            "stagingRepositories": [
              "target/staging-deploy"
            ]
          }
        }
      }  
    }
  }
}
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
<jreleaser>
  <deploy>
    <maven>
      <{deployer_id}>
        <app>
          <active>ALWAYS</active>
          <host>{deployer_url}</host>
          <projectIdentifier>12345678</projectIdentifier>
          <stagingRepositories>target/staging-deploy</stagingRepositories>
        </app>
      </{deployer_id}>
    </maven>
  </deploy>
</jreleaser>
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
jreleaser {
  deploy {
    maven {
      {deployer_id} {
        app {
          active = 'ALWAYS'
          host = '{deployer_url}'
          projectIdentifier = '12345678'
          stagingRepository('target/staging-deploy')
        }
      }
    }
  }
}
----
--
====

Any of the following environment variables may be defined to supply values for `username` and `password`:

 * `JRELEASER_DEPLOY_MAVEN_{deployer_env_key}_APP_USERNAME`
 * `JRELEASER_DEPLOY_MAVEN_{deployer_env_key}_USERNAME`
 * `JRELEASER_{deployer_env_key}_APP_USERNAME`
 * `JRELEASER_{deployer_env_key}_USERNAME`
 * `JRELEASER_DEPLOY_MAVEN_{deployer_env_key}_APP_PASSWORD`
 * `JRELEASER_DEPLOY_MAVEN_{deployer_env_key}_APP_TOKEN`
 * `JRELEASER_DEPLOY_MAVEN_{deployer_env_key}_PASSWORD`
 * `JRELEASER_DEPLOY_MAVEN_{deployer_env_key}_TOKEN`
 * `JRELEASER_{deployer_env_key}_APP_PASSWORD`
 * `JRELEASER_{deployer_env_key}_APP_TOKEN`
 * `JRELEASER_{deployer_env_key}_PASSWORD`
 * `JRELEASER_{deployer_env_key}_TOKEN`
