= Asdf
:tool_id:       asdf
:tool_name:     asdf
:tool_tap:      repository
:tool_tap_name: asdf-duke
:tool_manifest: plugin
:tool_package:  ${distribution.name}
:packager_sys_key: asdf
:packager_env_key: ASDF
:tap_sys_key:      repository
:tap_env_key:      REPOSITORY
:tap_basename_sys: asdf
:tap_basename_env: ASDF

link:https://asdf-vm.com/[asdf] is a tool version manager.

The following artifact extensions are supported by this packager:

* `.tgz`
* `.txz`
* `.tar.gz`
* `.tar.xz`
* `.tar`
* `.zip`

== Distribution Support

[%header, cols="<,^"]
|===
| Distribution                                  | Supported
| xref:concepts:distributions/binary.adoc[]         | {icon_req_y}
| xref:concepts:distributions/flat-binary.adoc[]    | {icon_req_y}
| xref:concepts:distributions/java-binary.adoc[]    | {icon_req_y}
| xref:concepts:distributions/jlink.adoc[]          | {icon_req_y}
| xref:concepts:distributions/native-image.adoc[]   | {icon_req_y}
| xref:concepts:distributions/native-package.adoc[] | {icon_req_n}
| xref:concepts:distributions/single-jar.adoc[]     | {icon_req_n}
|===

NOTE: Default templates for `asdf` assume the project relies on xref:reference:project.adoc#_semver[Semantic Versioning]. You'll have
to adjust the templates or provide your own if your project follows a different versioning scheme.

WARNING: Publication of snapshots is *not* allowed.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$packagers/yaml/common-head.adoc[]

include::partial$packagers/yaml/template-directory.adoc[]

include::partial$packagers/yaml/commitauthor.adoc[]

include::partial$packagers/yaml/tap.adoc[]

    # Tool verification command.
    # Defaults to `{{distributionExecutable}} --version`.
    # icon:dot-circle[] icon:file-alt[]
    toolCheck: '{{distributionExecutable}} --version'
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$packagers/toml/common-head.adoc[]

include::partial$packagers/toml/template-directory.adoc[]

include::partial$packagers/toml/commitauthor.adoc[]

include::partial$packagers/toml/tap.adoc[]

  # Tool verification command.
  # Defaults to `{{distributionExecutable}} --version`.
  # icon:dot-circle[] icon:file-alt[]
  toolCheck = "{{distributionExecutable}} --version"
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$packagers/json/common-head.adoc[]

include::partial$packagers/json/template-directory.adoc[]

include::partial$packagers/json/commitauthor.adoc[]

include::partial$packagers/json/tap.adoc[]

      // Tool verification command.
      // Defaults to `{{distributionExecutable}} --version`.
      // icon:dot-circle[] icon:file-alt[]
      "toolCheck": "{{distributionExecutable}} --version"
include::partial$packagers/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$packagers/maven/common-head.adoc[]

include::partial$packagers/maven/template-directory.adoc[]

include::partial$packagers/maven/commitauthor.adoc[]

include::partial$packagers/maven/tap.adoc[]

      <!--
        Tool verification command.
        Defaults to `{{distributionExecutable}} --version`.
        icon:dot-circle[] icon:file-alt[]
      -->
      <toolCheck>{{distributionExecutable}} --version</toolCheck>
include::partial$packagers/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$packagers/gradle/common-head.adoc[]

include::partial$packagers/gradle/template-directory.adoc[]

include::partial$packagers/gradle/commitauthor.adoc[]

include::partial$packagers/gradle/tap.adoc[]

      // Tool verification command.
      // Defaults to `{{distributionExecutable}} --version`.
      // icon:dot-circle[] icon:file-alt[]
      toolCheck = '{{distributionExecutable}} --version'
include::partial$packagers/gradle/common-footer.adoc[]
----
--
====

include::partial$envvars-header.adoc[]

**Inside `packagers` section**
[%header, cols="<1,<1,<1", width="100%"]
|===
| Property | System Property | Environment Variable
| active
| jreleaser.packagers.{packager_sys_key}.active
| JRELEASER_PACKAGERS_{packager_env_key}_ACTIVE
|===

**Inside `distributions` section**
[%header, cols="<1,<1,<1", width="100%"]
|===
| Property | System Property | Environment Variable
| active
| jreleaser.distributions.${name}.{packager_sys_key}.active
| JRELEASER_DISTRIBUTIONS_${name}_{packager_env_key}_ACTIVE
include::partial$packagers/tap-envvars.adoc[]
|===

include::partial$envvars-footer.adoc[]

include::partial$packagers/token.adoc[]

include::partial$packagers/downloadUrl.adoc[]

== Skip Artifacts

If there is more than one matching artifact in a given distribution you may add a `skipAsdf` extra property to the target
artifact to mark it as skipped for packaging with asdf.

== Templates

The default location for templates is:

`src/jreleaser/distributions/<distribution-name>/asdf`

The following list shows the filenames that may be used to override default templates:

* `.github/workflows/build.yml.tpl`
* `bin/download.tpl`
* `bin/install.tpl`
* `bin/list-all.tpl`
* `lib/utils.bash.tpl`
* `README.md.tpl`
* `README-github.md.tpl`

Any additional files found in the template directories will be copied as is unless their filename ends with `.tpl` in
which case xref:name-templates.adoc[] substitution will take place.

Templates may be initialized using the `template` command

 * xref:tools:jreleaser-cli.adoc#_template_generate[{icon_cli_s} template generate]
 * xref:tools:jreleaser-maven.adoc#_jreleasertemplate_generate[{icon_maven_s} jreleaser:template-generate]
 * xref:tools:jreleaser-gradle.adoc#_jreleasertemplategenerate[{icon_gradle_s} jreleaserTemplategGenerate]
 * xref:tools:jreleaser-ant.adoc#_jreleaser_template_generate[{icon_ant_s} jreleaser-template-generate]

== Skip Templates

You may skip any template files by defining a set of skip rules in the `skipTemplates` property. For example, you may use
any of these expressions to skip a template named `README.md.tpl`:

* `README.md.tpl`: matches the full template name
* `README.md`: matches the transformed template name
* `README.*`: matches using a regex
