= Homebrew
:tool_id:       brew
:tool_name:     Homebrew
:tool_tap_name: homebrew-tap
:tool_manifest: formula
:packager_sys_key: brew
:packager_env_key: BREW
:tap_basename_sys: homebrew
:tap_basename_env: HOMEBREW

The `brew` section specifies how the formula should be created. You can check the
link:https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.md[Homebrew documentation] and the
link:https://docs.brew.sh/Formula-Cookbook.md[formula cookbook] and
link:https://docs.brew.sh/Cask-Cookbook[cask-cookbook] for more details.

The following artifact extensions are supported by this packager for creating formulae:

* `.jar`
* `.zip`

The following artifact extensions are supported by this packager for creating casks:

* `.dmg`
* `.pkg`
* `.zip`

== Distribution Support

[%header, cols="<,^"]
|===
| Distribution                                      | Supported
| xref:concepts:distributions/binary.adoc[]         | {icon_req_y}
| xref:concepts:distributions/flat-binary.adoc[]    | {icon_req_y}
| xref:concepts:distributions/java-binary.adoc[]    | {icon_req_y}
| xref:concepts:distributions/jlink.adoc[]          | {icon_req_y}
| xref:concepts:distributions/native-image.adoc[]   | {icon_req_y}
| xref:concepts:distributions/native-package.adoc[] | {icon_req_y}
| xref:concepts:distributions/single-jar.adoc[]     | {icon_req_y}
|===

WARNING: Publication of snapshots is *not* allowed.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$packagers/yaml/common-head.adoc[]

include::partial$packagers/yaml/template-directory.adoc[]

include::partial$packagers/yaml/commitauthor.adoc[]

include::partial$packagers/yaml/tap.adoc[]

    # The class name of the generated formula.
    # If left unspecified, will use `{{projectNameCapitalized}}`.
    # icon:dot-circle[] icon:file-alt[]
    formulaName: App

    # Create a formula that supports OSX & Linux.
    # Applicable to distributions of type [`JLINK`, `BINARY`, `FLAT_BINARY`].
    # Default is `false`.
    # icon:dot-circle[]
    multiPlatform: false

    # Set a custom download strategy. Note that you'll need
    # to implement the strategy and add it to your tap repository.
    # Example: https://docs.brew.sh/Formula-Cookbook#url-download-strategies
    # icon:dot-circle[]
    downloadStrategy: CurlDownloadStrategy

    # Adds `require_relative` statements at the top of the formula template.
    # icon:dot-circle[]
    requireRelative:
      - custom_download_strategy

    # Customize the livecheck block.
    # Default is empty.
    # icon:dot-circle[] icon:file-alt[]
    livecheck:
      - 'url "pass:[https://host/sparkle/appcast-release.xml]"'
      - 'strategy :sparkle'

    # A map of Homebrew dependencies.
    # A dependency to `openjdk` is automatically added to applicable Java distributions.
    # icon:dot-circle[]
    dependencies:
      # key in symbol format
      # mapped as `depends_on :key1 => "value1"`
      ':key1': value1

      # plain key
      # mapped as `depends_on "key2" => "value2"`
      key2: value2

      # key in symbol format without value
      # mapped as `depends_on :key3`
      ':key3': 'null'

      # plain key without value
      # mapped as `depends_on "key4"`
      key4: 'null'

    # Cask configuration.
    # Requires artifact with extension `.dmg` or `.pkg`.
    # Defaults are shown.
    # icon:dot-circle[]
    cask:

      # Favors producing a cask instead of a formula.
      # Default is `false`.
      # icon:dot-circle[]
      enabled: true

      # The class name of the generated cask.
      # If left unspecified, will use `{{projectName}}`.
      # icon:dot-circle[] icon:file-alt[]
      name: app

      # The name of the generated cask.
      # If left unspecified, will use `{{brewFormulaName}}`.
      # icon:dot-circle[] icon:file-alt[]
      displayName: App

      # Relative path to the .pkg file.
      # If left unspecified, will use the filename of the .pkg file.
      # icon:dot-circle[] icon:file-alt[]
      pkgName: app-1.0.0.pkg

      # Name of the application folder.
      # If left unspecified, will use `{{brewFormulaName}}.app`.
      # icon:dot-circle[] icon:file-alt[]
      appName: App.app

      # URL providing an appcast feed to find updates for this Cask.
      # Default is empty.
      # icon:dot-circle[] icon:file-alt[]
      appcast: pass:[https://{{repoHost}}/{{repoOwner}}/{{repoName}}/releases.atom]

      # Procedures to uninstall the Cask.
      # icon:dot-circle[]
      uninstall:
        pkgutil:
          - com.acme.app

      # Additional procedures for a more complete uninstall.
      # icon:dot-circle[]
      zap:
        trash:
          - '~/Library/Caches/App'
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$packagers/toml/common-head.adoc[]

include::partial$packagers/toml/template-directory.adoc[]

include::partial$packagers/toml/commitauthor.adoc[]

include::partial$packagers/toml/tap.adoc[]

  # The class name of the generated formula.
  # If left unspecified, will use `{{projectNameCapitalized}}`.
  # icon:dot-circle[] icon:file-alt[]
  formulaName = "App"

  # Create a formula that supports OSX & Linux.
  # Applicable to distributions of type [`JLINK`, `BINARY`, `FLAT_BIINARY`].
  # Default is `false`.
  # icon:dot-circle[]
  multiPlatform = false

  # Set a custom download strategy. Note that you'll need
  # to implement the strategy and add it to your tap repository.
  # Example: https://docs.brew.sh/Formula-Cookbook#url-download-strategies
  # icon:dot-circle[]
  downloadStrategy = "CurlDownloadStrategy"

  # Adds `require_relative` statements at the top of the formula template.
  # icon:dot-circle[]
  requireRelative = ["custom_download_strategy"]

  # Customize the livecheck block.
  # Default is empty.
  # icon:dot-circle[] icon:file-alt[]
  livecheck = [
     "url 'pass:[https://host/sparkle/appcast-release.xml'",
     "strategy :sparkle'"]

  # A map of Homebrew dependencies.
  # A dependency to `openjdk` is automatically added to applicable Java distributions.
  # icon:dot-circle[]
  # key in symbol format
  # mapped as `depends_on :key1 => "value1"`
  dependencies.":key1" = "value1"
  # plain key
  # mapped as `depends_on "key2" => "value2"`
  dependencies.key2 = "value2"
  # key in symbol format without value
  # mapped as `depends_on :key3`
  dependencies.":key3" = "null"
  # plain key without value
  # mapped as `depends_on "key4"`
  dependencies.key4 = "null"

  # Cask configuration.
  # Requires artifact with extension `.dmg` or `.pkg`.
  # Defaults are shown.
  # icon:dot-circle[]

  # Favors producing a cask instead of a formula.
  # Default is `false`.
  # icon:dot-circle[]
  cask.enabled = true

  # The class name of the generated cask.
  # If left unspecified, will use `{{projectName}}`.
  # icon:dot-circle[] icon:file-alt[]
  cask.name = "app"

  # The name of the generated cask.
  # If left unspecified, will use `{{brewFormulaName}}`.
  # icon:dot-circle[] icon:file-alt[]
  cask.displayName = "App"

  # Relative path to the .pkg file.
  # If left unspecified, will use the filename of the .pkg file.
  # icon:dot-circle[] icon:file-alt[]
  cask.pkgName = "app-1.0.0.pkg"

  # Name of the application folder.
  # If left unspecified, will use `{{brewFormulaName}}.app`.
  # icon:dot-circle[] icon:file-alt[]
  cask.appName = "App.app"

  # URL providing an appcast feed to find updates for this Cask.
  # Default is empty.
  # icon:dot-circle[] icon:file-alt[]
  cask.appcast = "pass:[https://{{repoHost}}/{{repoOwner}}/{{repoName}}/releases.atom]"

  # Procedures to uninstall the Cask.
  # icon:dot-circle[]
  pass:[[[packagers.brew.cask.uninstall]]]
    pkgutil = ["com.acme.app"]

  # Additional procedures for a more complete uninstall.
  # icon:dot-circle[]
  pass:[[[packagers.brew.cask.zap]]]
    trash = ["~/Library/Caches/App"]
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$packagers/json/common-head.adoc[]

include::partial$packagers/json/template-directory.adoc[]

include::partial$packagers/json/commitauthor.adoc[]

include::partial$packagers/json/tap.adoc[]

      // The class name of the generated formula.
      // If left unspecified, will use `{{projectNameCapitalized}}`.
      // icon:dot-circle[] icon:file-alt[]
      "formulaName": "App",

      // Create a formula that supports OSX & Linux.
      // Applicable to distributions of type [`JLINK`, `BINARY`, `FLAT_BIINARY`].
      // Default is `false`.
      // icon:dot-circle[]
      "multiPlatform": false,

      // Set a custom download strategy. Note that you'll need
      // to implement the strategy and add it to your tap repository.
      // Example: https://docs.brew.sh/Formula-Cookbook#url-download-strategies
      // icon:dot-circle[]
      "downloadStrategy": "CurlDownloadStrategy",

      // Adds `require_relative` statements at the top of the formula template.
      // icon:dot-circle[]
      "requireRelative": [
        "custom_download_strategy"
      ],

      // Customize the livecheck block.
      // Default is empty.
      // icon:dot-circle[] icon:file-alt[]
      "livecheck": [
        "url 'pass:[https://host/sparkle/appcast-release.xml]'",
        "strategy :sparkle"
      ],

      // A map of Homebrew dependencies.
      // A dependency to `openjdk` is automatically added to applicable Java distributions.
      // icon:dot-circle[]
      "dependencies": {
        // key in symbol format
        // mapped as `depends_on :key1 => "value1"`
        ":key1": "value1",

        // plain key
        // mapped as `depends_on "key2" => "value2"`
        "key2": "value2",

        // key in symbol format without value
        // mapped as `depends_on :key3`
        ":key3": "null",

        // plain key without value
        // mapped as `depends_on "key4"`
        "key4": "null"
      },

      // Cask configuration.
      // Requires artifact with extension `.dmg` or `.pkg`.
      // Defaults are shown.
      // icon:dot-circle[]
      "cask": {

        // Favors producing a cask instead of a formula.
        // Default is `false`.
        // icon:dot-circle[]
        "enabled": true,

        // The class name of the generated cask.
        // If left unspecified, will use `{{projectName}}`.
        // icon:dot-circle[] icon:file-alt[]
        "name": "app",

        // The name of the generated cask.
        // If left unspecified, will use `{{brewFormulaName}}`.
        // icon:dot-circle[] icon:file-alt[]
        "displayName": "App",

        // Relative path to the .pkg file.
        // If left unspecified, will use the filename of the .pkg file.
        // icon:dot-circle[] icon:file-alt[]
        "pkgName": "app-1.0.0.pkg",

        // Name of the application folder.
        // If left unspecified, will use `{{brewFormulaName}}.app`.
        // icon:dot-circle[] icon:file-alt[]
        "appName": "App.app",

        // URL providing an appcast feed to find updates for this Cask.
        // Default is empty.
        // icon:dot-circle[] icon:file-alt[]
        "appcast": "pass:[https://{{repoHost}}/{{repoOwner}}/{{repoName}}/releases.atom]",

        // Procedures to uninstall the Cask.
        // icon:dot-circle[]
        "uninstall": {
          "pkgutil": {
            "com.acme.app"
          }
        },

        // Additional procedures for a more complete uninstall.
        // icon:dot-circle[]
        "zap": {
          "trash": {
            "~/Library/Caches/App"
          }
        }
      }
include::partial$packagers/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$packagers/maven/common-head.adoc[]

include::partial$packagers/maven/template-directory.adoc[]

include::partial$packagers/maven/commitauthor.adoc[]

include::partial$packagers/maven/tap.adoc[]

      <!--
        The class name of the generated formula.
        If left unspecified, will use `{{projectNameCapitalized}}`.
        icon:dot-circle[] icon:file-alt[]
      -->
      <formulaName>App</formulaName>

      <!--
        Create a formula that supports OSX & Linux.
        Applicable to distributions of type [`JLINK`, `BINARY`, `FLAT_BIINARY`].
        Default is `false`.
        icon:dot-circle[]
      -->
      <multiPlatform>false</multiPlatform>

      <!--
        Set a custom download strategy. Note that you'll need
        to implement the strategy and add it to your tap repository.
        Example: https://docs.brew.sh/Formula-Cookbook#url-download-strategies
        icon:dot-circle[]
      -->
      <downloadStrategy>CurlDownloadStrategy</downloadStrategy>

      <!--
        Adds `require_relative` statements at the top of the formula template.
        icon:dot-circle[]
      -->
      <requireRelative>
        <require>custom_download_strategy</require>
      </requireRelative>

      <!--
        Customize the livecheck block.
        Default is empty.
        icon:dot-circle[] icon:file-alt[]
      -->
      <livecheck>
        <livecheck>url "pass:[https://host/sparkle/appcast-release.xml]"</livecheck>
        <livecheck>strategy :sparkle</livecheck>
      </livecheck>

      <!--
        A map of Homebrew dependencies.
        A dependency to `openjdk` is automatically added to applicable Java distributions.
        icon:dot-circle[]
      -->
      <dependencies>
        <!--
          key in symbol format
          mapped as `depends_on :key1 => "value1"`
        -->
        <:key1>value1</:key1>

        <!--
          plain key
          mapped as `depends_on "key2" => "value2"`
        -->
        <key2>value2</key2>

        <!--
          key in symbol format without value
          mapped as `depends_on :key3`
        -->
        <:key3/>

        <!--
          plain key without value
          mapped as `depends_on "key4"`
        -->
        <key4/>
      </dependencies>

      <!--
        Cask configuration.
        Requires artifact with extension `.dmg` or `.pkg`.
        Defaults are shown.
        icon:dot-circle[]
      -->
      <cask>

        // Favors producing a cask instead of a formula.
        // Default is `false`.
        // icon:dot-circle[]
        <enabled>true</enabled>

        <!--
          The class name of the generated cask.
          If left unspecified, will use `{{projectName}}`.
          icon:dot-circle[] icon:file-alt[]
        -->
        <name>app</name>

        <!--
          The name of the generated cask.
          If left unspecified, will use `{{brewFormulaName}}`.
          icon:dot-circle[] icon:file-alt[]
        -->
        <displayName>App</displayName>

        <!--
          Relative path to the .pkg file.
          If left unspecified, will use the filename of the .pkg file.
          icon:dot-circle[] icon:file-alt[]
        -->
        <pkgName>app-1.0.0.pkg</pkgName>

        <!--
          Name of the application folder.
          If left unspecified, will use `{{brewFormulaName}}.app`.
          icon:dot-circle[] icon:file-alt[]
        -->
        <appName>App.app</appName>

        <!--
          URL providing an appcast feed to find updates for this Cask.
          Default is empty.
          icon:dot-circle[] icon:file-alt[]
        -->
        <appcast>pass:[https://{{repoHost}}/{{repoOwner}}/{{repoName}}/releases.atom]</appcast>

        <!--
          Procedures to uninstall the Cask.
          icon:dot-circle[]
        -->
        <uninstall>
          <pkgutil>
            <pkgutil>com.acme.app</pkgutil>
          </pkgutil>
        </uninstall>

        <!--
          Additional procedures for a more complete uninstall.
          icon:dot-circle[]
        -->
        <zap>
          <trash>
            <trash>~/Library/Caches/App</trash>
          </trash>
        </zap>
       </cask>
include::partial$packagers/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$packagers/gradle/common-head.adoc[]

include::partial$packagers/gradle/template-directory.adoc[]

include::partial$packagers/gradle/commitauthor.adoc[]

include::partial$packagers/gradle/tap.adoc[]

      // The class name of the generated formula.
      // If left unspecified, will use `{{projectNameCapitalized}}`.
      // icon:dot-circle[] icon:file-alt[]
      formulaName = 'App'

      // Create a formula that supports OSX & Linux.
      // Applicable to distributions of type [`JLINK`, `BINARY`, `FLAT_BIINARY`].
      // Default is `false`.
      // icon:dot-circle[]
      multiPlatform = false

      // Set a custom download strategy. Note that you'll need
      // to implement the strategy and add it to your tap repository.
      // Example: https://docs.brew.sh/Formula-Cookbook#url-download-strategies
      // icon:dot-circle[]
      downloadStrategy = 'CurlDownloadStrategy'

      // Adds `require_relative` statements at the top of the formula template.
      // icon:dot-circle[]
      requireRelative = ['custom_download_strategy']

      // Customize the livecheck block.
      // Default is empty.
      // icon:dot-circle[] icon:file-alt[]
      livecheck = [
        'url "pass:[https://host/sparkle/appcast-release.xml]"',
        'strategy :sparkle']

      // A map of Homebrew dependencies.
      // A dependency to `openjdk` is automatically added to applicable Java distributions.
      // icon:dot-circle[]
      dependencies {
        // key in symbol format
        // mapped as `depends_on :key1 => "value1"`
        dependency(':key1', 'value1')

        // plain key
        // mapped as `depends_on "key2" => "value2"`
        dependency('key2', 'value2')

        // key in symbol format without value
        // mapped as `depends_on :key3`
        dependency(':key3')

        // plain key without value
        // mapped as `depends_on "key4"`
        dependency('key4')
      }

      // Cask configuration.
      // Requires artifact with extension `.dmg` or `.pkg`.
      // Defaults are shown.
      // icon:dot-circle[]
      cask {

        // Favors producing a cask instead of a formula.
        // Default is `false`.
        // icon:dot-circle[]
        enabled = true

        // The class name of the generated cask.
        // If left unspecified, will use `{{projectName}}`.
        // icon:dot-circle[] icon:file-alt[]
        name = 'app'

        // The name of the generated cask.
        // If left unspecified, will use `{{brewFormulaName}}`.
        // icon:dot-circle[] icon:file-alt[]
        displayName = 'App'

        // Relative path to the .pkg file.
        // If left unspecified, will use the filename of the .pkg file.
        // icon:dot-circle[] icon:file-alt[]
        pkgName = 'app-1.0.0.pkg'

        // Name of the application folder.
        // If left unspecified, will use `{{brewFormulaName}}.app`.
        // icon:dot-circle[] icon:file-alt[]
        appName = 'App.app'

        // URL providing an appcast feed to find updates for this Cask.
        // Default is empty.
        // icon:dot-circle[] icon:file-alt[]
        appcast = 'pass:[https://{{repoHost}}/{{repoOwner}}/{{repoName}}/releases.atom]'

        // Procedures to uninstall the Cask.
        // icon:dot-circle[]
        uninstall = [
          pkgutil: [
            'com.acme.app'
          ]
        ]

        // Additional procedures for a more complete uninstall.
        // icon:dot-circle[]
        zap = [
          trash: [
            '~/Library/Caches/App'
          ]
        ]
      }
include::partial$packagers/gradle/common-footer.adoc[]
----
--
====

IMPORTANT: Formula names must be unique!

include::partial$envvars-header.adoc[]

**Inside `packagers` section**
[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
2+| *active*
| jreleaser.packagers.{packager_sys_key}.active
| JRELEASER_PACKAGERS_{packager_env_key}_ACTIVE
|===

**Inside `distributions` section**
[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
2+| *active*
| jreleaser.distributions.${name}.{packager_sys_key}.active
| JRELEASER_DISTRIBUTIONS_${name}_{packager_env_key}_ACTIVE
include::partial$packagers/tap-envvars.adoc[]
|===

include::partial$envvars-footer.adoc[]

include::partial$packagers/token.adoc[]

include::partial$packagers/downloadUrl.adoc[]

== Example

Assuming the current version is `1.2.3`, and a distribution named `app`, the above configuration will generate
a `app.rb` formula in the `duke/homebrew-tap` repository:

[source,ruby]
[subs="+macros"]
----
class App < Formula
  desc "Sample app"
  homepage "pass:[https://acme.com/app]"
  version "1.2.3"
  url "pass:[https://github.com/duke/app/releases/download/v1.2.3/app-1.2.3.zip]"
  sha256 "812121a64bbd3f49286f7b0be3c9209068f71fcf9541f313708979602e8de466"
  license "Apache-2.0"

  depends_on "openjdk@8"

  def install
    libexec.install Dir["*"]
    bin.install_symlink "#{libexec}/bin/app"
  end

  test do
    output = shell_output("#{bin}/app --version")
    assert_match "1.2.3", output
  end
end
----

NOTE: JReleaser does not generate a valid homebrew-core formula. The generated formulas are meant to be published as
link:https://docs.brew.sh/Taps.html[homebrew taps], and in their current form will not be accepted in any of the official
homebrew repositories.

== JDK dependency

For Java Binary and Single JAR distributions, a dependency to OpenJDK is added automatically. This can be disabled entirely by adding `skipJava` as an extra property on the distribution.

NOTE: As of JReleaser 1.x, the default is to add a dependency on the specific major JDK version known for the distribution (such as 8 or 17). Later major versions of JReleaser are expected to change this and default to adding a dependency to openjdk without a specific version, as is the usual pattern for link:https://docs.brew.sh/Homebrew-and-Java[Java software on Homebrew]. You can explicitly control this by setting the `useVersionedJava` extra property on the distribution.

== Casks

Casks require a `.zip`, `.dmg` or a `.pkg` artifact. Distributions that provide more than one of these files can mark which
artifacts should be skipped from being resolved as a Cask candidate by adding a `skipBrew` extra property to the target
artifacts.

The value of the `displayName` property will be automatically transformed to remove hyphens and have capitalization. If this
transformation were to produce the wrong result for you then you may either:

- set a extraProperty named `skipCaskDisplayNameTransform` to `true`.
- set an explicit value for `displayName`.

== Templates

The default location for templates is:

`src/jreleaser/distributions/<distribution-name>/brew`

The following list shows the filenames that may be used to override default templates:

* `cask.rb.tpl`
* `formula.rb.tpl`
* `formula-multi.rb.tpl`
* `README.md.tpl`

Any additional files found in the template directories will be copied as is unless their filename ends with `.tpl` in
which case xref:name-templates.adoc[] substitution will take place.

Templates may be initialized using the `template` command

 * xref:tools:jreleaser-cli.adoc#_template_generate[{icon_cli_s} template generate]
 * xref:tools:jreleaser-maven.adoc#_jreleasertemplate_generate[{icon_maven_s} jreleaser:template-generate]
 * xref:tools:jreleaser-gradle.adoc#_jreleasertemplategenerate[{icon_gradle_s} jreleaserTemplategGenerate]
 * xref:tools:jreleaser-ant.adoc#_jreleaser_template_generate[{icon_ant_s} jreleaser-template-generate]

== Skip Templates

You may skip any template files by defining a set of skip rules in the `skipTemplates` property. For example, you may use
any of these expressions to skip a template named `README.md.tpl`:

* `README.md.tpl`: matches the full template name
* `README.md`: matches the transformed template name
* `README.*`: matches using a regex

== Skip Artifacts

If there is more than one matching artifact in a given distribution you may add a `skipBrew` extra property
to the target artifact to mark it as skipped for packaging with {tool_id}.

== Skip License

If there's a matching `LICENSE` file available at the root of the project it will be copied to the repository by default.
You may set an extra property named `skipLicenseFile` on {tool_id} to skip this behavior.
