= Macports
:tool_id:       macports
:tool_name:     Macports
:tool_tap_name: macports
:tool_manifest: portfile
:tool_package:  #{distribution.name}
:packager_sys_key: macports
:packager_env_key: MACPORTS
:tap_basename_sys: macports
:tap_basename_env: MACPORTS

JReleaser can generate and publish a link:https://www.macports.org/[Macports] Portfile into a repository that you have
access to. This packager generates port file and publishes it to a repository of your choice. However, it's your
responsibility to update the official link:https://github.com/macports/macports-ports/[] with a PR of your own.

As a reference JReleaser publishes its release using a link:https://github.com/jreleaser/jreleaser-macports/blob/main/.github/workflows/update.yml[GitHub workflow]
triggered on every push to the `main` branch of link:https://github.com/jreleaser/jreleaser-macports[jreleaser/jreleaser-macports].

The `macports` section specifies how the Portfile should be created.

The following artifact extensions are supported by this packager:

* `.zip`
* `.dmg`

== Distribution Support

[%header, cols="<,^"]
|===
| Distribution                                      | Supported
| xref:concepts:distributions/binary.adoc[]         | {icon_req_y}
| xref:concepts:distributions/flat-binary.adoc[]    | {icon_req_y}
| xref:concepts:distributions/java-binary.adoc[]    | {icon_req_y}
| xref:concepts:distributions/jlink.adoc[]          | {icon_req_y}
| xref:concepts:distributions/native-image.adoc[]   | {icon_req_y}
| xref:concepts:distributions/native-package.adoc[] | {icon_req_y}
| xref:concepts:distributions/single-jar.adoc[]     | {icon_req_y}
|===

WARNING: Publication of snapshots is *not* allowed.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$packagers/yaml/common-head.adoc[]

include::partial$packagers/yaml/template-directory.adoc[]

include::partial$packagers/yaml/commitauthor.adoc[]

include::partial$packagers/yaml/tap.adoc[]

include::partial$packagers/yaml/package-name.adoc[]

    # URL used to check the latest version.
    # Defaults to `0`.
    # icon:dot-circle[]
    revision: 0

    # List of categories to use.
    # Defaults to `[devel]`.
    # icon:exclamation-triangle[]
    categories:
      - 'devel'

    # List of maintainers.
    # Accepted values described at link:https://guide.macports.org/#reference.keywords.maintainers[]
    # Defaults to `[@#{release.${releaser}.username}]`.
    # icon:exclamation-triangle[]
    maintainers:
      - 'nomaintainer'
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$packagers/toml/common-head.adoc[]

include::partial$packagers/toml/template-directory.adoc[]

include::partial$packagers/toml/commitauthor.adoc[]

include::partial$packagers/toml/tap.adoc[]

include::partial$packagers/toml/package-name.adoc[]

  # URL used to check the latest version.
  # Defaults to `0`.
  # icon:dot-circle[]
  revision = 0

  # List of categories to use.
  # Defaults to `[devel]`.
  # icon:exclamation-triangle[]
  categories = ["devel"]

  # List of maintainers.
  # Accepted values described at link:https://guide.macports.org/#reference.keywords.maintainers[]
  # Defaults to `[@#{release.${releaser}.username}]`.
  # icon:exclamation-triangle[]
  maintainers = ["nomaintainer"]
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$packagers/json/common-head.adoc[]

include::partial$packagers/json/template-directory.adoc[]

include::partial$packagers/json/commitauthor.adoc[]

include::partial$packagers/json/tap.adoc[]

include::partial$packagers/json/package-name.adoc[]

      // URL used to check the latest version.
      // Defaults to `0`.
      // icon:dot-circle[]
      "revision": 0,

      // List of categories to use.
      // Defaults to `[devel]`.
      // icon:exclamation-triangle[]
      "categories": ["devel"],

      // List of maintainers.
      // Accepted values described at link:https://guide.macports.org/#reference.keywords.maintainers[]
      // Defaults to `[@#{release.${releaser}.username}]`.
      // icon:exclamation-triangle[]
      "maintainers": ["nomaintainer"]
include::partial$packagers/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$packagers/maven/common-head.adoc[]

include::partial$packagers/maven/template-directory.adoc[]

include::partial$packagers/maven/commitauthor.adoc[]

include::partial$packagers/maven/tap.adoc[]

include::partial$packagers/maven/package-name.adoc[]

      <!--
        URL used to check the latest version.
        Defaults to `0`.
        icon:dot-circle[]
      -->
      <revision>0</revision>

      <!--
        List of categories to use.
        Defaults to `[devel]`.
        icon:exclamation-triangle[]
      -->
      <categories>devel</categories>

      <!--
        List of maintainers.
        Accepted values described at link:https://guide.macports.org/#reference.keywords.maintainers[]
        Defaults to `[@#{release.${releaser}.username}]`.
        icon:exclamation-triangle[]
      -->
      <maintainers>nomaintainer</maintainers>
include::partial$packagers/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$packagers/gradle/common-head.adoc[]

include::partial$packagers/gradle/template-directory.adoc[]

include::partial$packagers/gradle/commitauthor.adoc[]

include::partial$packagers/gradle/tap.adoc[]

include::partial$packagers/gradle/package-name.adoc[]

      // URL used to check the latest version.
      // Defaults to `0`.
      // icon:dot-circle[]
      revision = 0

      // List of categories to use.
      // Defaults to `[devel]`.
      // icon:exclamation-triangle[]
      categories = ['devel']

      // List of maintainers.
      // Accepted values described at link:https://guide.macports.org/#reference.keywords.maintainers[]
      // Defaults to `[@#{release.${releaser}.username}]`.
      // icon:exclamation-triangle[]
      maintainers = ['nomaintainer']
include::partial$packagers/gradle/common-footer.adoc[]
----
--
====

include::partial$envvars-header.adoc[]

**Inside `packagers` section**
[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
2+| *active*
| jreleaser.packagers.{packager_sys_key}.active
| JRELEASER_PACKAGERS_{packager_env_key}_ACTIVE
|===

**Inside `distributions` section**
[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
2+| *active*
| jreleaser.distributions.${name}.{packager_sys_key}.active
| JRELEASER_DISTRIBUTIONS_${name}_{packager_env_key}_ACTIVE
include::partial$packagers/tap-envvars.adoc[]
|===

include::partial$envvars-footer.adoc[]

include::partial$packagers/token.adoc[]

include::partial$packagers/downloadUrl.adoc[]

== Example

Assuming the current version is `1.2.3`, and a distribution named `app`, the above configuration will generate
a `ports/devel/app/Porfile` file in the `duke/macports` repository:

[source,tcl]
[subs="+macros"]
----
# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4

PortSystem       1.0
PortGroup        java 1.0

name             app
version          1.2.3
revision         0

categories       devel java
license          Apache-2.0
maintainers      @duke
platforms        darwin
supported_archs  noarch

description      Awesome App
long_description Awesome App

homepage         pass:[https://acme.com/app]

master_sites     pass:[https://github.com/duke/app/releases/download/v1.0.0/]
use_zip          yes

checksums        rmd160 f7e88b1c323b5c1772ebce05837a7cfd4ceda09d \
                 sha256 53e89097573fb807adcf410169f117532ae17a4cd72066f9e40420eaf0d13147 \
                 size   6481

java.version     1.8.+

use_configure    no

build {}

destroot {
    set target ${destroot}${prefix}/share/java/${name}

    # Create the target java directory
    xinstall -m 755 -d ${target}

    # Copy over the needed elements of our directory tree
    foreach d { bin lib } {
        copy ${worksrcpath}/${d} ${target}
    }

    # Remove extraneous bat files
    foreach f [glob -directory ${target}/bin *.bat] {
        delete ${f}
    }

    ln -s ../share/java/${name}/bin/app ${destroot}${prefix}/bin/app
}

livecheck.type   none
----

== AppName

JReleaser calculates the value of the containing app directory when packaging a xref:concepts:distributions/native-package.adoc[]
distribution for macOs and a `.dmg` file. The default value matches `{{distributionName}}.app`. If a different value were
to be needed then set the `appName` extra property on the `macports` packager. This property accepts xref:name-templates.adoc[].

== Templates

The default location for templates is:

`src/jreleaser/distributions/<distribution-name>/macports`

The following list shows the filenames that may be used to override default templates:

* `Portfile.tpl`

Any additional files found in the template directories will be copied as is unless their filename ends with `.tpl` in
which case xref:name-templates.adoc[] substitution will take place.

Templates may be initialized using the `template` command

 * xref:tools:jreleaser-cli.adoc#_template_generate[{icon_cli_s} template generate]
 * xref:tools:jreleaser-maven.adoc#_jreleasertemplate_generate[{icon_maven_s} jreleaser:template-generate]
 * xref:tools:jreleaser-gradle.adoc#_jreleasertemplategenerate[{icon_gradle_s} jreleaserTemplategGenerate]
 * xref:tools:jreleaser-ant.adoc#_jreleaser_template_generate[{icon_ant_s} jreleaser-template-generate]

== Skip Templates

You may skip any template files by defining a set of skip rules in the `skipTemplates` property. For example, you may use
any of these expressions to skip a template named `README.md.tpl`:

* `README.md.tpl`: matches the full template name
* `README.md`: matches the transformed template name
* `README.*`: matches using a regex

== Skip Artifacts

If there is more than one matching artifact in a given distribution you may add a `skip{tool_name}` extra property
to the target artifact to mark it as skipped for packaging with {tool_id}.

== Skip License

If there's a matching `LICENSE` file available at the root of the project it will be copied to the repository by default.
You may set an extra property named `skipLicenseFile` on {tool_id} to skip this behavior.

== Publication to Macports

You are responsible for submitting a ticket to MacPorts for updating an existing port of adding a new port.
JReleaser *does not* create a ticket nor a pull request for you.

Please consult the link:https://guide.macports.org/[MacPorts guide] to know more.
