= Scoop
:tool_id:       scoop
:tool_name:     Scoop
:tool_tap:      bucket
:tool_tap_name: scoop-duke
:tool_manifest: manifest
:tool_package:  ${distribution.executable}
:packager_sys_key: scoop
:packager_env_key: SCOOP
:tap_sys_key:      bucket
:tap_env_key:      BUCKET
:tap_basename_sys: scoop
:tap_basename_env: SCOOP

JReleaser can generate and publish a _Scoop App Manifest_ into a repository that you have access to.

The `scoop` section specifies how the manifest should be created.

The following artifact extensions are supported by this packager:

* `.jar`
* `.zip`
* `.msi`

== Distribution Support

[%header, cols="<,^"]
|===
| Distribution                                      | Supported
| xref:concepts:distributions/binary.adoc[]         | {icon_req_y}
| xref:concepts:distributions/flat-binary.adoc[]    | {icon_req_y}
| xref:concepts:distributions/java-binary.adoc[]    | {icon_req_y}
| xref:concepts:distributions/jlink.adoc[]          | {icon_req_y}
| xref:concepts:distributions/native-image.adoc[]   | {icon_req_y}
| xref:concepts:distributions/native-package.adoc[] | {icon_req_y}
| xref:concepts:distributions/single-jar.adoc[]     | {icon_req_y}
|===

WARNING: Publication of snapshots is *not* allowed.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$packagers/yaml/common-head.adoc[]

include::partial$packagers/yaml/template-directory.adoc[]

include::partial$packagers/yaml/commitauthor.adoc[]

include::partial$packagers/yaml/tap.adoc[]

include::partial$packagers/yaml/package-name.adoc[]

    # URL used to check the latest version.
    # Defaults to the releaser's `latestReleaseUrl`.
    # icon:dot-circle[] icon:file-alt[]
    checkverUrl: pass:[https://host/path]

    # URL used to download a new version.
    # Defaults to the releaser's `downloadUrl`.
    # icon:dot-circle[] icon:file-alt[]
    autoupdateUrl: pass:[https://host/path]
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$packagers/toml/common-head.adoc[]

include::partial$packagers/toml/template-directory.adoc[]

include::partial$packagers/toml/commitauthor.adoc[]

include::partial$packagers/toml/tap.adoc[]

include::partial$packagers/toml/package-name.adoc[]

  # URL used to check the latest version.
  # Defaults to the releaser's `latestReleaseUrl`.
  # icon:dot-circle[] icon:file-alt[]
  checkverUrl = "pass:[https://host/path]"

  # URL used to download a new version.
  # Defaults to the releaser's `downloadUrl`.
  # icon:dot-circle[] icon:file-alt[]
  autoupdateUrl = "pass:[https://host/path]"
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$packagers/json/common-head.adoc[]

include::partial$packagers/json/template-directory.adoc[]

include::partial$packagers/json/commitauthor.adoc[]

include::partial$packagers/json/tap.adoc[]

include::partial$packagers/json/package-name.adoc[]

      // URL used to check the latest version.
      // Defaults to the releaser's `latestReleaseUrl`.
      // icon:dot-circle[] icon:file-alt[]
      "checkverUrl": "pass:[https://host/path]",

      // URL used to download a new version.
      // Defaults to the releaser's `downloadUrl`.
      // icon:dot-circle[] icon:file-alt[]
      "autoupdateUrl": "pass:[https://host/path]"
include::partial$packagers/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$packagers/maven/common-head.adoc[]

include::partial$packagers/maven/template-directory.adoc[]

include::partial$packagers/maven/commitauthor.adoc[]

include::partial$packagers/maven/tap.adoc[]

include::partial$packagers/maven/package-name.adoc[]

      <!--
        URL used to check the latest version.
        Defaults to the releaser's `latestReleaseUrl`.
        icon:dot-circle[] icon:file-alt[]
      -->
      <checkverUrl>pass:[https://host/path]</checkverUrl>

      <!--
        URL used to download a new version.
        Defaults to the releaser's `downloadUrl`.
        icon:dot-circle[] icon:file-alt[]
      -->
      <autoupdateUrl>pass:[https://host/path]</autoupdateUrl>
include::partial$packagers/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$packagers/gradle/common-head.adoc[]

include::partial$packagers/gradle/template-directory.adoc[]

include::partial$packagers/gradle/commitauthor.adoc[]

include::partial$packagers/gradle/tap.adoc[]

include::partial$packagers/gradle/package-name.adoc[]

      // URL used to check the latest version.
      // Defaults to the releaser's `latestReleaseUrl`.
      // icon:dot-circle[] icon:file-alt[]
      checkverUrl = 'pass:[https://host/path]'

      // URL used to download a new version.
      // Defaults to the releaser's `downloadUrl`.
      // icon:dot-circle[] icon:file-alt[]
      autoupdateUrl = 'pass:[https://host/path]'
include::partial$packagers/gradle/common-footer.adoc[]
----
--
====

include::partial$envvars-header.adoc[]

**Inside `packagers` section**
[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
2+| *active*
| jreleaser.packagers.{packager_sys_key}.active
| JRELEASER_PACKAGERS_{packager_env_key}_ACTIVE
|===

**Inside `distributions` section**
[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
2+| *active*
| jreleaser.distributions.${name}.{packager_sys_key}.active
| JRELEASER_DISTRIBUTIONS_${name}_{packager_env_key}_ACTIVE
include::partial$packagers/tap-envvars.adoc[]
|===

include::partial$envvars-footer.adoc[]

include::partial$packagers/token.adoc[]

include::partial$packagers/downloadUrl.adoc[]

== Example

Assuming the current version is `1.2.3`, and a distribution named `app`, the above configuration will generate
a `manifest.json` formula in the `duke/scoop-duke` repository:

[source,json]
[subs="+macros"]
----
{
  "homepage": "pass:[https://acme.com/app]",
  "description": "Sample app",
  "version": "1.2.3",
  "license": "Apache-2.0",
  "url": "pass:[https://github.com/duke/app/releases/download/v1.2.3/app-1.2.3.zip]",
  "hash": "sha256:812121a64bbd3f49286f7b0be3c9209068f71fcf9541f313708979602e8de466",
  "extract_dir": "app-1.2.3",
  "env_add_path": "bin",
  "suggest": {
    "JDK": [
      "java/oraclejdk",
      "java/openjdk"
    ]
  },
  "checkver": {
    "url": "pass:[https://github.com/duke/app/releases/latest]",
    "re": "v([\\d.]+).zip"
  },
  "autoupdate": {
    "url": "pass:[https://github.com/duke/app/releases/download/v1.2.3/app-$version.zip]",
    "extract_dir": "app-$version",
    "hash": {
      "url": "$url.sha256"
    }
  }
}
----

Your users can then install your app by doing:

[source]
----
scoop bucket add duke https://github.com/duke/scoop-duke.git
scoop install app
----

== Templates

The default location for templates is:

`src/jreleaser/distributions/<distribution-name>/scoop`

The following list shows the filenames that may be used to override default templates:

* `manifest.json.tpl`
* `README.md.tpl`

Any additional files found in the template directories will be copied as is unless their filename ends with `.tpl` in
which case xref:name-templates.adoc[] substitution will take place.

Templates may be initialized using the `template` command

 * xref:tools:jreleaser-cli.adoc#_template_generate[{icon_cli_s} template generate]
 * xref:tools:jreleaser-maven.adoc#_jreleasertemplate_generate[{icon_maven_s} jreleaser:template-generate]
 * xref:tools:jreleaser-gradle.adoc#_jreleasertemplategenerate[{icon_gradle_s} jreleaserTemplategGenerate]
 * xref:tools:jreleaser-ant.adoc#_jreleaser_template_generate[{icon_ant_s} jreleaser-template-generate]

== Skip Templates

You may skip any template files by defining a set of skip rules in the `skipTemplates` property. For example, you may use
any of these expressions to skip a template named `README.md.tpl`:

* `README.md.tpl`: matches the full template name
* `README.md`: matches the transformed template name
* `README.*`: matches using a regex

== Skip Artifacts

If there is more than one matching artifact in a given distribution you may add a `skip{tool_name}` extra property
to the target artifact to mark it as skipped for packaging with {tool_id}.

== Skip License

If there's a matching `LICENSE` file available at the root of the project it will be copied to the {tool_tap} by default.
You may set an extra property named `skipLicenseFile` on {tool_id} to skip this behavior.

