= Sdkman
:tool_id:       sdkman
:tool_name:     Sdkman
:packager_sys_key: sdkman
:packager_env_key: SDKMAN

Publishes a distribution to link:https://sdkman.io[Sdkman]. Please follow the instructions at
link:https://sdkman.io/vendors[] to register your project as a candidate and obtain publishing credentials.

The following artifact extensions are supported by this packager:

* `.zip`

== Distribution Support

[%header, cols="<,^"]
|===
| Distribution                                      | Supported
| xref:concepts:distributions/binary.adoc[]         | {icon_req_n}
| xref:concepts:distributions/flat-binary.adoc[]    | {icon_req_n}
| xref:concepts:distributions/java-binary.adoc[]    | {icon_req_y}
| xref:concepts:distributions/jlink.adoc[]          | {icon_req_y}
| xref:concepts:distributions/native-image.adoc[]   | {icon_req_y}
| xref:concepts:distributions/native-package.adoc[] | {icon_req_n}
| xref:concepts:distributions/single-jar.adoc[]     | {icon_req_n}
|===

NOTE: Configuring this packager automatically enables the xref:reference:announce/sdkman.adoc[] announcer.

WARNING: Publication of snapshots is *not* allowed.

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$packagers/yaml/common-head.adoc[]

    # Defines the connection timeout in seconds.
    # Defaults to `20`.
    # icon:dot-circle[]
    connectTimeout: 20

    # Defines the read timeout in seconds.
    # Defaults to `60`.
    # icon:dot-circle[]
    readTimeout: 60

    # The name of the candidate registered in the Sdkman database.
    # If unspecified, will use `${distribution.name}`.
    # icon:dot-circle[]
    candidate: app

    # Sdkman command to use.
    # Supported values are [`MAJOR`, `MINOR`]
    # Defaults to `MAJOR`.
    # icon:dot-circle[]
    command: MAJOR

    # The release notes URL to use.
    # Defaults to `${release.${git}.releaseNotesUrl}`.
    # icon:dot-circle[] icon:file-alt[]
    releaseNotesUrl: pass:[https://host.com/{{projectName}}/{{tagName}}]

    # The consumer key for publishing to Sdkman.
    # icon:exclamation-triangle[] icon:eye-slash[]
    consumerKey: __USE_ENVIRONMENT_VARIABLE__

    # The consumer token for publishing to Sdkman.
    # icon:exclamation-triangle[] icon:eye-slash[]
    consumerToken: __USE_ENVIRONMENT_VARIABLE__
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$packagers/toml/common-head.adoc[]

  # Defines the connection timeout in seconds.
  # Defaults to `20`.
  # icon:dot-circle[]
  connectTimeout = 20

  # Defines the read timeout in seconds.
  # Defaults to `60`.
  # icon:dot-circle[]
  readTimeout = 60

  # The name of the candidate registered in thew Sdkman database.
  # If unspecified, will use ${project.name}.
  # icon:dot-circle[]
  candidate = "app"

  # The release notes URL to use.
  # Defaults to `${release.${git}.releaseNotesUrl}`.
  # icon:dot-circle[] icon:file-alt[]
  releaseNotesUrl = "pass:[https://host.com/{{projectName}}/{{tagName}}]"

  # Sdkman command to use.
  # Supported values are [`MAJOR`, `MINOR`]
  # Defaults to `MAJOR`.
  # icon:dot-circle[]
  command = "MAJOR"

  # The consumer key for publishing to Sdkman.
  # icon:exclamation-triangle[] icon:eye-slash[]
  consumerKey = "__USE_ENVIRONMENT_VARIABLE__"

  # The consumer token for publishing to Sdkman.
  # icon:exclamation-triangle[] icon:eye-slash[]
  consumerToken = "__USE_ENVIRONMENT_VARIABLE__"
----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$packagers/json/common-head.adoc[]

      // Defines the connection timeout in seconds.
      // Defaults to `20`.
      // icon:dot-circle[]
      "connectTimeout": 20,

      // Defines the read timeout in seconds.
      // Defaults to `60`.
      // icon:dot-circle[]
      "readTimeout": 60,

      // The name of the candidate registered in thew Sdkman database.
      // If unspecified, will use ${project.name}.
      // icon:dot-circle[]
      "candidate": "app",

      // The release notes URL to use.
      // Defaults to `${release.${git}.releaseNotesUrl}`.
      // icon:dot-circle[] icon:file-alt[]
      "releaseNotesUrl": "pass:[https://host.com/{{projectName}}/{{tagName}}]",

      // Sdkman command to use.
      // Supported values are [`MAJOR`, `MINOR`]
      // Defaults to `MAJOR`.
      // icon:dot-circle[]
      "command": "MAJOR",

      // The consumer key for publishing to Sdkman.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "consumerKey": "__USE_ENVIRONMENT_VARIABLE__",

      // The consumer token for publishing to Sdkman.
      // icon:exclamation-triangle[] icon:eye-slash[]
      "consumerToken": "__USE_ENVIRONMENT_VARIABLE__"
include::partial$packagers/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$packagers/maven/common-head.adoc[]

      <!--
        Defines the connection timeout in seconds.
        Defaults to `20`.
        icon:dot-circle[]
      -->
      <connectTimeout>20</connectTimeout>

      <!--
        Defines the read timeout in seconds.
        Defaults to `60`.
        icon:dot-circle[]
      -->
      <readTimeout>60</readTimeout>

      <!--
        The name of the candidate registered in thew Sdkman database.
        If unspecified, will use ${project.name}.
        icon:dot-circle[]
      -->
      <candidate>app</candidate>

      <!--
        The release notes URL to use.
        Defaults to `${release.${git}.releaseNotesUrl}`.
        icon:dot-circle[] icon:file-alt[]
      -->
      <releaseNotesUrl>pass:[https://host.com/{{projectName}}/{{tagName}}]</releaseNotesUrl>

      <!--
        Sdkman command to use.
        Supported values are [`MAJOR`, `MINOR`]
        Defaults to `MAJOR`.
        icon:dot-circle[]
      -->
      <command>MAJOR</command>

      <!--
        The consumer key for publishing to Sdkman.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <consumerKey>__USE_ENVIRONMENT_VARIABLE__</consumerKey>

      <!--
        The consumer token for publishing to Sdkman.
        icon:exclamation-triangle[] icon:eye-slash[]
      -->
      <consumerToken>__USE_ENVIRONMENT_VARIABLE__</consumerToken>
include::partial$packagers/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$packagers/gradle/common-head.adoc[]

      // Defines the connection timeout in seconds.
      // Defaults to `20`.
      // icon:dot-circle[]
      connectTimeout = 20

      // Defines the read timeout in seconds.
      // Defaults to `60`.
      // icon:dot-circle[]
      readTimeout = 60

      // The name of the candidate registered in thew Sdkman database.
      // If unspecified, will use ${project.name}.
      // icon:dot-circle[]
      candidate = 'app'

      // The release notes URL to use.
      // Defaults to `${release.${git}.releaseNotesUrl}`.
      // icon:dot-circle[] icon:file-alt[]
      releaseNotesUrl = 'pass:[https://host.com/{{projectName}}/{{tagName}}]'

      // Sdkman command to use.
      // Supported values are [`MAJOR`, `MINOR`]
      // Defaults to `MAJOR`.
      // icon:dot-circle[]
      command = 'MAJOR'

      // The consumer key for publishing to Sdkman.
      // icon:exclamation-triangle[] icon:eye-slash[]
      consumerKey = '__USE_ENVIRONMENT_VARIABLE__'

      // The consumer token for publishing to Sdkman.
      // icon:exclamation-triangle[] icon:eye-slash[]
      consumerToken = '__USE_ENVIRONMENT_VARIABLE__'
include::partial$packagers/gradle/common-footer.adoc[]
----
--
====

IMPORTANT: Candidate names must be unique!

include::partial$envvars-header.adoc[]

**Inside `packagers` section**
[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
2+| *active*
| jreleaser.packagers.{packager_sys_key}.active
| JRELEASER_PACKAGERS_{packager_env_key}_ACTIVE
|===

**Inside `distributions` section**
[%header, cols="<1,<1", width="100%"]
|===
| System Property | Environment Variable
2+| *active*
| jreleaser.distributions.${name}.{packager_sys_key}.active
| JRELEASER_DISTRIBUTIONS_${name}_{packager_env_key}_ACTIVE
2+| *consumerKey*
| jreleaser.distributions.${name}.{packager_sys_key}.consumer.key +
  jreleaser.{packager_sys_key}.consumer.key
| JRELEASER_DISTRIBUTIONS_${name}_{packager_env_key}_CONSUMER_KEY +
  JRELEASER_{packager_env_key}_CONSUMER_KEY
2+| *consumerToken*
| jreleaser.distributions.${name}.{packager_sys_key}.consumer.token +
  jreleaser.{packager_sys_key}.consumer.token
| JRELEASER_DISTRIBUTIONS_${name}_{packager_env_key}_CONSUMER_TOKEN +
  JRELEASER_{packager_env_key}_CONSUMER_TOKEN
|===

include::partial$envvars-footer.adoc[]

include::partial$packagers/downloadUrl.adoc[]

== Skip Artifacts

You may mark artifacts to be skipped for this packager by adding an extra property name `skipSdkman` set to `true`.

== Requirements

This packager has the following requirements:

* Only `zip` artifacts are supported.
* The default platform is set to `UNIVERSAL` if the artifact did not define a value for its `platform` field.
* If there's more than one artifact then each artifact requires distinct `platform` values, otherwise the latest
 artifact will override any previous matches by platform.
* You may explicitly skip an artifact by defining an extra property named `skipSdkman` with a `true` value.
* Publishing will be skipped if no suitable artifacts are found.

Supported platform values are:

* `mac`, `osx`.
* `win`, `windows`.
* `linux`.

