= Generic
:gitservice_id:       generic
:gitservice_name:     Generic
:gitservice_env_name: GENERIC
:gitservice_host:     pass:[https://my.githost.com]
:!gitservice_api:

Use this releaser if no specific releaser is available.

Refer to xref:reference:release/changelog.adoc[] for full options on changelog customizations.

IMPORTANT: The `{gitservice_id}` releaser does not support all features.

The following features are not available when the generic Git releaser is configured:

 * packaging tools: AppImage, Asdf, Flatpak, Homebrew, Chocolatey, JBang, Scoop, Snap, Spec.
 * announcers: Sdkman.
 * auto-config is not supported.

Only the release tag will be created. If you'd like to upload artifacts to a particular destination then configure an
xref:reference:upload/index.adoc[uploader].

== Configuration

include::partial$legend.adoc[]

[tabs]
====
YAML::
+
--
[source,yaml]
[subs="+macros,attributes"]
----
include::partial$release/yaml/common-head.adoc[]
include::partial$release/yaml/commitauthor.adoc[]
----
--
TOML::
+
--
[source,toml]
[subs="+macros,attributes"]
----
include::partial$release/toml/common-head.adoc[]
include::partial$release/toml/commitauthor.adoc[]

----
--
JSON::
+
--
[source,json]
[subs="+macros,attributes"]
----
include::partial$release/json/common-head.adoc[]
include::partial$release/json/commitauthor.adoc[]
include::partial$release/json/common-footer.adoc[]
----
--
Maven::
+
--
[source,xml]
[subs="+macros,attributes,verbatim"]
----
include::partial$release/maven/common-head.adoc[]
include::partial$release/maven/commitauthor.adoc[]
include::partial$release/maven/common-footer.adoc[]
----
--
Gradle::
+
--
[source,groovy]
[subs="+macros,attributes"]
----
include::partial$release/gradle/common-head.adoc[]
include::partial$release/gradle/commitauthor.adoc[]
include::partial$release/gradle/common-footer.adoc[]
----
--
====

include::partial$envvars-header.adoc[]

[%header, cols="<1,<1,<1", width="100%"]
|===
| Property | System Property | Environment Variable
| username        | jreleaser.{gitservice_id}.username | JRELEASER_{gitservice_env_name}_USERNAME
| token           | jreleaser.{gitservice_id}.token    | JRELEASER_{gitservice_env_name}_TOKEN
| tagName         | jreleaser.tag.name          | JRELEASER_TAG_NAME
| previousTagName | jreleaser.previous.tag.name | JRELEASER_PREVIOUS_TAG_NAME
| branch          | jreleaser.branch            | JRELEASER_BRANCH
| skipTag         | jreleaser.skip.tag          | JRELEASER_SKIP_TAG
|===

include::partial$envvars-footer.adoc[]